'use client';

import { useState, useMemo } from 'react';
import ToolLayout from '@/components/ToolLayout';
import CopyButton from '@/components/CopyButton';
import Link from 'next/link';
import { useLang } from '@/i18n/LangContext';

const ui: Record<string, Record<string, string>> = {
  en: {
    title: 'ASCII Art Generator',
    description: 'Convert text to ASCII art with multiple font styles. Choose from Banner, Block, Shadow, Small, and Standard fonts.',
    inputLabel: 'Enter Text',
    inputPlaceholder: 'Type your text here...',
    fontLabel: 'Font Style',
    output: 'ASCII Art Output',
    clear: 'Clear',
    charCount: 'characters',
    maxChars: 'Max 30 characters',
    preview: 'Preview',
    introTitle: 'Free Online ASCII Art Generator',
    introText: 'Generate ASCII art text from any input using multiple font styles. ASCII art uses printable characters to create visual text designs, perfect for README files, code comments, terminal banners, email signatures, and social media posts. All generation happens in your browser with no server required.',
    tipTitle: 'Common Uses for ASCII Art',
    tip1: 'README.md file headers and project banners',
    tip2: 'Terminal startup banners and CLI welcome messages',
    tip3: 'Code comments and section dividers',
    tip4: 'Email signatures and social media decoration',
    tip5: 'Retro-style text for creative projects and games',
    faqTitle: 'Frequently Asked Questions',
    faq1q: 'What is ASCII art?',
    faq1a: 'ASCII art is a graphic design technique that uses printable characters from the ASCII standard to create visual images and text designs. It originated in the early days of computing when graphical displays were limited, and remains popular for terminal output, code comments, and creative expression.',
    faq2q: 'What fonts are available?',
    faq2a: 'This generator includes five font styles: Banner (large block letters using # characters), Block (solid block-style letters), Shadow (letters with a 3D shadow effect), Small (compact 4-row letters), and Standard (classic 6-row FIGlet-style letters). Each font supports A-Z uppercase letters, numbers 0-9, and common punctuation.',
    faq3q: 'Can I use the generated ASCII art commercially?',
    faq3a: 'Yes, ASCII art generated by this tool is freely usable for any purpose including commercial projects. The font definitions are original implementations and do not carry licensing restrictions. You can use them in READMEs, documentation, applications, and any other context.',
    faq4q: 'Why does my text look wrong with special characters?',
    faq4a: 'This generator supports uppercase letters A-Z, digits 0-9, and basic punctuation (space, period, exclamation, question mark, dash). Lowercase letters are automatically converted to uppercase. Other special characters may appear as empty spaces. For best results, use simple alphanumeric text.',
    faq5q: 'Is this tool free?',
    faq5a: 'Yes, completely free with no limitations. All ASCII art is generated client-side in your browser. No account, sign-up, or API key required.',
    relatedTitle: 'Related Tools',
  },
  zh: {
    title: 'ASCII 艺术字生成器',
    description: '将文本转换为 ASCII 艺术字，支持多种字体样式。',
    inputLabel: '输入文本',
    inputPlaceholder: '在此输入文本...',
    fontLabel: '字体样式',
    output: 'ASCII 艺术输出',
    clear: '清除',
    charCount: '个字符',
    maxChars: '最多 30 个字符',
    preview: '预览',
    introTitle: '免费在线 ASCII 艺术字生成器',
    introText: '使用多种字体样式从任意输入生成 ASCII 艺术文本。ASCII 艺术使用可打印字符创建视觉文本设计，适用于 README 文件、代码注释、终端横幅和电子邮件签名。所有生成都在浏览器中完成。',
    tipTitle: 'ASCII 艺术的常见用途',
    tip1: 'README.md 文件标题和项目横幅',
    tip2: '终端启动横幅和 CLI 欢迎信息',
    tip3: '代码注释和段落分隔符',
    tip4: '电子邮件签名和社交媒体装饰',
    tip5: '创意项目和游戏的复古风格文本',
    faqTitle: '常见问题',
    faq1q: '什么是 ASCII 艺术？', faq1a: 'ASCII 艺术是一种使用 ASCII 标准中的可打印字符来创建视觉图像和文本设计的图形设计技术。它起源于计算机早期图形显示有限的时代，至今仍用于终端输出和创意表达。',
    faq2q: '有哪些字体可用？', faq2a: '本生成器包含五种字体：Banner（使用 # 字符的大型字母）、Block（实心块状字母）、Shadow（带 3D 阴影效果）、Small（紧凑的 4 行字母）和 Standard（经典 6 行 FIGlet 风格）。',
    faq3q: '生成的 ASCII 艺术可以商用吗？', faq3a: '可以。此工具生成的 ASCII 艺术可自由用于任何目的，包括商业项目。字体定义是原创实现，没有许可限制。',
    faq4q: '为什么特殊字符显示不正确？', faq4a: '本生成器支持大写字母 A-Z、数字 0-9 和基本标点。小写字母会自动转换为大写。其他特殊字符可能显示为空格。',
    faq5q: '这个工具免费吗？', faq5a: '完全免费，没有限制。所有 ASCII 艺术都在浏览器端生成。',
    relatedTitle: '相关工具',
  },
  fr: {
    title: 'Generateur d\'Art ASCII',
    description: 'Convertissez du texte en art ASCII avec plusieurs styles de polices.',
    inputLabel: 'Entrez le texte', inputPlaceholder: 'Tapez votre texte ici...', fontLabel: 'Style de police',
    output: 'Sortie Art ASCII', clear: 'Effacer', charCount: 'caracteres', maxChars: 'Max 30 caracteres', preview: 'Apercu',
    introTitle: 'Generateur d\'art ASCII gratuit', introText: 'Generez du texte en art ASCII avec plusieurs styles de polices. Parfait pour les fichiers README, commentaires et bannieres.',
    tipTitle: 'Utilisations courantes', tip1: 'En-tetes de fichiers README', tip2: 'Bannieres de terminal', tip3: 'Commentaires de code', tip4: 'Signatures email', tip5: 'Texte retro pour projets creatifs',
    faqTitle: 'Questions frequentes',
    faq1q: 'Qu\'est-ce que l\'art ASCII?', faq1a: 'L\'art ASCII utilise des caracteres imprimables pour creer des images et designs textuels visuels.',
    faq2q: 'Quelles polices sont disponibles?', faq2a: 'Banner, Block, Shadow, Small et Standard. Chacune supporte A-Z, 0-9 et la ponctuation courante.',
    faq3q: 'Utilisation commerciale possible?', faq3a: 'Oui, l\'art ASCII genere est libre d\'utilisation pour tout projet, y compris commercial.',
    faq4q: 'Pourquoi les caracteres speciaux ne fonctionnent pas?', faq4a: 'Le generateur supporte A-Z, 0-9 et la ponctuation de base. Les minuscules sont converties en majuscules.',
    faq5q: 'Est-ce gratuit?', faq5a: 'Oui, entierement gratuit. Tout est genere dans votre navigateur.',
    relatedTitle: 'Outils connexes',
  },
  de: {
    title: 'ASCII-Art Generator',
    description: 'Konvertieren Sie Text in ASCII-Art mit verschiedenen Schriftarten.',
    inputLabel: 'Text eingeben', inputPlaceholder: 'Geben Sie Ihren Text ein...', fontLabel: 'Schriftstil',
    output: 'ASCII-Art Ausgabe', clear: 'Loeschen', charCount: 'Zeichen', maxChars: 'Max 30 Zeichen', preview: 'Vorschau',
    introTitle: 'Kostenloser ASCII-Art Generator', introText: 'Generieren Sie ASCII-Art Text mit verschiedenen Schriftarten. Perfekt fuer README-Dateien, Codekommentare und Terminal-Banner.',
    tipTitle: 'Haeufige Verwendungen', tip1: 'README-Datei-Header', tip2: 'Terminal-Banner', tip3: 'Code-Kommentare', tip4: 'E-Mail-Signaturen', tip5: 'Retro-Text fuer kreative Projekte',
    faqTitle: 'Haeufig gestellte Fragen',
    faq1q: 'Was ist ASCII-Art?', faq1a: 'ASCII-Art verwendet druckbare Zeichen um visuelle Bilder und Textdesigns zu erstellen.',
    faq2q: 'Welche Schriften gibt es?', faq2a: 'Banner, Block, Shadow, Small und Standard. Jede unterstuetzt A-Z, 0-9 und gaengige Satzzeichen.',
    faq3q: 'Kommerzielle Nutzung moeglich?', faq3a: 'Ja, die generierte ASCII-Art ist frei nutzbar fuer alle Zwecke.',
    faq4q: 'Warum funktionieren Sonderzeichen nicht?', faq4a: 'Der Generator unterstuetzt A-Z, 0-9 und einfache Satzzeichen. Kleinbuchstaben werden automatisch in Grossbuchstaben umgewandelt.',
    faq5q: 'Ist es kostenlos?', faq5a: 'Ja, komplett kostenlos. Alles wird im Browser generiert.',
    relatedTitle: 'Verwandte Tools',
  },
  es: {
    title: 'Generador de Arte ASCII',
    description: 'Convierta texto en arte ASCII con multiples estilos de fuente.',
    inputLabel: 'Ingrese texto', inputPlaceholder: 'Escriba su texto aqui...', fontLabel: 'Estilo de fuente',
    output: 'Salida de Arte ASCII', clear: 'Limpiar', charCount: 'caracteres', maxChars: 'Max 30 caracteres', preview: 'Vista previa',
    introTitle: 'Generador de arte ASCII gratuito', introText: 'Genere texto en arte ASCII con multiples estilos. Perfecto para archivos README, comentarios y banners.',
    tipTitle: 'Usos comunes', tip1: 'Encabezados de archivos README', tip2: 'Banners de terminal', tip3: 'Comentarios de codigo', tip4: 'Firmas de email', tip5: 'Texto retro para proyectos creativos',
    faqTitle: 'Preguntas frecuentes',
    faq1q: 'Que es el arte ASCII?', faq1a: 'El arte ASCII utiliza caracteres imprimibles para crear imagenes y disenos de texto visuales.',
    faq2q: 'Que fuentes hay disponibles?', faq2a: 'Banner, Block, Shadow, Small y Standard. Cada una soporta A-Z, 0-9 y puntuacion comun.',
    faq3q: 'Se puede usar comercialmente?', faq3a: 'Si, el arte ASCII generado es libre para cualquier uso incluido comercial.',
    faq4q: 'Por que no funcionan los caracteres especiales?', faq4a: 'El generador soporta A-Z, 0-9 y puntuacion basica. Las minusculas se convierten a mayusculas.',
    faq5q: 'Es gratis?', faq5a: 'Si, completamente gratis. Todo se genera en su navegador.',
    relatedTitle: 'Herramientas relacionadas',
  },
  ja: {
    title: 'ASCII アートジェネレーター',
    description: '複数のフォントスタイルでテキストを ASCII アートに変換。',
    inputLabel: 'テキストを入力', inputPlaceholder: 'ここにテキストを入力...', fontLabel: 'フォントスタイル',
    output: 'ASCII アート出力', clear: 'クリア', charCount: '文字', maxChars: '最大30文字', preview: 'プレビュー',
    introTitle: '無料 ASCII アートジェネレーター', introText: '複数のフォントスタイルで ASCII アートテキストを生成。README ファイル、コードコメント、ターミナルバナーに最適。',
    tipTitle: '一般的な用途', tip1: 'README ファイルヘッダー', tip2: 'ターミナルバナー', tip3: 'コードコメント', tip4: 'メール署名', tip5: 'レトロスタイルテキスト',
    faqTitle: 'よくある質問',
    faq1q: 'ASCII アートとは？', faq1a: 'ASCII アートは印刷可能な文字を使用してビジュアルな画像やテキストデザインを作成する技術です。',
    faq2q: 'どのフォントが利用可能？', faq2a: 'Banner、Block、Shadow、Small、Standard の5種類。各フォントは A-Z、0-9、一般的な句読点をサポート。',
    faq3q: '商用利用できますか？', faq3a: 'はい、生成された ASCII アートは商用を含むすべての目的で自由に使用できます。',
    faq4q: '特殊文字が動作しない理由は？', faq4a: 'ジェネレーターは A-Z、0-9、基本句読点をサポート。小文字は自動的に大文字に変換されます。',
    faq5q: '無料ですか？', faq5a: 'はい、完全に無料です。すべてブラウザで生成されます。',
    relatedTitle: '関連ツール',
  },
  ko: {
    title: 'ASCII 아트 생성기',
    description: '다양한 글꼴 스타일로 텍스트를 ASCII 아트로 변환합니다.',
    inputLabel: '텍스트 입력', inputPlaceholder: '여기에 텍스트를 입력하세요...', fontLabel: '글꼴 스타일',
    output: 'ASCII 아트 출력', clear: '지우기', charCount: '문자', maxChars: '최대 30자', preview: '미리보기',
    introTitle: '무료 ASCII 아트 생성기', introText: '다양한 글꼴 스타일로 ASCII 아트 텍스트를 생성합니다. README 파일, 코드 주석, 터미널 배너에 적합합니다.',
    tipTitle: '일반적인 용도', tip1: 'README 파일 헤더', tip2: '터미널 배너', tip3: '코드 주석', tip4: '이메일 서명', tip5: '레트로 스타일 텍스트',
    faqTitle: '자주 묻는 질문',
    faq1q: 'ASCII 아트란?', faq1a: 'ASCII 아트는 인쇄 가능한 문자를 사용하여 시각적 이미지와 텍스트 디자인을 만드는 기술입니다.',
    faq2q: '어떤 글꼴을 사용할 수 있나요?', faq2a: 'Banner, Block, Shadow, Small, Standard 5종류. 각 글꼴은 A-Z, 0-9, 일반 구두점을 지원합니다.',
    faq3q: '상업적으로 사용할 수 있나요?', faq3a: '네, 생성된 ASCII 아트는 상업적 프로젝트를 포함한 모든 목적으로 자유롭게 사용할 수 있습니다.',
    faq4q: '특수 문자가 작동하지 않는 이유는?', faq4a: '생성기는 A-Z, 0-9, 기본 구두점을 지원합니다. 소문자는 자동으로 대문자로 변환됩니다.',
    faq5q: '무료인가요?', faq5a: '네, 완전히 무료입니다. 모든 것이 브라우저에서 생성됩니다.',
    relatedTitle: '관련 도구',
  },
  it: {
    title: 'Generatore di ASCII Art',
    description: 'Converti testo in arte ASCII con diversi stili di font.',
    inputLabel: 'Inserisci testo', inputPlaceholder: 'Digita il testo qui...', fontLabel: 'Stile font',
    output: 'Output ASCII Art', clear: 'Cancella', charCount: 'caratteri', maxChars: 'Max 30 caratteri', preview: 'Anteprima',
    introTitle: 'Generatore di ASCII Art gratuito', introText: 'Genera testo ASCII Art con diversi stili di font. Perfetto per file README, commenti e banner.',
    tipTitle: 'Usi comuni', tip1: 'Header di file README', tip2: 'Banner di terminale', tip3: 'Commenti nel codice', tip4: 'Firme email', tip5: 'Testo retro per progetti creativi',
    faqTitle: 'Domande frequenti',
    faq1q: 'Cos\'e l\'ASCII Art?', faq1a: 'L\'ASCII Art utilizza caratteri stampabili per creare immagini e design testuali visivi.',
    faq2q: 'Quali font sono disponibili?', faq2a: 'Banner, Block, Shadow, Small e Standard. Ogni font supporta A-Z, 0-9 e punteggiatura comune.',
    faq3q: 'Uso commerciale possibile?', faq3a: 'Si, l\'ASCII Art generata e libera per qualsiasi uso incluso commerciale.',
    faq4q: 'Perche i caratteri speciali non funzionano?', faq4a: 'Il generatore supporta A-Z, 0-9 e punteggiatura base. Le minuscole vengono convertite in maiuscole.',
    faq5q: 'E gratuito?', faq5a: 'Si, completamente gratuito. Tutto viene generato nel browser.',
    relatedTitle: 'Strumenti correlati',
  },
  pt: {
    title: 'Gerador de Arte ASCII',
    description: 'Converta texto em arte ASCII com varios estilos de fonte.',
    inputLabel: 'Digite o texto', inputPlaceholder: 'Digite seu texto aqui...', fontLabel: 'Estilo de fonte',
    output: 'Saida ASCII Art', clear: 'Limpar', charCount: 'caracteres', maxChars: 'Max 30 caracteres', preview: 'Visualizacao',
    introTitle: 'Gerador de arte ASCII gratuito', introText: 'Gere texto em arte ASCII com varios estilos de fonte. Perfeito para arquivos README, comentarios e banners.',
    tipTitle: 'Usos comuns', tip1: 'Cabecalhos de arquivo README', tip2: 'Banners de terminal', tip3: 'Comentarios de codigo', tip4: 'Assinaturas de email', tip5: 'Texto retro para projetos criativos',
    faqTitle: 'Perguntas frequentes',
    faq1q: 'O que e arte ASCII?', faq1a: 'Arte ASCII usa caracteres imprimiveis para criar imagens e designs de texto visuais.',
    faq2q: 'Quais fontes estao disponiveis?', faq2a: 'Banner, Block, Shadow, Small e Standard. Cada uma suporta A-Z, 0-9 e pontuacao comum.',
    faq3q: 'Pode ser usado comercialmente?', faq3a: 'Sim, a arte ASCII gerada e livre para qualquer uso incluindo comercial.',
    faq4q: 'Por que caracteres especiais nao funcionam?', faq4a: 'O gerador suporta A-Z, 0-9 e pontuacao basica. Minusculas sao convertidas automaticamente em maiusculas.',
    faq5q: 'E gratuito?', faq5a: 'Sim, completamente gratuito. Tudo e gerado no navegador.',
    relatedTitle: 'Ferramentas relacionadas',
  },
  nl: {
    title: 'ASCII Art Generator',
    description: 'Converteer tekst naar ASCII-kunst met meerdere lettertypes.',
    inputLabel: 'Voer tekst in', inputPlaceholder: 'Typ uw tekst hier...', fontLabel: 'Letterstijl',
    output: 'ASCII Art Output', clear: 'Wis', charCount: 'tekens', maxChars: 'Max 30 tekens', preview: 'Voorbeeld',
    introTitle: 'Gratis ASCII Art generator', introText: 'Genereer ASCII Art tekst met meerdere lettertypes. Perfect voor README-bestanden, code-opmerkingen en banners.',
    tipTitle: 'Veelvoorkomend gebruik', tip1: 'README bestandsheaders', tip2: 'Terminal banners', tip3: 'Code opmerkingen', tip4: 'E-mail handtekeningen', tip5: 'Retro tekst voor creatieve projecten',
    faqTitle: 'Veelgestelde vragen',
    faq1q: 'Wat is ASCII Art?', faq1a: 'ASCII Art gebruikt afdrukbare tekens om visuele afbeeldingen en tekstontwerpen te maken.',
    faq2q: 'Welke lettertypen zijn beschikbaar?', faq2a: 'Banner, Block, Shadow, Small en Standard. Elk ondersteunt A-Z, 0-9 en veelvoorkomende leestekens.',
    faq3q: 'Commercieel gebruik mogelijk?', faq3a: 'Ja, gegenereerde ASCII Art is vrij te gebruiken voor alle doeleinden.',
    faq4q: 'Waarom werken speciale tekens niet?', faq4a: 'De generator ondersteunt A-Z, 0-9 en basis leestekens. Kleine letters worden automatisch naar hoofdletters geconverteerd.',
    faq5q: 'Is het gratis?', faq5a: 'Ja, volledig gratis. Alles wordt in uw browser gegenereerd.',
    relatedTitle: 'Gerelateerde tools',
  },
  pl: {
    title: 'Generator Sztuki ASCII',
    description: 'Konwertuj tekst na sztuke ASCII z wieloma stylami czcionek.',
    inputLabel: 'Wpisz tekst', inputPlaceholder: 'Wpisz tekst tutaj...', fontLabel: 'Styl czcionki',
    output: 'Wyjscie ASCII Art', clear: 'Wyczysc', charCount: 'znakow', maxChars: 'Maks. 30 znakow', preview: 'Podglad',
    introTitle: 'Darmowy generator sztuki ASCII', introText: 'Generuj tekst ASCII Art z wieloma stylami czcionek. Idealny do plikow README, komentarzy i banierow.',
    tipTitle: 'Popularne zastosowania', tip1: 'Naglowki plikow README', tip2: 'Banery terminala', tip3: 'Komentarze w kodzie', tip4: 'Podpisy email', tip5: 'Tekst retro do projektow kreatywnych',
    faqTitle: 'Czesto zadawane pytania',
    faq1q: 'Czym jest sztuka ASCII?', faq1a: 'Sztuka ASCII wykorzystuje drukowalne znaki do tworzenia wizualnych obrazow i projektow tekstowych.',
    faq2q: 'Jakie czcionki sa dostepne?', faq2a: 'Banner, Block, Shadow, Small i Standard. Kazda obsluguje A-Z, 0-9 i popularne znaki interpunkcyjne.',
    faq3q: 'Mozna uzywac komercyjnie?', faq3a: 'Tak, wygenerowana sztuka ASCII jest wolna do dowolnego uzycia.',
    faq4q: 'Dlaczego znaki specjalne nie dzialaja?', faq4a: 'Generator obsluguje A-Z, 0-9 i podstawowe znaki interpunkcyjne. Male litery sa automatycznie zamieniane na wielkie.',
    faq5q: 'Czy jest darmowe?', faq5a: 'Tak, calkowicie darmowe. Wszystko jest generowane w przegladarce.',
    relatedTitle: 'Powiazane narzedzia',
  },
  sv: {
    title: 'ASCII-konst Generator',
    description: 'Konvertera text till ASCII-konst med flera teckensnitt.',
    inputLabel: 'Ange text', inputPlaceholder: 'Skriv din text haer...', fontLabel: 'Teckensnitt',
    output: 'ASCII-konst Utdata', clear: 'Rensa', charCount: 'tecken', maxChars: 'Max 30 tecken', preview: 'Foerhandsvisning',
    introTitle: 'Gratis ASCII-konst generator', introText: 'Generera ASCII-konst text med flera teckensnitt. Perfekt foer README-filer, kodkommentarer och banners.',
    tipTitle: 'Vanliga anvaendningar', tip1: 'README-filhuvuden', tip2: 'Terminalbanners', tip3: 'Kodkommentarer', tip4: 'E-postsignaturer', tip5: 'Retro-text foer kreativa projekt',
    faqTitle: 'Vanliga fragor',
    faq1q: 'Vad aer ASCII-konst?', faq1a: 'ASCII-konst anvaender utskrivbara tecken foer att skapa visuella bilder och textdesigner.',
    faq2q: 'Vilka teckensnitt finns?', faq2a: 'Banner, Block, Shadow, Small och Standard. Varje stoedjer A-Z, 0-9 och vanlig interpunktion.',
    faq3q: 'Kommersiell anvaendning moejilig?', faq3a: 'Ja, genererad ASCII-konst aer fri att anvaenda foer alla aendamaal.',
    faq4q: 'Varfoer fungerar inte specialtecken?', faq4a: 'Generatorn stoedjer A-Z, 0-9 och grundlaeeggande interpunktion. Gemener konverteras automatiskt till versaler.',
    faq5q: 'Aer det gratis?', faq5a: 'Ja, helt gratis. Allt genereras i din webblaesare.',
    relatedTitle: 'Relaterade verktyg',
  },
  no: {
    title: 'ASCII-kunst Generator',
    description: 'Konverter tekst til ASCII-kunst med flere skrifttyper.',
    inputLabel: 'Skriv inn tekst', inputPlaceholder: 'Skriv din tekst her...', fontLabel: 'Skrifttype',
    output: 'ASCII-kunst Utdata', clear: 'Toem', charCount: 'tegn', maxChars: 'Maks 30 tegn', preview: 'Foerhandsvisning',
    introTitle: 'Gratis ASCII-kunst generator', introText: 'Generer ASCII-kunst tekst med flere skrifttyper. Perfekt for README-filer, kodekommentarer og bannere.',
    tipTitle: 'Vanlige bruksomraader', tip1: 'README-filoverskrifter', tip2: 'Terminalbannere', tip3: 'Kodekommentarer', tip4: 'E-postsignaturer', tip5: 'Retro-tekst for kreative prosjekter',
    faqTitle: 'Ofte stilte sporsmaal',
    faq1q: 'Hva er ASCII-kunst?', faq1a: 'ASCII-kunst bruker utskrivbare tegn for aa lage visuelle bilder og tekstdesign.',
    faq2q: 'Hvilke skrifttyper er tilgjengelige?', faq2a: 'Banner, Block, Shadow, Small og Standard. Hver stoetter A-Z, 0-9 og vanlig tegnsetting.',
    faq3q: 'Kommersiell bruk mulig?', faq3a: 'Ja, generert ASCII-kunst er fri til enhver bruk.',
    faq4q: 'Hvorfor fungerer ikke spesialtegn?', faq4a: 'Generatoren stoetter A-Z, 0-9 og grunnleggende tegnsetting. Smaa bokstaver konverteres automatisk til store.',
    faq5q: 'Er det gratis?', faq5a: 'Ja, helt gratis. Alt genereres i nettleseren din.',
    relatedTitle: 'Relaterte verktoy',
  },
  id: {
    title: 'Generator Seni ASCII',
    description: 'Konversi teks menjadi seni ASCII dengan berbagai gaya font.',
    inputLabel: 'Masukkan teks', inputPlaceholder: 'Ketik teks Anda di sini...', fontLabel: 'Gaya font',
    output: 'Output Seni ASCII', clear: 'Hapus', charCount: 'karakter', maxChars: 'Maks 30 karakter', preview: 'Pratinjau',
    introTitle: 'Generator seni ASCII gratis', introText: 'Buat teks seni ASCII dengan berbagai gaya font. Sempurna untuk file README, komentar kode, dan banner.',
    tipTitle: 'Kegunaan umum', tip1: 'Header file README', tip2: 'Banner terminal', tip3: 'Komentar kode', tip4: 'Tanda tangan email', tip5: 'Teks retro untuk proyek kreatif',
    faqTitle: 'Pertanyaan yang sering diajukan',
    faq1q: 'Apa itu seni ASCII?', faq1a: 'Seni ASCII menggunakan karakter yang dapat dicetak untuk membuat gambar dan desain teks visual.',
    faq2q: 'Font apa saja yang tersedia?', faq2a: 'Banner, Block, Shadow, Small, dan Standard. Masing-masing mendukung A-Z, 0-9, dan tanda baca umum.',
    faq3q: 'Bisa digunakan komersial?', faq3a: 'Ya, seni ASCII yang dihasilkan bebas digunakan untuk tujuan apa pun termasuk komersial.',
    faq4q: 'Mengapa karakter khusus tidak berfungsi?', faq4a: 'Generator mendukung A-Z, 0-9, dan tanda baca dasar. Huruf kecil otomatis dikonversi ke huruf besar.',
    faq5q: 'Apakah gratis?', faq5a: 'Ya, sepenuhnya gratis. Semuanya dihasilkan di browser Anda.',
    relatedTitle: 'Alat terkait',
  },
  th: {
    title: 'เครื่องมือสร้าง ASCII Art',
    description: 'แปลงข้อความเป็น ASCII Art ด้วยหลายสไตล์ฟอนต์',
    inputLabel: 'ป้อนข้อความ', inputPlaceholder: 'พิมพ์ข้อความที่นี่...', fontLabel: 'สไตล์ฟอนต์',
    output: 'ผลลัพธ์ ASCII Art', clear: 'ล้าง', charCount: 'ตัวอักษร', maxChars: 'สูงสุด 30 ตัวอักษร', preview: 'ดูตัวอย่าง',
    introTitle: 'เครื่องมือสร้าง ASCII Art ฟรี', introText: 'สร้างข้อความ ASCII Art ด้วยหลายสไตล์ฟอนต์ เหมาะสำหรับไฟล์ README, คอมเมนต์โค้ด และแบนเนอร์',
    tipTitle: 'การใช้งานทั่วไป', tip1: 'หัวข้อไฟล์ README', tip2: 'แบนเนอร์เทอร์มินัล', tip3: 'คอมเมนต์โค้ด', tip4: 'ลายเซ็นอีเมล', tip5: 'ข้อความสไตล์เรโทร',
    faqTitle: 'คำถามที่พบบ่อย',
    faq1q: 'ASCII Art คืออะไร?', faq1a: 'ASCII Art ใช้ตัวอักษรที่พิมพ์ได้เพื่อสร้างภาพและการออกแบบข้อความแบบภาพ',
    faq2q: 'มีฟอนต์อะไรบ้าง?', faq2a: 'Banner, Block, Shadow, Small และ Standard แต่ละฟอนต์รองรับ A-Z, 0-9 และเครื่องหมายวรรคตอนทั่วไป',
    faq3q: 'ใช้เชิงพาณิชย์ได้ไหม?', faq3a: 'ได้ ASCII Art ที่สร้างขึ้นสามารถใช้ได้อย่างอิสระสำหรับทุกวัตถุประสงค์',
    faq4q: 'ทำไมอักขระพิเศษไม่ทำงาน?', faq4a: 'เครื่องมือรองรับ A-Z, 0-9 และเครื่องหมายวรรคตอนพื้นฐาน ตัวพิมพ์เล็กจะถูกแปลงเป็นตัวพิมพ์ใหญ่อัตโนมัติ',
    faq5q: 'ฟรีไหม?', faq5a: 'ใช่ ฟรีทั้งหมด ทุกอย่างสร้างในเบราว์เซอร์ของคุณ',
    relatedTitle: 'เครื่องมือที่เกี่ยวข้อง',
  },
};

// --- Font definitions ---
type FontMap = Record<string, string[]>;

function buildFont(defs: Record<string, string>, rows: number): FontMap {
  const map: FontMap = {};
  for (const [ch, raw] of Object.entries(defs)) {
    const parts = raw.split('|');
    while (parts.length < rows) parts.push('');
    const w = Math.max(...parts.map(r => r.length));
    map[ch] = parts.map(r => r.padEnd(w));
  }
  return map;
}

const BANNER_DEFS: Record<string, string> = {
  A: ' ### |#   #|#####|#   #|#   #', B: '#### |#   #|#### |#   #|#### ', C: ' ####|#    |#    |#    | ####',
  D: '#### |#   #|#   #|#   #|#### ', E: '#####|#    |#### |#    |#####', F: '#####|#    |#### |#    |#    ',
  G: ' ####|#    |# ###|#   #| ####', H: '#   #|#   #|#####|#   #|#   #', I: '###| # | # | # |###',
  J: '  ###|   # |   # |#  # | ## ', K: '#  # |# #  |##   |# #  |#  # ', L: '#    |#    |#    |#    |#####',
  M: '#   #|## ##|# # #|#   #|#   #', N: '#   #|##  #|# # #|#  ##|#   #', O: ' ### |#   #|#   #|#   #| ### ',
  P: '#### |#   #|#### |#    |#    ', Q: ' ### |#   #|# # #|#  # | ## #', R: '#### |#   #|#### |# #  |#  # ',
  S: ' ####|#    | ### |    #|#### ', T: '#####|  #  |  #  |  #  |  #  ', U: '#   #|#   #|#   #|#   #| ### ',
  V: '#   #|#   #|#   #| # # |  #  ', W: '#   #|#   #|# # #|## ##|#   #', X: '#   #| # # |  #  | # # |#   #',
  Y: '#   #| # # |  #  |  #  |  #  ', Z: '#####|   # |  #  | #   |#####',
  '0': ' ### |#  ##|# # #|##  #| ### ', '1': '  #  | ##  |  #  |  #  | ### ', '2': ' ### |#   #|  ## | #   |#####',
  '3': '#####|   # | ### |   # |#### ', '4': '#   #|#   #|#####|    #|    #', '5': '#####|#    |#### |    #|#### ',
  '6': ' ### |#    |#### |#   #| ### ', '7': '#####|   # |  #  | #   |#    ', '8': ' ### |#   #| ### |#   #| ### ',
  '9': ' ### |#   #| ####|    #| ### ', ' ': '     |     |     |     |     ', '.': '   |   |   |   | # ', '!': ' # | # | # |   | # ',
  '?': ' ### |#   #|  ## |     |  #  ', '-': '     |     |#####|     |     ',
};

const BLOCK_DEFS: Record<string, string> = {
  A: ' @@@ |@   @|@@@@@|@   @|@   @', B: '@@@@ |@   @|@@@@ |@   @|@@@@ ', C: ' @@@@|@    |@    |@    | @@@@',
  D: '@@@@ |@   @|@   @|@   @|@@@@ ', E: '@@@@@|@    |@@@@ |@    |@@@@@', F: '@@@@@|@    |@@@@ |@    |@    ',
  G: ' @@@@|@    |@ @@@|@   @| @@@@', H: '@   @|@   @|@@@@@|@   @|@   @', I: '@@@|_@_|_@_|_@_|@@@',
  J: '  @@@|   @ |   @ |@  @ | @@ ', K: '@  @ |@ @  |@@   |@ @  |@  @ ', L: '@    |@    |@    |@    |@@@@@',
  M: '@   @|@@ @@|@ @ @|@   @|@   @', N: '@   @|@@  @|@ @ @|@  @@|@   @', O: ' @@@ |@   @|@   @|@   @| @@@ ',
  P: '@@@@ |@   @|@@@@ |@    |@    ', Q: ' @@@ |@   @|@ @ @|@  @ | @@ @', R: '@@@@ |@   @|@@@@ |@ @  |@  @ ',
  S: ' @@@@|@    | @@@ |    @|@@@@ ', T: '@@@@@|  @  |  @  |  @  |  @  ', U: '@   @|@   @|@   @|@   @| @@@ ',
  V: '@   @|@   @|@   @| @ @ |  @  ', W: '@   @|@   @|@ @ @|@@ @@|@   @', X: '@   @| @ @ |  @  | @ @ |@   @',
  Y: '@   @| @ @ |  @  |  @  |  @  ', Z: '@@@@@|   @ |  @  | @   |@@@@@',
  '0': ' @@@ |@  @@|@ @ @|@@  @| @@@ ', '1': '  @  | @@  |  @  |  @  | @@@ ', '2': ' @@@ |@   @|  @@ | @   |@@@@@',
  '3': '@@@@@|   @ | @@@ |   @ |@@@@ ', '4': '@   @|@   @|@@@@@|    @|    @', '5': '@@@@@|@    |@@@@ |    @|@@@@ ',
  '6': ' @@@ |@    |@@@@ |@   @| @@@ ', '7': '@@@@@|   @ |  @  | @   |@    ', '8': ' @@@ |@   @| @@@ |@   @| @@@ ',
  '9': ' @@@ |@   @| @@@@|    @| @@@ ', ' ': '     |     |     |     |     ', '.': '   |   |   |   | @ ', '!': ' @ | @ | @ |   | @ ',
  '?': ' @@@ |@   @|  @@ |     |  @  ', '-': '     |     |@@@@@|     |     ',
};

const SHADOW_DEFS: Record<string, string> = {
  A: '  _   | / \\  |/ _ \\ |  _  ||_| |_|', B: ' ___  | |_) || ___/| |_) ||____/', C: '  ___ / ___|| |   | |___| \\____|',
  D: ' ____  |  _ \\ | | | || |_| ||____/ ', E: ' _____ | ____||  _|  | |___ |_____|', F: ' _____ | ____||  _|  | |   |_|    ',
  G: '  ____ / ___|| |  _ | |_| | \\____|', H: ' _   _ | | | || |_| || |_| ||_| |_|', I: ' ___ |_ _| | | | |_| ||___|',
  J: '     _ |   | ||   | || |_| | \\___/ ', K: ' _  __| |/ / | | < |  | . \\ |_|\\_\\', L: ' _     | |   | |   | |__ |_____|',
  M: ' __  __ |  \\/  || |\\/| || |  | ||_|  |_|', N: ' _   _ | \\ | || .` || |\\  ||_| \\_|', O: '  ___  / _ \\ | | | || |_| | \\___/ ',
  P: ' ____  |  _ \\ | |_) ||  __/ |_|    ', Q: '  ___  / _ \\ | | | || |_| | \\__\\_\\', R: ' ____  |  _ \\ | |_) ||  _ < |_| \\_\\',
  S: ' ____  / ___|| |_  |  _| ||____/', T: ' _____ |_   _| | |   | |   |_|   ', U: ' _   _ | | | || | | || |_| | \\___/ ',
  V: '__     __\\ \\   / / \\ \\ / /  \\ V /   \\_/   ', W: '__        __\\ \\      / / \\ \\ /\\ / /  \\ V  V /   \\_/\\_/  ',
  X: '__  __ \\ \\/ /  >  <  / /\\ \\/_/  \\_\\', Y: '__   __\\ \\ / / \\ V /  | |  |_|  ', Z: ' _____ |__  /  / /  / /__|_____|',
  '0': '  ___  / _ \\ | | | || |_| | \\___/ ', '1': ' _  / | | | | | |_|', '2': ' ____  |___ \\ __) || / __|_____|',
  '3': ' _____ |___ / |_ \\  ___) ||____/', '4': ' _  _  | || | |_  _|  |_|    ', '5': ' _____ | ____|___ \\ ___) ||____/',
  '6': '  __   / /_ | \'_ \\ | (_) | \\___/ ', '7': ' _____ |___  |  / / / /  /_/   ', '8': '  ___  ( _ ) / _ \\| (_) | \\___/ ',
  '9': '  ___  / _ \\| (_) | \\__, | /_/   ', ' ': '     |     |     |     |     ', '.': '   |   |   |   | _ ', '!': '  _  | | | | |_|  (_) ',
  '?': ' ___ |__ \\  / / |_|  (_) ', '-': '       |_____|      |      ',
};

const SMALL_DEFS: Record<string, string> = {
  A: ' _ |/_\\|/ _\\|_| |_', B: ' _ |/ )|_/ )|___/', C: ' __ / _|| _ |\\__|', D: ' __ | _\\| _/|__/', E: ' __|/__| __|___|', F: ' __|/__| __|_|  ',
  G: ' __ / _|| _)||__/', H: '    |_|_||_ _||_|_|', I: ' _ | || ||_|', J: '  _|  || _|/_/', K: '   |_/ || < |_\\_\\', L: '    | | | |__|___|',
  M: '     ||\\/||||\\/|||_||_|', N: '    |\\ ||\\.|||\\ ||_|\\_|', O: ' __ / _\\| _/|__/', P: ' __ | _\\| _/|_|  ', Q: ' __ | _\\| _/|__|\\',
  R: ' __ | _\\| _ ||_\\_\\', S: ' __ /__ |__ |___/', T: ' ___|_|_ | | |_|  ', U: '    | | || |_|\\_/ ', V: '    | | | \\ / | V||_|',
  W: '      |  /  || /\\ || V V||_/ \\_|', X: '   |\\_/| / \\|/_\\', Y: '   |\\_/| | |_| ', Z: '___|_ /| / |___|',
  '0': ' _ / \\|\\_/| _ |', '1': '  | /|| |__|', '2': ' _ |_)|/ ||__|', '3': '__ |_)| _)|__/', '4': '   |_|_| __|  _|', '5': ' __|/_ |__)|__/',
  '6': ' _ / )|__)|__/', '7': '___| /|/ |_| ', '8': ' _ |_)||_)| _ |', '9': ' _ |_)|| / |/ ',
  ' ': '    |    |    |    ', '.': '  |  |  |._', '!': '! |! |  |._', '?': ' _ |_)| / |._', '-': '    |    |___|    ',
};

const STANDARD_DEFS: Record<string, string> = {
  A: '    _    / \\  / _ \\ / ___ \\/_/   \\_\\|           ', B: ' ____  | __ ) |  _ \\| |_) ||____/ |      ',
  C: '  ____  / ___||| |    | |___ \\____||      ', D: ' ____  |  _ \\ | | | || |_| ||____/ |      ',
  E: ' _____  | ____|  |  _|   | |___  |_____|  |      ', F: ' _____  | ____|  |  _|   | |     |_|     |      ',
  G: '  ____  / ___| | |  _  | |_| | \\____||      ', H: ' _   _  | | | | | |_| | |  _  | |_| |_||      ',
  I: ' ___  |_ _|  | |   | |  |___|  |      ', J: '     _  |   | | |   | | |_| |  \\___/ |      ',
  K: ' _  __ | |/ /  |   <  |  . \\ |_|\\_\\|      ', L: ' _      | |     | |     | |__   |_____|  |      ',
  M: ' __  __  |  \\/  | | |\\/| | | |  | | |_|  |_||      ', N: ' _   _  | \\ | | |  \\| | | |\\  | |_| \\_||      ',
  O: '  ___   / _ \\  | | | | | |_| |  \\___/ |      ', P: ' ____   |  _ \\  | |_) | |  __/ |_|    |      ',
  Q: '  ___   / _ \\  | | | | | |_| |  \\___\\_\\|      ', R: ' ____   |  _ \\  | |_) | |  _ < |_| \\_\\|      ',
  S: ' ____   / ___|  \\___ \\   ___) | |____/ |      ', T: ' _____  |_   _|   | |     | |    |_|    |      ',
  U: ' _   _  | | | | | | | | | |_| |  \\___/ |      ', V: '__     __ \\ \\   / /  \\ \\ / /   \\ V /    \\_/   |      ',
  W: '__        __ \\ \\      / /  \\ \\ /\\ / /   \\ V  V /    \\_/\\_/  |      ',
  X: '__  __ \\ \\/ /  >  <  / /\\ \\/_/  \\_\\|      ', Y: '__   __ \\ \\ / /  \\ V /   | |   |_|  |      ',
  Z: ' _____  |__  /    / /   / /__  |_____|  |      ',
  ' ': '      |      |      |      |      |      ', '.': '  |  |  |  |  |._', '!': '  _  | | | | |_|  (_) |      ',
  '?': '  ___  |__ \\   / /  |_|   (_)  |      ', '-': '        |______|       |       |       |      ',
  '0': '  ___   / _ \\  | | | | | |_| |  \\___/ |      ', '1': '  _   / |  | |  | |  |_| |      ',
  '2': '  ____   |___ \\   __) |  / __/  |_____|  |      ', '3': '  _____  |___ /    |_ \\   ___) | |____/ |      ',
  '4': '  _  _   | || |  |_  _|    |_|  |      ', '5': '  _____  | ____|  |__ \\    ___) | |____/ |      ',
  '6': '   __    / /_   | \'_ \\  | (_) |  \\___/ |      ', '7': '  _____  |___  |    / /   / /   /_/   |      ',
  '8': '   ___   ( _ )  / _ \\  | (_) |  \\___/ |      ', '9': '   ___   / _ \\  | (_) |  \\__, |   /_/  |      ',
};

const FONTS: { name: string; defs: Record<string, string>; rows: number }[] = [
  { name: 'Banner', defs: BANNER_DEFS, rows: 5 },
  { name: 'Block', defs: BLOCK_DEFS, rows: 5 },
  { name: 'Shadow', defs: SHADOW_DEFS, rows: 5 },
  { name: 'Small', defs: SMALL_DEFS, rows: 4 },
  { name: 'Standard', defs: STANDARD_DEFS, rows: 6 },
];

function renderText(text: string, fontMap: FontMap, rows: number): string {
  const upper = text.toUpperCase();
  const lines: string[] = Array(rows).fill('');
  for (const ch of upper) {
    const glyph = fontMap[ch] || fontMap[' '];
    if (!glyph) continue;
    for (let r = 0; r < rows; r++) {
      lines[r] += (glyph[r] || '') + ' ';
    }
  }
  return lines.map(l => l.trimEnd()).join('\n');
}

export default function AsciiArtGenerator() {
  const { lang } = useLang();
  const t = ui[lang] || ui.en;
  const [text, setText] = useState('HELLO');
  const [fontIdx, setFontIdx] = useState(0);

  const font = FONTS[fontIdx];
  const fontMap = useMemo(() => buildFont(font.defs, font.rows), [font]);
  const output = useMemo(() => renderText(text || 'HELLO', fontMap, font.rows), [text, fontMap, font.rows]);

  const faqSchema = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: [
      { '@type': 'Question', name: t.faq1q, acceptedAnswer: { '@type': 'Answer', text: t.faq1a } },
      { '@type': 'Question', name: t.faq2q, acceptedAnswer: { '@type': 'Answer', text: t.faq2a } },
      { '@type': 'Question', name: t.faq3q, acceptedAnswer: { '@type': 'Answer', text: t.faq3a } },
      { '@type': 'Question', name: t.faq4q, acceptedAnswer: { '@type': 'Answer', text: t.faq4a } },
      { '@type': 'Question', name: t.faq5q, acceptedAnswer: { '@type': 'Answer', text: t.faq5a } },
    ],
  };

  return (
    <ToolLayout title={t.title} description={t.description} toolId="ascii-art-generator">
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />

      {/* Input */}
      <div style={{ marginBottom: 16 }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 6 }}>
          <label style={{ fontSize: 13, fontWeight: 600 }}>{t.inputLabel}</label>
          <span style={{ fontSize: 11, color: 'var(--text-secondary)' }}>
            {text.length} / 30 {t.charCount}
          </span>
        </div>
        <input
          type="text"
          value={text}
          onChange={e => setText(e.target.value.slice(0, 30))}
          placeholder={t.inputPlaceholder}
          maxLength={30}
          style={{ width: '100%', padding: '10px 12px', fontSize: 16, borderRadius: 8, border: '1px solid var(--border-color)', background: 'var(--bg-input)', color: 'var(--text-primary)' }}
        />
      </div>

      {/* Font selector */}
      <div style={{ marginBottom: 16 }}>
        <label style={{ fontSize: 13, fontWeight: 600, display: 'block', marginBottom: 6 }}>{t.fontLabel}</label>
        <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
          {FONTS.map((f, i) => (
            <button key={f.name} onClick={() => setFontIdx(i)}
              style={{
                padding: '8px 18px', borderRadius: 8, fontSize: 13, cursor: 'pointer',
                border: i === fontIdx ? '2px solid var(--accent-blue)' : '1px solid var(--border-color)',
                background: i === fontIdx ? 'rgba(59,130,246,0.1)' : 'var(--bg-input)',
                color: 'var(--text-primary)', fontWeight: i === fontIdx ? 700 : 400,
              }}>
              {f.name}
            </button>
          ))}
        </div>
      </div>

      {/* Output */}
      <div style={{ marginBottom: 16 }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 6 }}>
          <label style={{ fontSize: 13, fontWeight: 600 }}>{t.output}</label>
          <div style={{ display: 'flex', gap: 8 }}>
            <CopyButton text={output} />
            <button onClick={() => setText('')} className="btn btn-secondary" style={{ fontSize: 12, padding: '4px 12px' }}>{t.clear}</button>
          </div>
        </div>
        <pre style={{
          background: '#0a0a0a', color: '#22c55e', padding: 20, borderRadius: 8,
          fontSize: 11, fontFamily: 'monospace', overflow: 'auto', lineHeight: 1.3,
          border: '1px solid var(--border-color)', minHeight: 120, whiteSpace: 'pre',
        }}>
          {output}
        </pre>
      </div>

      {/* Quick preview of all fonts */}
      <div style={{ marginBottom: 16 }}>
        <label style={{ fontSize: 13, fontWeight: 600, display: 'block', marginBottom: 8 }}>{t.preview}</label>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
          {FONTS.map((f, i) => {
            if (i === fontIdx) return null;
            const fm = buildFont(f.defs, f.rows);
            const preview = renderText(text || 'HELLO', fm, f.rows);
            return (
              <div key={f.name} style={{ border: '1px solid var(--border-color)', borderRadius: 8, overflow: 'hidden', cursor: 'pointer' }}
                onClick={() => setFontIdx(i)}>
                <div style={{ padding: '6px 12px', fontSize: 12, fontWeight: 600, background: 'var(--bg-input)', borderBottom: '1px solid var(--border-color)' }}>{f.name}</div>
                <pre style={{ padding: 12, fontSize: 9, fontFamily: 'monospace', overflow: 'auto', lineHeight: 1.2, margin: 0, color: 'var(--text-secondary)', whiteSpace: 'pre' }}>
                  {preview}
                </pre>
              </div>
            );
          })}
        </div>
      </div>

      {/* SEO Content */}
      <div style={{ marginTop: 30, paddingTop: 24, borderTop: '1px solid var(--border-color)' }}>
        <h2 style={{ fontSize: 20, fontWeight: 700, marginBottom: 12 }}>{t.introTitle}</h2>
        <p style={{ fontSize: 14, color: 'var(--text-secondary)', lineHeight: 1.7, marginBottom: 20 }}>{t.introText}</p>

        <h3 style={{ fontSize: 16, fontWeight: 600, marginBottom: 8 }}>{t.tipTitle}</h3>
        <ul style={{ paddingLeft: 20, marginBottom: 24, fontSize: 13, lineHeight: 2, color: 'var(--text-secondary)' }}>
          <li>{t.tip1}</li><li>{t.tip2}</li><li>{t.tip3}</li><li>{t.tip4}</li><li>{t.tip5}</li>
        </ul>

        <h3 style={{ fontSize: 16, fontWeight: 600, marginBottom: 8 }}>{t.faqTitle}</h3>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 8, marginBottom: 24 }}>
          {[
            { q: t.faq1q, a: t.faq1a }, { q: t.faq2q, a: t.faq2a }, { q: t.faq3q, a: t.faq3a },
            { q: t.faq4q, a: t.faq4a }, { q: t.faq5q, a: t.faq5a },
          ].map((faq, idx) => (
            <details key={idx} style={{ border: '1px solid var(--border-color)', borderRadius: 8, overflow: 'hidden', background: 'var(--bg-input)' }}>
              <summary style={{ padding: '14px 16px', cursor: 'pointer', fontSize: 14, fontWeight: 600, color: 'var(--text-primary)' }}>{faq.q}</summary>
              <div style={{ padding: '0 16px 14px', fontSize: 13, lineHeight: 1.7, color: 'var(--text-secondary)' }}>{faq.a}</div>
            </details>
          ))}
        </div>

        <h3 style={{ fontSize: 16, fontWeight: 600, marginBottom: 8 }}>{t.relatedTitle}</h3>
        <div style={{ display: 'flex', flexWrap: 'wrap', gap: 8 }}>
          {[
            { href: `/${lang}/tools/ascii-art`, label: 'ASCII Art Converter' },
            { href: `/${lang}/tools/lorem-ipsum`, label: 'Lorem Ipsum Generator' },
            { href: `/${lang}/tools/text-diff`, label: 'Text Diff' },
            { href: `/${lang}/tools/string-case`, label: 'String Case Converter' },
          ].map(link => (
            <Link key={link.href} href={link.href}
              style={{ display: 'inline-block', padding: '8px 16px', borderRadius: 8, border: '1px solid var(--border-color)', fontSize: 13, color: 'var(--accent-blue)', textDecoration: 'none', background: 'var(--bg-input)' }}>
              {link.label}
            </Link>
          ))}
        </div>
      </div>
    </ToolLayout>
  );
}
