export interface Tool {
  id: string;
  name: string;
  description: string;
  icon: string;
  category: string;
  keywords: string[];
  path: string;
  relatedTools?: string[];
}

export const categories = [
  { id: 'encoder', name: 'Encoder / Decoder', icon: '🔐' },
  { id: 'formatter', name: 'Formatter / Beautifier', icon: '✨' },
  { id: 'generator', name: 'Generator', icon: '⚡' },
  { id: 'converter', name: 'Converter', icon: '🔄' },
  { id: 'css', name: 'CSS Tools', icon: '🎨' },
  { id: 'text', name: 'Text Tools', icon: '📝' },
  { id: 'web', name: 'Web Tools', icon: '🌐' },
];

export const tools: Tool[] = [
  {
    id: 'json-formatter',
    name: 'JSON Formatter',
    description: 'Format, validate, and beautify JSON data with syntax highlighting',
    icon: '{ }',
    category: 'formatter',
    keywords: ['json', 'format', 'validate', 'beautify', 'pretty print', 'minify'],
    path: '/tools/json-formatter',
    relatedTools: ['json-yaml', 'csv-json', 'xml-formatter', 'json-to-typescript', 'json-viewer', 'json-validator'],
  },
  {
    id: 'base64',
    name: 'Base64 Encoder/Decoder',
    description: 'Encode text to Base64 or decode Base64 back to text',
    icon: 'B64',
    category: 'encoder',
    keywords: ['base64', 'encode', 'decode', 'binary', 'text'],
    path: '/tools/base64',
    relatedTools: ['base64-encoder', 'base64-decoder', 'url-encoder', 'image-base64'],
  },
  {
    id: 'url-encoder',
    name: 'URL Encoder/Decoder',
    description: 'Encode or decode URL components and query parameters',
    icon: '%20',
    category: 'encoder',
    keywords: ['url', 'encode', 'decode', 'uri', 'percent encoding', 'query string'],
    path: '/tools/url-encoder',
    relatedTools: ['url-decoder', 'url-encode-online', 'percent-encoding-tool', 'base64'],
  },
  {
    id: 'hash-generator',
    name: 'Hash Generator',
    description: 'Generate MD5, SHA-1, SHA-256, SHA-512 hashes from text',
    icon: '#',
    category: 'generator',
    keywords: ['hash', 'md5', 'sha1', 'sha256', 'sha512', 'checksum', 'digest', 'sha256 hash generator', 'multi hash generator', 'sha1 hash generator'],
    path: '/tools/hash-generator',
    relatedTools: ['multi-hash-generator', 'md5-hash-generator', 'sha256-hash-generator', 'hmac-generator'],
  },
  {
    id: 'multi-hash-generator',
    name: 'Multi Hash Generator',
    description: 'Generate MD5, SHA-1, SHA-256, SHA-384, SHA-512 hashes simultaneously from text or files',
    icon: '🔐',
    category: 'generator',
    keywords: ['multi hash', 'hash generator', 'md5 generator', 'sha256 generator', 'sha1 generator', 'sha512 generator', 'file hash', 'checksum calculator', 'hash all', 'all hashes at once'],
    path: '/tools/multi-hash-generator',
    relatedTools: ['hash-generator', 'hmac-generator', 'bcrypt-generator', 'password-generator'],
  },
  {
    id: 'uuid-generator',
    name: 'UUID Generator',
    description: 'Generate random UUIDs (v4) in bulk with one click',
    icon: 'ID',
    category: 'generator',
    keywords: ['uuid', 'guid', 'unique id', 'random', 'identifier', 'uuid v4', 'uuid v7', 'guid generator', 'online uuid generator'],
    path: '/tools/uuid-generator',
    relatedTools: ['password-generator', 'fake-data', 'qrcode-generator', 'hash-generator'],
  },
  {
    id: 'timestamp-converter',
    name: 'Unix Timestamp Converter',
    description: 'Convert between Unix timestamps and human-readable dates',
    icon: '🕐',
    category: 'converter',
    keywords: ['timestamp', 'unix', 'epoch', 'date', 'time', 'convert', 'convert unix timestamp to date', 'epoch converter', 'timestamp to datetime', 'date to timestamp'],
    path: '/tools/timestamp-converter',
    relatedTools: ['unix-timestamp-converter', 'cron-parser', 'json-formatter', 'number-base'],
  },
  {
    id: 'color-converter',
    name: 'Color Converter',
    description: 'Convert colors between HEX, RGB, HSL formats with preview',
    icon: '🎨',
    category: 'converter',
    keywords: ['color', 'hex', 'rgb', 'hsl', 'convert', 'picker', 'palette', 'hex to rgb', 'hex to pantone', 'color code converter', 'hexadecimal to rgb'],
    path: '/tools/color-converter',
    relatedTools: ['hex-to-rgb', 'color-palette', 'color-name-to-hex', 'tailwind-colors'],
  },
  {
    id: 'regex-tester',
    name: 'Regex Tester',
    description: 'Test regular expressions with real-time matching and highlighting',
    icon: '.*',
    category: 'text',
    keywords: ['regex', 'regular expression', 'pattern', 'match', 'test', 'replace', 'regex tester', 'regex debugger', 'javascript regex', 'python regex'],
    path: '/tools/regex-tester',
    relatedTools: ['regex-checker', 'regex-matcher', 'regex-generator', 'escape-unescape'],
  },
  {
    id: 'markdown-preview',
    name: 'Markdown Preview',
    description: 'Write Markdown and see the rendered preview side by side',
    icon: 'MD',
    category: 'text',
    keywords: ['markdown', 'preview', 'render', 'md', 'editor'],
    path: '/tools/markdown-preview',
    relatedTools: ['markdown-to-html', 'html-to-markdown', 'word-counter', 'text-diff'],
  },
  {
    id: 'jwt-decoder',
    name: 'JWT Decoder',
    description: 'Decode and inspect JSON Web Tokens (header, payload, signature)',
    icon: 'JWT',
    category: 'encoder',
    keywords: ['jwt', 'json web token', 'decode', 'header', 'payload', 'auth'],
    path: '/tools/jwt-decoder',
    relatedTools: ['jwt-token-decoder', 'jwt-parser', 'jwt-validator', 'base64-decoder'],
  },
  {
    id: 'qrcode-generator',
    name: 'QR Code Generator',
    description: 'Generate QR codes from text, URLs, or any data',
    icon: '▣',
    category: 'generator',
    keywords: ['qr', 'qrcode', 'barcode', 'generate', 'scan'],
    path: '/tools/qrcode-generator',
    relatedTools: ['favicon-generator', 'placeholder-image', 'slug-generator', 'meta-tag-generator'],
  },
  {
    id: 'lorem-ipsum',
    name: 'Lorem Ipsum Generator',
    description: 'Generate placeholder text in paragraphs, sentences, or words',
    icon: 'Aa',
    category: 'generator',
    keywords: ['lorem', 'ipsum', 'placeholder', 'text', 'dummy', 'filler'],
    path: '/tools/lorem-ipsum',
    relatedTools: ['fake-data', 'word-counter', 'text-repeater', 'ascii-art'],
  },
  {
    id: 'html-entity',
    name: 'HTML Entity Encoder',
    description: 'Encode and decode HTML entities and special characters',
    icon: '&;',
    category: 'encoder',
    keywords: ['html', 'entity', 'encode', 'decode', 'escape', 'special characters'],
    path: '/tools/html-entity',
    relatedTools: ['escape-unescape', 'url-encoder', 'html-to-jsx', 'percent-encoding-tool'],
  },
  {
    id: 'css-minifier',
    name: 'CSS Minifier / Beautifier',
    description: 'Minify or beautify CSS code for production or readability',
    icon: '{ }',
    category: 'css',
    keywords: ['css', 'minify', 'beautify', 'compress', 'format', 'style'],
    path: '/tools/css-minifier',
    relatedTools: ['js-html-formatter', 'css-to-tailwind', 'css-gradient', 'css-to-js'],
  },
  {
    id: 'number-base',
    name: 'Number Base Converter',
    description: 'Convert numbers between binary, octal, decimal, and hexadecimal',
    icon: '01',
    category: 'converter',
    keywords: ['binary', 'octal', 'decimal', 'hex', 'convert', 'base', 'number'],
    path: '/tools/number-base',
    relatedTools: ['hex-to-decimal', 'hex-to-binary', 'octal-decimal-converter', 'binary-text'],
  },
  {
    id: 'text-diff',
    name: 'Text Diff Checker',
    description: 'Compare two texts and highlight the differences',
    icon: '±',
    category: 'text',
    keywords: ['diff', 'compare', 'difference', 'text', 'merge'],
    path: '/tools/text-diff',
    relatedTools: ['word-counter', 'line-sorter', 'string-case', 'markdown-preview'],
  },
  {
    id: 'word-counter',
    name: 'Word Counter',
    description: 'Count words, characters, sentences, and paragraphs in text',
    icon: '123',
    category: 'text',
    keywords: ['word', 'count', 'character', 'sentence', 'paragraph', 'length'],
    path: '/tools/word-counter',
    relatedTools: ['text-diff', 'lorem-ipsum', 'text-repeater', 'line-sorter'],
  },
  {
    id: 'password-generator',
    name: 'Password Generator',
    description: 'Generate secure random passwords with customizable options',
    icon: '🔑',
    category: 'generator',
    keywords: ['password', 'generate', 'random', 'secure', 'strong'],
    path: '/tools/password-generator',
    relatedTools: ['bcrypt-generator', 'hash-generator', 'uuid-generator', 'fake-data'],
  },
  {
    id: 'sql-formatter',
    name: 'SQL Formatter',
    description: 'Format and beautify SQL queries for better readability',
    icon: 'SQL',
    category: 'formatter',
    keywords: ['sql', 'format', 'beautify', 'query', 'database'],
    path: '/tools/sql-formatter',
    relatedTools: ['sql-to-prisma', 'json-formatter', 'xml-formatter', 'csv-json'],
  },
  {
    id: 'cron-parser',
    name: 'Cron Expression Parser',
    description: 'Parse and explain cron expressions with next run times',
    icon: '⏰',
    category: 'web',
    keywords: ['cron', 'schedule', 'parse', 'expression', 'time', 'job'],
    path: '/tools/cron-parser',
    relatedTools: ['cron-generator', 'crontab-generator', 'cron-job-scheduler', 'cron-expression-parser'],
  },
  {
    id: 'json-yaml',
    name: 'JSON ↔ YAML Converter',
    description: 'Convert between JSON and YAML formats instantly',
    icon: 'Y{}',
    category: 'converter',
    keywords: ['json', 'yaml', 'yml', 'convert', 'config', 'configuration', 'json to yaml', 'yaml to json', 'json to yaml converter', 'yaml to json converter', 'convert json to yaml', 'convert yaml to json'],
    path: '/tools/json-yaml',
    relatedTools: ['yaml-json-converter', 'yaml-validator', 'json-formatter', 'toml-yaml'],
  },
  {
    id: 'string-case',
    name: 'String Case Converter',
    description: 'Convert text between camelCase, snake_case, kebab-case, and more',
    icon: 'Aa',
    category: 'text',
    keywords: ['case', 'camel', 'snake', 'kebab', 'pascal', 'convert', 'string', 'naming'],
    path: '/tools/string-case',
    relatedTools: ['slug-generator', 'word-counter', 'text-repeater', 'line-sorter'],
  },
  {
    id: 'slug-generator',
    name: 'URL Slug Generator',
    description: 'Convert text to SEO-friendly URL slugs',
    icon: '🔗',
    category: 'web',
    keywords: ['slug', 'url', 'seo', 'permalink', 'friendly', 'generate'],
    path: '/tools/slug-generator',
    relatedTools: ['url-encoder', 'string-case', 'meta-tag-generator', 'url-parser'],
  },
  {
    id: 'line-sorter',
    name: 'Line Sort & Dedup',
    description: 'Sort lines, remove duplicates, reverse, shuffle, and more',
    icon: '↕️',
    category: 'text',
    keywords: ['sort', 'lines', 'deduplicate', 'unique', 'reverse', 'shuffle', 'alphabetical'],
    path: '/tools/line-sorter',
    relatedTools: ['text-diff', 'word-counter', 'string-case', 'lorem-ipsum'],
  },
  {
    id: 'js-html-formatter',
    name: 'JS/HTML Formatter',
    description: 'Minify or beautify JavaScript and HTML code',
    icon: 'JS',
    category: 'formatter',
    keywords: ['javascript', 'html', 'minify', 'beautify', 'compress', 'format', 'uglify'],
    path: '/tools/js-html-formatter',
    relatedTools: ['css-minifier', 'json-formatter', 'html-to-jsx', 'xml-formatter'],
  },
  {
    id: 'image-base64',
    name: 'Image Base64 Converter',
    description: 'Convert images to Base64 strings and data URIs with drag & drop',
    icon: '🖼️',
    category: 'encoder',
    keywords: ['image', 'base64', 'convert', 'data uri', 'encode', 'decode', 'png', 'jpg', 'svg'],
    path: '/tools/image-base64',
    relatedTools: ['base64', 'base64-encoder', 'svg-optimizer', 'placeholder-image'],
  },
  {
    id: 'git-command-generator',
    name: 'Git Command Generator',
    description: 'Visual Git command builder — select an action, fill in parameters, copy the command',
    icon: '🔀',
    category: 'web',
    keywords: ['git', 'command', 'generator', 'branch', 'merge', 'rebase', 'commit', 'push', 'pull', 'stash'],
    path: '/tools/git-command-generator',
    relatedTools: ['gitignore-generator', 'slug-generator', 'cron-parser', 'docker-compose-generator'],
  },
  {
    id: 'xml-formatter',
    name: 'XML Formatter',
    description: 'Format, minify, and validate XML with syntax highlighting',
    icon: '<>',
    category: 'formatter',
    keywords: ['xml', 'format', 'minify', 'validate', 'beautify', 'pretty print'],
    path: '/tools/xml-formatter',
    relatedTools: ['xml-to-json', 'json-formatter', 'html-entity', 'json-yaml'],
  },
  {
    id: 'csv-json',
    name: 'CSV ↔ JSON Converter',
    description: 'Convert between CSV and JSON formats instantly',
    icon: '📊',
    category: 'converter',
    keywords: ['csv', 'json', 'convert', 'spreadsheet', 'data', 'export', 'json to csv', 'csv to json', 'json to csv converter', 'csv to json converter', 'convert json to csv', 'convert csv to json'],
    path: '/tools/csv-json',
    relatedTools: ['json-formatter', 'json-to-table', 'html-table', 'xml-to-json'],
  },
  {
    id: 'http-status',
    name: 'HTTP Status Code Reference',
    description: 'Lookup HTTP status codes with meanings and use cases',
    icon: '4xx',
    category: 'web',
    keywords: ['http', 'status code', '404', '500', '200', 'reference', 'api'],
    path: '/tools/http-status',
    relatedTools: ['curl-to-code', 'url-parser', 'csp-generator', 'meta-tag-generator'],
  },
  {
    id: 'mime-types',
    name: 'MIME Type Lookup',
    description: 'Find MIME types by file extension or content type',
    icon: '📄',
    category: 'web',
    keywords: ['mime', 'content-type', 'file extension', 'lookup', 'media type'],
    path: '/tools/mime-types',
    relatedTools: ['http-status', 'url-parser', 'html-entity', 'pem-decoder'],
  },
  {
    id: 'escape-unescape',
    name: 'Escape / Unescape',
    description: 'Escape or unescape HTML, JavaScript, and JSON strings',
    icon: '\\',
    category: 'encoder',
    keywords: ['escape', 'unescape', 'html', 'javascript', 'json', 'encode', 'decode'],
    path: '/tools/escape-unescape',
    relatedTools: ['html-entity', 'url-encoder', 'base64', 'json-formatter'],
  },
  {
    id: 'ip-calculator',
    name: 'IP Subnet Calculator',
    description: 'Calculate subnet mask, network, broadcast, and host range',
    icon: '🌐',
    category: 'converter',
    keywords: ['ip', 'subnet', 'calculator', 'cidr', 'network', 'broadcast'],
    path: '/tools/ip-calculator',
    relatedTools: ['ip-to-binary', 'number-base', 'binary-text', 'hex-to-decimal'],
  },
  {
    id: 'fake-data',
    name: 'Fake Data Generator',
    description: 'Generate fake names, emails, addresses for testing',
    icon: '👤',
    category: 'generator',
    keywords: ['fake', 'test data', 'mock', 'names', 'emails', 'addresses'],
    path: '/tools/fake-data',
    relatedTools: ['lorem-ipsum', 'uuid-generator', 'password-generator', 'qrcode-generator'],
  },
  {
    id: 'hmac-generator',
    name: 'HMAC Generator',
    description: 'Generate HMAC-SHA256, HMAC-SHA1 from message and secret key',
    icon: '🔐',
    category: 'generator',
    keywords: ['hmac', 'sha256', 'sha1', 'signature', 'api', 'webhook'],
    path: '/tools/hmac-generator',
    relatedTools: ['hash-generator', 'multi-hash-generator', 'bcrypt-generator', 'password-generator'],
  },
  {
    id: 'url-parser',
    name: 'URL Parser',
    description: 'Parse URL into components: protocol, host, path, query params',
    icon: '🔗',
    category: 'web',
    keywords: ['url', 'parse', 'components', 'host', 'path', 'query', 'params'],
    path: '/tools/url-parser',
    relatedTools: ['url-encoder', 'slug-generator', 'http-status', 'curl-to-code'],
  },
  {
    id: 'binary-text',
    name: 'Text ↔ Binary Converter',
    description: 'Convert text to binary and binary to text',
    icon: '01',
    category: 'converter',
    keywords: ['binary', 'text', 'convert', 'ascii', 'utf8', 'encoding'],
    path: '/tools/binary-text',
    relatedTools: ['number-base', 'hex-to-binary', 'ascii-text-converter', 'base64'],
  },
  {
    id: 'pem-decoder',
    name: 'PEM / Certificate Decoder',
    description: 'Decode PEM certificates and view certificate details',
    icon: '📜',
    category: 'encoder',
    keywords: ['pem', 'certificate', 'ssl', 'tls', 'decode', 'x509'],
    path: '/tools/pem-decoder',
    relatedTools: ['jwt-decoder', 'base64-decoder', 'hash-generator', 'password-generator'],
  },
  {
    id: 'html-table',
    name: 'HTML Table Generator',
    description: 'Convert CSV or JSON to HTML table markup',
    icon: '📋',
    category: 'converter',
    keywords: ['html', 'table', 'csv', 'json', 'markup', 'generate'],
    path: '/tools/html-table',
    relatedTools: ['csv-json', 'json-to-table', 'json-formatter', 'xml-formatter'],
  },
  {
    id: 'bcrypt-generator',
    name: 'Bcrypt Hash Generator',
    description: 'Generate bcrypt password hashes with configurable cost',
    icon: '🔒',
    category: 'generator',
    keywords: ['bcrypt', 'hash', 'password', 'generate', 'security'],
    path: '/tools/bcrypt-generator',
    relatedTools: ['hash-generator', 'multi-hash-generator', 'hmac-generator', 'password-generator'],
  },
  // P0 — Code conversion tools (competing with transform.tools)
  {
    id: 'json-to-typescript',
    name: 'JSON to TypeScript',
    description: 'Convert JSON to TypeScript interfaces and types online',
    icon: 'TS',
    category: 'converter',
    keywords: ['json', 'typescript', 'interface', 'type', 'convert', 'ts', 'json to typescript', 'json to ts', 'json to typescript converter', 'convert json to typescript'],
    path: '/tools/json-to-typescript',
    relatedTools: ['json-formatter', 'json-to-go', 'json-to-java', 'json-to-zod', 'json-to-json-schema'],
  },
  {
    id: 'html-to-jsx',
    name: 'HTML to JSX',
    description: 'Convert HTML markup to JSX for React components',
    icon: 'JSX',
    category: 'converter',
    keywords: ['html', 'jsx', 'react', 'convert', 'component', 'html to jsx', 'html to react', 'html to jsx converter', 'convert html to jsx'],
    path: '/tools/html-to-jsx',
    relatedTools: ['svg-to-jsx', 'js-html-formatter', 'html-entity', 'html-to-markdown'],
  },
  {
    id: 'json-to-go',
    name: 'JSON to Go Struct',
    description: 'Convert JSON data to Go struct definitions',
    icon: 'Go',
    category: 'converter',
    keywords: ['json', 'go', 'golang', 'struct', 'convert', 'json to go struct', 'json to golang', 'json to go struct converter', 'convert json to go', 'json to go online'],
    path: '/tools/json-to-go',
    relatedTools: ['json-to-typescript', 'json-to-rust', 'json-to-java', 'json-formatter'],
  },
  {
    id: 'svg-to-jsx',
    name: 'SVG to JSX/React',
    description: 'Convert SVG markup to JSX React components',
    icon: 'SVG',
    category: 'converter',
    keywords: ['svg', 'jsx', 'react', 'component', 'convert', 'icon', 'svg to jsx', 'svg to react', 'svg to jsx converter', 'convert svg to jsx', 'svg to react component', 'svg to jsx online'],
    path: '/tools/svg-to-jsx',
    relatedTools: ['html-to-jsx', 'css-to-tailwind', 'image-base64', 'js-html-formatter', 'svg-optimizer'],
  },
  {
    id: 'css-to-tailwind',
    name: 'CSS to Tailwind',
    description: 'Convert CSS styles to Tailwind CSS utility classes',
    icon: 'TW',
    category: 'css',
    keywords: ['css', 'tailwind', 'convert', 'utility', 'classes', 'style'],
    path: '/tools/css-to-tailwind',
    relatedTools: ['css-minifier', 'css-to-js', 'html-to-jsx', 'svg-to-jsx'],
  },
  {
    id: 'typescript-to-javascript',
    name: 'TypeScript to JavaScript',
    description: 'Compile TypeScript code to plain JavaScript',
    icon: 'JS',
    category: 'converter',
    keywords: ['typescript', 'javascript', 'compile', 'convert', 'ts', 'js', 'typescript to javascript', 'ts to js', 'ts to js converter', 'ts to js online', 'typescript to javascript converter', 'convert typescript to javascript', 'typescript compiler online'],
    path: '/tools/typescript-to-javascript',
    relatedTools: ['json-to-typescript', 'js-html-formatter', 'html-to-jsx', 'graphql-to-typescript', 'svg-to-jsx'],
  },
  // P1 tools
  {
    id: 'json-to-graphql',
    name: 'JSON to GraphQL',
    description: 'Convert JSON data to GraphQL schema definitions',
    icon: 'GQL',
    category: 'converter',
    keywords: ['json', 'graphql', 'schema', 'convert', 'api', 'query'],
    path: '/tools/json-to-graphql',
    relatedTools: ['json-to-typescript', 'json-to-go', 'json-to-java', 'graphql-to-typescript'],
  },
  {
    id: 'json-to-java',
    name: 'JSON to Java Class',
    description: 'Convert JSON data to Java class definitions',
    icon: 'JV',
    category: 'converter',
    keywords: ['json', 'java', 'class', 'pojo', 'convert', 'bean', 'json to java', 'json to java class', 'json to pojo', 'json to java converter'],
    path: '/tools/json-to-java',
    relatedTools: ['json-to-kotlin', 'json-to-typescript', 'json-to-csharp', 'json-to-go'],
  },
  {
    id: 'json-to-kotlin',
    name: 'JSON to Kotlin',
    description: 'Convert JSON data to Kotlin data classes',
    icon: 'KT',
    category: 'converter',
    keywords: ['json', 'kotlin', 'data class', 'convert', 'android', 'json to kotlin', 'json to kotlin data class', 'json to kotlin converter', 'convert json to kotlin'],
    path: '/tools/json-to-kotlin',
    relatedTools: ['json-to-java', 'json-to-typescript', 'json-to-python', 'json-to-go'],
  },
  {
    id: 'json-to-python',
    name: 'JSON to Python',
    description: 'Convert JSON data to Python dataclass or TypedDict',
    icon: 'PY',
    category: 'converter',
    keywords: ['json', 'python', 'dataclass', 'typeddict', 'convert', 'pydantic', 'json to python', 'json to python dataclass', 'json to python converter', 'convert json to python'],
    path: '/tools/json-to-python',
    relatedTools: ['json-to-kotlin', 'json-to-java', 'json-to-typescript', 'json-to-go'],
  },
  {
    id: 'json-to-csharp',
    name: 'JSON to C#',
    description: 'Convert JSON data to C# class definitions',
    icon: 'C#',
    category: 'converter',
    keywords: ['json', 'csharp', 'c#', 'class', 'convert', 'dotnet', '.net', 'json to c#', 'json to csharp', 'json to c# class', 'json to csharp converter'],
    path: '/tools/json-to-csharp',
    relatedTools: ['json-to-java', 'json-to-typescript', 'json-to-kotlin', 'json-to-go'],
  },
  {
    id: 'markdown-to-html',
    name: 'Markdown to HTML',
    description: 'Convert Markdown text to HTML markup',
    icon: 'MD',
    category: 'converter',
    keywords: ['markdown', 'html', 'convert', 'markup', 'md'],
    path: '/tools/markdown-to-html',
    relatedTools: ['html-to-markdown', 'markdown-preview', 'html-to-jsx', 'html-entity'],
  },
  {
    id: 'html-to-markdown',
    name: 'HTML to Markdown',
    description: 'Convert HTML markup to Markdown text',
    icon: 'HM',
    category: 'converter',
    keywords: ['html', 'markdown', 'convert', 'markup', 'md'],
    path: '/tools/html-to-markdown',
    relatedTools: ['markdown-to-html', 'markdown-preview', 'html-to-jsx', 'html-entity'],
  },
  {
    id: 'toml-yaml',
    name: 'TOML ↔ YAML',
    description: 'Convert between TOML and YAML formats',
    icon: 'TY',
    category: 'converter',
    keywords: ['toml', 'yaml', 'convert', 'config', 'configuration'],
    path: '/tools/toml-yaml',
    relatedTools: ['json-yaml', 'json-formatter', 'xml-formatter', 'csv-json'],
  },
  // P2 tools
  {
    id: 'json-to-zod',
    name: 'JSON to Zod Schema',
    description: 'Convert JSON data to Zod validation schemas',
    icon: 'ZD',
    category: 'converter',
    keywords: ['json', 'zod', 'schema', 'validation', 'typescript', 'convert'],
    path: '/tools/json-to-zod',
    relatedTools: ['json-to-typescript', 'json-to-json-schema', 'json-formatter', 'json-to-graphql'],
  },
  {
    id: 'json-to-json-schema',
    name: 'JSON to JSON Schema Generator',
    description: 'Generate JSON Schema from JSON data — free JSON Schema generator',
    icon: 'JS',
    category: 'converter',
    keywords: ['json', 'json-schema', 'schema', 'validation', 'convert', 'json to json schema', 'json schema generator', 'create json schema from json', 'generate json schema from json', 'json schema from json', 'json to schema'],
    path: '/tools/json-to-json-schema',
    relatedTools: ['json-to-zod', 'json-to-typescript', 'json-formatter', 'json-validator', 'json-viewer'],
  },
  {
    id: 'css-to-js',
    name: 'CSS to JS Object',
    description: 'Convert CSS styles to JavaScript style objects',
    icon: 'CJ',
    category: 'css',
    keywords: ['css', 'javascript', 'style', 'object', 'convert', 'react'],
    path: '/tools/css-to-js',
    relatedTools: ['css-to-tailwind', 'html-to-jsx', 'css-minifier', 'svg-to-jsx'],
  },
  {
    id: 'graphql-to-typescript',
    name: 'GraphQL to TypeScript',
    description: 'Convert GraphQL schema to TypeScript types',
    icon: 'GT',
    category: 'converter',
    keywords: ['graphql', 'typescript', 'types', 'convert', 'codegen'],
    path: '/tools/graphql-to-typescript',
    relatedTools: ['json-to-graphql', 'json-to-typescript', 'typescript-to-javascript', 'json-to-go'],
  },
  {
    id: 'json-to-rust',
    name: 'JSON to Rust Struct',
    description: 'Convert JSON data to Rust struct definitions with serde',
    icon: 'RS',
    category: 'converter',
    keywords: ['json', 'rust', 'struct', 'serde', 'convert', 'derive', 'json to rust', 'json to rust struct', 'json to rust converter', 'convert json to rust'],
    path: '/tools/json-to-rust',
    relatedTools: ['json-to-go', 'json-to-typescript', 'json-to-csharp', 'json-to-java'],
  },
  {
    id: 'xml-to-json',
    name: 'XML to JSON Converter',
    description: 'Convert XML to JSON online free',
    icon: 'XJ',
    category: 'converter',
    keywords: ['xml', 'json', 'convert', 'markup', 'data', 'xml to json', 'xml to json converter', 'convert xml to json', 'xml to json online'],
    path: '/tools/xml-to-json',
    relatedTools: ['xml-formatter', 'json-formatter', 'json-yaml', 'csv-json'],
  },
  // CSS & Visual tools
  {
    id: 'css-gradient',
    name: 'CSS Gradient Generator',
    description: 'Create beautiful CSS gradients with a visual editor — linear, radial, and conic',
    icon: '🌈',
    category: 'css',
    keywords: ['css', 'gradient', 'linear-gradient', 'radial-gradient', 'conic-gradient', 'background', 'generator', 'color'],
    path: '/tools/css-gradient',
    relatedTools: ['box-shadow', 'color-converter', 'css-minifier', 'css-to-tailwind'],
  },
  {
    id: 'box-shadow',
    name: 'Box Shadow Generator',
    description: 'Design CSS box shadows visually with real-time preview and code output',
    icon: '🔲',
    category: 'css',
    keywords: ['box-shadow', 'css', 'shadow', 'drop shadow', 'generator', 'visual', 'design'],
    path: '/tools/box-shadow',
    relatedTools: ['css-gradient', 'color-converter', 'css-minifier', 'css-to-tailwind'],
  },
  // SEO tools
  {
    id: 'meta-tag-generator',
    name: 'Meta Tag Generator',
    description: 'Generate HTML meta tags, Open Graph, and Twitter Card tags for SEO',
    icon: '🏷️',
    category: 'web',
    keywords: ['meta tag', 'og tag', 'open graph', 'twitter card', 'seo', 'html', 'head'],
    path: '/tools/meta-tag-generator',
    relatedTools: ['schema-generator', 'robots-generator', 'slug-generator', 'html-entity'],
  },
  {
    id: 'schema-generator',
    name: 'Schema Markup Generator',
    description: 'Generate JSON-LD structured data for Article, FAQ, HowTo, and more',
    icon: '📐',
    category: 'web',
    keywords: ['schema', 'json-ld', 'structured data', 'seo', 'rich snippets', 'markup', 'google'],
    path: '/tools/schema-generator',
    relatedTools: ['meta-tag-generator', 'robots-generator', 'json-formatter', 'slug-generator'],
  },
  {
    id: 'robots-generator',
    name: 'Robots.txt Generator',
    description: 'Generate robots.txt files with user-agent rules, allow/disallow paths, and sitemap',
    icon: '🤖',
    category: 'web',
    keywords: ['robots.txt', 'robots', 'crawler', 'seo', 'sitemap', 'user-agent', 'disallow'],
    path: '/tools/robots-generator',
    relatedTools: ['meta-tag-generator', 'schema-generator', 'slug-generator', 'url-parser'],
  },
  // JSON tools
  {
    id: 'json-viewer',
    name: 'JSON Viewer / Tree',
    description: 'View JSON data as an interactive collapsible tree with search and path display',
    icon: '🌳',
    category: 'formatter',
    keywords: ['json', 'viewer', 'tree', 'visualizer', 'explorer', 'collapsible', 'interactive'],
    path: '/tools/json-viewer',
    relatedTools: ['json-formatter', 'json-yaml', 'json-to-typescript', 'csv-json'],
  },
  // Generator tools
  {
    id: 'favicon-generator',
    name: 'Favicon Generator',
    description: 'Create favicons from text or emoji with custom colors and sizes',
    icon: '⭐',
    category: 'generator',
    keywords: ['favicon', 'ico', 'icon', 'generator', 'website', 'tab icon', 'bookmark'],
    path: '/tools/favicon-generator',
    relatedTools: ['placeholder-image', 'qrcode-generator', 'color-converter', 'meta-tag-generator'],
  },
  {
    id: 'ascii-art',
    name: 'ASCII Art Generator',
    description: 'Convert text to ASCII art with multiple font styles',
    icon: 'A>',
    category: 'text',
    keywords: ['ascii', 'art', 'text art', 'figlet', 'banner', 'font', 'generator'],
    path: '/tools/ascii-art',
    relatedTools: ['string-case', 'word-counter', 'lorem-ipsum', 'markdown-preview'],
  },
  {
    id: 'svg-optimizer',
    name: 'SVG Optimizer',
    description: 'Optimize and minify SVG files — remove metadata, comments, and unnecessary attributes',
    icon: '💎',
    category: 'formatter',
    keywords: ['svg', 'optimize', 'minify', 'compress', 'clean', 'svgo'],
    path: '/tools/svg-optimizer',
    relatedTools: ['svg-to-jsx', 'image-base64', 'css-minifier', 'js-html-formatter'],
  },
  {
    id: 'placeholder-image',
    name: 'Placeholder Image Generator',
    description: 'Generate placeholder images with custom dimensions, colors, and text',
    icon: '🖼️',
    category: 'generator',
    keywords: ['placeholder', 'image', 'dummy', 'generator', 'dimensions', 'mockup'],
    path: '/tools/placeholder-image',
    relatedTools: ['favicon-generator', 'image-base64', 'qrcode-generator', 'color-converter'],
  },
  // Round 2 — CSS & Visual tools
  {
    id: 'color-palette',
    name: 'Color Palette Generator',
    description: 'Generate harmonious color palettes — complementary, analogous, triadic, tetradic schemes',
    icon: '🎨',
    category: 'css',
    keywords: ['color palette', 'color scheme', 'complementary', 'analogous', 'triadic', 'tetradic', 'harmony', 'generator'],
    path: '/tools/color-palette',
    relatedTools: ['color-converter', 'tailwind-colors', 'css-gradient', 'box-shadow'],
  },
  {
    id: 'flexbox-generator',
    name: 'Flexbox Generator',
    description: 'Visual Flexbox layout builder — configure direction, justify, align, wrap, and gap with live preview',
    icon: '📐',
    category: 'css',
    keywords: ['flexbox', 'flex', 'layout', 'css', 'direction', 'justify-content', 'align-items', 'wrap', 'gap'],
    path: '/tools/flexbox-generator',
    relatedTools: ['css-gradient', 'border-radius', 'box-shadow', 'css-minifier'],
  },
  {
    id: 'emoji-picker',
    name: 'Emoji Picker & Search',
    description: 'Browse and search emojis by category, copy Unicode, HTML entity, and shortcode',
    icon: '😀',
    category: 'text',
    keywords: ['emoji', 'picker', 'search', 'unicode', 'emoticon', 'smiley', 'copy', 'html entity'],
    path: '/tools/emoji-picker',
    relatedTools: ['html-entity', 'string-case', 'word-counter', 'ascii-art'],
  },
  {
    id: 'border-radius',
    name: 'Border Radius Generator',
    description: 'Design CSS border-radius with independent corner control and live preview',
    icon: '◻️',
    category: 'css',
    keywords: ['border-radius', 'css', 'rounded corners', 'generator', 'preview', 'design'],
    path: '/tools/border-radius',
    relatedTools: ['box-shadow', 'css-gradient', 'flexbox-generator', 'css-minifier'],
  },
  {
    id: 'css-unit-converter',
    name: 'CSS Unit Converter',
    description: 'Convert between px, rem, em, vw, vh, pt, and % with configurable root font-size',
    icon: 'px',
    category: 'css',
    keywords: ['css', 'unit', 'converter', 'px', 'rem', 'em', 'vw', 'vh', 'pt', 'percent', 'font-size'],
    path: '/tools/css-unit-converter',
    relatedTools: ['css-minifier', 'color-converter', 'number-base', 'flexbox-generator'],
  },
  {
    id: 'og-image-preview',
    name: 'Open Graph Image Preview',
    description: 'Preview how your page looks when shared on Facebook, Twitter, LinkedIn, and Discord',
    icon: '👁️',
    category: 'web',
    keywords: ['open graph', 'og image', 'social preview', 'facebook', 'twitter', 'linkedin', 'discord', 'share'],
    path: '/tools/og-image-preview',
    relatedTools: ['meta-tag-generator', 'schema-generator', 'slug-generator', 'favicon-generator'],
  },
  {
    id: 'tailwind-colors',
    name: 'Tailwind CSS Color Picker',
    description: 'Browse the full Tailwind CSS color palette — search, copy class names, HEX, and RGB values',
    icon: 'TW',
    category: 'css',
    keywords: ['tailwind', 'css', 'color', 'palette', 'picker', 'class', 'hex', 'rgb', 'utility'],
    path: '/tools/tailwind-colors',
    relatedTools: ['color-palette', 'color-converter', 'css-to-tailwind', 'css-gradient'],
  },
  // Round 3 — Blue ocean tools
  {
    id: 'curl-to-code',
    name: 'cURL to Code Converter',
    description: 'Convert cURL commands to Python, JavaScript, Go, PHP, Ruby, Java, and more',
    icon: '>>',
    category: 'converter',
    keywords: ['curl', 'curl to python', 'curl to javascript', 'curl to fetch', 'curl to go', 'curl converter', 'http request'],
    path: '/tools/curl-to-code',
    relatedTools: ['url-parser', 'json-formatter', 'http-status', 'url-encoder', 'html-entity'],
  },
  {
    id: 'yaml-validator',
    name: 'YAML Validator & Formatter',
    description: 'Validate, lint, and format YAML with error highlighting and auto-fix suggestions',
    icon: 'YML',
    category: 'formatter',
    keywords: ['yaml', 'validator', 'lint', 'yaml checker', 'yaml formatter', 'yaml beautify', 'kubernetes', 'docker compose'],
    path: '/tools/yaml-validator',
    relatedTools: ['json-yaml', 'toml-yaml', 'json-formatter', 'xml-formatter'],
  },
  {
    id: 'gitignore-generator',
    name: '.gitignore Generator',
    description: 'Generate .gitignore files for any language, framework, IDE, or OS',
    icon: '.gi',
    category: 'generator',
    keywords: ['gitignore', 'git', 'ignore', 'template', 'generator', 'node', 'python', 'java', 'vscode'],
    path: '/tools/gitignore-generator',
    relatedTools: ['git-command-generator', 'robots-generator', 'slug-generator', 'password-generator'],
  },
  {
    id: 'json-to-dart',
    name: 'JSON to Dart',
    description: 'Convert JSON data to Dart classes with fromJson/toJson for Flutter',
    icon: 'DT',
    category: 'converter',
    keywords: ['json', 'dart', 'flutter', 'class', 'convert', 'fromJson', 'toJson', 'model', 'json to dart', 'json to dart converter', 'json to flutter', 'convert json to dart'],
    path: '/tools/json-to-dart',
    relatedTools: ['json-to-typescript', 'json-to-kotlin', 'json-to-python', 'json-formatter'],
  },
  {
    id: 'nginx-config',
    name: 'Nginx Config Generator',
    description: 'Generate Nginx configuration for reverse proxy, SSL, static sites, and more',
    icon: 'NX',
    category: 'web',
    keywords: ['nginx', 'config', 'configuration', 'reverse proxy', 'ssl', 'https', 'server block', 'load balancer'],
    path: '/tools/nginx-config',
    relatedTools: ['htaccess-generator', 'csp-generator', 'robots-generator', 'meta-tag-generator'],
  },
  {
    id: 'htaccess-generator',
    name: '.htaccess Generator',
    description: 'Generate .htaccess files for redirects, security headers, caching, and URL rewriting',
    icon: '.ht',
    category: 'web',
    keywords: ['htaccess', 'redirect', '301', 'apache', 'rewrite', 'mod_rewrite', 'security headers', 'caching'],
    path: '/tools/htaccess-generator',
    relatedTools: ['nginx-config', 'robots-generator', 'csp-generator', 'slug-generator'],
  },
  {
    id: 'docker-compose-generator',
    name: 'Docker Compose Generator',
    description: 'Build docker-compose.yml visually with service presets for popular stacks',
    icon: '🐳',
    category: 'generator',
    keywords: ['docker', 'docker-compose', 'compose', 'container', 'yaml', 'service', 'postgresql', 'redis', 'mongodb'],
    path: '/tools/docker-compose-generator',
    relatedTools: ['yaml-validator', 'json-yaml', 'nginx-config', 'cron-parser'],
  },
  {
    id: 'json-to-protobuf',
    name: 'JSON to Protobuf',
    description: 'Convert JSON data to Protocol Buffers (.proto) schema definitions',
    icon: 'PB',
    category: 'converter',
    keywords: ['json', 'protobuf', 'protocol buffers', 'proto', 'grpc', 'schema', 'convert', 'microservices'],
    path: '/tools/json-to-protobuf',
    relatedTools: ['json-to-graphql', 'json-to-typescript', 'json-to-go', 'json-formatter'],
  },
  {
    id: 'csp-generator',
    name: 'CSP Header Generator',
    description: 'Build Content-Security-Policy headers with interactive directive editor',
    icon: '🛡️',
    category: 'web',
    keywords: ['csp', 'content security policy', 'security headers', 'xss', 'header', 'directive', 'nonce'],
    path: '/tools/csp-generator',
    relatedTools: ['meta-tag-generator', 'htaccess-generator', 'nginx-config', 'robots-generator'],
  },
  {
    id: 'sql-to-prisma',
    name: 'SQL to Prisma Schema',
    description: 'Convert SQL CREATE TABLE statements to Prisma schema models',
    icon: 'PS',
    category: 'converter',
    keywords: ['sql', 'prisma', 'schema', 'orm', 'convert', 'model', 'typescript', 'database'],
    path: '/tools/sql-to-prisma',
    relatedTools: ['sql-formatter', 'json-to-typescript', 'json-to-graphql', 'json-formatter'],
  },
  {
    id: 'cron-generator',
    name: 'Cron Expression Generator',
    description: 'Build, validate, and understand cron expressions with a visual editor',
    icon: '⏰',
    category: 'generator',
    keywords: ['cron', 'crontab', 'schedule', 'timer', 'cron expression', 'cron job', 'automated', 'recurring'],
    path: '/tools/cron-generator',
    relatedTools: ['timestamp-converter', 'uuid-generator', 'password-generator'],
  },
  {
    id: 'text-to-pdf',
    name: 'Text to PDF Converter',
    description: 'Convert plain text to PDF documents with custom formatting options',
    icon: '📄',
    category: 'converter',
    keywords: ['text to pdf', 'convert text to pdf', 'txt to pdf', 'text to pdf converter', 'text file to pdf', 'plain text to pdf', 'notepad to pdf', 'convert txt to pdf online'],
    path: '/tools/text-to-pdf',
    relatedTools: ['markdown-to-html', 'word-counter', 'csv-json', 'html-to-markdown'],
  },
  {
    id: 'chmod-calculator',
    name: 'Chmod Calculator',
    description: 'Calculate and visualize Linux file permissions with an interactive chmod calculator',
    icon: '🔐',
    category: 'web',
    keywords: ['chmod', 'chmod calculator', 'linux permissions', 'file permissions', 'chmod 755', 'chmod 644', 'permission calculator', 'unix permissions', 'chmod command'],
    path: '/tools/chmod-calculator',
    relatedTools: ['password-generator', 'htaccess-generator', 'cron-generator'],
  },
  {
    id: 'hex-to-decimal',
    name: 'Hex to Decimal Converter',
    description: 'Convert between hexadecimal, decimal, and binary number systems',
    icon: '🔢',
    category: 'converter',
    keywords: ['hex to decimal', 'hex to decimal converter', 'hex to decimal calculator', 'decimal to hex', 'hexadecimal converter', 'hex converter', 'number base converter', 'convert hex to decimal'],
    path: '/tools/hex-to-decimal',
    relatedTools: ['base64-encoder', 'binary-text', 'url-encoder'],
  },
  {
    id: 'yaml-json-converter',
    name: 'YAML ↔ JSON Converter',
    description: 'Convert between YAML and JSON formats with real-time preview',
    icon: '🔄',
    category: 'converter',
    keywords: ['yaml to json', 'json to yaml', 'yaml to json converter', 'json to yaml converter', 'convert yaml to json', 'yaml json', 'yaml converter', 'json converter'],
    path: '/tools/yaml-json-converter',
    relatedTools: ['json-formatter', 'yaml-validator', 'csv-json', 'xml-to-json'],
  },
  {
    id: 'hex-to-rgb',
    name: 'Hex to RGB Converter',
    description: 'Convert between hex color codes and RGB values with color preview',
    icon: '🎨',
    category: 'converter',
    keywords: ['hex to rgb', 'hex to rgb converter', 'hex to rgb color', 'rgb to hex', 'hex color to rgb', 'hex to rgb calculator', 'convert hex to rgb', 'hex to rgb color converter', 'hex to rgb conversion', 'color converter'],
    path: '/tools/hex-to-rgb',
    relatedTools: ['hex-to-decimal', 'css-gradient', 'color-converter', 'css-shadow'],
  },
  {
    id: 'octal-decimal-converter',
    name: 'Octal Decimal Converter',
    description: 'Convert between octal and decimal number systems with binary and hex output',
    icon: '8️⃣',
    category: 'converter',
    keywords: ['octal to decimal', 'decimal to octal', 'octal to decimal converter', 'octal to decimal calculator', 'decimal to octal converter', 'decimal to octal calculator', 'octal converter', 'convert octal to decimal', 'octal number converter'],
    path: '/tools/octal-decimal-converter',
    relatedTools: ['hex-to-decimal', 'binary-text', 'base64', 'chmod-calculator'],
  },
  {
    id: 'roman-numeral-converter',
    name: 'Roman Numeral Converter',
    description: 'Convert between numbers and Roman numerals with date converter',
    icon: 'IV',
    category: 'converter',
    keywords: ['roman numeral converter', 'roman numerals converter', 'roman numeral date converter', 'convert to roman numerals', 'roman numeral birthday converter', 'number to roman numeral', 'roman numeral calculator', 'roman numerals'],
    path: '/tools/roman-numeral-converter',
    relatedTools: ['hex-to-decimal', 'octal-decimal-converter', 'number-base-converter'],
  },
  {
    id: 'byte-converter',
    name: 'Byte Converter',
    description: 'Convert between bytes, KB, MB, GB, TB and other file size units',
    icon: '💾',
    category: 'converter',
    keywords: ['byte converter', 'kb to mb', 'mb to gb', 'gb to tb', 'file size converter', 'data size converter', 'bytes to kb', 'kb to gb', 'megabytes to gigabytes', 'storage converter'],
    path: '/tools/byte-converter',
    relatedTools: ['number-base-converter', 'hex-to-decimal', 'unit-converter'],
  },
  {
    id: 'ascii-text-converter',
    name: 'ASCII Text Converter',
    description: 'Convert between ASCII codes and text characters with reference table',
    icon: 'Aa',
    category: 'converter',
    keywords: ['ascii to text', 'text to ascii', 'ascii converter', 'ascii code converter', 'ascii table', 'ascii chart', 'character to ascii', 'ascii to string', 'ascii decoder', 'ascii encoder'],
    path: '/tools/ascii-text-converter',
    relatedTools: ['binary-text', 'hex-to-decimal', 'base64', 'unicode-converter'],
  },
  {
    id: 'hex-to-binary',
    name: 'Hex to Binary Converter',
    description: 'Convert between hexadecimal and binary number systems',
    icon: '🔄',
    category: 'converter',
    keywords: ['hex to binary', 'binary to hex', 'hexadecimal to binary', 'binary to hexadecimal', 'hex binary converter', 'convert hex to binary', 'hex to bin'],
    path: '/tools/hex-to-binary',
    relatedTools: ['hex-to-decimal', 'binary-text', 'octal-decimal-converter', 'number-base-converter'],
  },
  {
    id: 'fraction-decimal-converter',
    name: 'Fraction Decimal Converter',
    description: 'Convert between fractions and decimal numbers with simplification',
    icon: '½',
    category: 'converter',
    keywords: ['fraction to decimal', 'decimal to fraction', 'fraction converter', 'fraction calculator', 'convert fraction to decimal', 'decimal to fraction converter', 'simplify fraction'],
    path: '/tools/fraction-decimal-converter',
    relatedTools: ['hex-to-decimal', 'scientific-notation-converter', 'number-base-converter'],
  },
  {
    id: 'scientific-notation-converter',
    name: 'Scientific Notation Converter',
    description: 'Convert between scientific notation and standard numbers',
    icon: '🔬',
    category: 'converter',
    keywords: ['scientific notation converter', 'scientific notation calculator', 'scientific notation to standard form', 'standard form to scientific notation', 'e notation converter', 'exponential notation'],
    path: '/tools/scientific-notation-converter',
    relatedTools: ['fraction-decimal-converter', 'hex-to-decimal', 'number-base-converter'],
  },
  {
    id: 'color-name-to-hex',
    name: 'Color Name to Hex Converter',
    description: 'Convert CSS color names to hex codes, RGB and HSL values',
    icon: '🎨',
    category: 'css',
    keywords: ['color name to hex', 'css color names', 'color name converter', 'html color names', 'named colors', 'color names list', 'css colors', 'web colors', 'color name to rgb'],
    path: '/tools/color-name-to-hex',
    relatedTools: ['color-converter', 'hex-to-rgb', 'css-gradient', 'css-shadow'],
  },
  {
    id: 'text-repeater',
    name: 'Text Repeater',
    description: 'Repeat text or characters multiple times with separator options',
    icon: '🔁',
    category: 'text',
    keywords: ['text repeater', 'repeat text', 'text multiplier', 'repeat string', 'character repeater', 'text repeat generator', 'copy paste repeater', 'repeat words'],
    path: '/tools/text-repeater',
    relatedTools: ['lorem-ipsum', 'word-counter', 'text-diff', 'case-converter'],
  },
  {
    id: 'em-px-converter',
    name: 'Em/Px Converter',
    description: 'Convert between em, rem, px and other CSS units with base size control',
    icon: '📐',
    category: 'css',
    keywords: ['em to px', 'px to em', 'rem to px', 'px to rem', 'css unit converter', 'em px converter', 'rem converter', 'css units', 'font size converter'],
    path: '/tools/em-px-converter',
    relatedTools: ['css-gradient', 'css-shadow', 'css-flexbox', 'css-grid'],
  },
  {
    id: 'ip-to-binary',
    name: 'IP to Binary Converter',
    description: 'Convert IP addresses to binary and binary to IP format',
    icon: '🌐',
    category: 'converter',
    keywords: ['ip to binary', 'binary to ip', 'ip address binary', 'ip binary converter', 'convert ip to binary', 'ip address converter', 'ipv4 to binary', 'ip address to binary'],
    path: '/tools/ip-to-binary',
    relatedTools: ['ip-calculator', 'binary-text', 'hex-to-decimal', 'hex-to-binary'],
  },
  {
    id: 'unix-timestamp-converter',
    name: 'Unix Timestamp Converter',
    description: 'Convert between Unix timestamps and human-readable dates',
    icon: '⏱️',
    category: 'converter',
    keywords: ['unix timestamp converter', 'epoch converter', 'timestamp converter', 'unix time converter', 'epoch to date', 'date to timestamp', 'unix timestamp to date', 'epoch time converter'],
    path: '/tools/unix-timestamp-converter',
    relatedTools: ['cron-generator', 'uuid', 'json-formatter'],
  },
  // Programmatic SEO — Hash Generator variants
  {
    id: 'md5-hash-generator',
    name: 'MD5 Hash Generator',
    description: 'Generate MD5 hashes from text or files instantly. Free online MD5 checksum calculator',
    icon: 'M5',
    category: 'generator',
    keywords: ['md5', 'md5 hash', 'md5 generator', 'md5 hash generator', 'md5 checksum', 'md5 calculator', 'md5 online', 'generate md5'],
    path: '/tools/md5-hash-generator',
    relatedTools: ['hash-generator', 'sha256-hash-generator', 'sha1-hash-generator', 'sha512-hash-generator'],
  },
  {
    id: 'sha256-hash-generator',
    name: 'SHA-256 Hash Generator',
    description: 'Generate SHA-256 hashes from text instantly. Free online SHA256 hash calculator',
    icon: '256',
    category: 'generator',
    keywords: ['sha256', 'sha-256', 'sha256 hash', 'sha256 generator', 'sha256 hash generator', 'sha256 online', 'sha256 calculator', 'generate sha256'],
    path: '/tools/sha256-hash-generator',
    relatedTools: ['hash-generator', 'md5-hash-generator', 'sha1-hash-generator', 'sha512-hash-generator'],
  },
  {
    id: 'sha1-hash-generator',
    name: 'SHA-1 Hash Generator',
    description: 'Generate SHA-1 hashes from text instantly. Free online SHA1 hash calculator',
    icon: 'S1',
    category: 'generator',
    keywords: ['sha1', 'sha-1', 'sha1 hash', 'sha1 generator', 'sha1 hash generator', 'sha1 online', 'sha1 calculator', 'generate sha1'],
    path: '/tools/sha1-hash-generator',
    relatedTools: ['hash-generator', 'md5-hash-generator', 'sha256-hash-generator', 'sha512-hash-generator'],
  },
  {
    id: 'sha512-hash-generator',
    name: 'SHA-512 Hash Generator',
    description: 'Generate SHA-512 hashes from text instantly. Free online SHA512 hash calculator',
    icon: '512',
    category: 'generator',
    keywords: ['sha512', 'sha-512', 'sha512 hash', 'sha512 generator', 'sha512 hash generator', 'sha512 online', 'sha512 calculator', 'generate sha512'],
    path: '/tools/sha512-hash-generator',
    relatedTools: ['hash-generator', 'md5-hash-generator', 'sha256-hash-generator', 'sha1-hash-generator'],
  },
  // Programmatic SEO — Base64 variants
  {
    id: 'base64-encoder',
    name: 'Base64 Encoder',
    description: 'Encode text and strings to Base64 format instantly. Free online Base64 encoding tool',
    icon: 'B→',
    category: 'encoder',
    keywords: ['base64 encoder', 'base64 encode', 'text to base64', 'string to base64', 'base64 encoding', 'encode base64', 'base64 encode online'],
    path: '/tools/base64-encoder',
    relatedTools: ['base64', 'base64-decoder', 'url-encoder', 'hash-generator'],
  },
  {
    id: 'base64-decoder',
    name: 'Base64 Decoder',
    description: 'Decode Base64 strings back to plain text instantly. Free online Base64 decoding tool',
    icon: '→B',
    category: 'encoder',
    keywords: ['base64 decoder', 'base64 decode', 'base64 to text', 'base64 to string', 'base64 decoding', 'decode base64', 'base64 decode online'],
    path: '/tools/base64-decoder',
    relatedTools: ['base64', 'base64-encoder', 'url-encoder', 'jwt-decoder'],
  },
  {
    id: 'base64-to-hex',
    name: 'Base64 to Hex Converter',
    description: 'Convert between Base64 and hexadecimal formats. Free online Base64-Hex converter',
    icon: 'BH',
    category: 'converter',
    keywords: ['base64 to hex', 'hex to base64', 'base64 hex converter', 'base64 to hexadecimal', 'convert base64 to hex', 'hex base64'],
    path: '/tools/base64-to-hex',
    relatedTools: ['base64', 'hex-to-decimal', 'hex-to-binary', 'base64-encoder'],
  },
  {
    id: 'string-to-base64',
    name: 'String to Base64 Converter',
    description: 'Convert strings to Base64 encoding with UTF-8 support. Free online string encoder',
    icon: 'S→',
    category: 'encoder',
    keywords: ['string to base64', 'convert string to base64', 'text to base64', 'utf8 to base64', 'base64 string', 'encode string base64'],
    path: '/tools/string-to-base64',
    relatedTools: ['base64', 'base64-encoder', 'url-encoder', 'binary-text'],
  },
  // Programmatic SEO — JSON Formatter variants
  {
    id: 'json-beautifier',
    name: 'JSON Beautifier',
    description: 'Beautify and pretty-print JSON data with customizable indentation. Free online JSON beautifier',
    icon: '✨',
    category: 'formatter',
    keywords: ['json beautifier', 'json beautify', 'json pretty print', 'pretty print json', 'json beautifier online', 'beautify json', 'json pretty'],
    path: '/tools/json-beautifier',
    relatedTools: ['json-formatter', 'json-validator', 'json-minifier', 'json-to-typescript'],
  },
  {
    id: 'json-validator',
    name: 'JSON Validator',
    description: 'Validate JSON syntax and find errors with detailed error messages. Free online JSON checker',
    icon: '✓',
    category: 'formatter',
    keywords: ['json validator', 'json validate', 'json checker', 'json lint', 'json syntax check', 'validate json', 'json validator online', 'check json'],
    path: '/tools/json-validator',
    relatedTools: ['json-formatter', 'json-beautifier', 'json-minifier', 'yaml-validator'],
  },
  {
    id: 'json-minifier',
    name: 'JSON Minifier',
    description: 'Minify and compress JSON data by removing whitespace. Free online JSON minification tool',
    icon: '▪',
    category: 'formatter',
    keywords: ['json minifier', 'json minify', 'json compress', 'minify json', 'json compressor', 'json minifier online', 'compress json', 'json minimize'],
    path: '/tools/json-minifier',
    relatedTools: ['json-formatter', 'json-beautifier', 'json-validator', 'css-minifier'],
  },
  // Programmatic SEO — JWT variants
  {
    id: 'jwt-token-decoder',
    name: 'JWT Token Decoder',
    description: 'Decode and inspect JWT tokens online. View header, payload, and signature instantly',
    icon: 'JD',
    category: 'encoder',
    keywords: ['jwt token decoder', 'jwt decode', 'decode jwt token', 'jwt token decode online', 'jwt decoder online', 'jwt inspect'],
    path: '/tools/jwt-token-decoder',
    relatedTools: ['jwt-decoder', 'jwt-parser', 'jwt-validator', 'base64-decoder'],
  },
  {
    id: 'jwt-parser',
    name: 'JWT Parser',
    description: 'Parse JWT tokens and extract claims, expiration, issuer, and audience fields',
    icon: 'JP',
    category: 'encoder',
    keywords: ['jwt parser', 'jwt parse', 'jwt parser online', 'parse jwt token', 'jwt claims', 'jwt payload parser', 'jwt extract'],
    path: '/tools/jwt-parser',
    relatedTools: ['jwt-decoder', 'jwt-token-decoder', 'jwt-validator', 'json-formatter'],
  },
  {
    id: 'jwt-validator',
    name: 'JWT Validator',
    description: 'Validate JWT token structure, expiration time, and claims. Check if JWT is expired',
    icon: 'JV',
    category: 'encoder',
    keywords: ['jwt validator', 'jwt validate', 'jwt validation', 'jwt expired check', 'jwt expiration checker', 'validate jwt token', 'jwt verify online'],
    path: '/tools/jwt-validator',
    relatedTools: ['jwt-decoder', 'jwt-token-decoder', 'jwt-parser', 'json-validator'],
  },
  // Programmatic SEO — Regex variants
  {
    id: 'regex-checker',
    name: 'Regex Checker',
    description: 'Check and test regular expressions against text with match highlighting. Free online regex checker',
    icon: 'R✓',
    category: 'text',
    keywords: ['regex checker', 'regex check', 'regex checker online', 'check regex', 'regular expression checker', 'regex test online'],
    path: '/tools/regex-checker',
    relatedTools: ['regex-tester', 'regex-matcher', 'regex-generator', 'escape-unescape'],
  },
  {
    id: 'regex-matcher',
    name: 'Regex Matcher',
    description: 'Find all regex matches in text with capture groups and match positions. Free online regex matcher',
    icon: 'R≈',
    category: 'text',
    keywords: ['regex matcher', 'regex match', 'regex match online', 'regex find all', 'regex capture groups', 'regular expression match'],
    path: '/tools/regex-matcher',
    relatedTools: ['regex-tester', 'regex-checker', 'regex-generator', 'text-diff'],
  },
  {
    id: 'regex-generator',
    name: 'Regex Generator',
    description: 'Generate regular expressions from common patterns. Email, URL, phone, date regex patterns',
    icon: 'R+',
    category: 'text',
    keywords: ['regex generator', 'regex pattern generator', 'generate regex', 'regex builder', 'regex for email', 'regex for url', 'regex for phone', 'common regex patterns'],
    path: '/tools/regex-generator',
    relatedTools: ['regex-tester', 'regex-checker', 'regex-matcher', 'password-generator'],
  },
  // Programmatic SEO — Cron variants
  {
    id: 'crontab-generator',
    name: 'Crontab Generator',
    description: 'Generate crontab expressions with visual schedule builder. Free online crontab maker',
    icon: '⏲️',
    category: 'generator',
    keywords: ['crontab generator', 'crontab maker', 'crontab builder', 'crontab syntax', 'crontab schedule', 'crontab online', 'generate crontab'],
    path: '/tools/crontab-generator',
    relatedTools: ['cron-generator', 'cron-parser', 'cron-job-scheduler', 'cron-expression-parser'],
  },
  {
    id: 'cron-job-scheduler',
    name: 'Cron Job Scheduler',
    description: 'Schedule cron jobs with an interactive visual editor. Preview next run times',
    icon: '📅',
    category: 'generator',
    keywords: ['cron job scheduler', 'cron schedule', 'cron job maker', 'schedule cron', 'cron job builder', 'cron job online', 'cron timing'],
    path: '/tools/cron-job-scheduler',
    relatedTools: ['cron-generator', 'cron-parser', 'crontab-generator', 'cron-expression-parser'],
  },
  {
    id: 'cron-expression-parser',
    name: 'Cron Expression Parser',
    description: 'Parse and explain cron expressions in plain English. Understand any cron schedule',
    icon: '🔍',
    category: 'generator',
    keywords: ['cron expression parser', 'cron parser online', 'parse cron', 'cron expression explain', 'cron to english', 'cron expression reader', 'understand cron'],
    path: '/tools/cron-expression-parser',
    relatedTools: ['cron-parser', 'cron-generator', 'crontab-generator', 'cron-job-scheduler'],
  },
  // Programmatic SEO — URL Encoder variants
  {
    id: 'url-decoder',
    name: 'URL Decoder',
    description: 'Decode URL-encoded strings back to readable text. Free online URL decoding tool',
    icon: '%←',
    category: 'encoder',
    keywords: ['url decoder', 'url decode', 'url decode online', 'decode url', 'url decoding', 'urldecode', 'url unescape'],
    path: '/tools/url-decoder',
    relatedTools: ['url-encoder', 'url-encode-online', 'percent-encoding-tool', 'base64-decoder'],
  },
  {
    id: 'url-encode-online',
    name: 'URL Encode Online',
    description: 'Encode text for safe use in URLs. Free online URL encoding tool with encodeURIComponent',
    icon: '%→',
    category: 'encoder',
    keywords: ['url encode online', 'url encode', 'urlencode', 'url encoding', 'encode url', 'url encode tool', 'encodeURIComponent online'],
    path: '/tools/url-encode-online',
    relatedTools: ['url-encoder', 'url-decoder', 'percent-encoding-tool', 'base64-encoder'],
  },
  {
    id: 'percent-encoding-tool',
    name: 'Percent Encoding Tool',
    description: 'Convert characters to percent-encoded format for URLs. Complete percent encoding reference',
    icon: '%%',
    category: 'encoder',
    keywords: ['percent encoding', 'percent encode', 'percent encoding tool', 'url percent encoding', 'percent encoded characters', 'percent encoding table', 'rfc 3986'],
    path: '/tools/percent-encoding-tool',
    relatedTools: ['url-encoder', 'url-decoder', 'url-encode-online', 'html-entity'],
  },
  // Programmatic SEO — VS Comparison Pages
  {
    id: 'md5-vs-sha256',
    name: 'MD5 vs SHA-256',
    description: 'Compare MD5 and SHA-256 hash algorithms: speed, security, output length, and when to use each',
    icon: '⚔️',
    category: 'encoder',
    keywords: ['md5 vs sha256', 'md5 vs sha-256', 'sha256 vs md5', 'md5 or sha256', 'hash comparison', 'hash algorithm comparison'],
    path: '/tools/md5-vs-sha256',
    relatedTools: ['md5-hash-generator', 'sha256-hash-generator', 'hash-generator', 'multi-hash-generator'],
  },
  {
    id: 'base64-vs-url-encoding',
    name: 'Base64 vs URL Encoding',
    description: 'Compare Base64 and URL encoding: purpose, character sets, size overhead, and when to use each',
    icon: '⚔️',
    category: 'encoder',
    keywords: ['base64 vs url encoding', 'base64 or url encode', 'encoding comparison', 'base64 vs percent encoding', 'url encoding vs base64'],
    path: '/tools/base64-vs-url-encoding',
    relatedTools: ['base64', 'base64-encoder', 'url-encoder', 'percent-encoding-tool'],
  },
  {
    id: 'json-vs-yaml',
    name: 'JSON vs YAML',
    description: 'Compare JSON and YAML data formats: syntax, readability, comments, use cases, and which to choose',
    icon: '⚔️',
    category: 'formatter',
    keywords: ['json vs yaml', 'yaml vs json', 'json or yaml', 'json yaml comparison', 'config format comparison'],
    path: '/tools/json-vs-yaml',
    relatedTools: ['json-formatter', 'yaml-validator', 'json-yaml', 'yaml-json-converter'],
  },
  {
    id: 'jwt-vs-session',
    name: 'JWT vs Session',
    description: 'Compare JWT tokens and session-based authentication: scalability, security, storage, and best practices',
    icon: '⚔️',
    category: 'encoder',
    keywords: ['jwt vs session', 'session vs jwt', 'jwt or session', 'token vs session', 'authentication comparison', 'jwt vs cookie'],
    path: '/tools/jwt-vs-session',
    relatedTools: ['jwt-decoder', 'jwt-parser', 'jwt-validator', 'jwt-token-decoder'],
  },
  {
    id: 'rest-vs-graphql',
    name: 'REST vs GraphQL',
    description: 'Compare REST APIs and GraphQL: architecture, data fetching, performance, and when to use each',
    icon: '⚔️',
    category: 'web',
    keywords: ['rest vs graphql', 'graphql vs rest', 'rest or graphql', 'api comparison', 'rest api vs graphql', 'graphql vs rest api'],
    path: '/tools/rest-vs-graphql',
    relatedTools: ['json-formatter', 'json-to-typescript', 'json-to-graphql', 'curl-to-code'],
  },
  {
    id: 'json-vs-xml',
    name: 'JSON vs XML',
    description: 'Compare JSON and XML data formats: syntax, size, parsing speed, schema support, and use cases',
    icon: '⚔️',
    category: 'formatter',
    keywords: ['json vs xml', 'xml vs json', 'json or xml', 'data format comparison', 'json xml comparison'],
    path: '/tools/json-vs-xml',
    relatedTools: ['json-formatter', 'xml-formatter', 'xml-to-json', 'csv-json'],
  },
  {
    id: 'mysql-vs-postgresql',
    name: 'MySQL vs PostgreSQL',
    description: 'Compare MySQL and PostgreSQL databases: performance, features, JSON support, and when to use each',
    icon: '⚔️',
    category: 'web',
    keywords: ['mysql vs postgresql', 'postgresql vs mysql', 'mysql or postgres', 'database comparison', 'mysql vs postgres', 'sql database comparison'],
    path: '/tools/mysql-vs-postgresql',
    relatedTools: ['sql-formatter', 'sql-to-prisma', 'json-formatter', 'docker-compose-generator'],
  },
  {
    id: 'npm-vs-yarn-vs-pnpm',
    name: 'npm vs Yarn vs pnpm',
    description: 'Compare npm, Yarn, and pnpm package managers: speed, disk usage, features, and which to choose',
    icon: '⚔️',
    category: 'web',
    keywords: ['npm vs yarn', 'yarn vs pnpm', 'npm vs pnpm', 'npm vs yarn vs pnpm', 'package manager comparison', 'node package manager'],
    path: '/tools/npm-vs-yarn-vs-pnpm',
    relatedTools: ['json-formatter', 'gitignore-generator', 'json-validator', 'json-beautifier'],
  },
  {
    id: 'docker-vs-kubernetes',
    name: 'Docker vs Kubernetes',
    description: 'Compare Docker and Kubernetes: containerization vs orchestration, complexity, scaling, and use cases',
    icon: '⚔️',
    category: 'web',
    keywords: ['docker vs kubernetes', 'kubernetes vs docker', 'docker or kubernetes', 'k8s vs docker', 'container comparison', 'docker vs k8s'],
    path: '/tools/docker-vs-kubernetes',
    relatedTools: ['docker-compose-generator', 'yaml-validator', 'json-yaml', 'nginx-config'],
  },
  {
    id: 'typescript-vs-javascript',
    name: 'TypeScript vs JavaScript',
    description: 'Compare TypeScript and JavaScript: type safety, tooling, performance, and when to use each',
    icon: '⚔️',
    category: 'web',
    keywords: ['typescript vs javascript', 'javascript vs typescript', 'ts vs js', 'typescript or javascript', 'should i use typescript'],
    path: '/tools/typescript-vs-javascript',
    relatedTools: ['json-to-typescript', 'typescript-to-javascript', 'json-formatter', 'regex-tester'],
  },
  // JSON to Table — interactive table viewer
  {
    id: 'json-to-table',
    name: 'JSON to Table',
    description: 'Convert JSON data to an interactive, sortable HTML table with search, filter, and CSV export',
    icon: '📊',
    category: 'converter',
    keywords: ['json to table', 'json table viewer', 'json to html table', 'json table converter', 'view json as table', 'json table', 'json to csv', 'json viewer table', 'json data table'],
    path: '/tools/json-to-table',
    relatedTools: ['json-formatter', 'csv-json', 'json-viewer', 'json-to-typescript'],
  },
];

export function getToolsByCategory(categoryId: string): Tool[] {
  return tools.filter(t => t.category === categoryId);
}

export function searchTools(query: string): Tool[] {
  const q = query.toLowerCase();
  return tools.filter(t =>
    t.name.toLowerCase().includes(q) ||
    t.description.toLowerCase().includes(q) ||
    t.keywords.some(k => k.includes(q))
  );
}
