export interface Tool {
  id: string;
  name: string;
  description: string;
  icon: string;
  category: string;
  keywords: string[];
  path: string;
  relatedTools?: string[];
}

export const categories = [
  { id: 'encoder', name: 'Encoder / Decoder', icon: '🔐' },
  { id: 'formatter', name: 'Formatter / Beautifier', icon: '✨' },
  { id: 'generator', name: 'Generator', icon: '⚡' },
  { id: 'converter', name: 'Converter', icon: '🔄' },
  { id: 'css', name: 'CSS Tools', icon: '🎨' },
  { id: 'text', name: 'Text Tools', icon: '📝' },
  { id: 'web', name: 'Web Tools', icon: '🌐' },
];

export const tools: Tool[] = [
  {
    id: 'json-formatter',
    name: 'JSON Formatter',
    description: 'Format, validate, and beautify JSON data with syntax highlighting',
    icon: '{ }',
    category: 'formatter',
    keywords: ['json', 'format', 'validate', 'beautify', 'pretty print', 'minify'],
    path: '/tools/json-formatter',
    relatedTools: ['json-yaml', 'csv-json', 'xml-formatter', 'json-to-typescript'],
  },
  {
    id: 'base64',
    name: 'Base64 Encoder/Decoder',
    description: 'Encode text to Base64 or decode Base64 back to text',
    icon: 'B64',
    category: 'encoder',
    keywords: ['base64', 'encode', 'decode', 'binary', 'text'],
    path: '/tools/base64',
  },
  {
    id: 'url-encoder',
    name: 'URL Encoder/Decoder',
    description: 'Encode or decode URL components and query parameters',
    icon: '%20',
    category: 'encoder',
    keywords: ['url', 'encode', 'decode', 'uri', 'percent encoding', 'query string'],
    path: '/tools/url-encoder',
  },
  {
    id: 'hash-generator',
    name: 'Hash Generator',
    description: 'Generate MD5, SHA-1, SHA-256, SHA-512 hashes from text',
    icon: '#',
    category: 'generator',
    keywords: ['hash', 'md5', 'sha1', 'sha256', 'sha512', 'checksum', 'digest', 'sha256 hash generator', 'multi hash generator', 'sha1 hash generator'],
    path: '/tools/hash-generator',
  },
  {
    id: 'multi-hash-generator',
    name: 'Multi Hash Generator',
    description: 'Generate MD5, SHA-1, SHA-256, SHA-384, SHA-512 hashes simultaneously from text or files',
    icon: '🔐',
    category: 'generator',
    keywords: ['multi hash', 'hash generator', 'md5 generator', 'sha256 generator', 'sha1 generator', 'sha512 generator', 'file hash', 'checksum calculator', 'hash all', 'all hashes at once'],
    path: '/tools/multi-hash-generator',
    relatedTools: ['hash-generator', 'hmac-generator', 'bcrypt-generator', 'password-generator'],
  },
  {
    id: 'uuid-generator',
    name: 'UUID Generator',
    description: 'Generate random UUIDs (v4) in bulk with one click',
    icon: 'ID',
    category: 'generator',
    keywords: ['uuid', 'guid', 'unique id', 'random', 'identifier', 'uuid v4', 'uuid v7', 'guid generator', 'online uuid generator'],
    path: '/tools/uuid-generator',
  },
  {
    id: 'timestamp-converter',
    name: 'Unix Timestamp Converter',
    description: 'Convert between Unix timestamps and human-readable dates',
    icon: '🕐',
    category: 'converter',
    keywords: ['timestamp', 'unix', 'epoch', 'date', 'time', 'convert', 'convert unix timestamp to date', 'epoch converter', 'timestamp to datetime', 'date to timestamp'],
    path: '/tools/timestamp-converter',
  },
  {
    id: 'color-converter',
    name: 'Color Converter',
    description: 'Convert colors between HEX, RGB, HSL formats with preview',
    icon: '🎨',
    category: 'converter',
    keywords: ['color', 'hex', 'rgb', 'hsl', 'convert', 'picker', 'palette', 'hex to rgb', 'hex to pantone', 'color code converter', 'hexadecimal to rgb'],
    path: '/tools/color-converter',
  },
  {
    id: 'regex-tester',
    name: 'Regex Tester',
    description: 'Test regular expressions with real-time matching and highlighting',
    icon: '.*',
    category: 'text',
    keywords: ['regex', 'regular expression', 'pattern', 'match', 'test', 'replace', 'regex tester', 'regex debugger', 'javascript regex', 'python regex'],
    path: '/tools/regex-tester',
  },
  {
    id: 'markdown-preview',
    name: 'Markdown Preview',
    description: 'Write Markdown and see the rendered preview side by side',
    icon: 'MD',
    category: 'text',
    keywords: ['markdown', 'preview', 'render', 'md', 'editor'],
    path: '/tools/markdown-preview',
  },
  {
    id: 'jwt-decoder',
    name: 'JWT Decoder',
    description: 'Decode and inspect JSON Web Tokens (header, payload, signature)',
    icon: 'JWT',
    category: 'encoder',
    keywords: ['jwt', 'json web token', 'decode', 'header', 'payload', 'auth'],
    path: '/tools/jwt-decoder',
  },
  {
    id: 'qrcode-generator',
    name: 'QR Code Generator',
    description: 'Generate QR codes from text, URLs, or any data',
    icon: '▣',
    category: 'generator',
    keywords: ['qr', 'qrcode', 'barcode', 'generate', 'scan'],
    path: '/tools/qrcode-generator',
  },
  {
    id: 'lorem-ipsum',
    name: 'Lorem Ipsum Generator',
    description: 'Generate placeholder text in paragraphs, sentences, or words',
    icon: 'Aa',
    category: 'generator',
    keywords: ['lorem', 'ipsum', 'placeholder', 'text', 'dummy', 'filler'],
    path: '/tools/lorem-ipsum',
  },
  {
    id: 'html-entity',
    name: 'HTML Entity Encoder',
    description: 'Encode and decode HTML entities and special characters',
    icon: '&;',
    category: 'encoder',
    keywords: ['html', 'entity', 'encode', 'decode', 'escape', 'special characters'],
    path: '/tools/html-entity',
  },
  {
    id: 'css-minifier',
    name: 'CSS Minifier / Beautifier',
    description: 'Minify or beautify CSS code for production or readability',
    icon: '{ }',
    category: 'css',
    keywords: ['css', 'minify', 'beautify', 'compress', 'format', 'style'],
    path: '/tools/css-minifier',
  },
  {
    id: 'number-base',
    name: 'Number Base Converter',
    description: 'Convert numbers between binary, octal, decimal, and hexadecimal',
    icon: '01',
    category: 'converter',
    keywords: ['binary', 'octal', 'decimal', 'hex', 'convert', 'base', 'number'],
    path: '/tools/number-base',
  },
  {
    id: 'text-diff',
    name: 'Text Diff Checker',
    description: 'Compare two texts and highlight the differences',
    icon: '±',
    category: 'text',
    keywords: ['diff', 'compare', 'difference', 'text', 'merge'],
    path: '/tools/text-diff',
  },
  {
    id: 'word-counter',
    name: 'Word Counter',
    description: 'Count words, characters, sentences, and paragraphs in text',
    icon: '123',
    category: 'text',
    keywords: ['word', 'count', 'character', 'sentence', 'paragraph', 'length'],
    path: '/tools/word-counter',
  },
  {
    id: 'password-generator',
    name: 'Password Generator',
    description: 'Generate secure random passwords with customizable options',
    icon: '🔑',
    category: 'generator',
    keywords: ['password', 'generate', 'random', 'secure', 'strong'],
    path: '/tools/password-generator',
  },
  {
    id: 'sql-formatter',
    name: 'SQL Formatter',
    description: 'Format and beautify SQL queries for better readability',
    icon: 'SQL',
    category: 'formatter',
    keywords: ['sql', 'format', 'beautify', 'query', 'database'],
    path: '/tools/sql-formatter',
  },
  {
    id: 'cron-parser',
    name: 'Cron Expression Parser',
    description: 'Parse and explain cron expressions with next run times',
    icon: '⏰',
    category: 'web',
    keywords: ['cron', 'schedule', 'parse', 'expression', 'time', 'job'],
    path: '/tools/cron-parser',
  },
  {
    id: 'json-yaml',
    name: 'JSON ↔ YAML Converter',
    description: 'Convert between JSON and YAML formats instantly',
    icon: 'Y{}',
    category: 'converter',
    keywords: ['json', 'yaml', 'yml', 'convert', 'config', 'configuration'],
    path: '/tools/json-yaml',
  },
  {
    id: 'string-case',
    name: 'String Case Converter',
    description: 'Convert text between camelCase, snake_case, kebab-case, and more',
    icon: 'Aa',
    category: 'text',
    keywords: ['case', 'camel', 'snake', 'kebab', 'pascal', 'convert', 'string', 'naming'],
    path: '/tools/string-case',
  },
  {
    id: 'slug-generator',
    name: 'URL Slug Generator',
    description: 'Convert text to SEO-friendly URL slugs',
    icon: '🔗',
    category: 'web',
    keywords: ['slug', 'url', 'seo', 'permalink', 'friendly', 'generate'],
    path: '/tools/slug-generator',
  },
  {
    id: 'chmod-calculator',
    name: 'Chmod Calculator',
    description: 'Calculate Linux file permissions with interactive checkboxes',
    icon: '🛡️',
    category: 'web',
    keywords: ['chmod', 'permissions', 'linux', 'unix', 'file', 'rwx', 'octal'],
    path: '/tools/chmod-calculator',
  },
  {
    id: 'line-sorter',
    name: 'Line Sort & Dedup',
    description: 'Sort lines, remove duplicates, reverse, shuffle, and more',
    icon: '↕️',
    category: 'text',
    keywords: ['sort', 'lines', 'deduplicate', 'unique', 'reverse', 'shuffle', 'alphabetical'],
    path: '/tools/line-sorter',
  },
  {
    id: 'js-html-formatter',
    name: 'JS/HTML Formatter',
    description: 'Minify or beautify JavaScript and HTML code',
    icon: 'JS',
    category: 'formatter',
    keywords: ['javascript', 'html', 'minify', 'beautify', 'compress', 'format', 'uglify'],
    path: '/tools/js-html-formatter',
  },
  {
    id: 'image-base64',
    name: 'Image Base64 Converter',
    description: 'Convert images to Base64 strings and data URIs with drag & drop',
    icon: '🖼️',
    category: 'encoder',
    keywords: ['image', 'base64', 'convert', 'data uri', 'encode', 'decode', 'png', 'jpg', 'svg'],
    path: '/tools/image-base64',
  },
  {
    id: 'git-command-generator',
    name: 'Git Command Generator',
    description: 'Visual Git command builder — select an action, fill in parameters, copy the command',
    icon: '🔀',
    category: 'web',
    keywords: ['git', 'command', 'generator', 'branch', 'merge', 'rebase', 'commit', 'push', 'pull', 'stash'],
    path: '/tools/git-command-generator',
  },
  {
    id: 'xml-formatter',
    name: 'XML Formatter',
    description: 'Format, minify, and validate XML with syntax highlighting',
    icon: '<>',
    category: 'formatter',
    keywords: ['xml', 'format', 'minify', 'validate', 'beautify', 'pretty print'],
    path: '/tools/xml-formatter',
  },
  {
    id: 'csv-json',
    name: 'CSV ↔ JSON Converter',
    description: 'Convert between CSV and JSON formats instantly',
    icon: '📊',
    category: 'converter',
    keywords: ['csv', 'json', 'convert', 'spreadsheet', 'data', 'export'],
    path: '/tools/csv-json',
  },
  {
    id: 'http-status',
    name: 'HTTP Status Code Reference',
    description: 'Lookup HTTP status codes with meanings and use cases',
    icon: '4xx',
    category: 'web',
    keywords: ['http', 'status code', '404', '500', '200', 'reference', 'api'],
    path: '/tools/http-status',
  },
  {
    id: 'mime-types',
    name: 'MIME Type Lookup',
    description: 'Find MIME types by file extension or content type',
    icon: '📄',
    category: 'web',
    keywords: ['mime', 'content-type', 'file extension', 'lookup', 'media type'],
    path: '/tools/mime-types',
  },
  {
    id: 'escape-unescape',
    name: 'Escape / Unescape',
    description: 'Escape or unescape HTML, JavaScript, and JSON strings',
    icon: '\\',
    category: 'encoder',
    keywords: ['escape', 'unescape', 'html', 'javascript', 'json', 'encode', 'decode'],
    path: '/tools/escape-unescape',
  },
  {
    id: 'ip-calculator',
    name: 'IP Subnet Calculator',
    description: 'Calculate subnet mask, network, broadcast, and host range',
    icon: '🌐',
    category: 'converter',
    keywords: ['ip', 'subnet', 'calculator', 'cidr', 'network', 'broadcast'],
    path: '/tools/ip-calculator',
  },
  {
    id: 'fake-data',
    name: 'Fake Data Generator',
    description: 'Generate fake names, emails, addresses for testing',
    icon: '👤',
    category: 'generator',
    keywords: ['fake', 'test data', 'mock', 'names', 'emails', 'addresses'],
    path: '/tools/fake-data',
  },
  {
    id: 'hmac-generator',
    name: 'HMAC Generator',
    description: 'Generate HMAC-SHA256, HMAC-SHA1 from message and secret key',
    icon: '🔐',
    category: 'generator',
    keywords: ['hmac', 'sha256', 'sha1', 'signature', 'api', 'webhook'],
    path: '/tools/hmac-generator',
  },
  {
    id: 'url-parser',
    name: 'URL Parser',
    description: 'Parse URL into components: protocol, host, path, query params',
    icon: '🔗',
    category: 'web',
    keywords: ['url', 'parse', 'components', 'host', 'path', 'query', 'params'],
    path: '/tools/url-parser',
  },
  {
    id: 'binary-text',
    name: 'Text ↔ Binary Converter',
    description: 'Convert text to binary and binary to text',
    icon: '01',
    category: 'converter',
    keywords: ['binary', 'text', 'convert', 'ascii', 'utf8', 'encoding'],
    path: '/tools/binary-text',
  },
  {
    id: 'pem-decoder',
    name: 'PEM / Certificate Decoder',
    description: 'Decode PEM certificates and view certificate details',
    icon: '📜',
    category: 'encoder',
    keywords: ['pem', 'certificate', 'ssl', 'tls', 'decode', 'x509'],
    path: '/tools/pem-decoder',
  },
  {
    id: 'html-table',
    name: 'HTML Table Generator',
    description: 'Convert CSV or JSON to HTML table markup',
    icon: '📋',
    category: 'converter',
    keywords: ['html', 'table', 'csv', 'json', 'markup', 'generate'],
    path: '/tools/html-table',
  },
  {
    id: 'bcrypt-generator',
    name: 'Bcrypt Hash Generator',
    description: 'Generate bcrypt password hashes with configurable cost',
    icon: '🔒',
    category: 'generator',
    keywords: ['bcrypt', 'hash', 'password', 'generate', 'security'],
    path: '/tools/bcrypt-generator',
  },
  // P0 — Code conversion tools (competing with transform.tools)
  {
    id: 'json-to-typescript',
    name: 'JSON to TypeScript',
    description: 'Convert JSON data to TypeScript interfaces and types',
    icon: 'TS',
    category: 'converter',
    keywords: ['json', 'typescript', 'interface', 'type', 'convert', 'ts'],
    path: '/tools/json-to-typescript',
    relatedTools: ['json-formatter', 'json-to-go', 'json-to-java', 'json-to-zod'],
  },
  {
    id: 'html-to-jsx',
    name: 'HTML to JSX',
    description: 'Convert HTML markup to JSX for React components',
    icon: 'JSX',
    category: 'converter',
    keywords: ['html', 'jsx', 'react', 'convert', 'component'],
    path: '/tools/html-to-jsx',
    relatedTools: ['svg-to-jsx', 'js-html-formatter', 'html-entity', 'html-to-markdown'],
  },
  {
    id: 'json-to-go',
    name: 'JSON to Go Struct',
    description: 'Convert JSON data to Go struct definitions',
    icon: 'Go',
    category: 'converter',
    keywords: ['json', 'go', 'golang', 'struct', 'convert'],
    path: '/tools/json-to-go',
    relatedTools: ['json-to-typescript', 'json-to-rust', 'json-to-java', 'json-formatter'],
  },
  {
    id: 'svg-to-jsx',
    name: 'SVG to JSX/React',
    description: 'Convert SVG markup to JSX React components',
    icon: 'SVG',
    category: 'converter',
    keywords: ['svg', 'jsx', 'react', 'component', 'convert', 'icon'],
    path: '/tools/svg-to-jsx',
    relatedTools: ['html-to-jsx', 'image-base64', 'js-html-formatter', 'css-to-tailwind'],
  },
  {
    id: 'css-to-tailwind',
    name: 'CSS to Tailwind',
    description: 'Convert CSS styles to Tailwind CSS utility classes',
    icon: 'TW',
    category: 'css',
    keywords: ['css', 'tailwind', 'convert', 'utility', 'classes', 'style'],
    path: '/tools/css-to-tailwind',
    relatedTools: ['css-minifier', 'css-to-js', 'html-to-jsx', 'svg-to-jsx'],
  },
  {
    id: 'typescript-to-javascript',
    name: 'TypeScript to JavaScript',
    description: 'Compile TypeScript code to plain JavaScript',
    icon: 'JS',
    category: 'converter',
    keywords: ['typescript', 'javascript', 'compile', 'convert', 'ts', 'js'],
    path: '/tools/typescript-to-javascript',
    relatedTools: ['json-to-typescript', 'js-html-formatter', 'html-to-jsx', 'graphql-to-typescript'],
  },
  // P1 tools
  {
    id: 'json-to-graphql',
    name: 'JSON to GraphQL',
    description: 'Convert JSON data to GraphQL schema definitions',
    icon: 'GQL',
    category: 'converter',
    keywords: ['json', 'graphql', 'schema', 'convert', 'api', 'query'],
    path: '/tools/json-to-graphql',
    relatedTools: ['json-to-typescript', 'json-to-go', 'json-to-java', 'graphql-to-typescript'],
  },
  {
    id: 'json-to-java',
    name: 'JSON to Java Class',
    description: 'Convert JSON data to Java class definitions',
    icon: 'JV',
    category: 'converter',
    keywords: ['json', 'java', 'class', 'pojo', 'convert', 'bean'],
    path: '/tools/json-to-java',
    relatedTools: ['json-to-kotlin', 'json-to-typescript', 'json-to-csharp', 'json-to-go'],
  },
  {
    id: 'json-to-kotlin',
    name: 'JSON to Kotlin',
    description: 'Convert JSON data to Kotlin data classes',
    icon: 'KT',
    category: 'converter',
    keywords: ['json', 'kotlin', 'data class', 'convert', 'android'],
    path: '/tools/json-to-kotlin',
    relatedTools: ['json-to-java', 'json-to-typescript', 'json-to-python', 'json-to-go'],
  },
  {
    id: 'json-to-python',
    name: 'JSON to Python',
    description: 'Convert JSON data to Python dataclass or TypedDict',
    icon: 'PY',
    category: 'converter',
    keywords: ['json', 'python', 'dataclass', 'typeddict', 'convert', 'pydantic'],
    path: '/tools/json-to-python',
    relatedTools: ['json-to-kotlin', 'json-to-java', 'json-to-typescript', 'json-to-go'],
  },
  {
    id: 'json-to-csharp',
    name: 'JSON to C#',
    description: 'Convert JSON data to C# class definitions',
    icon: 'C#',
    category: 'converter',
    keywords: ['json', 'csharp', 'c#', 'class', 'convert', 'dotnet', '.net'],
    path: '/tools/json-to-csharp',
    relatedTools: ['json-to-java', 'json-to-typescript', 'json-to-kotlin', 'json-to-go'],
  },
  {
    id: 'markdown-to-html',
    name: 'Markdown to HTML',
    description: 'Convert Markdown text to HTML markup',
    icon: 'MD',
    category: 'converter',
    keywords: ['markdown', 'html', 'convert', 'markup', 'md'],
    path: '/tools/markdown-to-html',
    relatedTools: ['html-to-markdown', 'markdown-preview', 'html-to-jsx', 'html-entity'],
  },
  {
    id: 'html-to-markdown',
    name: 'HTML to Markdown',
    description: 'Convert HTML markup to Markdown text',
    icon: 'HM',
    category: 'converter',
    keywords: ['html', 'markdown', 'convert', 'markup', 'md'],
    path: '/tools/html-to-markdown',
    relatedTools: ['markdown-to-html', 'markdown-preview', 'html-to-jsx', 'html-entity'],
  },
  {
    id: 'toml-yaml',
    name: 'TOML ↔ YAML',
    description: 'Convert between TOML and YAML formats',
    icon: 'TY',
    category: 'converter',
    keywords: ['toml', 'yaml', 'convert', 'config', 'configuration'],
    path: '/tools/toml-yaml',
    relatedTools: ['json-yaml', 'json-formatter', 'xml-formatter', 'csv-json'],
  },
  // P2 tools
  {
    id: 'json-to-zod',
    name: 'JSON to Zod Schema',
    description: 'Convert JSON data to Zod validation schemas',
    icon: 'ZD',
    category: 'converter',
    keywords: ['json', 'zod', 'schema', 'validation', 'typescript', 'convert'],
    path: '/tools/json-to-zod',
    relatedTools: ['json-to-typescript', 'json-to-json-schema', 'json-formatter', 'json-to-graphql'],
  },
  {
    id: 'json-to-json-schema',
    name: 'JSON to JSON Schema',
    description: 'Generate JSON Schema from JSON data',
    icon: 'JS',
    category: 'converter',
    keywords: ['json', 'json-schema', 'schema', 'validation', 'convert'],
    path: '/tools/json-to-json-schema',
    relatedTools: ['json-to-zod', 'json-to-typescript', 'json-formatter', 'json-to-graphql'],
  },
  {
    id: 'css-to-js',
    name: 'CSS to JS Object',
    description: 'Convert CSS styles to JavaScript style objects',
    icon: 'CJ',
    category: 'css',
    keywords: ['css', 'javascript', 'style', 'object', 'convert', 'react'],
    path: '/tools/css-to-js',
    relatedTools: ['css-to-tailwind', 'html-to-jsx', 'css-minifier', 'svg-to-jsx'],
  },
  {
    id: 'graphql-to-typescript',
    name: 'GraphQL to TypeScript',
    description: 'Convert GraphQL schema to TypeScript types',
    icon: 'GT',
    category: 'converter',
    keywords: ['graphql', 'typescript', 'types', 'convert', 'codegen'],
    path: '/tools/graphql-to-typescript',
    relatedTools: ['json-to-graphql', 'json-to-typescript', 'typescript-to-javascript', 'json-to-go'],
  },
  {
    id: 'json-to-rust',
    name: 'JSON to Rust Struct',
    description: 'Convert JSON data to Rust struct definitions with serde',
    icon: 'RS',
    category: 'converter',
    keywords: ['json', 'rust', 'struct', 'serde', 'convert', 'derive'],
    path: '/tools/json-to-rust',
    relatedTools: ['json-to-go', 'json-to-typescript', 'json-to-csharp', 'json-to-java'],
  },
  {
    id: 'xml-to-json',
    name: 'XML to JSON',
    description: 'Convert XML markup to JSON format',
    icon: 'XJ',
    category: 'converter',
    keywords: ['xml', 'json', 'convert', 'markup', 'data'],
    path: '/tools/xml-to-json',
    relatedTools: ['xml-formatter', 'json-formatter', 'json-yaml', 'csv-json'],
  },
  // CSS & Visual tools
  {
    id: 'css-gradient',
    name: 'CSS Gradient Generator',
    description: 'Create beautiful CSS gradients with a visual editor — linear, radial, and conic',
    icon: '🌈',
    category: 'css',
    keywords: ['css', 'gradient', 'linear-gradient', 'radial-gradient', 'conic-gradient', 'background', 'generator', 'color'],
    path: '/tools/css-gradient',
    relatedTools: ['box-shadow', 'color-converter', 'css-minifier', 'css-to-tailwind'],
  },
  {
    id: 'box-shadow',
    name: 'Box Shadow Generator',
    description: 'Design CSS box shadows visually with real-time preview and code output',
    icon: '🔲',
    category: 'css',
    keywords: ['box-shadow', 'css', 'shadow', 'drop shadow', 'generator', 'visual', 'design'],
    path: '/tools/box-shadow',
    relatedTools: ['css-gradient', 'color-converter', 'css-minifier', 'css-to-tailwind'],
  },
  // SEO tools
  {
    id: 'meta-tag-generator',
    name: 'Meta Tag Generator',
    description: 'Generate HTML meta tags, Open Graph, and Twitter Card tags for SEO',
    icon: '🏷️',
    category: 'web',
    keywords: ['meta tag', 'og tag', 'open graph', 'twitter card', 'seo', 'html', 'head'],
    path: '/tools/meta-tag-generator',
    relatedTools: ['schema-generator', 'robots-generator', 'slug-generator', 'html-entity'],
  },
  {
    id: 'schema-generator',
    name: 'Schema Markup Generator',
    description: 'Generate JSON-LD structured data for Article, FAQ, HowTo, and more',
    icon: '📐',
    category: 'web',
    keywords: ['schema', 'json-ld', 'structured data', 'seo', 'rich snippets', 'markup', 'google'],
    path: '/tools/schema-generator',
    relatedTools: ['meta-tag-generator', 'robots-generator', 'json-formatter', 'slug-generator'],
  },
  {
    id: 'robots-generator',
    name: 'Robots.txt Generator',
    description: 'Generate robots.txt files with user-agent rules, allow/disallow paths, and sitemap',
    icon: '🤖',
    category: 'web',
    keywords: ['robots.txt', 'robots', 'crawler', 'seo', 'sitemap', 'user-agent', 'disallow'],
    path: '/tools/robots-generator',
    relatedTools: ['meta-tag-generator', 'schema-generator', 'slug-generator', 'url-parser'],
  },
  // JSON tools
  {
    id: 'json-viewer',
    name: 'JSON Viewer / Tree',
    description: 'View JSON data as an interactive collapsible tree with search and path display',
    icon: '🌳',
    category: 'formatter',
    keywords: ['json', 'viewer', 'tree', 'visualizer', 'explorer', 'collapsible', 'interactive'],
    path: '/tools/json-viewer',
    relatedTools: ['json-formatter', 'json-yaml', 'json-to-typescript', 'csv-json'],
  },
  // Generator tools
  {
    id: 'favicon-generator',
    name: 'Favicon Generator',
    description: 'Create favicons from text or emoji with custom colors and sizes',
    icon: '⭐',
    category: 'generator',
    keywords: ['favicon', 'ico', 'icon', 'generator', 'website', 'tab icon', 'bookmark'],
    path: '/tools/favicon-generator',
    relatedTools: ['placeholder-image', 'qrcode-generator', 'color-converter', 'meta-tag-generator'],
  },
  {
    id: 'ascii-art',
    name: 'ASCII Art Generator',
    description: 'Convert text to ASCII art with multiple font styles',
    icon: 'A>',
    category: 'text',
    keywords: ['ascii', 'art', 'text art', 'figlet', 'banner', 'font', 'generator'],
    path: '/tools/ascii-art',
    relatedTools: ['string-case', 'word-counter', 'lorem-ipsum', 'markdown-preview'],
  },
  {
    id: 'svg-optimizer',
    name: 'SVG Optimizer',
    description: 'Optimize and minify SVG files — remove metadata, comments, and unnecessary attributes',
    icon: '💎',
    category: 'formatter',
    keywords: ['svg', 'optimize', 'minify', 'compress', 'clean', 'svgo'],
    path: '/tools/svg-optimizer',
    relatedTools: ['svg-to-jsx', 'image-base64', 'css-minifier', 'js-html-formatter'],
  },
  {
    id: 'placeholder-image',
    name: 'Placeholder Image Generator',
    description: 'Generate placeholder images with custom dimensions, colors, and text',
    icon: '🖼️',
    category: 'generator',
    keywords: ['placeholder', 'image', 'dummy', 'generator', 'dimensions', 'mockup'],
    path: '/tools/placeholder-image',
    relatedTools: ['favicon-generator', 'image-base64', 'qrcode-generator', 'color-converter'],
  },
  // Round 2 — CSS & Visual tools
  {
    id: 'color-palette',
    name: 'Color Palette Generator',
    description: 'Generate harmonious color palettes — complementary, analogous, triadic, tetradic schemes',
    icon: '🎨',
    category: 'css',
    keywords: ['color palette', 'color scheme', 'complementary', 'analogous', 'triadic', 'tetradic', 'harmony', 'generator'],
    path: '/tools/color-palette',
    relatedTools: ['color-converter', 'tailwind-colors', 'css-gradient', 'box-shadow'],
  },
  {
    id: 'flexbox-generator',
    name: 'Flexbox Generator',
    description: 'Visual Flexbox layout builder — configure direction, justify, align, wrap, and gap with live preview',
    icon: '📐',
    category: 'css',
    keywords: ['flexbox', 'flex', 'layout', 'css', 'direction', 'justify-content', 'align-items', 'wrap', 'gap'],
    path: '/tools/flexbox-generator',
    relatedTools: ['css-gradient', 'border-radius', 'box-shadow', 'css-minifier'],
  },
  {
    id: 'emoji-picker',
    name: 'Emoji Picker & Search',
    description: 'Browse and search emojis by category, copy Unicode, HTML entity, and shortcode',
    icon: '😀',
    category: 'text',
    keywords: ['emoji', 'picker', 'search', 'unicode', 'emoticon', 'smiley', 'copy', 'html entity'],
    path: '/tools/emoji-picker',
    relatedTools: ['html-entity', 'string-case', 'word-counter', 'ascii-art'],
  },
  {
    id: 'border-radius',
    name: 'Border Radius Generator',
    description: 'Design CSS border-radius with independent corner control and live preview',
    icon: '◻️',
    category: 'css',
    keywords: ['border-radius', 'css', 'rounded corners', 'generator', 'preview', 'design'],
    path: '/tools/border-radius',
    relatedTools: ['box-shadow', 'css-gradient', 'flexbox-generator', 'css-minifier'],
  },
  {
    id: 'css-unit-converter',
    name: 'CSS Unit Converter',
    description: 'Convert between px, rem, em, vw, vh, pt, and % with configurable root font-size',
    icon: 'px',
    category: 'css',
    keywords: ['css', 'unit', 'converter', 'px', 'rem', 'em', 'vw', 'vh', 'pt', 'percent', 'font-size'],
    path: '/tools/css-unit-converter',
    relatedTools: ['css-minifier', 'color-converter', 'number-base', 'flexbox-generator'],
  },
  {
    id: 'og-image-preview',
    name: 'Open Graph Image Preview',
    description: 'Preview how your page looks when shared on Facebook, Twitter, LinkedIn, and Discord',
    icon: '👁️',
    category: 'web',
    keywords: ['open graph', 'og image', 'social preview', 'facebook', 'twitter', 'linkedin', 'discord', 'share'],
    path: '/tools/og-image-preview',
    relatedTools: ['meta-tag-generator', 'schema-generator', 'slug-generator', 'favicon-generator'],
  },
  {
    id: 'tailwind-colors',
    name: 'Tailwind CSS Color Picker',
    description: 'Browse the full Tailwind CSS color palette — search, copy class names, HEX, and RGB values',
    icon: 'TW',
    category: 'css',
    keywords: ['tailwind', 'css', 'color', 'palette', 'picker', 'class', 'hex', 'rgb', 'utility'],
    path: '/tools/tailwind-colors',
    relatedTools: ['color-palette', 'color-converter', 'css-to-tailwind', 'css-gradient'],
  },
  // Round 3 — Blue ocean tools
  {
    id: 'curl-to-code',
    name: 'cURL to Code Converter',
    description: 'Convert cURL commands to Python, JavaScript, Go, PHP, Ruby, Java, and more',
    icon: '>>',
    category: 'converter',
    keywords: ['curl', 'curl to python', 'curl to javascript', 'curl to fetch', 'curl to go', 'curl converter', 'http request'],
    path: '/tools/curl-to-code',
    relatedTools: ['url-parser', 'json-formatter', 'http-status', 'html-entity'],
  },
  {
    id: 'yaml-validator',
    name: 'YAML Validator & Formatter',
    description: 'Validate, lint, and format YAML with error highlighting and auto-fix suggestions',
    icon: 'YML',
    category: 'formatter',
    keywords: ['yaml', 'validator', 'lint', 'yaml checker', 'yaml formatter', 'yaml beautify', 'kubernetes', 'docker compose'],
    path: '/tools/yaml-validator',
    relatedTools: ['json-yaml', 'toml-yaml', 'json-formatter', 'xml-formatter'],
  },
  {
    id: 'gitignore-generator',
    name: '.gitignore Generator',
    description: 'Generate .gitignore files for any language, framework, IDE, or OS',
    icon: '.gi',
    category: 'generator',
    keywords: ['gitignore', 'git', 'ignore', 'template', 'generator', 'node', 'python', 'java', 'vscode'],
    path: '/tools/gitignore-generator',
    relatedTools: ['git-command-generator', 'robots-generator', 'slug-generator', 'password-generator'],
  },
  {
    id: 'json-to-dart',
    name: 'JSON to Dart',
    description: 'Convert JSON data to Dart classes with fromJson/toJson for Flutter',
    icon: 'DT',
    category: 'converter',
    keywords: ['json', 'dart', 'flutter', 'class', 'convert', 'fromJson', 'toJson', 'model'],
    path: '/tools/json-to-dart',
    relatedTools: ['json-to-typescript', 'json-to-kotlin', 'json-to-python', 'json-formatter'],
  },
  {
    id: 'nginx-config',
    name: 'Nginx Config Generator',
    description: 'Generate Nginx configuration for reverse proxy, SSL, static sites, and more',
    icon: 'NX',
    category: 'web',
    keywords: ['nginx', 'config', 'configuration', 'reverse proxy', 'ssl', 'https', 'server block', 'load balancer'],
    path: '/tools/nginx-config',
    relatedTools: ['htaccess-generator', 'csp-generator', 'robots-generator', 'meta-tag-generator'],
  },
  {
    id: 'htaccess-generator',
    name: '.htaccess Generator',
    description: 'Generate .htaccess files for redirects, security headers, caching, and URL rewriting',
    icon: '.ht',
    category: 'web',
    keywords: ['htaccess', 'redirect', '301', 'apache', 'rewrite', 'mod_rewrite', 'security headers', 'caching'],
    path: '/tools/htaccess-generator',
    relatedTools: ['nginx-config', 'robots-generator', 'csp-generator', 'slug-generator'],
  },
  {
    id: 'docker-compose-generator',
    name: 'Docker Compose Generator',
    description: 'Build docker-compose.yml visually with service presets for popular stacks',
    icon: '🐳',
    category: 'generator',
    keywords: ['docker', 'docker-compose', 'compose', 'container', 'yaml', 'service', 'postgresql', 'redis', 'mongodb'],
    path: '/tools/docker-compose-generator',
    relatedTools: ['yaml-validator', 'json-yaml', 'nginx-config', 'cron-parser'],
  },
  {
    id: 'json-to-protobuf',
    name: 'JSON to Protobuf',
    description: 'Convert JSON data to Protocol Buffers (.proto) schema definitions',
    icon: 'PB',
    category: 'converter',
    keywords: ['json', 'protobuf', 'protocol buffers', 'proto', 'grpc', 'schema', 'convert', 'microservices'],
    path: '/tools/json-to-protobuf',
    relatedTools: ['json-to-graphql', 'json-to-typescript', 'json-to-go', 'json-formatter'],
  },
  {
    id: 'csp-generator',
    name: 'CSP Header Generator',
    description: 'Build Content-Security-Policy headers with interactive directive editor',
    icon: '🛡️',
    category: 'web',
    keywords: ['csp', 'content security policy', 'security headers', 'xss', 'header', 'directive', 'nonce'],
    path: '/tools/csp-generator',
    relatedTools: ['meta-tag-generator', 'htaccess-generator', 'nginx-config', 'robots-generator'],
  },
  {
    id: 'sql-to-prisma',
    name: 'SQL to Prisma Schema',
    description: 'Convert SQL CREATE TABLE statements to Prisma schema models',
    icon: 'PS',
    category: 'converter',
    keywords: ['sql', 'prisma', 'schema', 'orm', 'convert', 'model', 'typescript', 'database'],
    path: '/tools/sql-to-prisma',
    relatedTools: ['sql-formatter', 'json-to-typescript', 'json-to-graphql', 'json-formatter'],
  },
  {
    id: 'cron-generator',
    name: 'Cron Expression Generator',
    description: 'Build, validate, and understand cron expressions with a visual editor',
    icon: '⏰',
    category: 'generator',
    keywords: ['cron', 'crontab', 'schedule', 'timer', 'cron expression', 'cron job', 'automated', 'recurring'],
    path: '/tools/cron-generator',
    relatedTools: ['timestamp-converter', 'uuid-generator', 'password-generator'],
  },
  {
    id: 'text-to-pdf',
    name: 'Text to PDF Converter',
    description: 'Convert plain text to PDF documents with custom formatting options',
    icon: '📄',
    category: 'converter',
    keywords: ['text to pdf', 'convert text to pdf', 'txt to pdf', 'text to pdf converter', 'text file to pdf', 'plain text to pdf', 'notepad to pdf', 'convert txt to pdf online'],
    path: '/tools/text-to-pdf',
    relatedTools: ['markdown-to-html', 'word-counter', 'csv-json', 'html-to-markdown'],
  },
  {
    id: 'chmod-calculator',
    name: 'Chmod Calculator',
    description: 'Calculate and visualize Linux file permissions with an interactive chmod calculator',
    icon: '🔐',
    category: 'web',
    keywords: ['chmod', 'chmod calculator', 'linux permissions', 'file permissions', 'chmod 755', 'chmod 644', 'permission calculator', 'unix permissions', 'chmod command'],
    path: '/tools/chmod-calculator',
    relatedTools: ['password-generator', 'htaccess-generator', 'cron-generator'],
  },
  {
    id: 'hex-to-decimal',
    name: 'Hex to Decimal Converter',
    description: 'Convert between hexadecimal, decimal, and binary number systems',
    icon: '🔢',
    category: 'converter',
    keywords: ['hex to decimal', 'hex to decimal converter', 'hex to decimal calculator', 'decimal to hex', 'hexadecimal converter', 'hex converter', 'number base converter', 'convert hex to decimal'],
    path: '/tools/hex-to-decimal',
    relatedTools: ['base64-encoder', 'binary-text', 'url-encoder'],
  },
  {
    id: 'yaml-json-converter',
    name: 'YAML ↔ JSON Converter',
    description: 'Convert between YAML and JSON formats with real-time preview',
    icon: '🔄',
    category: 'converter',
    keywords: ['yaml to json', 'json to yaml', 'yaml to json converter', 'json to yaml converter', 'convert yaml to json', 'yaml json', 'yaml converter', 'json converter'],
    path: '/tools/yaml-json-converter',
    relatedTools: ['json-formatter', 'yaml-validator', 'csv-json', 'xml-to-json'],
  },
  {
    id: 'hex-to-rgb',
    name: 'Hex to RGB Converter',
    description: 'Convert between hex color codes and RGB values with color preview',
    icon: '🎨',
    category: 'converter',
    keywords: ['hex to rgb', 'hex to rgb converter', 'hex to rgb color', 'rgb to hex', 'hex color to rgb', 'hex to rgb calculator', 'convert hex to rgb', 'hex to rgb color converter', 'hex to rgb conversion', 'color converter'],
    path: '/tools/hex-to-rgb',
    relatedTools: ['hex-to-decimal', 'css-gradient', 'color-converter', 'css-shadow'],
  },
  {
    id: 'octal-decimal-converter',
    name: 'Octal Decimal Converter',
    description: 'Convert between octal and decimal number systems with binary and hex output',
    icon: '8️⃣',
    category: 'converter',
    keywords: ['octal to decimal', 'decimal to octal', 'octal to decimal converter', 'octal to decimal calculator', 'decimal to octal converter', 'decimal to octal calculator', 'octal converter', 'convert octal to decimal', 'octal number converter'],
    path: '/tools/octal-decimal-converter',
    relatedTools: ['hex-to-decimal', 'binary-text', 'base64', 'chmod-calculator'],
  },
  {
    id: 'roman-numeral-converter',
    name: 'Roman Numeral Converter',
    description: 'Convert between numbers and Roman numerals with date converter',
    icon: 'IV',
    category: 'converter',
    keywords: ['roman numeral converter', 'roman numerals converter', 'roman numeral date converter', 'convert to roman numerals', 'roman numeral birthday converter', 'number to roman numeral', 'roman numeral calculator', 'roman numerals'],
    path: '/tools/roman-numeral-converter',
    relatedTools: ['hex-to-decimal', 'octal-decimal-converter', 'number-base-converter'],
  },
];

export function getToolsByCategory(categoryId: string): Tool[] {
  return tools.filter(t => t.category === categoryId);
}

export function searchTools(query: string): Tool[] {
  const q = query.toLowerCase();
  return tools.filter(t =>
    t.name.toLowerCase().includes(q) ||
    t.description.toLowerCase().includes(q) ||
    t.keywords.some(k => k.includes(q))
  );
}
