'use client';
import React from 'react';
import Link from 'next/link';

const translations: Record<string, Record<string, string>> = {
  en: {
    title: 'Docker Volumes vs Bind Mounts Explained',
    intro: 'Docker containers are ephemeral by design — when a container is removed, all data inside it is lost. Docker provides three storage mechanisms to persist data beyond the container lifecycle: volumes, bind mounts, and tmpfs mounts. This guide covers every aspect of Docker storage, from basic volume commands to advanced driver configurations, backup strategies, and performance tuning.',

    overviewTitle: 'Storage Types Overview',
    overviewDesc: 'Docker offers three primary storage options for containers. Understanding the differences is critical for choosing the right approach for each use case.',
    storageType: 'Storage Type',
    managedBy: 'Managed By',
    hostLocation: 'Host Location',
    bestFor: 'Best For',
    volumeDesc: 'Production data, databases',
    bindDesc: 'Development, config files',
    tmpfsDesc: 'Secrets, temp data (Linux only)',
    overviewNote: 'Volumes are the recommended mechanism for persisting data generated by and used by Docker containers. Unlike bind mounts, volumes are completely managed by Docker and are isolated from the host machine\'s filesystem.',

    namedVolTitle: 'Named Volumes',
    namedVolDesc: 'Named volumes are the most common and recommended way to persist data in Docker. Docker manages the entire lifecycle of the volume, including creation, storage location, and cleanup.',
    namedVolCreateTitle: 'Creating and Using Named Volumes',
    namedVolLifecycleTitle: 'Volume Lifecycle',
    namedVolLifecycleDesc: 'Named volumes persist independently of containers. They survive container stops, restarts, and removals. The only way to remove a named volume is to explicitly delete it with docker volume rm or docker volume prune.',

    bindTitle: 'Bind Mounts',
    bindFullDesc: 'Bind mounts map a specific host directory or file directly into a container. The host path must be an absolute path. Bind mounts are ideal for development workflows where you need live code reloading.',
    bindSyntaxTitle: 'Bind Mount Syntax',
    bindDevTitle: 'Development Workflow with Bind Mounts',
    bindDevDesc: 'Bind mounts shine in development — edit code on your host, and changes appear immediately inside the container without rebuilding the image.',
    bindWarning: 'Warning: Bind mounts give the container direct access to the host filesystem. A container running as root can modify or delete host files. Use read-only mounts (:ro) when the container only needs to read data.',

    composeVolTitle: 'Docker Compose Volumes',
    composeVolDesc: 'Docker Compose provides a declarative way to define volumes alongside your services. Volumes can be defined using short syntax or long syntax for more control.',
    composeShortTitle: 'Short Syntax',
    composeLongTitle: 'Long Syntax',
    composeLongDesc: 'The long syntax provides more configuration options including read-only mode, volume sub-paths, and bind propagation.',
    composeExternalTitle: 'External and Shared Volumes',
    composeExternalDesc: 'Use external volumes to share data between multiple Compose projects, or reference volumes created outside of Compose.',

    driversTitle: 'Volume Drivers',
    driversDesc: 'Docker supports pluggable volume drivers that allow you to store data on remote hosts or cloud providers. The default driver is "local" which stores data on the Docker host.',
    driversLocalTitle: 'Local Driver with Options',
    driversNFSTitle: 'NFS Volume Driver',
    driversCloudTitle: 'Cloud Volume Drivers',
    driversCloudDesc: 'For production workloads in the cloud, use provider-specific volume drivers to mount cloud storage directly into containers.',

    readonlyTitle: 'Read-Only Volumes',
    readonlyDesc: 'The :ro flag (or read_only option in long syntax) mounts a volume as read-only inside the container. This is a critical security practice — if a container is compromised, it cannot modify the mounted data.',
    readonlyBenefitsTitle: 'Security Benefits of Read-Only Mounts',
    readonlyBenefit1: 'Prevents container from modifying configuration files',
    readonlyBenefit2: 'Protects host filesystem from compromised containers',
    readonlyBenefit3: 'Enforces immutable infrastructure patterns',
    readonlyBenefit4: 'Reduces blast radius of container escape vulnerabilities',

    persistTitle: 'Data Persistence',
    persistDesc: 'Understanding when data persists and when it is lost is essential for reliable container deployments.',
    scenario: 'Scenario',
    volumeData: 'Volume Data',
    bindData: 'Bind Mount Data',
    containerData: 'Container Data',
    persist_stop: 'Container stopped',
    persist_restart: 'Container restarted',
    persist_rm: 'Container removed',
    persist_down: 'docker compose down',
    persist_downv: 'docker compose down -v',
    persist_prune: 'docker volume prune',
    preserved: 'Preserved',
    lost: 'Lost',
    removed: 'Removed (unused)',
    persistStrategyTitle: 'Backup Strategies',
    persistStrategyDesc: 'Always maintain a backup strategy for critical data. Named volumes should be backed up regularly, especially for databases.',

    backupTitle: 'Backup & Restore',
    backupDesc: 'Docker does not provide built-in backup commands for volumes. The standard approach is to use a temporary container that mounts the volume and creates a tar archive.',
    backupCreateTitle: 'Backup a Volume',
    backupRestoreTitle: 'Restore a Volume',
    backupFromTitle: 'Backup Using --volumes-from',
    backupFromDesc: 'The --volumes-from flag mounts all volumes from another container, which is useful when you don\'t know the exact volume mount paths.',
    backupAutoTitle: 'Automated Backup Script',

    mgmtTitle: 'Volume Management Commands',
    mgmtDesc: 'Docker provides a complete set of CLI commands for managing volumes throughout their lifecycle.',
    command: 'Command',
    description: 'Description',

    perfTitle: 'Performance Considerations',
    perfDesc: 'Volume performance varies significantly across operating systems. On Linux, both volumes and bind mounts achieve near-native performance. On macOS and Windows, there are important differences.',
    perfLinuxTitle: 'Linux',
    perfLinuxDesc: 'Both volumes and bind mounts use the native filesystem. Performance is identical to direct host access. This is the recommended platform for production Docker workloads.',
    perfMacTitle: 'macOS and Windows',
    perfMacDesc: 'Docker Desktop runs Linux containers inside a lightweight VM. File sharing between the host and the VM introduces I/O overhead, especially for bind mounts with many small files (like node_modules).',
    perfFlagsTitle: 'Consistency Flags (macOS)',
    perfFlagsDesc: 'Docker on macOS supports consistency flags to tune the tradeoff between performance and data consistency. Note: these flags are deprecated in recent Docker Desktop versions which use VirtioFS by default.',
    flag: 'Flag',
    behavior: 'Behavior',
    useCase: 'Use Case',
    perfTipsTitle: 'Performance Tips',
    perfTip1: 'Use named volumes for node_modules to avoid cross-filesystem sync',
    perfTip2: 'On macOS/Windows, use VirtioFS (default in Docker Desktop 4.15+) for best bind mount performance',
    perfTip3: 'Exclude large dependency directories from bind mounts using a named volume overlay',
    perfTip4: 'For database volumes, always use named volumes instead of bind mounts',

    patternsTitle: 'Common Patterns',
    patternsDesc: 'Here are battle-tested patterns for common Docker storage scenarios.',
    pattern1Title: 'Database Data Persistence',
    pattern2Title: 'Shared Configuration Files',
    pattern3Title: 'Development Hot-Reload with Dependency Isolation',
    pattern3Desc: 'This pattern bind-mounts your source code for live reloading while using a named volume for node_modules to avoid performance issues and platform-specific binary mismatches.',
    pattern4Title: 'Build Artifact Output',
    pattern4Desc: 'Use a named volume to share build artifacts between a builder container and a web server container.',

    relatedToolTitle: 'Related Tool',
    relatedToolDesc: 'Generate Docker Compose configurations visually with our Docker Compose Generator tool:',
    relatedToolLink: 'Docker Compose Generator',

    faqTitle: 'FAQ',
    faq1q: 'What is the difference between Docker volumes and bind mounts?',
    faq1a: 'Volumes are managed by Docker and stored in a Docker-controlled area of the host filesystem (/var/lib/docker/volumes/). Bind mounts map a specific host path directly into the container. Volumes are more portable, easier to back up, and work consistently across platforms. Bind mounts depend on the host filesystem structure and are primarily used for development workflows.',
    faq2q: 'Do Docker volumes persist after container removal?',
    faq2a: 'Yes. Named volumes persist independently of containers. Removing a container with docker rm does not remove its volumes. Volumes are only removed when explicitly deleted with docker volume rm, docker volume prune, or docker compose down -v. Anonymous volumes (created without a name) may be removed with docker rm -v or docker volume prune.',
    faq3q: 'How do I backup a Docker volume?',
    faq3a: 'Use a temporary container to create a tar archive of the volume contents: docker run --rm -v myvolume:/data -v $(pwd):/backup alpine tar czf /backup/myvolume-backup.tar.gz -C /data . This mounts the volume and your current directory, then creates a compressed archive. For databases, prefer using the database\'s native dump tools (pg_dump, mysqldump) for consistent backups.',
    faq4q: 'Why are Docker volumes slow on macOS?',
    faq4a: 'Docker Desktop on macOS runs Linux containers inside a lightweight VM. Bind mounts require file synchronization between the macOS host and the Linux VM, which introduces I/O overhead. This is especially noticeable with many small files (like node_modules). Solutions include: using named volumes for dependency directories, enabling VirtioFS in Docker Desktop settings, and minimizing the number of files in bind mounts.',
    faq5q: 'Should I use volumes or bind mounts for development?',
    faq5a: 'Use bind mounts for source code so changes on your host are immediately reflected in the container. Use named volumes for dependency directories (node_modules, vendor, venv) to avoid performance issues and platform-specific binary problems. This hybrid approach gives you live reloading for your code while keeping dependencies fast and isolated.',
  },
  zh: {
    title: 'Docker 卷与绑定挂载详解',
    intro: 'Docker 容器的设计是临时性的——容器被删除时，其中所有数据都会丢失。Docker 提供三种存储机制来将数据持久化到容器生命周期之外：卷（volumes）、绑定挂载（bind mounts）和 tmpfs 挂载。本指南涵盖 Docker 存储的方方面面，从基本卷命令到高级驱动配置、备份策略和性能调优。',

    overviewTitle: '存储类型概览',
    overviewDesc: 'Docker 为容器提供三种主要存储选项。了解它们的区别对于为每个场景选择正确的方案至关重要。',
    storageType: '存储类型',
    managedBy: '管理者',
    hostLocation: '主机位置',
    bestFor: '最佳用途',
    volumeDesc: '生产数据、数据库',
    bindDesc: '开发环境、配置文件',
    tmpfsDesc: '密钥、临时数据（仅 Linux）',
    overviewNote: '卷是 Docker 推荐的数据持久化机制。与绑定挂载不同，卷完全由 Docker 管理，与宿主机文件系统隔离。',

    namedVolTitle: '命名卷',
    namedVolDesc: '命名卷是 Docker 中最常用且推荐的数据持久化方式。Docker 管理卷的完整生命周期，包括创建、存储位置和清理。',
    namedVolCreateTitle: '创建和使用命名卷',
    namedVolLifecycleTitle: '卷生命周期',
    namedVolLifecycleDesc: '命名卷独立于容器持久化。它们在容器停止、重启和删除后仍然存在。删除命名卷的唯一方式是通过 docker volume rm 或 docker volume prune 显式删除。',

    bindTitle: '绑定挂载',
    bindFullDesc: '绑定挂载将宿主机的特定目录或文件直接映射到容器中。宿主机路径必须是绝对路径。绑定挂载非常适合需要实时代码重载的开发工作流。',
    bindSyntaxTitle: '绑定挂载语法',
    bindDevTitle: '使用绑定挂载的开发工作流',
    bindDevDesc: '绑定挂载在开发中表现出色——在宿主机上编辑代码，更改立即出现在容器内，无需重建镜像。',
    bindWarning: '警告：绑定挂载允许容器直接访问宿主机文件系统。以 root 运行的容器可以修改或删除宿主机文件。当容器只需要读取数据时，使用只读挂载（:ro）。',

    composeVolTitle: 'Docker Compose 卷',
    composeVolDesc: 'Docker Compose 提供声明式方式来定义服务的卷。卷可以使用短语法或长语法来定义，长语法提供更多控制选项。',
    composeShortTitle: '短语法',
    composeLongTitle: '长语法',
    composeLongDesc: '长语法提供更多配置选项，包括只读模式、卷子路径和绑定传播。',
    composeExternalTitle: '外部卷和共享卷',
    composeExternalDesc: '使用外部卷在多个 Compose 项目之间共享数据，或引用在 Compose 之外创建的卷。',

    driversTitle: '卷驱动',
    driversDesc: 'Docker 支持可插拔的卷驱动，允许将数据存储在远程主机或云服务商。默认驱动是 "local"，将数据存储在 Docker 宿主机上。',
    driversLocalTitle: '带选项的本地驱动',
    driversNFSTitle: 'NFS 卷驱动',
    driversCloudTitle: '云卷驱动',
    driversCloudDesc: '在云端生产工作负载中，使用特定云服务商的卷驱动将云存储直接挂载到容器中。',

    readonlyTitle: '只读卷',
    readonlyDesc: ':ro 标志（或长语法中的 read_only 选项）将卷以只读方式挂载到容器内。这是关键的安全实践——如果容器被攻破，它无法修改挂载的数据。',
    readonlyBenefitsTitle: '只读挂载的安全优势',
    readonlyBenefit1: '防止容器修改配置文件',
    readonlyBenefit2: '保护宿主机文件系统免受被攻破容器的影响',
    readonlyBenefit3: '强制执行不可变基础设施模式',
    readonlyBenefit4: '减少容器逃逸漏洞的影响范围',

    persistTitle: '数据持久化',
    persistDesc: '了解数据何时持久化、何时丢失，对于可靠的容器部署至关重要。',
    scenario: '场景',
    volumeData: '卷数据',
    bindData: '绑定挂载数据',
    containerData: '容器数据',
    persist_stop: '容器停止',
    persist_restart: '容器重启',
    persist_rm: '容器删除',
    persist_down: 'docker compose down',
    persist_downv: 'docker compose down -v',
    persist_prune: 'docker volume prune',
    preserved: '保留',
    lost: '丢失',
    removed: '删除（未使用的）',
    persistStrategyTitle: '备份策略',
    persistStrategyDesc: '始终为关键数据维护备份策略。命名卷应定期备份，特别是数据库。',

    backupTitle: '备份与恢复',
    backupDesc: 'Docker 没有提供内置的卷备份命令。标准方法是使用临时容器挂载卷并创建 tar 归档。',
    backupCreateTitle: '备份卷',
    backupRestoreTitle: '恢复卷',
    backupFromTitle: '使用 --volumes-from 备份',
    backupFromDesc: '--volumes-from 标志挂载另一个容器的所有卷，当你不知道确切的卷挂载路径时非常有用。',
    backupAutoTitle: '自动备份脚本',

    mgmtTitle: '卷管理命令',
    mgmtDesc: 'Docker 提供了一套完整的 CLI 命令来管理卷的整个生命周期。',
    command: '命令',
    description: '说明',

    perfTitle: '性能考量',
    perfDesc: '卷性能在不同操作系统上差异显著。在 Linux 上，卷和绑定挂载都能达到接近原生的性能。在 macOS 和 Windows 上，有一些重要区别。',
    perfLinuxTitle: 'Linux',
    perfLinuxDesc: '卷和绑定挂载都使用原生文件系统。性能与直接访问宿主机相同。这是生产环境 Docker 工作负载的推荐平台。',
    perfMacTitle: 'macOS 和 Windows',
    perfMacDesc: 'Docker Desktop 在轻量级虚拟机内运行 Linux 容器。宿主机和虚拟机之间的文件共享引入了 I/O 开销，特别是对于包含大量小文件的绑定挂载（如 node_modules）。',
    perfFlagsTitle: '一致性标志（macOS）',
    perfFlagsDesc: 'macOS 上的 Docker 支持一致性标志来调整性能与数据一致性之间的权衡。注意：这些标志在使用 VirtioFS 的新版 Docker Desktop 中已弃用。',
    flag: '标志',
    behavior: '行为',
    useCase: '使用场景',
    perfTipsTitle: '性能建议',
    perfTip1: '使用命名卷来存储 node_modules，避免跨文件系统同步',
    perfTip2: '在 macOS/Windows 上，使用 VirtioFS（Docker Desktop 4.15+ 默认）获取最佳绑定挂载性能',
    perfTip3: '使用命名卷覆盖层将大型依赖目录从绑定挂载中排除',
    perfTip4: '对于数据库卷，始终使用命名卷而非绑定挂载',

    patternsTitle: '常见模式',
    patternsDesc: '以下是常见 Docker 存储场景中经过实战检验的模式。',
    pattern1Title: '数据库数据持久化',
    pattern2Title: '共享配置文件',
    pattern3Title: '开发热重载与依赖隔离',
    pattern3Desc: '此模式绑定挂载源代码以实现实时重载，同时使用命名卷存储 node_modules 以避免性能问题和平台特定的二进制不兼容。',
    pattern4Title: '构建产物输出',
    pattern4Desc: '使用命名卷在构建容器和 Web 服务容器之间共享构建产物。',

    relatedToolTitle: '相关工具',
    relatedToolDesc: '使用我们的 Docker Compose 生成器可视化生成 Docker Compose 配置：',
    relatedToolLink: 'Docker Compose 生成器',

    faqTitle: '常见问题',
    faq1q: 'Docker 卷和绑定挂载有什么区别？',
    faq1a: '卷由 Docker 管理，存储在 Docker 控制的宿主机文件系统区域（/var/lib/docker/volumes/）。绑定挂载将特定的宿主机路径直接映射到容器中。卷更具可移植性、更易于备份，且跨平台表现一致。绑定挂载依赖宿主机文件系统结构，主要用于开发工作流。',
    faq2q: 'Docker 卷在容器删除后还存在吗？',
    faq2a: '是的。命名卷独立于容器持久化。使用 docker rm 删除容器不会删除其卷。卷只有在通过 docker volume rm、docker volume prune 或 docker compose down -v 显式删除时才会被移除。匿名卷（未命名创建的）可能会被 docker rm -v 或 docker volume prune 删除。',
    faq3q: '如何备份 Docker 卷？',
    faq3a: '使用临时容器创建卷内容的 tar 归档：docker run --rm -v myvolume:/data -v $(pwd):/backup alpine tar czf /backup/myvolume-backup.tar.gz -C /data . 这将挂载卷和当前目录，然后创建压缩归档。对于数据库，建议使用数据库原生导出工具（pg_dump、mysqldump）进行一致性备份。',
    faq4q: '为什么 Docker 卷在 macOS 上很慢？',
    faq4a: 'macOS 上的 Docker Desktop 在轻量级虚拟机内运行 Linux 容器。绑定挂载需要在 macOS 宿主机和 Linux 虚拟机之间同步文件，引入了 I/O 开销。这在大量小文件（如 node_modules）时特别明显。解决方案包括：对依赖目录使用命名卷、在 Docker Desktop 设置中启用 VirtioFS、减少绑定挂载中的文件数量。',
    faq5q: '开发时应该用卷还是绑定挂载？',
    faq5a: '对源代码使用绑定挂载，这样宿主机上的更改会立即反映到容器中。对依赖目录（node_modules、vendor、venv）使用命名卷，以避免性能问题和平台特定的二进制兼容问题。这种混合方式既能让代码实时重载，又能保持依赖快速且隔离。',
  },
};

const codeStyle: React.CSSProperties = { background: 'var(--bg-input)', borderRadius: 8, padding: 16, overflowX: 'auto', fontSize: 13, lineHeight: 1.7, fontFamily: 'monospace', color: 'var(--text-primary)', border: '1px solid var(--border-color)', margin: '12px 0' };
const tableStyle: React.CSSProperties = { width: '100%', borderCollapse: 'collapse', fontSize: 14, margin: '16px 0' };
const thStyle: React.CSSProperties = { textAlign: 'left', padding: '10px 12px', borderBottom: '2px solid var(--border-color)', fontWeight: 700, color: 'var(--text-primary)', background: 'var(--bg-input)' };
const tdStyle: React.CSSProperties = { padding: '10px 12px', borderBottom: '1px solid var(--border-color)', color: 'var(--text-secondary)' };
const h2Style: React.CSSProperties = { fontSize: 22, fontWeight: 700, marginTop: 40, marginBottom: 16, color: 'var(--text-primary)' };
const h3Style: React.CSSProperties = { fontSize: 18, fontWeight: 600, marginTop: 32, marginBottom: 12, color: 'var(--text-primary)' };
const pStyle: React.CSSProperties = { color: 'var(--text-secondary)', lineHeight: 1.8, marginBottom: 12 };
const ulStyle: React.CSSProperties = { color: 'var(--text-secondary)', lineHeight: 1.8, paddingLeft: 24, marginBottom: 12 };
const alertStyle: React.CSSProperties = { padding: '14px 18px', borderRadius: 8, border: '1px solid var(--border-color)', background: 'var(--bg-input)', marginBottom: 16, lineHeight: 1.7, color: 'var(--text-secondary)' };

export default function DockerVolumesBindMountsGuide({ lang }: { lang: string }) {
  const t = translations[lang] || translations['en'];

  const faqSchema = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: [
      { '@type': 'Question', name: t.faq1q, acceptedAnswer: { '@type': 'Answer', text: t.faq1a } },
      { '@type': 'Question', name: t.faq2q, acceptedAnswer: { '@type': 'Answer', text: t.faq2a } },
      { '@type': 'Question', name: t.faq3q, acceptedAnswer: { '@type': 'Answer', text: t.faq3a } },
      { '@type': 'Question', name: t.faq4q, acceptedAnswer: { '@type': 'Answer', text: t.faq4a } },
      { '@type': 'Question', name: t.faq5q, acceptedAnswer: { '@type': 'Answer', text: t.faq5a } },
    ],
  };

  return (
    <div>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />

      <p style={pStyle}>{t.intro}</p>

      {/* Section 1: Storage Types Overview */}
      <h2 style={h2Style}>{t.overviewTitle}</h2>
      <p style={pStyle}>{t.overviewDesc}</p>
      <table style={tableStyle}>
        <thead>
          <tr>
            <th style={thStyle}>{t.storageType}</th>
            <th style={thStyle}>{t.managedBy}</th>
            <th style={thStyle}>{t.hostLocation}</th>
            <th style={thStyle}>{t.bestFor}</th>
          </tr>
        </thead>
        <tbody>
          {[
            ['Volume', 'Docker', '/var/lib/docker/volumes/', t.volumeDesc],
            ['Bind Mount', lang === 'zh' ? '用户' : 'User', lang === 'zh' ? '任意宿主机路径' : 'Any host path', t.bindDesc],
            ['tmpfs', 'Docker', lang === 'zh' ? '内存（RAM）' : 'Memory (RAM)', t.tmpfsDesc],
          ].map(([type, managed, location, best], i) => (
            <tr key={i}>
              <td style={{ ...tdStyle, fontWeight: 600 }}>{type}</td>
              <td style={tdStyle}>{managed}</td>
              <td style={{ ...tdStyle, fontFamily: 'monospace', fontSize: 13 }}>{location}</td>
              <td style={tdStyle}>{best}</td>
            </tr>
          ))}
        </tbody>
      </table>
      <pre style={codeStyle}><code>{`# Comparison of storage types in docker run
# Named volume
docker run -v mydata:/app/data nginx

# Bind mount
docker run -v /home/user/data:/app/data nginx

# tmpfs mount
docker run --tmpfs /app/temp nginx

# Using --mount flag (more explicit)
docker run --mount type=volume,source=mydata,target=/app/data nginx
docker run --mount type=bind,source=/home/user/data,target=/app/data nginx
docker run --mount type=tmpfs,target=/app/temp nginx`}</code></pre>
      <div style={alertStyle}>
        <strong>{lang === 'zh' ? '提示：' : 'Tip:'}</strong> {t.overviewNote}
      </div>

      {/* Section 2: Named Volumes */}
      <h2 style={h2Style}>{t.namedVolTitle}</h2>
      <p style={pStyle}>{t.namedVolDesc}</p>

      <h3 style={h3Style}>{t.namedVolCreateTitle}</h3>
      <pre style={codeStyle}><code>{`# Create a named volume
docker volume create mydata

# Create with specific driver and options
docker volume create --driver local \\
  --opt type=none \\
  --opt device=/path/to/data \\
  --opt o=bind \\
  my-bind-vol

# Use a named volume in docker run
docker run -d \\
  --name postgres-db \\
  -v pgdata:/var/lib/postgresql/data \\
  -e POSTGRES_PASSWORD=secret \\
  postgres:16

# Volume is auto-created if it doesn't exist
docker run -d -v mydata:/data alpine

# Use --mount for explicit volume creation
docker run -d \\
  --mount type=volume,source=mydata,target=/data \\
  alpine

# Inspect volume details
docker volume inspect mydata
# Output:
# [
#   {
#     "CreatedAt": "2025-01-15T10:30:00Z",
#     "Driver": "local",
#     "Labels": {},
#     "Mountpoint": "/var/lib/docker/volumes/mydata/_data",
#     "Name": "mydata",
#     "Options": {},
#     "Scope": "local"
#   }
# ]`}</code></pre>

      <h3 style={h3Style}>{t.namedVolLifecycleTitle}</h3>
      <p style={pStyle}>{t.namedVolLifecycleDesc}</p>
      <pre style={codeStyle}><code>{`# Create container with volume
docker run -d --name app1 -v shared-data:/data alpine sleep 3600

# Write data inside the volume
docker exec app1 sh -c 'echo "Hello from app1" > /data/message.txt'

# Stop and remove the container
docker stop app1 && docker rm app1

# Data persists! Create new container with same volume
docker run --rm -v shared-data:/data alpine cat /data/message.txt
# Output: Hello from app1

# Multiple containers can share the same volume
docker run -d --name writer -v shared-data:/data alpine sh -c \\
  'while true; do date >> /data/log.txt; sleep 5; done'
docker run -d --name reader -v shared-data:/data:ro alpine tail -f /data/log.txt`}</code></pre>

      {/* Section 3: Bind Mounts */}
      <h2 style={h2Style}>{t.bindTitle}</h2>
      <p style={pStyle}>{t.bindFullDesc}</p>

      <h3 style={h3Style}>{t.bindSyntaxTitle}</h3>
      <pre style={codeStyle}><code>{`# Short syntax: -v host_path:container_path
docker run -v /home/user/project:/app node:20

# Short syntax with read-only
docker run -v /home/user/config:/etc/app/config:ro nginx

# Long syntax: --mount (recommended for clarity)
docker run --mount type=bind,source=/home/user/project,target=/app node:20

# --mount with read-only
docker run \\
  --mount type=bind,source=/home/user/config,target=/etc/app/config,readonly \\
  nginx

# Key difference: -v creates the host dir if missing
# --mount fails with an error if host dir doesn't exist
docker run -v /nonexistent/path:/data alpine    # Creates /nonexistent/path
docker run --mount type=bind,source=/nonexistent/path,target=/data alpine  # ERROR`}</code></pre>

      <h3 style={h3Style}>{t.bindDevTitle}</h3>
      <p style={pStyle}>{t.bindDevDesc}</p>
      <pre style={codeStyle}><code>{`# React development with hot reload
docker run -d \\
  --name react-dev \\
  -v $(pwd)/src:/app/src \\
  -v $(pwd)/public:/app/public \\
  -p 3000:3000 \\
  -e CHOKIDAR_USEPOLLING=true \\
  my-react-app

# Python Flask development
docker run -d \\
  --name flask-dev \\
  -v $(pwd):/app \\
  -p 5000:5000 \\
  -e FLASK_DEBUG=1 \\
  my-flask-app

# Go development with air (live reload)
docker run -d \\
  --name go-dev \\
  -v $(pwd):/app \\
  -p 8080:8080 \\
  cosmtrek/air`}</code></pre>
      <div style={alertStyle}>
        <strong>{lang === 'zh' ? '警告：' : 'Warning:'}</strong> {t.bindWarning}
      </div>

      {/* Section 4: Docker Compose Volumes */}
      <h2 style={h2Style}>{t.composeVolTitle}</h2>
      <p style={pStyle}>{t.composeVolDesc}</p>

      <h3 style={h3Style}>{t.composeShortTitle}</h3>
      <pre style={codeStyle}><code>{`services:
  db:
    image: postgres:16
    volumes:
      # Named volume
      - pgdata:/var/lib/postgresql/data

      # Bind mount (relative path)
      - ./init-scripts:/docker-entrypoint-initdb.d

      # Bind mount (absolute path)
      - /var/log/postgres:/var/log/postgresql

      # Read-only bind mount
      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf:ro

      # Anonymous volume
      - /var/lib/postgresql/temp

volumes:
  pgdata:           # Named volume declaration
    driver: local`}</code></pre>

      <h3 style={h3Style}>{t.composeLongTitle}</h3>
      <p style={pStyle}>{t.composeLongDesc}</p>
      <pre style={codeStyle}><code>{`services:
  web:
    image: nginx:alpine
    volumes:
      # Long syntax - named volume
      - type: volume
        source: web-data
        target: /usr/share/nginx/html
        volume:
          nocopy: true    # Don't copy container data into volume

      # Long syntax - bind mount
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true

      # Long syntax - tmpfs
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 100000000  # 100MB limit

volumes:
  web-data:`}</code></pre>

      <h3 style={h3Style}>{t.composeExternalTitle}</h3>
      <p style={pStyle}>{t.composeExternalDesc}</p>
      <pre style={codeStyle}><code>{`# Project A: creates the volume
# docker-compose.yml (Project A)
services:
  api:
    image: my-api
    volumes:
      - shared-data:/data

volumes:
  shared-data:
    name: my-shared-data    # Explicit name (not prefixed with project name)

---
# Project B: uses the same volume
# docker-compose.yml (Project B)
services:
  worker:
    image: my-worker
    volumes:
      - shared-data:/data

volumes:
  shared-data:
    external: true
    name: my-shared-data    # Must match the volume name from Project A

---
# Pre-create a volume externally
docker volume create --driver local my-shared-data`}</code></pre>

      {/* Section 5: Volume Drivers */}
      <h2 style={h2Style}>{t.driversTitle}</h2>
      <p style={pStyle}>{t.driversDesc}</p>

      <h3 style={h3Style}>{t.driversLocalTitle}</h3>
      <pre style={codeStyle}><code>{`# Local driver with tmpfs backend (RAM-based volume)
docker volume create --driver local \\
  --opt type=tmpfs \\
  --opt device=tmpfs \\
  --opt o=size=256m \\
  ramdisk

# Local driver with ext4 filesystem on a specific device
docker volume create --driver local \\
  --opt type=ext4 \\
  --opt device=/dev/sdb1 \\
  fast-storage

# Local driver binding to a specific directory
docker volume create --driver local \\
  --opt type=none \\
  --opt device=/mnt/data/app \\
  --opt o=bind \\
  app-data`}</code></pre>

      <h3 style={h3Style}>{t.driversNFSTitle}</h3>
      <pre style={codeStyle}><code>{`# NFS volume using the local driver
docker volume create --driver local \\
  --opt type=nfs \\
  --opt o=addr=192.168.1.100,rw,nfsvers=4 \\
  --opt device=:/exports/data \\
  nfs-data

# NFS volume in Docker Compose
services:
  app:
    image: my-app
    volumes:
      - nfs-data:/app/data

volumes:
  nfs-data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.100,rw,nfsvers=4
      device: ":/exports/data"

# CIFS/SMB volume (Windows shares)
docker volume create --driver local \\
  --opt type=cifs \\
  --opt device=//server/share \\
  --opt o=addr=server,username=user,password=pass \\
  smb-data`}</code></pre>

      <h3 style={h3Style}>{t.driversCloudTitle}</h3>
      <p style={pStyle}>{t.driversCloudDesc}</p>
      <pre style={codeStyle}><code>{`# AWS EFS volume (using amazon-ecs-volume-plugin or docker plugin)
# First install the plugin
docker plugin install rexray/efs

# Create volume backed by EFS
docker volume create --driver rexray/efs \\
  --opt filesystem=fs-12345678 \\
  efs-data

# Azure Files in Docker Compose
volumes:
  azure-data:
    driver: azure_file
    driver_opts:
      share_name: myshare
      storage_account_name: mystorageaccount

# GCP Filestore / persistent disk (via CSI or plugin)
# Typically used with Kubernetes rather than standalone Docker`}</code></pre>

      {/* Section 6: Read-Only Volumes */}
      <h2 style={h2Style}>{t.readonlyTitle}</h2>
      <p style={pStyle}>{t.readonlyDesc}</p>
      <pre style={codeStyle}><code>{`# Read-only with -v flag
docker run -v myconfig:/etc/app/config:ro nginx

# Read-only with --mount
docker run \\
  --mount type=volume,source=myconfig,target=/etc/app/config,readonly \\
  nginx

# Read-only bind mount
docker run -v $(pwd)/nginx.conf:/etc/nginx/nginx.conf:ro nginx

# Docker Compose - short syntax
services:
  web:
    volumes:
      - ./config:/etc/app/config:ro
      - certs:/etc/ssl/certs:ro

# Docker Compose - long syntax
services:
  web:
    volumes:
      - type: bind
        source: ./config
        target: /etc/app/config
        read_only: true

# Entire container filesystem as read-only (--read-only flag)
docker run --read-only \\
  --tmpfs /tmp \\
  --tmpfs /run \\
  -v data:/app/data \\
  my-app`}</code></pre>

      <h3 style={h3Style}>{t.readonlyBenefitsTitle}</h3>
      <ul style={ulStyle}>
        <li>{t.readonlyBenefit1}</li>
        <li>{t.readonlyBenefit2}</li>
        <li>{t.readonlyBenefit3}</li>
        <li>{t.readonlyBenefit4}</li>
      </ul>

      {/* Section 7: Data Persistence */}
      <h2 style={h2Style}>{t.persistTitle}</h2>
      <p style={pStyle}>{t.persistDesc}</p>
      <table style={tableStyle}>
        <thead>
          <tr>
            <th style={thStyle}>{t.scenario}</th>
            <th style={thStyle}>{t.volumeData}</th>
            <th style={thStyle}>{t.bindData}</th>
            <th style={thStyle}>{t.containerData}</th>
          </tr>
        </thead>
        <tbody>
          {[
            [t.persist_stop, t.preserved, t.preserved, t.preserved],
            [t.persist_restart, t.preserved, t.preserved, t.preserved],
            [t.persist_rm, t.preserved, t.preserved, t.lost],
            [t.persist_down, t.preserved, t.preserved, t.lost],
            [t.persist_downv, t.lost, t.preserved, t.lost],
            [t.persist_prune, t.removed, t.preserved, 'N/A'],
          ].map(([scenario, vol, bind, container], i) => (
            <tr key={i}>
              <td style={{ ...tdStyle, fontFamily: 'monospace', fontSize: 13, fontWeight: 600 }}>{scenario}</td>
              <td style={{ ...tdStyle, color: vol === t.preserved ? 'var(--accent-green, #22c55e)' : 'var(--accent-red, #ef4444)' }}>{vol}</td>
              <td style={{ ...tdStyle, color: bind === t.preserved ? 'var(--accent-green, #22c55e)' : 'var(--accent-red, #ef4444)' }}>{bind}</td>
              <td style={{ ...tdStyle, color: container === t.preserved ? 'var(--accent-green, #22c55e)' : 'var(--accent-red, #ef4444)' }}>{container}</td>
            </tr>
          ))}
        </tbody>
      </table>

      {/* Section 8: Backup & Restore */}
      <h2 style={h2Style}>{t.backupTitle}</h2>
      <p style={pStyle}>{t.backupDesc}</p>

      <h3 style={h3Style}>{t.backupCreateTitle}</h3>
      <pre style={codeStyle}><code>{`# Backup a named volume to a tar.gz file
docker run --rm \\
  -v mydata:/source:ro \\
  -v $(pwd)/backups:/backup \\
  alpine tar czf /backup/mydata-$(date +%Y%m%d).tar.gz -C /source .

# Backup PostgreSQL volume (prefer pg_dump for consistency)
docker exec postgres-db pg_dump -U postgres mydb > backup.sql

# Backup MySQL volume
docker exec mysql-db mysqldump -u root -p mydb > backup.sql

# Backup with compression and timestamp
docker run --rm \\
  -v pgdata:/source:ro \\
  -v $(pwd)/backups:/backup \\
  alpine sh -c 'tar czf /backup/pgdata-$(date +%Y%m%d-%H%M%S).tar.gz -C /source .'`}</code></pre>

      <h3 style={h3Style}>{t.backupRestoreTitle}</h3>
      <pre style={codeStyle}><code>{`# Restore a volume from backup
docker volume create mydata-restored

docker run --rm \\
  -v mydata-restored:/target \\
  -v $(pwd)/backups:/backup:ro \\
  alpine sh -c 'cd /target && tar xzf /backup/mydata-20250115.tar.gz'

# Restore PostgreSQL from SQL dump
docker exec -i postgres-db psql -U postgres mydb < backup.sql

# Clone a volume (backup + restore in one step)
docker run --rm \\
  -v source-vol:/source:ro \\
  -v target-vol:/target \\
  alpine sh -c 'cd /source && tar cf - . | (cd /target && tar xf -)'`}</code></pre>

      <h3 style={h3Style}>{t.backupFromTitle}</h3>
      <p style={pStyle}>{t.backupFromDesc}</p>
      <pre style={codeStyle}><code>{`# Backup all volumes from a running container
docker run --rm \\
  --volumes-from my-running-container \\
  -v $(pwd)/backups:/backup \\
  alpine tar czf /backup/all-volumes.tar.gz \\
    /var/lib/postgresql/data \\
    /etc/app/config

# This is useful when containers have multiple volumes
# and you want a single backup of all data`}</code></pre>

      <h3 style={h3Style}>{t.backupAutoTitle}</h3>
      <pre style={codeStyle}><code>{`#!/bin/bash
# backup-volumes.sh - Automated Docker volume backup
BACKUP_DIR="/backups/docker"
RETENTION_DAYS=30
DATE=$(date +%Y%m%d-%H%M%S)

# Backup each named volume
for vol in $(docker volume ls -q); do
  echo "Backing up volume: $vol"
  docker run --rm \\
    -v "$vol":/source:ro \\
    -v "$BACKUP_DIR":/backup \\
    alpine tar czf "/backup/$vol-$DATE.tar.gz" -C /source .
done

# Clean up old backups
find "$BACKUP_DIR" -name "*.tar.gz" -mtime +$RETENTION_DAYS -delete

echo "Backup complete: $(ls -1 $BACKUP_DIR/*$DATE* | wc -l) volumes backed up"

# Add to crontab for daily backups at 2 AM:
# 0 2 * * * /path/to/backup-volumes.sh >> /var/log/docker-backup.log 2>&1`}</code></pre>

      {/* Section 9: Volume Management */}
      <h2 style={h2Style}>{t.mgmtTitle}</h2>
      <p style={pStyle}>{t.mgmtDesc}</p>
      <table style={tableStyle}>
        <thead>
          <tr>
            <th style={thStyle}>{t.command}</th>
            <th style={thStyle}>{t.description}</th>
          </tr>
        </thead>
        <tbody>
          {[
            ['docker volume create mydata', lang === 'zh' ? '创建命名卷' : 'Create a named volume'],
            ['docker volume ls', lang === 'zh' ? '列出所有卷' : 'List all volumes'],
            ['docker volume ls -f dangling=true', lang === 'zh' ? '列出未被任何容器使用的卷' : 'List volumes not used by any container'],
            ['docker volume inspect mydata', lang === 'zh' ? '显示卷的详细信息' : 'Show detailed volume information'],
            ['docker volume rm mydata', lang === 'zh' ? '删除指定卷（必须未被使用）' : 'Remove a volume (must be unused)'],
            ['docker volume rm $(docker volume ls -q)', lang === 'zh' ? '删除所有卷（危险！）' : 'Remove ALL volumes (dangerous!)'],
            ['docker volume prune', lang === 'zh' ? '删除所有未使用的卷' : 'Remove all unused volumes'],
            ['docker volume prune -f', lang === 'zh' ? '强制删除未使用的卷（无确认）' : 'Force remove unused volumes (no prompt)'],
            ['docker system df -v', lang === 'zh' ? '显示卷磁盘使用情况' : 'Show volume disk usage'],
            ['docker inspect -f \'{{.Mounts}}\' container', lang === 'zh' ? '查看容器的挂载信息' : 'View container mount information'],
          ].map(([cmd, desc], i) => (
            <tr key={i}>
              <td style={{ ...tdStyle, fontFamily: 'monospace', fontWeight: 600, fontSize: 13 }}>{cmd}</td>
              <td style={tdStyle}>{desc}</td>
            </tr>
          ))}
        </tbody>
      </table>

      {/* Section 10: Performance */}
      <h2 style={h2Style}>{t.perfTitle}</h2>
      <p style={pStyle}>{t.perfDesc}</p>

      <h3 style={h3Style}>{t.perfLinuxTitle}</h3>
      <p style={pStyle}>{t.perfLinuxDesc}</p>

      <h3 style={h3Style}>{t.perfMacTitle}</h3>
      <p style={pStyle}>{t.perfMacDesc}</p>
      <pre style={codeStyle}><code>{`# Problem: node_modules in bind mount is extremely slow on macOS
# BAD - entire project as bind mount (slow npm install, slow builds)
docker run -v $(pwd):/app node:20 npm install
# This syncs thousands of node_modules files between host and VM

# GOOD - use named volume for node_modules
docker run \\
  -v $(pwd):/app \\
  -v node_modules:/app/node_modules \\
  node:20 npm install
# node_modules stays inside the VM, only source code is synced`}</code></pre>

      <h3 style={h3Style}>{t.perfFlagsTitle}</h3>
      <p style={pStyle}>{t.perfFlagsDesc}</p>
      <table style={tableStyle}>
        <thead>
          <tr>
            <th style={thStyle}>{t.flag}</th>
            <th style={thStyle}>{t.behavior}</th>
            <th style={thStyle}>{t.useCase}</th>
          </tr>
        </thead>
        <tbody>
          {[
            ['consistent', lang === 'zh' ? '完全一致（默认），宿主机和容器始终看到相同内容' : 'Full consistency (default), host and container always see same view', lang === 'zh' ? '需要强一致性时' : 'When strong consistency needed'],
            ['cached', lang === 'zh' ? '宿主机写入最终会在容器中可见（有延迟）' : 'Host writes are eventually visible in container (delay allowed)', lang === 'zh' ? '源代码（宿主机编辑，容器读取）' : 'Source code (host edits, container reads)'],
            ['delegated', lang === 'zh' ? '容器写入最终会在宿主机上可见（有延迟）' : 'Container writes are eventually visible on host (delay allowed)', lang === 'zh' ? '构建输出（容器写入，宿主机读取）' : 'Build output (container writes, host reads)'],
          ].map(([flag, beh, use], i) => (
            <tr key={i}>
              <td style={{ ...tdStyle, fontFamily: 'monospace', fontWeight: 600 }}>{flag}</td>
              <td style={tdStyle}>{beh}</td>
              <td style={tdStyle}>{use}</td>
            </tr>
          ))}
        </tbody>
      </table>
      <pre style={codeStyle}><code>{`# Legacy consistency flags (deprecated with VirtioFS)
docker run -v $(pwd)/src:/app/src:cached node:20
docker run -v $(pwd)/dist:/app/dist:delegated node:20

# Modern Docker Desktop (4.15+) uses VirtioFS by default
# which provides near-native performance without flags
# Check: Docker Desktop → Settings → General → Virtual file sharing`}</code></pre>

      <h3 style={h3Style}>{t.perfTipsTitle}</h3>
      <ul style={ulStyle}>
        <li style={{ marginBottom: 8 }}>{t.perfTip1}</li>
        <li style={{ marginBottom: 8 }}>{t.perfTip2}</li>
        <li style={{ marginBottom: 8 }}>{t.perfTip3}</li>
        <li style={{ marginBottom: 8 }}>{t.perfTip4}</li>
      </ul>

      {/* Section 11: Common Patterns */}
      <h2 style={h2Style}>{t.patternsTitle}</h2>
      <p style={pStyle}>{t.patternsDesc}</p>

      <h3 style={{ ...h3Style, color: 'var(--accent-blue)' }}>{t.pattern1Title}</h3>
      <pre style={codeStyle}><code>{`# PostgreSQL with persistent data
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: myapp
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: unless-stopped

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: myapp
    volumes:
      - mysqldata:/var/lib/mysql
    restart: unless-stopped

  mongo:
    image: mongo:7
    volumes:
      - mongodata:/data/db
      - mongoconfig:/data/configdb
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redisdata:/data
    restart: unless-stopped

volumes:
  pgdata:
  mysqldata:
  mongodata:
  mongoconfig:
  redisdata:`}</code></pre>

      <h3 style={{ ...h3Style, color: 'var(--accent-blue)' }}>{t.pattern2Title}</h3>
      <pre style={codeStyle}><code>{`# Share config files across multiple services
services:
  web:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - web-logs:/var/log/nginx

  app:
    build: .
    volumes:
      - ./config/app.yml:/app/config/app.yml:ro
      - app-logs:/app/logs

  # Log aggregator reads logs from both services
  logrotate:
    image: alpine
    volumes:
      - web-logs:/logs/nginx:ro
      - app-logs:/logs/app:ro

volumes:
  web-logs:
  app-logs:`}</code></pre>

      <h3 style={{ ...h3Style, color: 'var(--accent-blue)' }}>{t.pattern3Title}</h3>
      <p style={pStyle}>{t.pattern3Desc}</p>
      <pre style={codeStyle}><code>{`# Development setup with hot-reload + fast dependencies
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      # Bind mount source code for hot-reload
      - ./src:/app/src
      - ./public:/app/public
      - ./package.json:/app/package.json

      # Named volume for node_modules (performance + isolation)
      - node_modules:/app/node_modules

      # Exclude build artifacts
      - dist:/app/dist
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

volumes:
  node_modules:    # Stays in Docker VM, no host sync overhead
  dist:            # Build output stays fast

# After changing package.json, rebuild:
# docker compose run --rm app npm install
# docker compose up`}</code></pre>

      <h3 style={{ ...h3Style, color: 'var(--accent-blue)' }}>{t.pattern4Title}</h3>
      <p style={pStyle}>{t.pattern4Desc}</p>
      <pre style={codeStyle}><code>{`# Multi-stage build with artifact sharing
services:
  builder:
    build:
      context: .
      target: builder
    volumes:
      - build-output:/app/dist

  web:
    image: nginx:alpine
    volumes:
      - build-output:/usr/share/nginx/html:ro
    ports:
      - "80:80"
    depends_on:
      builder:
        condition: service_completed_successfully

volumes:
  build-output:`}</code></pre>

      {/* Related Tool */}
      <h2 style={h2Style}>{t.relatedToolTitle}</h2>
      <p style={pStyle}>{t.relatedToolDesc}</p>
      <p style={{ marginBottom: 24 }}>
        <Link href={`/${lang}/tools/docker-compose-generator`} style={{ color: 'var(--accent-blue)', fontWeight: 700, fontSize: 15 }}>
          {t.relatedToolLink} &rarr;
        </Link>
      </p>

      {/* Section 12: FAQ */}
      <h2 style={h2Style}>{t.faqTitle}</h2>
      {[
        { q: t.faq1q, a: t.faq1a },
        { q: t.faq2q, a: t.faq2a },
        { q: t.faq3q, a: t.faq3a },
        { q: t.faq4q, a: t.faq4a },
        { q: t.faq5q, a: t.faq5a },
      ].map((faq, i) => (
        <details key={i} style={{ marginBottom: 12, padding: '12px 16px', background: 'var(--bg-input)', borderRadius: 8, border: '1px solid var(--border-color)' }}>
          <summary style={{ fontWeight: 700, cursor: 'pointer', color: 'var(--text-primary)' }}>{faq.q}</summary>
          <p style={{ marginTop: 8, color: 'var(--text-secondary)', lineHeight: 1.7 }}>{faq.a}</p>
        </details>
      ))}
    </div>
  );
}
