'use client';
import React from 'react';
import Link from 'next/link';

const translations: Record<string, Record<string, string>> = {
  en: {
    title: '.gitignore Templates & Common Patterns for Every Project',
    intro: 'A well-crafted <strong>.gitignore</strong> file keeps your repository clean by excluding build artifacts, dependencies, secrets, and OS-specific files. This comprehensive guide covers gitignore syntax, templates for every major language and framework, IDE patterns, common mistakes, and our generator tool.',

    h2_what: 'What is .gitignore — Syntax Rules',
    what_desc: 'A .gitignore file tells Git which files and directories to exclude from version control. It uses a simple pattern-matching syntax:',
    rule_comments: 'Comments — Lines starting with # are comments and ignored by Git.',
    rule_negation: 'Negation — Prefix a pattern with ! to re-include a previously excluded file.',
    rule_directories: 'Directories — Append / to match only directories, not files with the same name.',
    rule_globbing: 'Globbing — Use * to match any characters (except /), ** to match nested directories, and ? to match a single character.',
    rule_anchoring: 'Anchoring — A pattern without / matches anywhere in the tree. A leading / anchors to the repo root.',
    syntax_example_title: 'Syntax Examples',

    h2_global_local: 'Global vs Local .gitignore',
    global_local_desc: 'Git supports three levels of ignore rules, each serving a different purpose:',
    local_title: 'Repository .gitignore (committed)',
    local_desc: 'The standard .gitignore at the repo root. Shared with all collaborators. Use for project-specific patterns like build output, dependencies, and environment files.',
    global_title: 'Global ~/.gitignore_global (personal)',
    global_desc: 'Your personal ignore rules applied to every repository on your machine. Use for OS files (.DS_Store, Thumbs.db) and editor files (.vscode, .idea) that should not pollute shared .gitignore.',
    global_setup: 'Set up your global gitignore:',
    exclude_title: '.git/info/exclude (local, not committed)',
    exclude_desc: 'Per-repository ignore rules that are NOT committed. Use for personal files specific to one project that other collaborators do not need to know about (e.g., local test scripts, personal notes).',

    h2_nodejs: 'Node.js .gitignore Template',
    nodejs_desc: 'The essential .gitignore for Node.js projects. Covers npm/yarn/pnpm dependency folders, build output, environment files, and caches:',
    nodejs_node_modules: 'node_modules/ — Dependencies installed by npm/yarn/pnpm. Always regenerated from package.json.',
    nodejs_dist: 'dist/ and build/ — Compiled output. Regenerated by your build tool.',
    nodejs_env: '.env files — Contains API keys, database passwords, and other secrets. Never commit these.',
    nodejs_coverage: 'coverage/ — Test coverage reports generated by Jest, Istanbul, or c8.',
    nodejs_cache: '.cache/ — Build caches from Babel, Parcel, Webpack, etc.',
    nodejs_debug: 'Debug logs — npm-debug.log, yarn-debug.log, yarn-error.log files.',

    h2_python: 'Python .gitignore Template',
    python_desc: 'Python projects generate many bytecode and build artifacts. This template covers all common patterns:',
    python_pycache: '__pycache__/ and *.pyc — Python bytecode files. Regenerated automatically on import.',
    python_venv: 'venv/ and .venv/ — Virtual environment directories. Each developer creates their own.',
    python_egg: '*.egg-info/ and dist/ — Package distribution artifacts from setuptools/pip.',
    python_mypy: '.mypy_cache/ — Type checking cache from mypy.',
    python_pytest: '.pytest_cache/ — Pytest session cache.',
    python_tox: '.tox/ — Tox testing environment directories.',

    h2_java: 'Java / Kotlin .gitignore Template',
    java_desc: 'Java and Kotlin projects using Maven or Gradle produce compiled classes and build directories:',
    java_class: '*.class — Compiled Java bytecode files.',
    java_target: 'target/ — Maven build output directory.',
    java_build: 'build/ — Gradle build output directory.',
    java_gradle: '.gradle/ — Gradle wrapper cache and configuration.',
    java_jar: '*.jar, *.war, *.ear — Compiled archive files. Use dependency management instead.',
    java_idea: '.idea/ — IntelliJ IDEA project files (also covered in IDE section).',

    h2_react: 'React / Next.js .gitignore Template',
    react_desc: 'React and Next.js projects combine Node.js patterns with framework-specific directories:',
    react_next: '.next/ — Next.js build output and cache. Regenerated on every build.',
    react_out: 'out/ — Next.js static export output directory.',
    react_node: 'node_modules/ — Same as any Node.js project.',
    react_env: '.env.local and .env*.local — Local environment overrides with secrets.',
    react_vercel: '.vercel/ — Vercel CLI deployment configuration.',

    h2_go: 'Go .gitignore Template',
    go_desc: 'Go projects are typically lean, but there are still files to exclude:',
    go_bin: 'bin/ — Compiled binary output directory.',
    go_vendor: 'vendor/ — Vendored dependencies (if not using Go modules or if you prefer to exclude).',
    go_exe: '*.exe, *.exe~, *.dll, *.so, *.dylib — Compiled binary files for various platforms.',
    go_test: '*.test — Compiled test binaries from go test -c.',
    go_out: '*.out — Coverage output files from go test -coverprofile.',

    h2_rust: 'Rust .gitignore Template',
    rust_desc: 'Rust and Cargo projects have a straightforward ignore setup:',
    rust_target: 'target/ — All build artifacts, debug and release builds, incremental compilation cache.',
    rust_lock: 'Cargo.lock — For libraries, Cargo.lock should NOT be committed (it is regenerated for consumers). For binaries/applications, DO commit Cargo.lock.',
    rust_pdb: '*.pdb — Windows debug symbol files.',

    h2_ide_os: 'IDE & OS Patterns',
    ide_os_desc: 'These patterns should ideally go in your global ~/.gitignore_global to keep the repository .gitignore clean. But if your team agrees, add them to the project .gitignore:',
    ide_vscode: '.vscode/ — VS Code workspace settings. Alternatively, commit .vscode/settings.json but ignore .vscode/launch.json.',
    ide_idea: '.idea/ — JetBrains IDEs (IntelliJ, WebStorm, PyCharm) project directory.',
    ide_ds_store: '.DS_Store — macOS Finder metadata file. Created in every directory you open in Finder.',
    ide_thumbs: 'Thumbs.db — Windows thumbnail cache file.',
    ide_swp: '*.swp, *.swo — Vim swap files created during editing.',
    ide_sublime: '*.sublime-workspace — Sublime Text workspace files.',

    h2_mistakes: 'Common Mistakes & Fixes',
    mistakes_desc: 'Even experienced developers make these .gitignore mistakes. Here is how to diagnose and fix each one:',
    mistake1_title: '.gitignore not working (file already tracked)',
    mistake1_desc: 'Adding a pattern to .gitignore does NOT remove files that are already tracked by Git. You must untrack them first:',
    mistake1_fix: 'Fix: Remove from Git cache, then commit',
    mistake2_title: 'Ordering matters for negation',
    mistake2_desc: 'Negation patterns (!) only re-include files excluded by earlier patterns. The order matters:',
    mistake3_title: 'Forgetting to ignore .env files',
    mistake3_desc: 'This is the #1 security mistake. If you have already committed a .env file, removing it from .gitignore alone is not enough — the secrets are in Git history.',
    mistake3_fix: 'Fix: Remove from tracking and rotate all secrets',
    mistake4_title: 'Ignoring directories vs files',
    mistake4_desc: 'A trailing slash makes a difference. Without it, the pattern matches both files and directories:',
    mistake5_title: 'Global patterns polluting project .gitignore',
    mistake5_desc: 'Patterns like .DS_Store, Thumbs.db, and .idea/ are personal preferences, not project requirements. Move them to your global gitignore to keep the project .gitignore focused.',

    h2_generators: '.gitignore Generators & Tools',
    generators_desc: 'Instead of manually crafting .gitignore files, use a generator tool to create a comprehensive template for your project stack:',
    generators_our_tool: 'Our Gitignore Generator tool lets you select your languages, frameworks, and IDEs to create a complete .gitignore file in seconds.',
    generators_github: 'GitHub maintains a collection of .gitignore templates at github/gitignore for most languages and frameworks.',
    generators_tip: 'Pro tip: Start with a generated template, then customize it for your specific project needs. Review it periodically as your project evolves.',

    tryTool: 'Generate your .gitignore file instantly',
    tryToolLink: 'Gitignore Generator',

    h2_faq: 'Frequently Asked Questions',
    faq1_q: 'Why is my .gitignore not working?',
    faq1_a: 'The most common reason is that the files are already tracked by Git. Adding a pattern to .gitignore only affects untracked files. To fix this, run "git rm --cached <file>" to untrack the file, then commit the change. The file will remain on disk but Git will stop tracking it.',
    faq2_q: 'Should I commit .gitignore to the repository?',
    faq2_a: 'Yes, always commit your .gitignore file. It ensures all collaborators share the same ignore rules. However, personal preferences like IDE settings and OS-specific files should go in your global ~/.gitignore_global instead.',
    faq3_q: 'What is the difference between .gitignore and .git/info/exclude?',
    faq3_a: '.gitignore is committed to the repository and shared with all collaborators. .git/info/exclude is local to your clone and never committed. Use .git/info/exclude for personal ignore rules that only apply to you in one specific repository.',
    faq4_q: 'How do I ignore a file that is already committed?',
    faq4_a: 'First, add the pattern to .gitignore. Then run "git rm --cached <file>" to remove it from tracking without deleting it from disk. Finally, commit both changes. Note: the file will still exist in Git history. If it contained secrets, you need to rewrite history or rotate the secrets.',
    faq5_q: 'Can I have multiple .gitignore files in a repository?',
    faq5_a: 'Yes, Git supports .gitignore files in any subdirectory. Patterns in a subdirectory .gitignore only apply to files within that directory and its children. The root .gitignore applies to the entire repository. This is useful for monorepos where different packages need different ignore rules.',
  },
  zh: {
    title: '.gitignore 模板与常用模式大全',
    intro: '一个精心编写的 <strong>.gitignore</strong> 文件可以通过排除构建产物、依赖项、密钥和操作系统特定文件来保持仓库整洁。本指南全面介绍了 gitignore 语法、各主流语言和框架的模板、IDE 配置、常见错误以及我们的生成器工具。',

    h2_what: '什么是 .gitignore — 语法规则',
    what_desc: '.gitignore 文件告诉 Git 哪些文件和目录应该排除在版本控制之外。它使用简单的模式匹配语法：',
    rule_comments: '注释 — 以 # 开头的行是注释，Git 会忽略它们。',
    rule_negation: '否定 — 在模式前加 ! 可以重新包含之前被排除的文件。',
    rule_directories: '目录 — 在模式末尾添加 / 仅匹配目录，不匹配同名文件。',
    rule_globbing: '通配符 — 使用 * 匹配任意字符（/ 除外），** 匹配嵌套目录，? 匹配单个字符。',
    rule_anchoring: '锚定 — 不含 / 的模式在整个目录树中匹配。前导 / 锚定到仓库根目录。',
    syntax_example_title: '语法示例',

    h2_global_local: '全局与本地 .gitignore',
    global_local_desc: 'Git 支持三个级别的忽略规则，每个级别有不同的用途：',
    local_title: '仓库 .gitignore（已提交）',
    local_desc: '仓库根目录下的标准 .gitignore 文件。与所有协作者共享。用于项目特定的模式，如构建输出、依赖项和环境文件。',
    global_title: '全局 ~/.gitignore_global（个人）',
    global_desc: '应用于你机器上所有仓库的个人忽略规则。用于操作系统文件（.DS_Store、Thumbs.db）和编辑器文件（.vscode、.idea），这些不应该污染共享的 .gitignore。',
    global_setup: '设置全局 gitignore：',
    exclude_title: '.git/info/exclude（本地，不提交）',
    exclude_desc: '每个仓库的忽略规则，不会被提交。用于其他协作者不需要知道的、特定于某个项目的个人文件（例如本地测试脚本、个人笔记）。',

    h2_nodejs: 'Node.js .gitignore 模板',
    nodejs_desc: 'Node.js 项目的基本 .gitignore。涵盖 npm/yarn/pnpm 依赖文件夹、构建输出、环境文件和缓存：',
    nodejs_node_modules: 'node_modules/ — npm/yarn/pnpm 安装的依赖项。始终从 package.json 重新生成。',
    nodejs_dist: 'dist/ 和 build/ — 编译输出。由构建工具重新生成。',
    nodejs_env: '.env 文件 — 包含 API 密钥、数据库密码和其他密钥。绝不要提交这些文件。',
    nodejs_coverage: 'coverage/ — Jest、Istanbul 或 c8 生成的测试覆盖率报告。',
    nodejs_cache: '.cache/ — Babel、Parcel、Webpack 等的构建缓存。',
    nodejs_debug: '调试日志 — npm-debug.log、yarn-debug.log、yarn-error.log 文件。',

    h2_python: 'Python .gitignore 模板',
    python_desc: 'Python 项目会生成许多字节码和构建产物。此模板涵盖所有常见模式：',
    python_pycache: '__pycache__/ 和 *.pyc — Python 字节码文件。导入时自动重新生成。',
    python_venv: 'venv/ 和 .venv/ — 虚拟环境目录。每个开发者创建自己的。',
    python_egg: '*.egg-info/ 和 dist/ — setuptools/pip 的包分发产物。',
    python_mypy: '.mypy_cache/ — mypy 的类型检查缓存。',
    python_pytest: '.pytest_cache/ — Pytest 会话缓存。',
    python_tox: '.tox/ — Tox 测试环境目录。',

    h2_java: 'Java / Kotlin .gitignore 模板',
    java_desc: '使用 Maven 或 Gradle 的 Java 和 Kotlin 项目会生成编译的类文件和构建目录：',
    java_class: '*.class — 编译的 Java 字节码文件。',
    java_target: 'target/ — Maven 构建输出目录。',
    java_build: 'build/ — Gradle 构建输出目录。',
    java_gradle: '.gradle/ — Gradle 包装器缓存和配置。',
    java_jar: '*.jar、*.war、*.ear — 编译的归档文件。应使用依赖管理代替。',
    java_idea: '.idea/ — IntelliJ IDEA 项目文件（也在 IDE 部分介绍）。',

    h2_react: 'React / Next.js .gitignore 模板',
    react_desc: 'React 和 Next.js 项目结合了 Node.js 模式和框架特定目录：',
    react_next: '.next/ — Next.js 构建输出和缓存。每次构建时重新生成。',
    react_out: 'out/ — Next.js 静态导出输出目录。',
    react_node: 'node_modules/ — 与任何 Node.js 项目相同。',
    react_env: '.env.local 和 .env*.local — 包含密钥的本地环境覆盖。',
    react_vercel: '.vercel/ — Vercel CLI 部署配置。',

    h2_go: 'Go .gitignore 模板',
    go_desc: 'Go 项目通常很精简，但仍有一些文件需要排除：',
    go_bin: 'bin/ — 编译的二进制输出目录。',
    go_vendor: 'vendor/ — 第三方依赖（如果未使用 Go modules 或你选择排除的话）。',
    go_exe: '*.exe、*.exe~、*.dll、*.so、*.dylib — 各平台的编译二进制文件。',
    go_test: '*.test — go test -c 生成的编译测试二进制文件。',
    go_out: '*.out — go test -coverprofile 生成的覆盖率输出文件。',

    h2_rust: 'Rust .gitignore 模板',
    rust_desc: 'Rust 和 Cargo 项目的忽略设置很简单：',
    rust_target: 'target/ — 所有构建产物，包括调试和发布版本、增量编译缓存。',
    rust_lock: 'Cargo.lock — 对于库项目，Cargo.lock 不应该提交（消费者会重新生成）。对于二进制/应用项目，应该提交 Cargo.lock。',
    rust_pdb: '*.pdb — Windows 调试符号文件。',

    h2_ide_os: 'IDE 与操作系统模式',
    ide_os_desc: '这些模式理想情况下应该放在全局 ~/.gitignore_global 中，以保持仓库 .gitignore 的整洁。但如果团队一致同意，也可以添加到项目 .gitignore 中：',
    ide_vscode: '.vscode/ — VS Code 工作区设置。也可以提交 .vscode/settings.json 但忽略 .vscode/launch.json。',
    ide_idea: '.idea/ — JetBrains IDE（IntelliJ、WebStorm、PyCharm）项目目录。',
    ide_ds_store: '.DS_Store — macOS Finder 元数据文件。在 Finder 中打开的每个目录都会创建。',
    ide_thumbs: 'Thumbs.db — Windows 缩略图缓存文件。',
    ide_swp: '*.swp、*.swo — Vim 编辑时创建的交换文件。',
    ide_sublime: '*.sublime-workspace — Sublime Text 工作区文件。',

    h2_mistakes: '常见错误与修复',
    mistakes_desc: '即使是经验丰富的开发者也会犯这些 .gitignore 错误。以下是诊断和修复每个错误的方法：',
    mistake1_title: '.gitignore 不生效（文件已被跟踪）',
    mistake1_desc: '将模式添加到 .gitignore 不会移除 Git 已经跟踪的文件。你必须先取消跟踪：',
    mistake1_fix: '修复：从 Git 缓存中移除，然后提交',
    mistake2_title: '否定模式的顺序很重要',
    mistake2_desc: '否定模式 (!) 只能重新包含被前面模式排除的文件。顺序很重要：',
    mistake3_title: '忘记忽略 .env 文件',
    mistake3_desc: '这是最常见的安全错误。如果你已经提交了 .env 文件，仅从 .gitignore 中删除是不够的 — 密钥已经在 Git 历史中了。',
    mistake3_fix: '修复：从跟踪中移除并轮换所有密钥',
    mistake4_title: '忽略目录 vs 文件',
    mistake4_desc: '尾部斜杠会产生区别。没有它，模式会同时匹配文件和目录：',
    mistake5_title: '全局模式污染项目 .gitignore',
    mistake5_desc: '像 .DS_Store、Thumbs.db 和 .idea/ 这样的模式是个人偏好，不是项目需求。将它们移到全局 gitignore 中，以保持项目 .gitignore 的专注。',

    h2_generators: '.gitignore 生成器与工具',
    generators_desc: '与其手动编写 .gitignore 文件，不如使用生成器工具为你的项目技术栈创建全面的模板：',
    generators_our_tool: '我们的 Gitignore 生成器工具让你选择语言、框架和 IDE，几秒钟内创建完整的 .gitignore 文件。',
    generators_github: 'GitHub 在 github/gitignore 仓库中维护了大多数语言和框架的 .gitignore 模板集合。',
    generators_tip: '专业提示：从生成的模板开始，然后根据你的特定项目需求进行自定义。随着项目的发展，定期检查。',

    tryTool: '立即生成你的 .gitignore 文件',
    tryToolLink: 'Gitignore 生成器',

    h2_faq: '常见问题',
    faq1_q: '为什么我的 .gitignore 不生效？',
    faq1_a: '最常见的原因是文件已经被 Git 跟踪。将模式添加到 .gitignore 只影响未跟踪的文件。要修复此问题，运行 "git rm --cached <file>" 来取消跟踪该文件，然后提交更改。文件将保留在磁盘上，但 Git 将停止跟踪它。',
    faq2_q: '应该将 .gitignore 提交到仓库吗？',
    faq2_a: '是的，始终提交你的 .gitignore 文件。这确保所有协作者共享相同的忽略规则。但是，像 IDE 设置和操作系统特定文件这样的个人偏好应该放在全局 ~/.gitignore_global 中。',
    faq3_q: '.gitignore 和 .git/info/exclude 有什么区别？',
    faq3_a: '.gitignore 被提交到仓库并与所有协作者共享。.git/info/exclude 是你克隆的本地文件，永远不会被提交。对于只适用于你在某个特定仓库中的个人忽略规则，使用 .git/info/exclude。',
    faq4_q: '如何忽略已经提交的文件？',
    faq4_a: '首先，将模式添加到 .gitignore。然后运行 "git rm --cached <file>" 从跟踪中移除它，而不从磁盘删除。最后，提交这两个更改。注意：文件仍然存在于 Git 历史中。如果它包含密钥，你需要重写历史或轮换密钥。',
    faq5_q: '一个仓库中可以有多个 .gitignore 文件吗？',
    faq5_a: '可以，Git 支持在任何子目录中放置 .gitignore 文件。子目录中 .gitignore 的模式仅适用于该目录及其子目录中的文件。根 .gitignore 适用于整个仓库。这对于不同包需要不同忽略规则的 monorepo 很有用。',
  },
};

export default function GitignoreTemplatesCommonPatterns({ lang }: { lang: string }) {
  const t = translations[lang] || translations.en;

  const faqSchema = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: [
      { '@type': 'Question', name: t.faq1_q, acceptedAnswer: { '@type': 'Answer', text: t.faq1_a } },
      { '@type': 'Question', name: t.faq2_q, acceptedAnswer: { '@type': 'Answer', text: t.faq2_a } },
      { '@type': 'Question', name: t.faq3_q, acceptedAnswer: { '@type': 'Answer', text: t.faq3_a } },
      { '@type': 'Question', name: t.faq4_q, acceptedAnswer: { '@type': 'Answer', text: t.faq4_a } },
      { '@type': 'Question', name: t.faq5_q, acceptedAnswer: { '@type': 'Answer', text: t.faq5_a } },
    ],
  };

  const codeStyle: React.CSSProperties = { background: 'var(--bg-input)', border: '1px solid var(--border-color)', borderRadius: 8, padding: '16px 20px', overflowX: 'auto', fontSize: 13, lineHeight: 1.8 };
  const h2Style: React.CSSProperties = { fontSize: 22, fontWeight: 700, marginTop: 40, marginBottom: 16, color: 'var(--text-primary)' };
  const h3Style: React.CSSProperties = { fontSize: 17, fontWeight: 600, marginTop: 24, marginBottom: 12, color: 'var(--text-primary)' };
  const pStyle: React.CSSProperties = { lineHeight: 1.8, color: 'var(--text-secondary)', marginBottom: 16 };
  const ulStyle: React.CSSProperties = { lineHeight: 2, color: 'var(--text-secondary)', paddingLeft: 20, marginBottom: 16 };
  const cardStyle: React.CSSProperties = { padding: 16, background: 'var(--bg-input)', borderRadius: 8, border: '1px solid var(--border-color)', marginBottom: 12 };

  return (
    <div>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />

      <p style={{ fontSize: 16, lineHeight: 1.8, color: 'var(--text-secondary)', marginBottom: 30 }} dangerouslySetInnerHTML={{ __html: t.intro }} />

      {/* ─── Section 1: What is .gitignore ─── */}
      <h2 style={h2Style}>{t.h2_what}</h2>
      <p style={pStyle}>{t.what_desc}</p>
      <ul style={ulStyle}>
        <li><code style={{ color: 'var(--accent-blue)' }}>#</code> — {t.rule_comments}</li>
        <li><code style={{ color: 'var(--accent-blue)' }}>!</code> — {t.rule_negation}</li>
        <li><code style={{ color: 'var(--accent-blue)' }}>/</code> — {t.rule_directories}</li>
        <li><code style={{ color: 'var(--accent-blue)' }}>*</code> <code style={{ color: 'var(--accent-blue)' }}>**</code> <code style={{ color: 'var(--accent-blue)' }}>?</code> — {t.rule_globbing}</li>
        <li>{t.rule_anchoring}</li>
      </ul>

      <h3 style={h3Style}>{t.syntax_example_title}</h3>
      <pre style={codeStyle}><code>{`# Ignore all .log files
*.log

# Ignore the build directory
build/

# Ignore all files in temp/ recursively
temp/**

# But keep .gitkeep files
!temp/.gitkeep

# Ignore .env in root only
/.env

# Ignore all .txt files in doc/ and subdirectories
doc/**/*.txt

# Ignore any file named "secret" anywhere
secret`}</code></pre>

      {/* ─── Section 2: Global vs Local ─── */}
      <h2 style={h2Style}>{t.h2_global_local}</h2>
      <p style={pStyle}>{t.global_local_desc}</p>

      <div style={cardStyle}>
        <strong style={{ color: '#3b82f6' }}>{t.local_title}</strong>
        <p style={{ margin: '6px 0 0', fontSize: 14, color: 'var(--text-secondary)', lineHeight: 1.6 }}>{t.local_desc}</p>
      </div>
      <div style={cardStyle}>
        <strong style={{ color: '#22c55e' }}>{t.global_title}</strong>
        <p style={{ margin: '6px 0 0', fontSize: 14, color: 'var(--text-secondary)', lineHeight: 1.6 }}>{t.global_desc}</p>
      </div>
      <p style={{ ...pStyle, fontWeight: 600 }}>{t.global_setup}</p>
      <pre style={codeStyle}><code>{`# Create a global gitignore file
touch ~/.gitignore_global

# Tell Git to use it
git config --global core.excludesfile ~/.gitignore_global

# Add common patterns
echo ".DS_Store" >> ~/.gitignore_global
echo "Thumbs.db" >> ~/.gitignore_global
echo ".idea/" >> ~/.gitignore_global
echo ".vscode/" >> ~/.gitignore_global
echo "*.swp" >> ~/.gitignore_global`}</code></pre>

      <div style={cardStyle}>
        <strong style={{ color: '#f59e0b' }}>{t.exclude_title}</strong>
        <p style={{ margin: '6px 0 0', fontSize: 14, color: 'var(--text-secondary)', lineHeight: 1.6 }}>{t.exclude_desc}</p>
      </div>

      {/* ─── Section 3: Node.js Template ─── */}
      <h2 style={h2Style}>{t.h2_nodejs}</h2>
      <p style={pStyle}>{t.nodejs_desc}</p>
      <pre style={codeStyle}><code>{`# Dependencies
node_modules/
.pnp
.pnp.js

# Build output
dist/
build/
out/

# Environment files
.env
.env.local
.env.*.local

# Testing
coverage/

# Cache
.cache/
.parcel-cache/
.next/
.nuxt/
.turbo/

# Debug logs
npm-debug.log*
yarn-debug.log*
yarn-error.log*
pnpm-debug.log*

# Editor directories and files
*.tsbuildinfo`}</code></pre>
      <ul style={ulStyle}>
        <li>{t.nodejs_node_modules}</li>
        <li>{t.nodejs_dist}</li>
        <li>{t.nodejs_env}</li>
        <li>{t.nodejs_coverage}</li>
        <li>{t.nodejs_cache}</li>
        <li>{t.nodejs_debug}</li>
      </ul>

      {/* ─── Section 4: Python Template ─── */}
      <h2 style={h2Style}>{t.h2_python}</h2>
      <p style={pStyle}>{t.python_desc}</p>
      <pre style={codeStyle}><code>{`# Byte-compiled / optimized
__pycache__/
*.py[cod]
*$py.class

# Virtual environments
venv/
.venv/
env/
ENV/

# Distribution / packaging
dist/
build/
*.egg-info/
*.egg
.eggs/
*.whl

# Testing
.pytest_cache/
.coverage
htmlcov/
.tox/
.nox/

# Type checking
.mypy_cache/
.pytype/
.pyre/

# IDE
.spyderproject
.spyproject

# Jupyter
.ipynb_checkpoints/

# Environment
.env
.env.local`}</code></pre>
      <ul style={ulStyle}>
        <li>{t.python_pycache}</li>
        <li>{t.python_venv}</li>
        <li>{t.python_egg}</li>
        <li>{t.python_mypy}</li>
        <li>{t.python_pytest}</li>
        <li>{t.python_tox}</li>
      </ul>

      {/* ─── Section 5: Java/Kotlin Template ─── */}
      <h2 style={h2Style}>{t.h2_java}</h2>
      <p style={pStyle}>{t.java_desc}</p>
      <pre style={codeStyle}><code>{`# Compiled class files
*.class

# Maven
target/
pom.xml.tag
pom.xml.releaseBackup
pom.xml.versionsBackup
pom.xml.next
release.properties

# Gradle
build/
.gradle/
gradle-app.setting
!gradle-wrapper.jar
!gradle-wrapper.properties

# Package files
*.jar
*.war
*.nar
*.ear
*.zip
*.tar.gz
*.rar

# IDE - IntelliJ
.idea/
*.iws
*.iml
*.ipr
out/

# IDE - Eclipse
.classpath
.project
.settings/
bin/`}</code></pre>
      <ul style={ulStyle}>
        <li>{t.java_class}</li>
        <li>{t.java_target}</li>
        <li>{t.java_build}</li>
        <li>{t.java_gradle}</li>
        <li>{t.java_jar}</li>
        <li>{t.java_idea}</li>
      </ul>

      {/* ─── Section 6: React / Next.js Template ─── */}
      <h2 style={h2Style}>{t.h2_react}</h2>
      <p style={pStyle}>{t.react_desc}</p>
      <pre style={codeStyle}><code>{`# Dependencies
node_modules/

# Next.js
.next/
out/

# Production build
build/
dist/

# Environment files
.env
.env.local
.env.development.local
.env.test.local
.env.production.local

# Testing
coverage/

# Vercel
.vercel/

# TypeScript
*.tsbuildinfo
next-env.d.ts

# Debug
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# Cache
.cache/
.turbo/`}</code></pre>
      <ul style={ulStyle}>
        <li>{t.react_next}</li>
        <li>{t.react_out}</li>
        <li>{t.react_node}</li>
        <li>{t.react_env}</li>
        <li>{t.react_vercel}</li>
      </ul>

      {/* ─── Section 7: Go Template ─── */}
      <h2 style={h2Style}>{t.h2_go}</h2>
      <p style={pStyle}>{t.go_desc}</p>
      <pre style={codeStyle}><code>{`# Binaries
bin/
*.exe
*.exe~
*.dll
*.so
*.dylib

# Test binary
*.test

# Output of go coverage
*.out

# Vendor (optional — some teams commit vendor/)
vendor/

# Go workspace
go.work

# IDE
.idea/
.vscode/

# OS
.DS_Store
Thumbs.db

# Environment
.env`}</code></pre>
      <ul style={ulStyle}>
        <li>{t.go_bin}</li>
        <li>{t.go_vendor}</li>
        <li>{t.go_exe}</li>
        <li>{t.go_test}</li>
        <li>{t.go_out}</li>
      </ul>

      {/* ─── Section 8: Rust Template ─── */}
      <h2 style={h2Style}>{t.h2_rust}</h2>
      <p style={pStyle}>{t.rust_desc}</p>
      <pre style={codeStyle}><code>{`# Build artifacts
/target/

# Cargo.lock — ONLY ignore for libraries
# For binaries (applications), DO commit Cargo.lock
# Cargo.lock

# Debug symbols (Windows)
*.pdb

# IDE
.idea/
.vscode/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db

# Environment
.env`}</code></pre>
      <ul style={ulStyle}>
        <li>{t.rust_target}</li>
        <li>{t.rust_lock}</li>
        <li>{t.rust_pdb}</li>
      </ul>

      {/* ─── Section 9: IDE & OS Patterns ─── */}
      <h2 style={h2Style}>{t.h2_ide_os}</h2>
      <p style={pStyle}>{t.ide_os_desc}</p>
      <pre style={codeStyle}><code>{`# ─── VS Code ───
.vscode/
!.vscode/settings.json
!.vscode/tasks.json
!.vscode/extensions.json

# ─── JetBrains IDEs ───
.idea/
*.iws
*.iml
*.ipr

# ─── Vim ───
*.swp
*.swo
*~
.netrwhist

# ─── Sublime Text ───
*.sublime-workspace
*.sublime-project

# ─── macOS ───
.DS_Store
.AppleDouble
.LSOverride
._*

# ─── Windows ───
Thumbs.db
Thumbs.db:encryptable
ehthumbs.db
Desktop.ini

# ─── Linux ───
*~
.fuse_hidden*
.Trash-*`}</code></pre>
      <ul style={ulStyle}>
        <li>{t.ide_vscode}</li>
        <li>{t.ide_idea}</li>
        <li>{t.ide_ds_store}</li>
        <li>{t.ide_thumbs}</li>
        <li>{t.ide_swp}</li>
        <li>{t.ide_sublime}</li>
      </ul>

      {/* ─── Section 10: Common Mistakes ─── */}
      <h2 style={h2Style}>{t.h2_mistakes}</h2>
      <p style={pStyle}>{t.mistakes_desc}</p>

      <div style={{ ...cardStyle, borderLeftWidth: 3, borderLeftColor: '#ef4444' }}>
        <strong style={{ color: '#ef4444' }}>{t.mistake1_title}</strong>
        <p style={{ margin: '6px 0 8px', fontSize: 14, color: 'var(--text-secondary)', lineHeight: 1.6 }}>{t.mistake1_desc}</p>
        <p style={{ fontSize: 13, fontWeight: 600, color: 'var(--text-primary)', marginBottom: 8 }}>{t.mistake1_fix}</p>
        <pre style={{ ...codeStyle, padding: '10px 14px' }}><code>{`# Remove file from Git tracking (keeps it on disk)
git rm --cached .env

# Remove an entire directory from tracking
git rm -r --cached node_modules/

# Commit the change
git add .gitignore
git commit -m "Stop tracking ignored files"

# Verify it worked
git status`}</code></pre>
      </div>

      <div style={{ ...cardStyle, borderLeftWidth: 3, borderLeftColor: '#f59e0b' }}>
        <strong style={{ color: '#f59e0b' }}>{t.mistake2_title}</strong>
        <p style={{ margin: '6px 0 8px', fontSize: 14, color: 'var(--text-secondary)', lineHeight: 1.6 }}>{t.mistake2_desc}</p>
        <pre style={{ ...codeStyle, padding: '10px 14px' }}><code>{`# WRONG — negation before exclusion has no effect
!important.log
*.log

# CORRECT — exclude first, then negate
*.log
!important.log

# Another example: ignore everything in docs/ except PDFs
docs/*
!docs/*.pdf`}</code></pre>
      </div>

      <div style={{ ...cardStyle, borderLeftWidth: 3, borderLeftColor: '#ef4444' }}>
        <strong style={{ color: '#ef4444' }}>{t.mistake3_title}</strong>
        <p style={{ margin: '6px 0 8px', fontSize: 14, color: 'var(--text-secondary)', lineHeight: 1.6 }}>{t.mistake3_desc}</p>
        <p style={{ fontSize: 13, fontWeight: 600, color: 'var(--text-primary)', marginBottom: 8 }}>{t.mistake3_fix}</p>
        <pre style={{ ...codeStyle, padding: '10px 14px' }}><code>{`# 1. Add .env to .gitignore
echo ".env" >> .gitignore

# 2. Remove from Git tracking
git rm --cached .env

# 3. Commit
git add .gitignore
git commit -m "Remove .env from tracking"

# 4. IMPORTANT: Rotate all secrets in that .env file!
# The old values are still in Git history.`}</code></pre>
      </div>

      <div style={{ ...cardStyle, borderLeftWidth: 3, borderLeftColor: '#3b82f6' }}>
        <strong style={{ color: '#3b82f6' }}>{t.mistake4_title}</strong>
        <p style={{ margin: '6px 0 8px', fontSize: 14, color: 'var(--text-secondary)', lineHeight: 1.6 }}>{t.mistake4_desc}</p>
        <pre style={{ ...codeStyle, padding: '10px 14px' }}><code>{`# Matches both a FILE named "logs" and a DIRECTORY named "logs"
logs

# Matches ONLY a directory named "logs"
logs/

# Example: you have a file "build" and a directory "build/"
# "build" in .gitignore ignores BOTH
# "build/" in .gitignore ignores only the directory`}</code></pre>
      </div>

      <div style={{ ...cardStyle, borderLeftWidth: 3, borderLeftColor: '#22c55e' }}>
        <strong style={{ color: '#22c55e' }}>{t.mistake5_title}</strong>
        <p style={{ margin: '6px 0 0', fontSize: 14, color: 'var(--text-secondary)', lineHeight: 1.6 }}>{t.mistake5_desc}</p>
      </div>

      {/* ─── Section 11: Generators & Tools ─── */}
      <h2 style={h2Style}>{t.h2_generators}</h2>
      <p style={pStyle}>{t.generators_desc}</p>
      <ul style={ulStyle}>
        <li><strong>{t.generators_our_tool}</strong></li>
        <li>{t.generators_github}</li>
        <li>{t.generators_tip}</li>
      </ul>

      <div style={{ padding: 20, background: 'linear-gradient(135deg, rgba(59,130,246,0.1), rgba(139,92,246,0.1))', borderRadius: 12, border: '1px solid rgba(59,130,246,0.3)', textAlign: 'center', marginBottom: 30 }}>
        <p style={{ fontSize: 16, fontWeight: 600, marginBottom: 8 }}>{t.tryTool}</p>
        <Link href={`/${lang}/tools/gitignore-generator`} style={{ color: 'var(--accent-blue)', fontWeight: 700, fontSize: 15 }}>
          {t.tryToolLink} →
        </Link>
      </div>

      {/* ─── Section 12: FAQ ─── */}
      <h2 style={h2Style}>{t.h2_faq}</h2>
      {[
        [t.faq1_q, t.faq1_a], [t.faq2_q, t.faq2_a], [t.faq3_q, t.faq3_a], [t.faq4_q, t.faq4_a], [t.faq5_q, t.faq5_a],
      ].map(([q, a], i) => (
        <div key={i} style={{ marginBottom: 16, padding: 16, background: 'var(--bg-input)', borderRadius: 8, border: '1px solid var(--border-color)' }}>
          <h3 style={{ fontSize: 15, fontWeight: 700, marginBottom: 8, color: 'var(--text-primary)' }}>{q}</h3>
          <p style={{ fontSize: 14, color: 'var(--text-secondary)', lineHeight: 1.7, margin: 0 }}>{a}</p>
        </div>
      ))}
    </div>
  );
}
