'use client';
import React from 'react';
import Link from 'next/link';

/* ------------------------------------------------------------------ */
/*  GraphQL to TypeScript Online Guide                                  */
/* ------------------------------------------------------------------ */

export default function GraphqlToTypescriptOnlineGuide({ lang }: { lang: string }) {
  const l = lang || 'en';
  const toolLink = `/${l}/tools/graphql-to-typescript`;

  /* ---------- translations ---------- */
  const translations: Record<string, {
    tldr: string;
    whyTitle: string;
    takeawaysTitle: string;
    tryTool: string;
    faqTitle: string;
  }> = {
    zh: {
      tldr: '使用 @graphql-codegen/cli 从 GraphQL 模式和查询生成 TypeScript 类型。配置 codegen.ts，在开发时运行 graphql-codegen --watch，自动获得完整类型化的查询、变更和片段。',
      whyTitle: '为什么要从 GraphQL 生成 TypeScript？',
      takeawaysTitle: '核心要点',
      tryTool: '立即使用免费的 GraphQL 转 TypeScript 工具 \u2192',
      faqTitle: '常见问题',
    },
    en: {
      tldr: 'Generate TypeScript types from GraphQL schemas and queries using @graphql-codegen/cli. Configure codegen.ts, run graphql-codegen --watch during development, and get fully typed queries, mutations, and fragments automatically.',
      whyTitle: 'Why Generate TypeScript from GraphQL?',
      takeawaysTitle: 'Key Takeaways',
      tryTool: 'Try our free GraphQL to TypeScript tool \u2192',
      faqTitle: 'Frequently Asked Questions',
    },
  };

  const t = translations[l] || translations['en'];

  /* ---------- FAQ items ---------- */
  const faqItems = [
    {
      q: 'What is @graphql-codegen?',
      a: '@graphql-codegen (graphql-code-generator) is a CLI tool and plugin ecosystem that reads your GraphQL schema and operation files (queries, mutations, fragments) and generates TypeScript types, typed hooks, and client utilities automatically. It eliminates the need to manually write TypeScript interfaces that mirror your GraphQL schema. The generated code is always in sync with your schema, preventing runtime type mismatches between client and server.',
    },
    {
      q: 'How do I set up graphql-codegen?',
      a: 'Install the CLI and core plugins: npm install -D @graphql-codegen/cli @graphql-codegen/typescript @graphql-codegen/typescript-operations. Then create a codegen.ts (or codegen.yml) file at the project root. Point it to your schema (a URL, a .graphql file, or an introspection JSON) and your operation files (e.g., src/**/*.graphql). Run npx graphql-codegen to generate types. Add "codegen": "graphql-codegen" to your package.json scripts for convenience.',
    },
    {
      q: 'What is TypedDocumentNode?',
      a: 'TypedDocumentNode is a typed wrapper around the standard DocumentNode (from graphql-js) that carries TypeScript generic parameters for both the result type and the variables type. When you pass a TypedDocumentNode to Apollo Client, urql, or React Query\'s fetcher, TypeScript can automatically infer what data the query returns and what variables it requires, without any manual type annotation. It is generated by @graphql-codegen/typed-document-node and is the recommended approach for full end-to-end type safety.',
    },
    {
      q: 'How do I handle nullable fields from GraphQL?',
      a: 'GraphQL fields are nullable by default unless you add a ! non-null marker in the schema. @graphql-codegen faithfully represents this: a nullable field becomes T | null in TypeScript. You have two main strategies: (1) Use optional chaining (data?.user?.email) throughout your code, or (2) add avoidOptionals: true in codegen config to prefer T | null over T | undefined. In your schema, mark fields as non-null with ! whenever the server guarantees a value. Avoid the strictNullChecks: false escape hatch as it defeats the purpose.',
    },
    {
      q: 'What are custom scalars in GraphQL codegen?',
      a: 'GraphQL has built-in scalars (String, Int, Float, Boolean, ID) but schemas often define custom scalars like DateTime, UUID, or JSON. By default, @graphql-codegen maps unknown scalars to any. You should provide explicit TypeScript mappings in codegen.ts: config: { scalars: { DateTime: "string", UUID: "string", JSON: "Record<string, unknown>" } }. For Date objects, map DateTime to "Date" and handle the parsing in your network layer or with a custom scalar resolver.',
    },
    {
      q: 'Can I use graphql-codegen with React Query?',
      a: 'Yes. Install @graphql-codegen/typescript-react-query and add it to your codegen.ts generates block. It produces typed useQuery and useMutation hooks for each operation in your .graphql files. Configure the fetcher option to point to your fetch function or axios instance. The generated hooks are fully typed: calling useGetUserQuery() automatically provides TypeScript types for both the data and variables without any manual annotation. You can also use @tanstack/react-query v5 with the TypedDocumentNode approach for more flexibility.',
    },
    {
      q: 'How do I keep generated types up to date?',
      a: 'Use two complementary strategies: (1) During development, run graphql-codegen --watch to automatically regenerate types whenever a .graphql file or the schema changes. (2) In CI, add a codegen step before your TypeScript compiler check: run graphql-codegen, then tsc --noEmit. If the schema or operations change without regenerating types, the CI build will fail, preventing type drift from being merged. You can also set up a git pre-commit hook with husky + lint-staged to run codegen before commits.',
    },
    {
      q: 'What is the difference between TypedDocumentNode and DocumentNode?',
      a: 'DocumentNode is the base AST representation of a parsed GraphQL document. It carries no TypeScript type information about what the operation returns or what variables it takes. TypedDocumentNode<TResult, TVariables> extends DocumentNode with two generic parameters that encode the result and variables types. GraphQL client libraries (Apollo, urql, React Query) have overloads that detect TypedDocumentNode and use those generics to type the return value of useQuery, execute, etc. TypedDocumentNode is the recommended approach over inline type assertions or separate TypeScript interfaces.',
    },
  ];

  const faqSchema = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: faqItems.map(item => ({
      '@type': 'Question',
      name: item.q,
      acceptedAnswer: {
        '@type': 'Answer',
        text: item.a,
      },
    })),
  };

  return (
    <article style={{ maxWidth: 820, margin: '0 auto', lineHeight: 1.75 }}>
      {/* FAQ Schema.org JSON-LD */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
      />

      {/* ---- TL;DR Box ---- */}
      <div style={{
        background: '#f0f9ff',
        border: '1px solid #bae6fd',
        borderRadius: 8,
        padding: '16px 20px',
        marginBottom: 32,
      }}>
        <p style={{ fontWeight: 700, fontSize: 16, marginBottom: 8, marginTop: 0 }}>TL;DR</p>
        <p style={{ margin: 0, fontSize: 15 }}>
          {t.tldr}{' '}
          <Link href={toolLink} style={{ color: '#2563eb', fontWeight: 600 }}>
            {t.tryTool}
          </Link>
        </p>
      </div>

      {/* ---- Key Takeaways ---- */}
      <div style={{
        background: '#f8fafc',
        borderRadius: 8,
        padding: '16px 20px',
        marginBottom: 40,
      }}>
        <p style={{ fontWeight: 700, fontSize: 16, marginBottom: 12, marginTop: 0 }}>{t.takeawaysTitle}</p>
        <ul style={{ margin: 0, paddingLeft: 20, fontSize: 15, display: 'flex', flexDirection: 'column', gap: 6 }}>
          <li><code style={{ background: '#f1f5f9', padding: '1px 4px', borderRadius: 3 }}>@graphql-codegen/cli</code> is the standard tool for GraphQL TypeScript code generation.</li>
          <li>Add a <code style={{ background: '#f1f5f9', padding: '1px 4px', borderRadius: 3 }}>generates</code> config in <code style={{ background: '#f1f5f9', padding: '1px 4px', borderRadius: 3 }}>codegen.ts</code> pointing to your schema and operations.</li>
          <li><code style={{ background: '#f1f5f9', padding: '1px 4px', borderRadius: 3 }}>TypedDocumentNode</code> ensures TypeScript knows exactly what data each query returns.</li>
          <li>All GraphQL types are nullable by default &mdash; use <code style={{ background: '#f1f5f9', padding: '1px 4px', borderRadius: 3 }}>!</code> in your schema for non-null fields.</li>
          <li>Custom scalars (<code style={{ background: '#f1f5f9', padding: '1px 4px', borderRadius: 3 }}>DateTime</code>, <code style={{ background: '#f1f5f9', padding: '1px 4px', borderRadius: 3 }}>UUID</code>) need TypeScript type mappings in codegen config.</li>
          <li>Fragment types let you reuse partial type definitions across multiple components.</li>
          <li>Run <code style={{ background: '#f1f5f9', padding: '1px 4px', borderRadius: 3 }}>codegen --watch</code> in dev and add codegen to CI to keep types in sync.</li>
        </ul>
      </div>

      {/* ---- Section 1: Why Generate TypeScript from GraphQL ---- */}
      <h2 style={{ fontSize: 26, fontWeight: 800, marginTop: 48, marginBottom: 16 }}>
        Why Generate TypeScript from GraphQL?
      </h2>
      <p style={{ fontSize: 15, marginBottom: 12 }}>
        GraphQL gives you a strongly typed schema on the server side. Without code generation, you must manually write TypeScript
        interfaces that mirror every type, field, and operation in that schema. This creates a dual source of truth: if the
        server changes a field from <code style={{ background: '#f1f5f9', padding: '1px 5px', borderRadius: 3 }}>String</code> to{' '}
        <code style={{ background: '#f1f5f9', padding: '1px 5px', borderRadius: 3 }}>Int</code>, your TypeScript types stay
        wrong until someone manually updates them.
      </p>
      <p style={{ fontSize: 15, marginBottom: 12 }}>
        Code generation eliminates this problem. Tools like <code style={{ background: '#f1f5f9', padding: '1px 5px', borderRadius: 3 }}>@graphql-codegen/cli</code> read
        the actual schema and generate TypeScript types automatically. When the schema changes, you rerun the generator and
        TypeScript immediately flags any broken usages in your codebase. The benefits are significant:
      </p>

      <h3 style={{ fontSize: 20, fontWeight: 700, marginTop: 24, marginBottom: 10 }}>Type Safety vs Manual Maintenance</h3>
      <div style={{ overflowX: 'auto', marginBottom: 24 }}>
        <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 14, textAlign: 'left' }}>
          <thead>
            <tr style={{ background: '#f1f5f9', borderBottom: '2px solid #e2e8f0' }}>
              <th style={{ padding: '10px 14px', fontWeight: 700 }}>Approach</th>
              <th style={{ padding: '10px 14px', fontWeight: 700 }}>Type Safety</th>
              <th style={{ padding: '10px 14px', fontWeight: 700 }}>Maintenance</th>
              <th style={{ padding: '10px 14px', fontWeight: 700 }}>Schema Drift</th>
            </tr>
          </thead>
          <tbody>
            {[
              ['Manual TypeScript interfaces', 'Partial', 'High — manual updates', 'Silently wrong'],
              ['graphql-codegen (typescript)', 'Full', 'Zero — auto-generated', 'Build error on drift'],
              ['graphql-codegen + TypedDocumentNode', 'Full + variables', 'Zero — auto-generated', 'Build error on drift'],
              ['No types (any)', 'None', 'None', 'Runtime errors only'],
            ].map(([approach, safety, maint, drift], i) => (
              <tr key={i} style={{ borderBottom: '1px solid #e2e8f0', background: i % 2 === 0 ? '#fff' : '#f8fafc' }}>
                <td style={{ padding: '9px 14px', fontFamily: 'monospace', fontSize: 13 }}>{approach}</td>
                <td style={{ padding: '9px 14px' }}>{safety}</td>
                <td style={{ padding: '9px 14px' }}>{maint}</td>
                <td style={{ padding: '9px 14px' }}>{drift}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      <p style={{ fontSize: 15, marginBottom: 12 }}>
        Client-server synchronization is the most valuable benefit. When your frontend team writes a query that selects fields
        your backend no longer exposes, the TypeScript compiler catches it before the code reaches production. This is especially
        critical in large teams where frontend and backend evolve independently.
      </p>
      <p style={{ fontSize: 15, marginBottom: 24 }}>
        You can also try the{' '}
        <Link href={toolLink} style={{ color: '#2563eb', fontWeight: 600 }}>
          DevToolBox GraphQL to TypeScript tool
        </Link>{' '}
        at <strong>https://viadreams.cc/en/tools/graphql-to-typescript</strong> for quick, browser-based schema-to-type conversion
        without installing anything locally.
      </p>

      {/* ---- Section 2: graphql-codegen Setup ---- */}
      <h2 style={{ fontSize: 26, fontWeight: 800, marginTop: 48, marginBottom: 16 }}>
        Setting Up @graphql-codegen/cli
      </h2>
      <p style={{ fontSize: 15, marginBottom: 12 }}>
        The core package is <code style={{ background: '#f1f5f9', padding: '1px 5px', borderRadius: 3 }}>@graphql-codegen/cli</code>.
        You always need it alongside two plugins: <code style={{ background: '#f1f5f9', padding: '1px 5px', borderRadius: 3 }}>@graphql-codegen/typescript</code>{' '}
        (base schema types) and <code style={{ background: '#f1f5f9', padding: '1px 5px', borderRadius: 3 }}>@graphql-codegen/typescript-operations</code>{' '}
        (types for your queries and mutations).
      </p>
      <pre style={{ background: '#1e293b', color: '#e2e8f0', padding: '16px 20px', borderRadius: 8, overflowX: 'auto', fontSize: 13, marginBottom: 20 }}>
        <code>{`# Install CLI and core plugins
npm install -D \\
  @graphql-codegen/cli \\
  @graphql-codegen/typescript \\
  @graphql-codegen/typescript-operations \\
  @graphql-codegen/typed-document-node

# Optional: typed hooks for Apollo Client
npm install -D @graphql-codegen/typescript-react-apollo

# Optional: typed hooks for React Query / TanStack Query
npm install -D @graphql-codegen/typescript-react-query`}</code>
      </pre>
      <p style={{ fontSize: 15, marginBottom: 12 }}>
        Add a script to <code style={{ background: '#f1f5f9', padding: '1px 5px', borderRadius: 3 }}>package.json</code> so
        you can run codegen with a short command:
      </p>
      <pre style={{ background: '#1e293b', color: '#e2e8f0', padding: '16px 20px', borderRadius: 8, overflowX: 'auto', fontSize: 13, marginBottom: 20 }}>
        <code>{`{
  "scripts": {
    "codegen": "graphql-codegen",
    "codegen:watch": "graphql-codegen --watch"
  }
}`}</code>
      </pre>

      {/* ---- Section 3: codegen.ts configuration ---- */}
      <h2 style={{ fontSize: 26, fontWeight: 800, marginTop: 48, marginBottom: 16 }}>
        codegen.ts Configuration
      </h2>
      <p style={{ fontSize: 15, marginBottom: 12 }}>
        Create a <code style={{ background: '#f1f5f9', padding: '1px 5px', borderRadius: 3 }}>codegen.ts</code> file at the
        root of your project. The TypeScript config format gives you full IDE autocompletion and type checking for the
        configuration itself.
      </p>
      <pre style={{ background: '#1e293b', color: '#e2e8f0', padding: '16px 20px', borderRadius: 8, overflowX: 'auto', fontSize: 13, marginBottom: 20 }}>
        <code>{`// codegen.ts
import type { CodegenConfig } from '@graphql-codegen/cli';

const config: CodegenConfig = {
  schema: 'https://your-api.com/graphql',  // or './schema.graphql'
  documents: ['src/**/*.graphql', 'src/**/*.tsx'],
  generates: {
    // 1. Base schema types
    'src/generated/graphql.ts': {
      plugins: ['typescript'],
      config: {
        scalars: {
          DateTime: 'string',
          UUID: 'string',
          JSON: 'Record<string, unknown>',
        },
        avoidOptionals: false,
        maybeValue: 'T | null',
      },
    },
    // 2. Operation types (queries, mutations, fragments)
    'src/generated/operations.ts': {
      plugins: ['typescript', 'typescript-operations', 'typed-document-node'],
      config: {
        scalars: {
          DateTime: 'string',
          UUID: 'string',
        },
      },
    },
  },
  hooks: {
    afterAllFileWrite: ['prettier --write'],
  },
};

export default config;`}</code>
      </pre>
      <p style={{ fontSize: 15, marginBottom: 12 }}>
        The <code style={{ background: '#f1f5f9', padding: '1px 5px', borderRadius: 3 }}>schema</code> field accepts a
        GraphQL endpoint URL (codegen will introspect it), a path to a <code style={{ background: '#f1f5f9', padding: '1px 5px', borderRadius: 3 }}>.graphql</code> schema
        file, a glob pattern matching multiple schema files, or an introspection JSON. The{' '}
        <code style={{ background: '#f1f5f9', padding: '1px 5px', borderRadius: 3 }}>documents</code> field specifies where
        your operation files (queries, mutations, fragments) live.
      </p>

      {/* ---- Section 4: TypedDocumentNode ---- */}
      <h2 style={{ fontSize: 26, fontWeight: 800, marginTop: 48, marginBottom: 16 }}>
        TypedDocumentNode for Typed Queries
      </h2>
      <p style={{ fontSize: 15, marginBottom: 12 }}>
        The <code style={{ background: '#f1f5f9', padding: '1px 5px', borderRadius: 3 }}>typed-document-node</code> plugin is
        the key that connects your GraphQL operations to TypeScript. Instead of an untyped{' '}
        <code style={{ background: '#f1f5f9', padding: '1px 5px', borderRadius: 3 }}>DocumentNode</code>, it generates a{' '}
        <code style={{ background: '#f1f5f9', padding: '1px 5px', borderRadius: 3 }}>TypedDocumentNode&lt;TResult, TVariables&gt;</code>{' '}
        that carries type information directly in the document object.
      </p>
      <p style={{ fontSize: 15, marginBottom: 12 }}>
        Write your operation in a <code style={{ background: '#f1f5f9', padding: '1px 5px', borderRadius: 3 }}>.graphql</code> file:
      </p>
      <pre style={{ background: '#1e293b', color: '#e2e8f0', padding: '16px 20px', borderRadius: 8, overflowX: 'auto', fontSize: 13, marginBottom: 20 }}>
        <code>{`# src/queries/GetUser.graphql
query GetUser($id: ID!) {
  user(id: $id) {
    id
    name
    email
    createdAt
    role
  }
}`}</code>
      </pre>
      <p style={{ fontSize: 15, marginBottom: 12 }}>
        After running <code style={{ background: '#f1f5f9', padding: '1px 5px', borderRadius: 3 }}>npm run codegen</code>,
        the generator produces:
      </p>
      <pre style={{ background: '#1e293b', color: '#e2e8f0', padding: '16px 20px', borderRadius: 8, overflowX: 'auto', fontSize: 13, marginBottom: 20 }}>
        <code>{`// src/generated/operations.ts (auto-generated, do not edit)
export type GetUserQuery = {
  user: {
    id: string;
    name: string;
    email: string;
    createdAt: string;        // DateTime scalar → mapped to string
    role: UserRole;           // enum type
  } | null;
};

export type GetUserQueryVariables = {
  id: string;
};

export const GetUserDocument: TypedDocumentNode<GetUserQuery, GetUserQueryVariables> = {
  kind: 'Document',
  definitions: [/* AST nodes */],
};`}</code>
      </pre>
      <p style={{ fontSize: 15, marginBottom: 24 }}>
        Now <code style={{ background: '#f1f5f9', padding: '1px 5px', borderRadius: 3 }}>GetUserDocument</code> is a
        fully typed GraphQL document. Pass it to any compatible client library and TypeScript will automatically infer
        the query result and variables types.
      </p>

      {/* ---- Section 5: React Query Integration ---- */}
      <h2 style={{ fontSize: 26, fontWeight: 800, marginTop: 48, marginBottom: 16 }}>
        React Query Integration with Generated Types
      </h2>
      <p style={{ fontSize: 15, marginBottom: 12 }}>
        TanStack Query (React Query) does not have a built-in GraphQL client, but you can use it with a custom fetcher
        and TypedDocumentNode for full type safety. This approach is framework-agnostic and works with any HTTP client.
      </p>
      <pre style={{ background: '#1e293b', color: '#e2e8f0', padding: '16px 20px', borderRadius: 8, overflowX: 'auto', fontSize: 13, marginBottom: 20 }}>
        <code>{`// lib/graphql-fetcher.ts
import { TypedDocumentNode } from '@graphql-typed-document-node/core';

export async function fetchGraphQL<TResult, TVariables>(
  document: TypedDocumentNode<TResult, TVariables>,
  variables: TVariables,
): Promise<TResult> {
  const response = await fetch('/graphql', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ query: document, variables }),
  });
  const json = await response.json();
  if (json.errors) throw new Error(json.errors[0].message);
  return json.data;
}

// components/UserProfile.tsx
import { useQuery } from '@tanstack/react-query';
import { GetUserDocument } from '../generated/operations';
import { fetchGraphQL } from '../lib/graphql-fetcher';

export function UserProfile({ userId }: { userId: string }) {
  const { data, isLoading } = useQuery({
    queryKey: ['user', userId],
    queryFn: () => fetchGraphQL(GetUserDocument, { id: userId }),
    // data is automatically typed as GetUserQuery
  });

  if (isLoading) return <div>Loading...</div>;

  // TypeScript knows data.user.name is string | null
  return <h1>{data?.user?.name}</h1>;
}`}</code>
      </pre>
      <p style={{ fontSize: 15, marginBottom: 12 }}>
        Alternatively, use the <code style={{ background: '#f1f5f9', padding: '1px 5px', borderRadius: 3 }}>@graphql-codegen/typescript-react-query</code> plugin
        to generate hooks directly. Configure it in <code style={{ background: '#f1f5f9', padding: '1px 5px', borderRadius: 3 }}>codegen.ts</code>:
      </p>
      <pre style={{ background: '#1e293b', color: '#e2e8f0', padding: '16px 20px', borderRadius: 8, overflowX: 'auto', fontSize: 13, marginBottom: 20 }}>
        <code>{`// codegen.ts — add to generates section
'src/generated/react-query-hooks.ts': {
  plugins: ['typescript', 'typescript-operations', 'typescript-react-query'],
  config: {
    fetcher: {
      func: '../lib/graphql-fetcher#fetchGraphQL',
      isReactHook: false,
    },
  },
},`}</code>
      </pre>
      <p style={{ fontSize: 15, marginBottom: 24 }}>
        This produces a <code style={{ background: '#f1f5f9', padding: '1px 5px', borderRadius: 3 }}>useGetUserQuery(variables)</code> hook
        with fully typed return values and variable parameters.
      </p>

      {/* ---- Section 6: Apollo Client ---- */}
      <h2 style={{ fontSize: 26, fontWeight: 800, marginTop: 48, marginBottom: 16 }}>
        Apollo Client with Generated Types
      </h2>
      <p style={{ fontSize: 15, marginBottom: 12 }}>
        Apollo Client has native support for TypedDocumentNode. Pass the generated document to{' '}
        <code style={{ background: '#f1f5f9', padding: '1px 5px', borderRadius: 3 }}>useQuery</code> and TypeScript
        automatically infers the result and variables types:
      </p>
      <pre style={{ background: '#1e293b', color: '#e2e8f0', padding: '16px 20px', borderRadius: 8, overflowX: 'auto', fontSize: 13, marginBottom: 20 }}>
        <code>{`import { useQuery } from '@apollo/client';
import { GetUserDocument } from '../generated/operations';

function UserProfile({ userId }: { userId: string }) {
  // No generic annotation needed — TypeScript infers from GetUserDocument
  const { data, loading, error } = useQuery(GetUserDocument, {
    variables: { id: userId },
  });

  if (loading) return <p>Loading...</p>;
  if (error) return <p>Error: {error.message}</p>;

  return (
    <div>
      <h1>{data?.user?.name}</h1>
      <p>{data?.user?.email}</p>
    </div>
  );
}`}</code>
      </pre>
      <p style={{ fontSize: 15, marginBottom: 12 }}>
        For typed mutations with Apollo, the same pattern applies:
      </p>
      <pre style={{ background: '#1e293b', color: '#e2e8f0', padding: '16px 20px', borderRadius: 8, overflowX: 'auto', fontSize: 13, marginBottom: 20 }}>
        <code>{`import { useMutation } from '@apollo/client';
import { UpdateUserDocument } from '../generated/operations';

function UpdateUserForm() {
  // TypeScript enforces correct variable shape
  const [updateUser, { loading }] = useMutation(UpdateUserDocument);

  const handleSubmit = async (data: { id: string; name: string }) => {
    await updateUser({
      variables: { id: data.id, input: { name: data.name } },
    });
  };

  return (/* form JSX */);
}`}</code>
      </pre>
      <p style={{ fontSize: 15, marginBottom: 12 }}>
        You can also use the <code style={{ background: '#f1f5f9', padding: '1px 5px', borderRadius: 3 }}>@graphql-codegen/typescript-react-apollo</code> plugin
        to generate <code style={{ background: '#f1f5f9', padding: '1px 5px', borderRadius: 3 }}>useGetUserQuery</code> and{' '}
        <code style={{ background: '#f1f5f9', padding: '1px 5px', borderRadius: 3 }}>useUpdateUserMutation</code> hooks
        directly, with inline types ready to use.
      </p>

      {/* ---- Section 7: urql ---- */}
      <h2 style={{ fontSize: 26, fontWeight: 800, marginTop: 48, marginBottom: 16 }}>
        urql with Generated Types
      </h2>
      <p style={{ fontSize: 15, marginBottom: 12 }}>
        urql also supports TypedDocumentNode natively. The{' '}
        <code style={{ background: '#f1f5f9', padding: '1px 5px', borderRadius: 3 }}>useQuery</code> hook from urql infers
        types from the document you pass:
      </p>
      <pre style={{ background: '#1e293b', color: '#e2e8f0', padding: '16px 20px', borderRadius: 8, overflowX: 'auto', fontSize: 13, marginBottom: 20 }}>
        <code>{`import { useQuery } from 'urql';
import { GetUserDocument } from '../generated/operations';

function UserProfile({ userId }: { userId: string }) {
  const [{ data, fetching, error }] = useQuery({
    query: GetUserDocument,
    variables: { id: userId },
    // TypeScript infers: data is GetUserQuery | undefined
  });

  if (fetching) return <p>Loading...</p>;
  if (error) return <p>Error: {error.message}</p>;

  return <h1>{data?.user?.name}</h1>;
}`}</code>
      </pre>
      <p style={{ fontSize: 15, marginBottom: 24 }}>
        For urql, you can also use the{' '}
        <code style={{ background: '#f1f5f9', padding: '1px 5px', borderRadius: 3 }}>@graphql-codegen/typescript-urql</code> plugin
        to generate typed hooks directly. All three major GraphQL client libraries (Apollo, urql, React Query) work
        seamlessly with the TypedDocumentNode pattern.
      </p>

      {/* ---- Section 8: Types Only vs Full Client Code ---- */}
      <h2 style={{ fontSize: 26, fontWeight: 800, marginTop: 48, marginBottom: 16 }}>
        Generating Only Types vs Full Client Code
      </h2>
      <p style={{ fontSize: 15, marginBottom: 12 }}>
        You do not always need to generate hooks or client utilities. Sometimes you only need the TypeScript types that
        mirror your schema — for example, when you are building a server-side resolver in Node.js, or when you want to
        use a low-level fetch with manual type assertions.
      </p>
      <p style={{ fontSize: 15, marginBottom: 12 }}>
        Use only the <code style={{ background: '#f1f5f9', padding: '1px 5px', borderRadius: 3 }}>typescript</code> plugin for schema types:
      </p>
      <pre style={{ background: '#1e293b', color: '#e2e8f0', padding: '16px 20px', borderRadius: 8, overflowX: 'auto', fontSize: 13, marginBottom: 20 }}>
        <code>{`// codegen.ts — types only
generates: {
  'src/generated/schema-types.ts': {
    plugins: ['typescript'],
    // This generates interfaces for every type in the schema
    // but does NOT generate operation-specific types or hooks
  },
}`}</code>
      </pre>
      <p style={{ fontSize: 15, marginBottom: 12 }}>
        For server-side resolvers (e.g., in a Node.js GraphQL server), use{' '}
        <code style={{ background: '#f1f5f9', padding: '1px 5px', borderRadius: 3 }}>@graphql-codegen/typescript-resolvers</code>:
      </p>
      <pre style={{ background: '#1e293b', color: '#e2e8f0', padding: '16px 20px', borderRadius: 8, overflowX: 'auto', fontSize: 13, marginBottom: 20 }}>
        <code>{`'src/generated/resolvers.ts': {
  plugins: ['typescript', 'typescript-resolvers'],
  config: {
    contextType: '../context#MyContext',
  },
}`}</code>
      </pre>
      <div style={{ overflowX: 'auto', marginBottom: 24 }}>
        <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 14, textAlign: 'left' }}>
          <thead>
            <tr style={{ background: '#f1f5f9', borderBottom: '2px solid #e2e8f0' }}>
              <th style={{ padding: '10px 14px', fontWeight: 700 }}>Plugin</th>
              <th style={{ padding: '10px 14px', fontWeight: 700 }}>Use Case</th>
              <th style={{ padding: '10px 14px', fontWeight: 700 }}>Output</th>
            </tr>
          </thead>
          <tbody>
            {[
              ['typescript', 'Schema types only', 'TypeScript interfaces for all schema types'],
              ['typescript-operations', 'Client query types', 'Types for each query/mutation/fragment'],
              ['typed-document-node', 'TypedDocumentNode', 'Typed AST document with generics'],
              ['typescript-react-apollo', 'Apollo Client hooks', 'useXxxQuery / useXxxMutation hooks'],
              ['typescript-react-query', 'React Query hooks', 'Typed useQuery wrappers per operation'],
              ['typescript-resolvers', 'Server resolvers', 'Typed resolver function signatures'],
            ].map(([plugin, useCase, output], i) => (
              <tr key={i} style={{ borderBottom: '1px solid #e2e8f0', background: i % 2 === 0 ? '#fff' : '#f8fafc' }}>
                <td style={{ padding: '9px 14px', fontFamily: 'monospace', fontSize: 13 }}>{plugin}</td>
                <td style={{ padding: '9px 14px' }}>{useCase}</td>
                <td style={{ padding: '9px 14px' }}>{output}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* ---- Section 9: Scalar Types ---- */}
      <h2 style={{ fontSize: 26, fontWeight: 800, marginTop: 48, marginBottom: 16 }}>
        Custom Scalar Types (DateTime, UUID, JSON)
      </h2>
      <p style={{ fontSize: 15, marginBottom: 12 }}>
        GraphQL schemas frequently define custom scalars for domain-specific values. Without explicit mappings, codegen
        falls back to <code style={{ background: '#f1f5f9', padding: '1px 5px', borderRadius: 3 }}>any</code>, which defeats
        the purpose of type safety. Always map your scalars explicitly in{' '}
        <code style={{ background: '#f1f5f9', padding: '1px 5px', borderRadius: 3 }}>codegen.ts</code>:
      </p>
      <pre style={{ background: '#1e293b', color: '#e2e8f0', padding: '16px 20px', borderRadius: 8, overflowX: 'auto', fontSize: 13, marginBottom: 20 }}>
        <code>{`// codegen.ts — scalar mappings
config: {
  scalars: {
    // ISO 8601 string from server → string in TypeScript
    DateTime: 'string',

    // UUIDs are strings
    UUID: 'string',

    // Opaque JSON blobs
    JSON: 'Record<string, unknown>',

    // If your app parses dates client-side
    Date: 'Date',

    // Money amounts (avoid float precision issues)
    Decimal: 'string',

    // Arbitrary binary data (e.g., file uploads)
    Upload: 'File',
  },
}`}</code>
      </pre>
      <p style={{ fontSize: 15, marginBottom: 12 }}>
        For <code style={{ background: '#f1f5f9', padding: '1px 5px', borderRadius: 3 }}>DateTime</code> scalars, a common
        pattern is to map them to <code style={{ background: '#f1f5f9', padding: '1px 5px', borderRadius: 3 }}>string</code> in
        the generated types and then parse them to{' '}
        <code style={{ background: '#f1f5f9', padding: '1px 5px', borderRadius: 3 }}>Date</code> objects in your UI layer using
        a utility like <code style={{ background: '#f1f5f9', padding: '1px 5px', borderRadius: 3 }}>date-fns</code> or{' '}
        <code style={{ background: '#f1f5f9', padding: '1px 5px', borderRadius: 3 }}>dayjs</code>. This keeps the generated
        types serialization-safe while giving you rich date manipulation in components.
      </p>

      {/* ---- Section 10: Fragment Types ---- */}
      <h2 style={{ fontSize: 26, fontWeight: 800, marginTop: 48, marginBottom: 16 }}>
        Fragment Types
      </h2>
      <p style={{ fontSize: 15, marginBottom: 12 }}>
        GraphQL fragments let you define reusable field selections. Code generation creates corresponding TypeScript types
        for each fragment, enabling you to share partial type definitions across components without duplication.
      </p>
      <pre style={{ background: '#1e293b', color: '#e2e8f0', padding: '16px 20px', borderRadius: 8, overflowX: 'auto', fontSize: 13, marginBottom: 20 }}>
        <code>{`# src/fragments/UserFields.graphql
fragment UserFields on User {
  id
  name
  avatarUrl
}

# src/queries/GetUsers.graphql
query GetUsers {
  users {
    ...UserFields
    email
  }
}`}</code>
      </pre>
      <p style={{ fontSize: 15, marginBottom: 12 }}>
        Codegen generates a <code style={{ background: '#f1f5f9', padding: '1px 5px', borderRadius: 3 }}>UserFieldsFragment</code> type:
      </p>
      <pre style={{ background: '#1e293b', color: '#e2e8f0', padding: '16px 20px', borderRadius: 8, overflowX: 'auto', fontSize: 13, marginBottom: 20 }}>
        <code>{`// Generated
export type UserFieldsFragment = {
  id: string;
  name: string;
  avatarUrl: string | null;
};

// Use as prop type in components
interface UserAvatarProps {
  user: UserFieldsFragment;
}

function UserAvatar({ user }: UserAvatarProps) {
  return <img src={user.avatarUrl ?? '/default-avatar.png'} alt={user.name} />;
}`}</code>
      </pre>
      <p style={{ fontSize: 15, marginBottom: 24 }}>
        Fragment types are especially useful for component-level data requirements. Each component declares the fragment
        it needs, and the parent query composes those fragments. This is known as the Colocation pattern and is a best
        practice with Apollo Client and Relay.
      </p>

      {/* ---- Section 11: Input Types and Mutations ---- */}
      <h2 style={{ fontSize: 26, fontWeight: 800, marginTop: 48, marginBottom: 16 }}>
        Input Types and Mutations
      </h2>
      <p style={{ fontSize: 15, marginBottom: 12 }}>
        GraphQL mutations take input types as variables. Codegen generates TypeScript types for both the mutation result
        and the input variables. This means your form data, API calls, and state management are all type-checked against
        the schema.
      </p>
      <pre style={{ background: '#1e293b', color: '#e2e8f0', padding: '16px 20px', borderRadius: 8, overflowX: 'auto', fontSize: 13, marginBottom: 20 }}>
        <code>{`# src/mutations/CreatePost.graphql
mutation CreatePost($input: CreatePostInput!) {
  createPost(input: $input) {
    id
    title
    publishedAt
    author {
      id
      name
    }
  }
}`}</code>
      </pre>
      <pre style={{ background: '#1e293b', color: '#e2e8f0', padding: '16px 20px', borderRadius: 8, overflowX: 'auto', fontSize: 13, marginBottom: 20 }}>
        <code>{`// Generated types
export type CreatePostInput = {
  title: string;
  body: string;
  tags?: string[] | null;
  publishAt?: string | null;  // DateTime scalar
};

export type CreatePostMutation = {
  createPost: {
    id: string;
    title: string;
    publishedAt: string | null;
    author: {
      id: string;
      name: string;
    };
  };
};

export type CreatePostMutationVariables = {
  input: CreatePostInput;
};`}</code>
      </pre>
      <pre style={{ background: '#1e293b', color: '#e2e8f0', padding: '16px 20px', borderRadius: 8, overflowX: 'auto', fontSize: 13, marginBottom: 20 }}>
        <code>{`// Usage with Apollo
import { useMutation } from '@apollo/client';
import { CreatePostDocument } from '../generated/operations';

function CreatePostForm() {
  const [createPost, { loading, error }] = useMutation(CreatePostDocument);

  const handleSubmit = async (formData: CreatePostInput) => {
    const { data } = await createPost({
      variables: { input: formData },
      // TypeScript validates formData matches CreatePostInput
    });
    console.log('Created:', data?.createPost.id);
  };

  // ... form JSX
}`}</code>
      </pre>

      {/* ---- Section 12: Watch Mode and CI ---- */}
      <h2 style={{ fontSize: 26, fontWeight: 800, marginTop: 48, marginBottom: 16 }}>
        Watch Mode and CI Integration
      </h2>
      <p style={{ fontSize: 15, marginBottom: 12 }}>
        Running codegen manually is error-prone. Use watch mode during development and integrate codegen into your CI
        pipeline to ensure types are always up to date.
      </p>

      <h3 style={{ fontSize: 20, fontWeight: 700, marginTop: 24, marginBottom: 10 }}>Watch Mode in Development</h3>
      <pre style={{ background: '#1e293b', color: '#e2e8f0', padding: '16px 20px', borderRadius: 8, overflowX: 'auto', fontSize: 13, marginBottom: 20 }}>
        <code>{`# Start watch mode alongside your dev server
npx graphql-codegen --watch

# Or in package.json with concurrently:
{
  "scripts": {
    "dev": "concurrently \\"next dev\\" \\"npm run codegen:watch\\"",
    "codegen:watch": "graphql-codegen --watch"
  }
}`}</code>
      </pre>
      <p style={{ fontSize: 15, marginBottom: 12 }}>
        Watch mode monitors your <code style={{ background: '#f1f5f9', padding: '1px 5px', borderRadius: 3 }}>documents</code> glob
        and the schema source. When either changes, it regenerates the types automatically. No manual rerun needed.
      </p>

      <h3 style={{ fontSize: 20, fontWeight: 700, marginTop: 24, marginBottom: 10 }}>CI Pipeline Integration</h3>
      <pre style={{ background: '#1e293b', color: '#e2e8f0', padding: '16px 20px', borderRadius: 8, overflowX: 'auto', fontSize: 13, marginBottom: 20 }}>
        <code>{`# GitHub Actions example
- name: Generate GraphQL types
  run: npm run codegen

- name: Check for uncommitted changes
  run: |
    git diff --exit-code src/generated/
    # Fails if generated files were not committed

- name: TypeScript type check
  run: npx tsc --noEmit --skipLibCheck`}</code>
      </pre>
      <p style={{ fontSize: 15, marginBottom: 12 }}>
        The CI check pattern above ensures that:
      </p>
      <ol style={{ fontSize: 15, paddingLeft: 20, marginBottom: 24, display: 'flex', flexDirection: 'column', gap: 6 }}>
        <li>Generated types are always committed alongside the operations that produce them.</li>
        <li>Any schema change that breaks existing queries is caught as a TypeScript error in CI.</li>
        <li>Pull requests cannot merge with stale generated types.</li>
      </ol>

      <h3 style={{ fontSize: 20, fontWeight: 700, marginTop: 24, marginBottom: 10 }}>Pre-commit Hook with Husky</h3>
      <pre style={{ background: '#1e293b', color: '#e2e8f0', padding: '16px 20px', borderRadius: 8, overflowX: 'auto', fontSize: 13, marginBottom: 20 }}>
        <code>{`# .husky/pre-commit
#!/bin/sh
npm run codegen
git add src/generated/`}</code>
      </pre>
      <p style={{ fontSize: 15, marginBottom: 24 }}>
        This hook regenerates types before each commit and stages the updated files automatically, so generated
        types are always in sync with operations in every commit.
      </p>

      {/* ---- Section 13: Tools ---- */}
      <h2 style={{ fontSize: 26, fontWeight: 800, marginTop: 48, marginBottom: 16 }}>
        Tools for GraphQL to TypeScript Conversion
      </h2>
      <p style={{ fontSize: 15, marginBottom: 12 }}>
        Several tools can help you convert GraphQL schemas and operations to TypeScript types:
      </p>

      <h3 style={{ fontSize: 20, fontWeight: 700, marginTop: 24, marginBottom: 10 }}>@graphql-codegen/cli</h3>
      <p style={{ fontSize: 15, marginBottom: 12 }}>
        The industry-standard CLI tool. Supports all major GraphQL clients, produces TypedDocumentNode, resolver types,
        and more. Highly configurable via plugins. Best for production projects with ongoing schema evolution.
      </p>

      <h3 style={{ fontSize: 20, fontWeight: 700, marginTop: 24, marginBottom: 10 }}>DevToolBox GraphQL to TypeScript</h3>
      <p style={{ fontSize: 15, marginBottom: 12 }}>
        For quick, one-off conversions without installing anything, the{' '}
        <Link href={toolLink} style={{ color: '#2563eb', fontWeight: 600 }}>
          DevToolBox GraphQL to TypeScript tool
        </Link>{' '}
        converts GraphQL SDL (Schema Definition Language) to TypeScript interfaces directly in your browser. Paste a schema
        fragment and get typed interfaces instantly. Useful for exploring a schema or learning what the generated types
        look like before setting up the full codegen pipeline.
      </p>

      <h3 style={{ fontSize: 20, fontWeight: 700, marginTop: 24, marginBottom: 10 }}>Other Tools</h3>
      <div style={{ overflowX: 'auto', marginBottom: 24 }}>
        <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 14, textAlign: 'left' }}>
          <thead>
            <tr style={{ background: '#f1f5f9', borderBottom: '2px solid #e2e8f0' }}>
              <th style={{ padding: '10px 14px', fontWeight: 700 }}>Tool</th>
              <th style={{ padding: '10px 14px', fontWeight: 700 }}>Type</th>
              <th style={{ padding: '10px 14px', fontWeight: 700 }}>Best For</th>
            </tr>
          </thead>
          <tbody>
            {[
              ['@graphql-codegen/cli', 'CLI / npm', 'Full production pipeline'],
              ['DevToolBox GraphQL→TS', 'Online browser tool', 'Quick schema exploration'],
              ['graphql-zeus', 'CLI / npm', 'Fully-typed client generation'],
              ['gqty', 'CLI / npm', 'Auto-generating reactive queries'],
              ['Relay compiler', 'CLI / npm', 'Facebook Relay framework'],
            ].map(([tool, type, best], i) => (
              <tr key={i} style={{ borderBottom: '1px solid #e2e8f0', background: i % 2 === 0 ? '#fff' : '#f8fafc' }}>
                <td style={{ padding: '9px 14px', fontFamily: 'monospace', fontSize: 13 }}>{tool}</td>
                <td style={{ padding: '9px 14px' }}>{type}</td>
                <td style={{ padding: '9px 14px' }}>{best}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* ---- Section 14: Common Pitfalls ---- */}
      <h2 style={{ fontSize: 26, fontWeight: 800, marginTop: 48, marginBottom: 16 }}>
        Common Pitfalls
      </h2>

      <h3 style={{ fontSize: 20, fontWeight: 700, marginTop: 24, marginBottom: 10 }}>Nullable Fields Everywhere</h3>
      <p style={{ fontSize: 15, marginBottom: 12 }}>
        GraphQL fields are nullable by default. In a schema like <code style={{ background: '#f1f5f9', padding: '1px 5px', borderRadius: 3 }}>type User &#123; name: String &#125;</code>,
        the <code style={{ background: '#f1f5f9', padding: '1px 5px', borderRadius: 3 }}>name</code> field is{' '}
        <code style={{ background: '#f1f5f9', padding: '1px 5px', borderRadius: 3 }}>String | null</code> in TypeScript.
        Many developers are surprised by the volume of optional chaining required. The solution is to mark fields
        non-null in the schema with <code style={{ background: '#f1f5f9', padding: '1px 5px', borderRadius: 3 }}>!</code> whenever
        the server guarantees a value:{' '}
        <code style={{ background: '#f1f5f9', padding: '1px 5px', borderRadius: 3 }}>name: String!</code>. Do not work
        around nullability by disabling <code style={{ background: '#f1f5f9', padding: '1px 5px', borderRadius: 3 }}>strictNullChecks</code> &mdash;
        that eliminates all the safety benefits.
      </p>

      <h3 style={{ fontSize: 20, fontWeight: 700, marginTop: 24, marginBottom: 10 }}>__typename Conflicts</h3>
      <p style={{ fontSize: 15, marginBottom: 12 }}>
        By default, codegen adds a <code style={{ background: '#f1f5f9', padding: '1px 5px', borderRadius: 3 }}>__typename: 'TypeName'</code> literal
        to every generated type. This is useful for Apollo Client&#39;s normalized cache but can cause unexpected type
        union narrowing issues. If you do not need inline fragment type narrowing, disable it with:
      </p>
      <pre style={{ background: '#1e293b', color: '#e2e8f0', padding: '16px 20px', borderRadius: 8, overflowX: 'auto', fontSize: 13, marginBottom: 20 }}>
        <code>{`// codegen.ts
config: {
  skipTypename: true,  // omit __typename from generated types
}`}</code>
      </pre>

      <h3 style={{ fontSize: 20, fontWeight: 700, marginTop: 24, marginBottom: 10 }}>Schema Changes Breaking Generated Types</h3>
      <p style={{ fontSize: 15, marginBottom: 12 }}>
        When the server removes or renames a field, your operation files may still reference the old name. After running
        codegen, TypeScript will immediately flag the broken references. The fix is to update your operations to use the
        new field names. This is actually the system working correctly: schema drift is caught at compile time rather
        than at runtime in production.
      </p>

      <h3 style={{ fontSize: 20, fontWeight: 700, marginTop: 24, marginBottom: 10 }}>Committing Generated Files</h3>
      <p style={{ fontSize: 15, marginBottom: 12 }}>
        A common question is whether to commit the <code style={{ background: '#f1f5f9', padding: '1px 5px', borderRadius: 3 }}>src/generated/</code> folder.
        The answer depends on your team workflow:
      </p>
      <ul style={{ fontSize: 15, paddingLeft: 20, marginBottom: 24, display: 'flex', flexDirection: 'column', gap: 6 }}>
        <li><strong>Commit generated files:</strong> Easier for onboarding, no codegen step needed to run TypeScript, CI can check for drift.</li>
        <li><strong>Gitignore generated files:</strong> Cleaner diffs, always regenerated fresh in CI. Requires codegen to run before tsc in every environment.</li>
        <li>Most teams commit generated files and use the CI diff check pattern to catch stale types.</li>
      </ul>

      {/* ---- FAQ Section ---- */}
      <h2 id="faq" style={{ fontSize: 26, fontWeight: 800, marginTop: 48, marginBottom: 24 }}>
        {t.faqTitle}
      </h2>
      {faqItems.map((item, i) => (
        <div key={i} style={{ marginBottom: 28, paddingBottom: 28, borderBottom: i < faqItems.length - 1 ? '1px solid #e2e8f0' : 'none' }}>
          <h3 style={{ fontSize: 18, fontWeight: 700, marginBottom: 8, marginTop: 0 }}>
            {item.q}
          </h3>
          <p style={{ fontSize: 15, margin: 0, lineHeight: 1.7 }}>
            {item.a}
          </p>
        </div>
      ))}

      {/* ---- CTA ---- */}
      <div style={{
        background: '#f0f9ff',
        border: '1px solid #bae6fd',
        borderRadius: 8,
        padding: '20px 24px',
        marginTop: 48,
        marginBottom: 16,
        textAlign: 'center',
      }}>
        <p style={{ fontWeight: 700, fontSize: 18, marginBottom: 8, marginTop: 0 }}>
          Try GraphQL to TypeScript Online
        </p>
        <p style={{ fontSize: 15, marginBottom: 16, marginTop: 0, color: '#475569' }}>
          Convert GraphQL SDL to TypeScript interfaces instantly in your browser &mdash; no install required.
        </p>
        <Link
          href={toolLink}
          style={{
            display: 'inline-block',
            background: '#2563eb',
            color: '#fff',
            padding: '10px 24px',
            borderRadius: 6,
            fontWeight: 700,
            fontSize: 15,
            textDecoration: 'none',
          }}
        >
          Open GraphQL to TypeScript Tool
        </Link>
      </div>
    </article>
  );
}
