'use client';
import React from 'react';

const codeTurboSetup = `# Create a new Turborepo monorepo
npx create-turbo@latest my-monorepo
cd my-monorepo

# Or add Turborepo to an existing monorepo
npm install turbo --save-dev

# Directory structure
my-monorepo/
├── apps/
│   ├── web/          # Next.js app
│   └── docs/         # Docs site
├── packages/
│   ├── ui/           # Shared React components
│   ├── utils/        # Shared utilities
│   └── tsconfig/     # Shared TypeScript configs
├── turbo.json        # Pipeline configuration
└── package.json      # Root workspace config`;

const codeTurboJson = `// turbo.json — pipeline definition
{
    "$schema": "https://turbo.build/schema.json",
    "pipeline": {
        "build": {
            "dependsOn": ["^build"],   // ^ means: run in dependency order
            "outputs": [".next/**", "!.next/cache/**", "dist/**"]
        },
        "test": {
            "dependsOn": ["^build"],
            "inputs": ["src/**/*.tsx", "src/**/*.ts", "test/**/*.ts"]
        },
        "lint": {
            "outputs": []
        },
        "dev": {
            "cache": false,            // Never cache dev servers
            "persistent": true         // Long-running task
        },
        "type-check": {
            "dependsOn": ["^build"],
            "outputs": []
        }
    },
    "globalEnv": ["NODE_ENV", "DATABASE_URL"]
}

# Run all build tasks (uses cache if inputs unchanged)
npx turbo build

# Run only for specific apps/packages
npx turbo build --filter=web
npx turbo build --filter=...ui  # ui and all its dependents

# Force re-run (bypass cache)
npx turbo build --force

# View task graph
npx turbo build --graph`;

const codeNxSetup = `# Create Nx monorepo
npx create-nx-workspace@latest my-nx-repo --preset=ts

# Add Nx to existing monorepo
npx nx@latest init

# Generate a new app or library
nx generate @nx/next:app web
nx generate @nx/react:library ui
nx generate @nx/node:library utils

# nx.json — workspace configuration
{
    "tasksRunnerOptions": {
        "default": {
            "runner": "nx/tasks-runners/default",
            "options": {
                "cacheableOperations": ["build", "test", "lint", "e2e"],
                "parallel": 3
            }
        }
    },
    "targetDefaults": {
        "build": {
            "dependsOn": ["^build"],
            "inputs": ["production", "^production"]
        }
    },
    "namedInputs": {
        "default": ["{projectRoot}/**/*", "sharedGlobals"],
        "production": ["default", "!{projectRoot}/**/?(*.)+(spec|test).[jt]s?(x)"],
        "sharedGlobals": []
    }
}`;

const codePnpmWorkspaces = `# pnpm-workspace.yaml
packages:
  - 'apps/*'
  - 'packages/*'

# Install all workspace dependencies
pnpm install

# Add a package to a specific workspace
pnpm add react --filter @myapp/web

# Add a local workspace package as dependency
# In apps/web/package.json:
{
    "dependencies": {
        "@myapp/ui": "workspace:*"
    }
}

# Run scripts across all packages
pnpm --filter '*' run build
pnpm --filter './apps/*' run dev
pnpm --filter '...@myapp/ui' run test  # ui and dependents

# Publish all public packages
pnpm publish -r --access public`;

const codeRemoteCache = `# Turborepo Remote Cache (Vercel)
# Enables sharing build cache across developers and CI

# 1. Link to Vercel
npx turbo login
npx turbo link

# 2. Now CI builds share cache with local dev:
# CI run: builds from scratch, uploads to cache
# Developer: pulls cache, gets instant builds

# Self-host with Turborepo Remote Cache (open source)
# docker run -p 3000:3000 ducktors/turborepo-remote-cache

# .turbo/config.json (auto-generated by turbo link)
{
    "teamId": "team_xxx",
    "apiUrl": "https://vercel.com"
}

# Nx Cloud (similar offering from Nx)
# nx connect-to-nx-cloud
# Provides remote caching + task distribution`;

const codeChangesets = `# Changesets — versioning and publishing for monorepos
# Works with npm/yarn/pnpm workspaces

pnpm add -D @changesets/cli
pnpm changeset init

# When you make a change that needs a version bump:
pnpm changeset
# → Interactive prompt: which packages changed, bump type (major/minor/patch)

# Creates a markdown file in .changeset/ describing the change
# Example .changeset/funny-bears-dance.md:
---
"@myapp/ui": minor
"@myapp/utils": patch
---

Add new Button component with loading state

# Apply changesets (bumps versions, updates CHANGELOG.md)
pnpm changeset version

# Publish all changed packages
pnpm changeset publish`;

const translations: Record<string, Record<string, string>> = {
  en: {
    title: 'Monorepo Tools in 2026: Turborepo, Nx, and pnpm Workspaces',
    intro: 'A monorepo (single repository for multiple packages and apps) improves code sharing, refactoring, and dependency management. In 2026, the three dominant approaches are Turborepo (fast caching, simple config), Nx (powerful generators and affected detection), and pnpm Workspaces (lightweight, no additional tooling). This guide covers setup, task caching, and CI integration for all three.',
    turboTitle: 'Turborepo: Setup and Structure',
    turboDesc: 'Turborepo is optimized for JavaScript/TypeScript monorepos. It uses a simple pipeline definition and aggressive caching to skip tasks whose inputs haven\'t changed.',
    turboPipelineTitle: 'Turborepo Pipeline Configuration',
    turboPipelineDesc: 'The turbo.json pipeline defines how tasks relate to each other and what outputs to cache. The ^ prefix means "wait for dependent packages to build first."',
    nxTitle: 'Nx: Setup and Project Graph',
    nxDesc: 'Nx provides a richer feature set: code generators, affected commands (only run tasks for changed code), and first-class support for many frameworks including React, Angular, Node, and .NET.',
    pnpmTitle: 'pnpm Workspaces: Lightweight Approach',
    pnpmDesc: 'pnpm workspaces provide native monorepo support without additional tooling. Combine with Turborepo or Nx for caching, or use alone for simpler projects.',
    remoteCacheTitle: 'Remote Caching',
    remoteCacheDesc: 'Remote caching shares build artifacts between developers and CI systems. A cache hit means instant builds — no recompilation needed if inputs are unchanged.',
    changesetsTitle: 'Versioning with Changesets',
    changesetsDesc: 'Changesets is the standard tool for versioning and publishing packages in a monorepo. It tracks which packages changed and generates CHANGELOG.md entries.',
    comparisonTitle: 'Turborepo vs Nx vs pnpm Workspaces',
    bestPracticesTitle: 'Best Practices',
    bp1: 'Start with pnpm workspaces + Turborepo — lowest friction, excellent caching, good documentation.',
    bp2: 'Define clear boundaries: shared packages in packages/, applications in apps/. Never import app code from a shared package.',
    bp3: 'Use Changesets for versioning and publishing. Automate releases with GitHub Actions on merge to main.',
    bp4: 'Enable remote caching early — Turborepo\'s Vercel cache is free for hobby projects. CI time drops from minutes to seconds.',
    bp5: 'Keep each package\'s package.json explicit: list all direct dependencies even if they are hoisted. This prevents phantom dependency bugs.',
    faqTitle: 'Frequently Asked Questions',
    faq1q: 'Should I use Turborepo or Nx?',
    faq1a: 'Turborepo is simpler and faster to set up — ideal for most JavaScript/TypeScript projects. Nx has more features: code generators, affected detection, module boundaries enforcement, and better support for polyglot repos (Java, .NET). Choose Nx if you need those features or are working on a large enterprise repo.',
    faq2q: 'What is the difference between monorepo and polyrepo?',
    faq2a: 'A monorepo stores all code in one repository. A polyrepo (multi-repo) has separate repositories per package or service. Monorepos make cross-package refactoring easier and ensure all packages are always compatible. Polyrepos have simpler CI and more team autonomy. Most companies at scale use monorepos.',
    faq3q: 'How does Turborepo caching work?',
    faq3a: 'Turborepo hashes the inputs to each task (source files, environment variables, dependencies). If the hash matches a previous run, it restores outputs from cache (locally or remotely). The cache is content-addressable, so identical inputs always produce cache hits regardless of when they were created.',
    faq4q: 'Can I have different package managers in a monorepo?',
    faq4a: 'No. All workspaces in a monorepo must use the same package manager. The workspace protocol (workspace:*) is implemented differently in npm, yarn, and pnpm. Pick one and stick with it. pnpm is the most efficient for monorepos due to its symlink-based node_modules.',
    faq5q: 'How do I handle environment variables in a monorepo?',
    faq5a: 'Define environment variables per app (each app has its own .env). For shared secrets, use a secrets manager (Vault, AWS SSM). In Turborepo, list environment variables in turbo.json globalEnv (for all tasks) or per-task env array. Turborepo includes env vars in the cache key to prevent stale cache hits.',
    relatedTitle: 'Related Tools',
  },
  zh: {
    title: 'Monorepo 工具 2026：Turborepo、Nx 和 pnpm 工作区',
    intro: 'Monorepo（多包和应用的单一仓库）改善了代码共享、重构和依赖管理。2026 年，三种主流方法是 Turborepo（快速缓存、简单配置）、Nx（强大的生成器和影响检测）和 pnpm 工作区（轻量级，无需额外工具）。',
    turboTitle: 'Turborepo：设置和结构',
    turboDesc: 'Turborepo 针对 JavaScript/TypeScript monorepo 进行了优化。它使用简单的管道定义和激进的缓存来跳过输入未更改的任务。',
    turboPipelineTitle: 'Turborepo 管道配置',
    turboPipelineDesc: 'turbo.json 管道定义了任务之间的关系和要缓存的输出。^ 前缀表示"等待依赖包首先构建"。',
    nxTitle: 'Nx：设置和项目图',
    nxDesc: 'Nx 提供更丰富的功能集：代码生成器、影响命令（仅为更改的代码运行任务），以及对许多框架的一流支持。',
    pnpmTitle: 'pnpm 工作区：轻量级方法',
    pnpmDesc: 'pnpm 工作区提供原生 monorepo 支持，无需额外工具。与 Turborepo 或 Nx 结合使用以进行缓存，或单独用于更简单的项目。',
    remoteCacheTitle: '远程缓存',
    remoteCacheDesc: '远程缓存在开发人员和 CI 系统之间共享构建产物。缓存命中意味着即时构建——如果输入未更改，则无需重新编译。',
    changesetsTitle: '使用 Changesets 进行版本管理',
    changesetsDesc: 'Changesets 是 monorepo 中版本管理和发布包的标准工具。它跟踪哪些包发生了更改并生成 CHANGELOG.md 条目。',
    comparisonTitle: 'Turborepo vs Nx vs pnpm 工作区',
    bestPracticesTitle: '最佳实践',
    bp1: '从 pnpm 工作区 + Turborepo 开始——摩擦最小，缓存出色，文档良好。',
    bp2: '定义清晰边界：共享包在 packages/ 中，应用在 apps/ 中。切勿从共享包中导入应用代码。',
    bp3: '使用 Changesets 进行版本管理和发布。通过 GitHub Actions 在合并到 main 时自动化发布。',
    bp4: '尽早启用远程缓存——Turborepo 的 Vercel 缓存对爱好项目免费。CI 时间从几分钟减少到几秒钟。',
    bp5: '保持每个包的 package.json 明确：列出所有直接依赖，即使它们被提升。这可以防止幻影依赖错误。',
    faqTitle: '常见问题',
    faq1q: '我应该使用 Turborepo 还是 Nx？',
    faq1a: 'Turborepo 更简单，设置更快——对大多数 JavaScript/TypeScript 项目来说是理想的。Nx 具有更多功能：代码生成器、影响检测、模块边界执行，以及对多语言仓库的更好支持。如果需要这些功能或正在处理大型企业仓库，请选择 Nx。',
    faq2q: 'Monorepo 和 polyrepo 有什么区别？',
    faq2a: 'Monorepo 将所有代码存储在一个仓库中。Polyrepo（多仓库）每个包或服务有单独的仓库。Monorepo 使跨包重构更容易，确保所有包始终兼容。Polyrepo 拥有更简单的 CI 和更多团队自主权。',
    faq3q: 'Turborepo 缓存如何工作？',
    faq3a: 'Turborepo 对每个任务的输入（源文件、环境变量、依赖）进行哈希。如果哈希与之前的运行匹配，它从缓存（本地或远程）恢复输出。缓存是内容寻址的，所以相同的输入总是产生缓存命中。',
    faq4q: 'monorepo 中可以有不同的包管理器吗？',
    faq4a: '不可以。monorepo 中的所有工作区必须使用相同的包管理器。工作区协议（workspace:*）在 npm、yarn 和 pnpm 中实现不同。选择一个并坚持使用。',
    faq5q: '如何在 monorepo 中处理环境变量？',
    faq5a: '为每个应用定义环境变量（每个应用有自己的 .env）。在 Turborepo 中，在 turbo.json globalEnv 中列出环境变量（用于所有任务）或每个任务的 env 数组。',
    relatedTitle: '相关工具',
  },
  fr: { title: 'Outils Monorepo en 2026 : Turborepo, Nx et pnpm Workspaces', intro: 'Un monorepo améliore le partage de code, la refactorisation et la gestion des dépendances. En 2026, les trois approches dominantes sont Turborepo, Nx et pnpm Workspaces.', turboTitle: 'Turborepo : configuration et structure', turboDesc: 'Turborepo est optimisé pour les monorepos JavaScript/TypeScript avec un cache agressif.', turboPipelineTitle: 'Configuration du pipeline Turborepo', turboPipelineDesc: 'Le pipeline turbo.json définit comment les tâches se rapportent les unes aux autres.', nxTitle: 'Nx : configuration et graphe de projet', nxDesc: 'Nx offre un ensemble de fonctionnalités plus riche : générateurs de code, commandes affected.', pnpmTitle: 'pnpm Workspaces : approche légère', pnpmDesc: 'pnpm workspaces fournit un support natif des monorepos sans outils supplémentaires.', remoteCacheTitle: 'Cache distant', remoteCacheDesc: 'Le cache distant partage les artefacts entre développeurs et systèmes CI.', changesetsTitle: 'Versionnage avec Changesets', changesetsDesc: 'Changesets est l\'outil standard pour versionner et publier des packages dans un monorepo.', comparisonTitle: 'Turborepo vs Nx vs pnpm Workspaces', bestPracticesTitle: 'Bonnes pratiques', bp1: 'Commencer avec pnpm workspaces + Turborepo.', bp2: 'Définir des limites claires : packages partagés dans packages/, applications dans apps/.', bp3: 'Utiliser Changesets pour le versionnage et la publication.', bp4: 'Activer le cache distant tôt.', bp5: 'Garder le package.json de chaque package explicite.', faqTitle: 'FAQ', faq1q: 'Turborepo ou Nx ?', faq1a: 'Turborepo est plus simple pour la plupart des projets JavaScript. Nx a plus de fonctionnalités pour les grands dépôts.', faq2q: 'Monorepo vs polyrepo ?', faq2a: 'Un monorepo stocke tout le code dans un dépôt. Polyrepo a des dépôts séparés par package.', faq3q: 'Comment fonctionne le cache Turborepo ?', faq3a: 'Turborepo hache les entrées de chaque tâche. Si le hash correspond à une exécution précédente, il restaure les sorties du cache.', faq4q: 'Peut-on avoir différents gestionnaires de packages ?', faq4a: 'Non. Tous les workspaces doivent utiliser le même gestionnaire de packages.', faq5q: 'Comment gérer les variables d\'environnement ?', faq5a: 'Définir les variables d\'environnement par application. Les lister dans turbo.json globalEnv.', relatedTitle: 'Outils associés' },
  de: { title: 'Monorepo-Tools 2026: Turborepo, Nx und pnpm Workspaces', intro: 'Ein Monorepo verbessert Code-Sharing, Refactoring und Abhängigkeitsverwaltung. In 2026 dominieren Turborepo, Nx und pnpm Workspaces.', turboTitle: 'Turborepo: Einrichtung und Struktur', turboDesc: 'Turborepo ist für JavaScript/TypeScript-Monorepos optimiert.', turboPipelineTitle: 'Turborepo-Pipeline-Konfiguration', turboPipelineDesc: 'Die turbo.json-Pipeline definiert Task-Abhängigkeiten und gecachte Ausgaben.', nxTitle: 'Nx: Einrichtung und Projektgraph', nxDesc: 'Nx bietet mehr Funktionen: Code-Generatoren, Affected-Befehle.', pnpmTitle: 'pnpm Workspaces: Leichtgewichtiger Ansatz', pnpmDesc: 'pnpm Workspaces bietet nativen Monorepo-Support ohne zusätzliche Tools.', remoteCacheTitle: 'Entfernter Cache', remoteCacheDesc: 'Remote-Caching teilt Build-Artefakte zwischen Entwicklern und CI.', changesetsTitle: 'Versionierung mit Changesets', changesetsDesc: 'Changesets ist das Standardtool für Versionierung und Veröffentlichung in Monorepos.', comparisonTitle: 'Turborepo vs Nx vs pnpm Workspaces', bestPracticesTitle: 'Best Practices', bp1: 'Mit pnpm Workspaces + Turborepo beginnen.', bp2: 'Klare Grenzen definieren: Shared Packages in packages/, Apps in apps/.', bp3: 'Changesets für Versionierung verwenden.', bp4: 'Remote-Caching früh aktivieren.', bp5: 'Jedes package.json explizit halten.', faqTitle: 'FAQ', faq1q: 'Turborepo oder Nx?', faq1a: 'Turborepo ist für die meisten JS-Projekte einfacher. Nx hat mehr Features für große Repos.', faq2q: 'Monorepo vs Polyrepo?', faq2a: 'Monorepo speichert allen Code in einem Repository.', faq3q: 'Wie funktioniert Turborepo-Caching?', faq3a: 'Turborepo hasht die Eingaben jeder Task und stellt Ausgaben aus dem Cache wieder her.', faq4q: 'Verschiedene Paketmanager im Monorepo?', faq4a: 'Nein. Alle Workspaces müssen denselben Paketmanager verwenden.', faq5q: 'Umgebungsvariablen im Monorepo?', faq5a: 'Umgebungsvariablen pro App definieren und in turbo.json globalEnv auflisten.', relatedTitle: 'Verwandte Tools' },
  es: { title: 'Herramientas Monorepo en 2026: Turborepo, Nx y pnpm Workspaces', intro: 'Un monorepo mejora el intercambio de código, refactoring y gestión de dependencias.', turboTitle: 'Turborepo: configuración y estructura', turboDesc: 'Turborepo está optimizado para monorepos JavaScript/TypeScript.', turboPipelineTitle: 'Configuración del pipeline Turborepo', turboPipelineDesc: 'El pipeline turbo.json define cómo se relacionan las tareas entre sí.', nxTitle: 'Nx: configuración y gráfico de proyecto', nxDesc: 'Nx ofrece un conjunto de características más rico.', pnpmTitle: 'pnpm Workspaces: enfoque ligero', pnpmDesc: 'pnpm workspaces proporciona soporte nativo de monorepo sin herramientas adicionales.', remoteCacheTitle: 'Caché remota', remoteCacheDesc: 'La caché remota comparte artefactos de compilación entre desarrolladores y CI.', changesetsTitle: 'Versionado con Changesets', changesetsDesc: 'Changesets es la herramienta estándar para versionar y publicar paquetes en un monorepo.', comparisonTitle: 'Turborepo vs Nx vs pnpm Workspaces', bestPracticesTitle: 'Mejores prácticas', bp1: 'Empezar con pnpm workspaces + Turborepo.', bp2: 'Definir límites claros: paquetes compartidos en packages/, apps en apps/.', bp3: 'Usar Changesets para versionado.', bp4: 'Activar caché remota pronto.', bp5: 'Mantener el package.json de cada paquete explícito.', faqTitle: 'FAQ', faq1q: '¿Turborepo o Nx?', faq1a: 'Turborepo es más simple para la mayoría de proyectos JS. Nx tiene más características para grandes repos.', faq2q: '¿Monorepo vs polyrepo?', faq2a: 'Un monorepo almacena todo el código en un repositorio.', faq3q: '¿Cómo funciona el caché de Turborepo?', faq3a: 'Turborepo hashea las entradas de cada tarea y restaura salidas desde el caché.', faq4q: '¿Diferentes gestores de paquetes en monorepo?', faq4a: 'No. Todos los workspaces deben usar el mismo gestor de paquetes.', faq5q: '¿Variables de entorno en monorepo?', faq5a: 'Definir variables por app y listarlas en turbo.json globalEnv.', relatedTitle: 'Herramientas relacionadas' },
  ja: { title: 'Monoレポツール2026：Turborepo、Nx、pnpm Workspaces', intro: 'モノレポはコード共有、リファクタリング、依存関係管理を改善します。2026年はTurborepo、Nx、pnpm Workspacesが主流です。', turboTitle: 'Turborepo：セットアップと構造', turboDesc: 'TurborepoはJavaScript/TypeScriptモノレポに最適化されています。', turboPipelineTitle: 'Turborepoパイプライン設定', turboPipelineDesc: 'turbo.jsonパイプラインはタスク間の依存関係とキャッシュ対象の出力を定義します。', nxTitle: 'Nx：セットアップとプロジェクトグラフ', nxDesc: 'NxはよりリッチなフィーチャーセットをO提供：コードジェネレーター、Affectedコマンド。', pnpmTitle: 'pnpm Workspaces：軽量アプローチ', pnpmDesc: 'pnpm workspacesは追加ツールなしでネイティブモノレポサポートを提供。', remoteCacheTitle: 'リモートキャッシュ', remoteCacheDesc: 'リモートキャッシュは開発者とCIシステム間でビルドアーティファクトを共有。', changesetsTitle: 'Changesetsでのバージョン管理', changesetsDesc: 'Changesetsはモノレポでパッケージをバージョン管理・公開するための標準ツール。', comparisonTitle: 'Turborepo vs Nx vs pnpm Workspaces', bestPracticesTitle: 'ベストプラクティス', bp1: 'pnpm workspaces + Turborepoから始める。', bp2: '明確な境界を定義：共有パッケージはpackages/、アプリはapps/に。', bp3: 'バージョン管理にChangesetsを使用。', bp4: 'リモートキャッシュを早期に有効化。', bp5: '各パッケージのpackage.jsonを明示的に保つ。', faqTitle: 'よくある質問', faq1q: 'TurborepoかNxか？', faq1a: 'Turborepoは多くのJSプロジェクトにとってよりシンプル。Nxは大規模リポ向けのより多くの機能を持つ。', faq2q: 'モノレポとポリレポの違いは？', faq2a: 'モノレポはすべてのコードを1つのリポジトリに格納します。', faq3q: 'Turborepoキャッシュの仕組みは？', faq3a: 'Turborepoは各タスクの入力をハッシュ化し、キャッシュから出力を復元します。', faq4q: 'モノレポで異なるパッケージマネージャーは？', faq4a: 'いいえ。すべてのワークスペースは同じパッケージマネージャーを使用する必要があります。', faq5q: 'モノレポでの環境変数は？', faq5a: 'アプリごとに環境変数を定義し、turbo.json globalEnvにリスト。', relatedTitle: '関連ツール' },
  ko: { title: '2026년 모노레포 도구: Turborepo, Nx, pnpm 워크스페이스', intro: '모노레포는 코드 공유, 리팩토링, 의존성 관리를 개선합니다. 2026년에는 Turborepo, Nx, pnpm 워크스페이스가 주류입니다.', turboTitle: 'Turborepo: 설정과 구조', turboDesc: 'Turborepo는 JavaScript/TypeScript 모노레포에 최적화되어 있습니다.', turboPipelineTitle: 'Turborepo 파이프라인 설정', turboPipelineDesc: 'turbo.json 파이프라인은 태스크 간의 관계와 캐시할 출력을 정의합니다.', nxTitle: 'Nx: 설정과 프로젝트 그래프', nxDesc: 'Nx는 코드 생성기, affected 명령 등 더 풍부한 기능을 제공합니다.', pnpmTitle: 'pnpm 워크스페이스: 경량 접근법', pnpmDesc: 'pnpm 워크스페이스는 추가 도구 없이 네이티브 모노레포 지원을 제공합니다.', remoteCacheTitle: '원격 캐시', remoteCacheDesc: '원격 캐시는 개발자와 CI 시스템 간에 빌드 아티팩트를 공유합니다.', changesetsTitle: 'Changesets로 버전 관리', changesetsDesc: 'Changesets는 모노레포에서 패키지를 버전 관리하고 게시하는 표준 도구입니다.', comparisonTitle: 'Turborepo vs Nx vs pnpm 워크스페이스', bestPracticesTitle: '모범 사례', bp1: 'pnpm 워크스페이스 + Turborepo로 시작하세요.', bp2: '명확한 경계를 정의하세요: 공유 패키지는 packages/, 앱은 apps/에.', bp3: '버전 관리에 Changesets를 사용하세요.', bp4: '원격 캐시를 일찍 활성화하세요.', bp5: '각 패키지의 package.json을 명시적으로 유지하세요.', faqTitle: '자주 묻는 질문', faq1q: 'Turborepo와 Nx 중 어느 것을 선택해야 하나요?', faq1a: 'Turborepo는 대부분의 JS 프로젝트에 더 간단합니다. Nx는 대규모 저장소를 위한 더 많은 기능을 갖고 있습니다.', faq2q: '모노레포와 폴리레포의 차이는?', faq2a: '모노레포는 모든 코드를 하나의 저장소에 저장합니다.', faq3q: 'Turborepo 캐싱은 어떻게 작동하나요?', faq3a: 'Turborepo는 각 태스크의 입력을 해시하고 캐시에서 출력을 복원합니다.', faq4q: '모노레포에서 다른 패키지 관리자를 사용할 수 있나요?', faq4a: '아니요. 모든 워크스페이스는 동일한 패키지 관리자를 사용해야 합니다.', faq5q: '모노레포에서 환경 변수는 어떻게 처리하나요?', faq5a: '앱별로 환경 변수를 정의하고 turbo.json globalEnv에 나열하세요.', relatedTitle: '관련 도구' },
  pt: { title: 'Ferramentas Monorepo em 2026: Turborepo, Nx e pnpm Workspaces', intro: 'Um monorepo melhora o compartilhamento de código, refatoração e gerenciamento de dependências.', turboTitle: 'Turborepo: configuração e estrutura', turboDesc: 'Turborepo é otimizado para monorepos JavaScript/TypeScript.', turboPipelineTitle: 'Configuração do pipeline Turborepo', turboPipelineDesc: 'O pipeline turbo.json define como as tarefas se relacionam entre si.', nxTitle: 'Nx: configuração e gráfico de projeto', nxDesc: 'Nx oferece um conjunto de recursos mais rico: geradores de código, comandos affected.', pnpmTitle: 'pnpm Workspaces: abordagem leve', pnpmDesc: 'pnpm workspaces fornece suporte nativo a monorepos sem ferramentas adicionais.', remoteCacheTitle: 'Cache remoto', remoteCacheDesc: 'O cache remoto compartilha artefatos de build entre desenvolvedores e CI.', changesetsTitle: 'Versionamento com Changesets', changesetsDesc: 'Changesets é a ferramenta padrão para versionar e publicar pacotes em monorepos.', comparisonTitle: 'Turborepo vs Nx vs pnpm Workspaces', bestPracticesTitle: 'Boas práticas', bp1: 'Começar com pnpm workspaces + Turborepo.', bp2: 'Definir limites claros: pacotes compartilhados em packages/, apps em apps/.', bp3: 'Usar Changesets para versionamento.', bp4: 'Ativar cache remoto cedo.', bp5: 'Manter o package.json de cada pacote explícito.', faqTitle: 'FAQ', faq1q: 'Turborepo ou Nx?', faq1a: 'Turborepo é mais simples para a maioria dos projetos JS. Nx tem mais recursos para grandes repos.', faq2q: 'Monorepo vs polyrepo?', faq2a: 'Um monorepo armazena todo o código em um repositório.', faq3q: 'Como funciona o cache do Turborepo?', faq3a: 'Turborepo faz hash das entradas de cada tarefa e restaura saídas do cache.', faq4q: 'Diferentes gerenciadores de pacotes no monorepo?', faq4a: 'Não. Todos os workspaces devem usar o mesmo gerenciador de pacotes.', faq5q: 'Variáveis de ambiente no monorepo?', faq5a: 'Definir variáveis por app e listá-las no turbo.json globalEnv.', relatedTitle: 'Ferramentas relacionadas' },
  it: { title: 'Strumenti Monorepo nel 2026: Turborepo, Nx e pnpm Workspaces', intro: 'Un monorepo migliora la condivisione del codice, il refactoring e la gestione delle dipendenze.', turboTitle: 'Turborepo: configurazione e struttura', turboDesc: 'Turborepo è ottimizzato per monorepo JavaScript/TypeScript.', turboPipelineTitle: 'Configurazione pipeline Turborepo', turboPipelineDesc: 'Il pipeline turbo.json definisce come le attività si relazionano tra loro.', nxTitle: 'Nx: configurazione e grafico del progetto', nxDesc: 'Nx offre un set di funzionalità più ricco.', pnpmTitle: 'pnpm Workspaces: approccio leggero', pnpmDesc: 'pnpm workspaces fornisce supporto nativo per monorepo senza strumenti aggiuntivi.', remoteCacheTitle: 'Cache remota', remoteCacheDesc: 'La cache remota condivide gli artefatti di build tra sviluppatori e CI.', changesetsTitle: 'Versioning con Changesets', changesetsDesc: 'Changesets è lo strumento standard per il versioning e la pubblicazione in monorepo.', comparisonTitle: 'Turborepo vs Nx vs pnpm Workspaces', bestPracticesTitle: 'Best practice', bp1: 'Iniziare con pnpm workspaces + Turborepo.', bp2: 'Definire confini chiari: pacchetti condivisi in packages/, app in apps/.', bp3: 'Usare Changesets per il versioning.', bp4: 'Abilitare la cache remota presto.', bp5: 'Tenere esplicito il package.json di ogni pacchetto.', faqTitle: 'FAQ', faq1q: 'Turborepo o Nx?', faq1a: 'Turborepo è più semplice per la maggior parte dei progetti JS. Nx ha più funzionalità per grandi repo.', faq2q: 'Monorepo vs polyrepo?', faq2a: 'Un monorepo memorizza tutto il codice in un unico repository.', faq3q: 'Come funziona il caching di Turborepo?', faq3a: 'Turborepo fa l\'hash degli input di ogni task e ripristina gli output dalla cache.', faq4q: 'Diversi gestori di pacchetti nel monorepo?', faq4a: 'No. Tutti i workspace devono usare lo stesso gestore di pacchetti.', faq5q: 'Variabili d\'ambiente nel monorepo?', faq5a: 'Definire le variabili per app e elencarle in turbo.json globalEnv.', relatedTitle: 'Strumenti correlati' },
  nl: { title: 'Monorepo-tools in 2026: Turborepo, Nx en pnpm Workspaces', intro: 'Een monorepo verbetert code-delen, refactoring en afhankelijkheidsbeheer.', turboTitle: 'Turborepo: opzet en structuur', turboDesc: 'Turborepo is geoptimaliseerd voor JavaScript/TypeScript-monorepo\'s.', turboPipelineTitle: 'Turborepo-pijplijnconfiguratie', turboPipelineDesc: 'De turbo.json-pijplijn definieert hoe taken met elkaar samenhangen.', nxTitle: 'Nx: opzet en projectgraph', nxDesc: 'Nx biedt een rijker functieset: codegenerators, affected-opdrachten.', pnpmTitle: 'pnpm Workspaces: lichtgewicht aanpak', pnpmDesc: 'pnpm workspaces biedt native monorepo-ondersteuning zonder extra tools.', remoteCacheTitle: 'Remote cache', remoteCacheDesc: 'Remote caching deelt bouw-artefacten tussen ontwikkelaars en CI.', changesetsTitle: 'Versiebeheer met Changesets', changesetsDesc: 'Changesets is de standaardtool voor versiebeheer en publicatie in monorepo\'s.', comparisonTitle: 'Turborepo vs Nx vs pnpm Workspaces', bestPracticesTitle: 'Best practices', bp1: 'Beginnen met pnpm workspaces + Turborepo.', bp2: 'Duidelijke grenzen definiëren: gedeelde packages in packages/, apps in apps/.', bp3: 'Changesets gebruiken voor versiebeheer.', bp4: 'Remote cache vroeg inschakelen.', bp5: 'Elk package.json expliciet houden.', faqTitle: 'FAQ', faq1q: 'Turborepo of Nx?', faq1a: 'Turborepo is eenvoudiger voor de meeste JS-projecten. Nx heeft meer functies voor grote repo\'s.', faq2q: 'Monorepo vs polyrepo?', faq2a: 'Een monorepo slaat alle code op in één repository.', faq3q: 'Hoe werkt Turborepo-caching?', faq3a: 'Turborepo hasht de invoer van elke taak en herstelt uitvoer uit de cache.', faq4q: 'Verschillende pakketbeheerders in monorepo?', faq4a: 'Nee. Alle workspaces moeten dezelfde pakketbeheerder gebruiken.', faq5q: 'Omgevingsvariabelen in monorepo?', faq5a: 'Variabelen per app definiëren en vermelden in turbo.json globalEnv.', relatedTitle: 'Gerelateerde tools' },
  pl: { title: 'Narzędzia Monorepo w 2026: Turborepo, Nx i pnpm Workspaces', intro: 'Monorepo poprawia współdzielenie kodu, refaktoryzację i zarządzanie zależnościami.', turboTitle: 'Turborepo: konfiguracja i struktura', turboDesc: 'Turborepo jest zoptymalizowany dla monorepo JavaScript/TypeScript.', turboPipelineTitle: 'Konfiguracja pipeline Turborepo', turboPipelineDesc: 'Pipeline turbo.json definiuje zależności między zadaniami.', nxTitle: 'Nx: konfiguracja i graf projektu', nxDesc: 'Nx oferuje bogatszy zestaw funkcji: generatory kodu, komendy affected.', pnpmTitle: 'pnpm Workspaces: lekkie podejście', pnpmDesc: 'pnpm workspaces zapewnia natywne wsparcie monorepo bez dodatkowych narzędzi.', remoteCacheTitle: 'Zdalny cache', remoteCacheDesc: 'Zdalny cache dzieli artefakty budowania między deweloperami i CI.', changesetsTitle: 'Wersjonowanie z Changesets', changesetsDesc: 'Changesets to standardowe narzędzie do wersjonowania i publikowania w monorepo.', comparisonTitle: 'Turborepo vs Nx vs pnpm Workspaces', bestPracticesTitle: 'Najlepsze praktyki', bp1: 'Zacząć od pnpm workspaces + Turborepo.', bp2: 'Definiować jasne granice: shared w packages/, apps w apps/.', bp3: 'Używać Changesets do wersjonowania.', bp4: 'Włączyć zdalny cache wcześnie.', bp5: 'Utrzymywać każdy package.json jako explicite.', faqTitle: 'FAQ', faq1q: 'Turborepo czy Nx?', faq1a: 'Turborepo jest prostszy dla większości projektów JS. Nx ma więcej funkcji dla dużych repozytoriów.', faq2q: 'Monorepo vs polyrepo?', faq2a: 'Monorepo przechowuje cały kod w jednym repozytorium.', faq3q: 'Jak działa cache Turborepo?', faq3a: 'Turborepo hashuje wejścia każdego zadania i przywraca wyjścia z cache.', faq4q: 'Różne menedżery pakietów w monorepo?', faq4a: 'Nie. Wszystkie workspace muszą używać tego samego menedżera pakietów.', faq5q: 'Zmienne środowiskowe w monorepo?', faq5a: 'Definiować zmienne per aplikacja i listowaé w turbo.json globalEnv.', relatedTitle: 'Powiązane narzędzia' },
  sv: { title: 'Monorepo-verktyg 2026: Turborepo, Nx och pnpm Workspaces', intro: 'Ett monorepo förbättrar koddelning, refaktorering och beroendehantering.', turboTitle: 'Turborepo: installation och struktur', turboDesc: 'Turborepo är optimerat för JavaScript/TypeScript-monorepos.', turboPipelineTitle: 'Turborepo pipeline-konfiguration', turboPipelineDesc: 'turbo.json-pipelinen definierar hur uppgifter relaterar till varandra.', nxTitle: 'Nx: installation och projektgraf', nxDesc: 'Nx erbjuder en rikare funktionsuppsättning: kodgeneratorer, affected-kommandon.', pnpmTitle: 'pnpm Workspaces: lättviktsapproach', pnpmDesc: 'pnpm workspaces ger inbyggt monorepo-stöd utan extra verktyg.', remoteCacheTitle: 'Fjärrcache', remoteCacheDesc: 'Fjärrcaching delar byggartefakter mellan utvecklare och CI.', changesetsTitle: 'Versionshantering med Changesets', changesetsDesc: 'Changesets är standardverktyget för versionshantering och publicering i monorepos.', comparisonTitle: 'Turborepo vs Nx vs pnpm Workspaces', bestPracticesTitle: 'Bästa praxis', bp1: 'Börja med pnpm workspaces + Turborepo.', bp2: 'Definiera tydliga gränser: delade paket i packages/, appar i apps/.', bp3: 'Använda Changesets för versionshantering.', bp4: 'Aktivera fjärrcache tidigt.', bp5: 'Hålla varje package.json explicit.', faqTitle: 'Vanliga frågor', faq1q: 'Turborepo eller Nx?', faq1a: 'Turborepo är enklare för de flesta JS-projekt. Nx har fler funktioner för stora repos.', faq2q: 'Monorepo vs polyrepo?', faq2a: 'Ett monorepo lagrar all kod i ett enda repository.', faq3q: 'Hur fungerar Turborepo-caching?', faq3a: 'Turborepo hashar indata för varje uppgift och återställer utdata från cache.', faq4q: 'Olika pakethanterare i monorepo?', faq4a: 'Nej. Alla workspaces måste använda samma pakethanterare.', faq5q: 'Miljövariabler i monorepo?', faq5a: 'Definiera variabler per app och lista dem i turbo.json globalEnv.', relatedTitle: 'Relaterade verktyg' },
  no: { title: 'Monorepo-verktøy i 2026: Turborepo, Nx og pnpm Workspaces', intro: 'Et monorepo forbedrer kodedeling, refaktorering og avhengighetsstyring.', turboTitle: 'Turborepo: oppsett og struktur', turboDesc: 'Turborepo er optimert for JavaScript/TypeScript-monorepos.', turboPipelineTitle: 'Turborepo pipeline-konfigurasjon', turboPipelineDesc: 'turbo.json-pipelinen definerer hvordan oppgaver er relatert til hverandre.', nxTitle: 'Nx: oppsett og prosjektgraf', nxDesc: 'Nx tilbyr et rikere funksjonssett: kodegeneratorer, affected-kommandoer.', pnpmTitle: 'pnpm Workspaces: lettvektsapproach', pnpmDesc: 'pnpm workspaces gir innebygd monorepo-støtte uten ekstra verktøy.', remoteCacheTitle: 'Ekstern cache', remoteCacheDesc: 'Ekstern caching deler byggeartefakter mellom utviklere og CI.', changesetsTitle: 'Versjonering med Changesets', changesetsDesc: 'Changesets er standardverktøyet for versjonering og publisering i monorepos.', comparisonTitle: 'Turborepo vs Nx vs pnpm Workspaces', bestPracticesTitle: 'Beste praksis', bp1: 'Starte med pnpm workspaces + Turborepo.', bp2: 'Definere klare grenser: delte pakker i packages/, apper i apps/.', bp3: 'Bruke Changesets for versjonering.', bp4: 'Aktivere ekstern cache tidlig.', bp5: 'Holde hvert package.json eksplisitt.', faqTitle: 'Ofte stilte spørsmål', faq1q: 'Turborepo eller Nx?', faq1a: 'Turborepo er enklere for de fleste JS-prosjekter. Nx har flere funksjoner for store repos.', faq2q: 'Monorepo vs polyrepo?', faq2a: 'Et monorepo lagrer all kode i ett enkelt repository.', faq3q: 'Hvordan fungerer Turborepo-caching?', faq3a: 'Turborepo hasher input for hvert oppdrag og gjenoppretter output fra cache.', faq4q: 'Forskjellige pakkebehandlere i monorepo?', faq4a: 'Nei. Alle workspaces må bruke samme pakkebehandler.', faq5q: 'Miljøvariabler i monorepo?', faq5a: 'Definere variabler per app og liste dem i turbo.json globalEnv.', relatedTitle: 'Relaterte verktøy' },
  id: { title: 'Alat Monorepo di 2026: Turborepo, Nx, dan pnpm Workspaces', intro: 'Monorepo meningkatkan berbagi kode, refactoring, dan manajemen dependensi.', turboTitle: 'Turborepo: Setup dan Struktur', turboDesc: 'Turborepo dioptimalkan untuk monorepo JavaScript/TypeScript.', turboPipelineTitle: 'Konfigurasi Pipeline Turborepo', turboPipelineDesc: 'Pipeline turbo.json mendefinisikan bagaimana tugas-tugas saling berhubungan.', nxTitle: 'Nx: Setup dan Grafik Proyek', nxDesc: 'Nx menyediakan set fitur yang lebih kaya: generator kode, perintah affected.', pnpmTitle: 'pnpm Workspaces: Pendekatan Ringan', pnpmDesc: 'pnpm workspaces menyediakan dukungan monorepo native tanpa alat tambahan.', remoteCacheTitle: 'Cache Jarak Jauh', remoteCacheDesc: 'Remote caching berbagi artefak build antara developer dan CI.', changesetsTitle: 'Versioning dengan Changesets', changesetsDesc: 'Changesets adalah alat standar untuk versioning dan penerbitan dalam monorepo.', comparisonTitle: 'Turborepo vs Nx vs pnpm Workspaces', bestPracticesTitle: 'Praktik Terbaik', bp1: 'Mulai dengan pnpm workspaces + Turborepo.', bp2: 'Definisikan batas yang jelas: paket bersama di packages/, apps di apps/.', bp3: 'Gunakan Changesets untuk versioning.', bp4: 'Aktifkan remote cache lebih awal.', bp5: 'Jaga setiap package.json agar eksplisit.', faqTitle: 'FAQ', faq1q: 'Turborepo atau Nx?', faq1a: 'Turborepo lebih sederhana untuk kebanyakan proyek JS. Nx memiliki lebih banyak fitur untuk repo besar.', faq2q: 'Monorepo vs polyrepo?', faq2a: 'Monorepo menyimpan semua kode dalam satu repositori.', faq3q: 'Bagaimana cara kerja caching Turborepo?', faq3a: 'Turborepo meng-hash input setiap tugas dan memulihkan output dari cache.', faq4q: 'Package manager berbeda dalam monorepo?', faq4a: 'Tidak. Semua workspace harus menggunakan package manager yang sama.', faq5q: 'Variabel lingkungan dalam monorepo?', faq5a: 'Tentukan variabel per app dan daftarkan di turbo.json globalEnv.', relatedTitle: 'Alat Terkait' },
  th: { title: 'เครื่องมือ Monorepo ในปี 2026: Turborepo, Nx และ pnpm Workspaces', intro: 'Monorepo ช่วยปรับปรุงการแชร์โค้ด การ refactor และการจัดการ dependencies', turboTitle: 'Turborepo: การตั้งค่าและโครงสร้าง', turboDesc: 'Turborepo ได้รับการปรับให้เหมาะสมสำหรับ JavaScript/TypeScript monorepos', turboPipelineTitle: 'การตั้งค่า Pipeline ของ Turborepo', turboPipelineDesc: 'pipeline turbo.json กำหนดความสัมพันธ์ระหว่าง tasks และ outputs ที่จะ cache', nxTitle: 'Nx: การตั้งค่าและกราฟโปรเจ็กต์', nxDesc: 'Nx มี feature set ที่หลากหลาย: code generators, คำสั่ง affected', pnpmTitle: 'pnpm Workspaces: แนวทางน้ำหนักเบา', pnpmDesc: 'pnpm workspaces รองรับ monorepo แบบ native โดยไม่ต้องใช้เครื่องมือเพิ่มเติม', remoteCacheTitle: 'Remote Cache', remoteCacheDesc: 'Remote caching แชร์ build artifacts ระหว่าง developers และ CI', changesetsTitle: 'การจัดการเวอร์ชันด้วย Changesets', changesetsDesc: 'Changesets คือเครื่องมือมาตรฐานสำหรับการจัดการเวอร์ชันและการเผยแพร่ใน monorepo', comparisonTitle: 'Turborepo vs Nx vs pnpm Workspaces', bestPracticesTitle: 'แนวปฏิบัติที่ดีที่สุด', bp1: 'เริ่มต้นด้วย pnpm workspaces + Turborepo', bp2: 'กำหนดขอบเขตที่ชัดเจน: shared packages ใน packages/, apps ใน apps/', bp3: 'ใช้ Changesets สำหรับการจัดการเวอร์ชัน', bp4: 'เปิดใช้งาน remote cache ตั้งแต่เนิ่นๆ', bp5: 'รักษา package.json ของแต่ละ package ให้ชัดเจน', faqTitle: 'คำถามที่พบบ่อย', faq1q: 'ควรใช้ Turborepo หรือ Nx?', faq1a: 'Turborepo ง่ายกว่าสำหรับโปรเจ็กต์ JS ส่วนใหญ่ Nx มี features มากกว่าสำหรับ repo ขนาดใหญ่', faq2q: 'Monorepo กับ polyrepo ต่างกันอย่างไร?', faq2a: 'Monorepo เก็บโค้ดทั้งหมดในที่เก็บเดียว', faq3q: 'Turborepo caching ทำงานอย่างไร?', faq3a: 'Turborepo hash input ของแต่ละ task และคืนค่า output จาก cache', faq4q: 'สามารถใช้ package manager ต่างกันใน monorepo ได้ไหม?', faq4a: 'ไม่ได้ ทุก workspace ต้องใช้ package manager เดียวกัน', faq5q: 'จะจัดการ environment variables ใน monorepo อย่างไร?', faq5a: 'กำหนด variables ต่อ app และแสดงรายการใน turbo.json globalEnv', relatedTitle: 'เครื่องมือที่เกี่ยวข้อง' },
};

export default function MonorepoTools2026({ lang }: { lang: string }) {
  const t = translations[lang] || translations.en;

  const faqSchema = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: [
      { '@type': 'Question', name: t.faq1q, acceptedAnswer: { '@type': 'Answer', text: t.faq1a } },
      { '@type': 'Question', name: t.faq2q, acceptedAnswer: { '@type': 'Answer', text: t.faq2a } },
      { '@type': 'Question', name: t.faq3q, acceptedAnswer: { '@type': 'Answer', text: t.faq3a } },
      { '@type': 'Question', name: t.faq4q, acceptedAnswer: { '@type': 'Answer', text: t.faq4a } },
      { '@type': 'Question', name: t.faq5q, acceptedAnswer: { '@type': 'Answer', text: t.faq5a } },
    ],
  };

  const compRows = [
    { feature: 'Setup complexity', turbo: 'Low', nx: 'Medium', pnpm: 'Very Low' },
    { feature: 'Task caching', turbo: 'Built-in', nx: 'Built-in', pnpm: 'Manual/external' },
    { feature: 'Remote cache', turbo: 'Vercel (free tier)', nx: 'Nx Cloud (paid)', pnpm: 'None built-in' },
    { feature: 'Code generators', turbo: 'No', nx: 'Yes (rich)', pnpm: 'No' },
    { feature: 'Affected detection', turbo: 'Basic (--filter)', nx: 'Advanced (nx affected)', pnpm: 'Via Changesets' },
    { feature: 'Language support', turbo: 'JS/TS focused', nx: 'Polyglot', pnpm: 'Any' },
    { feature: 'Learning curve', turbo: 'Low', nx: 'Medium-High', pnpm: 'Low' },
  ];

  const preStyle: React.CSSProperties = { background: '#1e1e1e', color: '#d4d4d4', padding: '1.25rem', borderRadius: '8px', overflowX: 'auto', fontSize: '0.875rem', lineHeight: '1.6' };

  return (
    <article style={{ maxWidth: 'none' }}>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />

      <p style={{ fontSize: '1.1rem', lineHeight: '1.8', marginBottom: '2rem' }}>{t.intro}</p>

      <h2>{t.turboTitle}</h2>
      <p>{t.turboDesc}</p>
      <pre style={preStyle}><code>{codeTurboSetup}</code></pre>

      <h2 style={{ marginTop: '2.5rem' }}>{t.turboPipelineTitle}</h2>
      <p>{t.turboPipelineDesc}</p>
      <pre style={preStyle}><code>{codeTurboJson}</code></pre>

      <h2 style={{ marginTop: '2.5rem' }}>{t.nxTitle}</h2>
      <p>{t.nxDesc}</p>
      <pre style={preStyle}><code>{codeNxSetup}</code></pre>

      <h2 style={{ marginTop: '2.5rem' }}>{t.pnpmTitle}</h2>
      <p>{t.pnpmDesc}</p>
      <pre style={preStyle}><code>{codePnpmWorkspaces}</code></pre>

      <h2 style={{ marginTop: '2.5rem' }}>{t.remoteCacheTitle}</h2>
      <p>{t.remoteCacheDesc}</p>
      <pre style={preStyle}><code>{codeRemoteCache}</code></pre>

      <h2 style={{ marginTop: '2.5rem' }}>{t.changesetsTitle}</h2>
      <p>{t.changesetsDesc}</p>
      <pre style={preStyle}><code>{codeChangesets}</code></pre>

      <h2 style={{ marginTop: '2.5rem' }}>{t.comparisonTitle}</h2>
      <div style={{ overflowX: 'auto', marginTop: '1rem' }}>
        <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.85rem' }}>
          <thead>
            <tr style={{ background: '#f8f9fa' }}>
              {['Feature', 'Turborepo', 'Nx', 'pnpm Workspaces'].map(h => (
                <th key={h} style={{ padding: '0.75rem', textAlign: 'left', border: '1px solid #dee2e6' }}>{h}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {compRows.map((row, i) => (
              <tr key={i} style={{ background: i % 2 === 0 ? '#fff' : '#f8f9fa' }}>
                <td style={{ padding: '0.75rem', border: '1px solid #dee2e6', fontWeight: 500 }}>{row.feature}</td>
                <td style={{ padding: '0.75rem', border: '1px solid #dee2e6' }}>{row.turbo}</td>
                <td style={{ padding: '0.75rem', border: '1px solid #dee2e6' }}>{row.nx}</td>
                <td style={{ padding: '0.75rem', border: '1px solid #dee2e6' }}>{row.pnpm}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <h2 style={{ marginTop: '2.5rem' }}>{t.bestPracticesTitle}</h2>
      <ul style={{ lineHeight: '2', paddingLeft: '1.5rem' }}>
        <li>{t.bp1}</li>
        <li>{t.bp2}</li>
        <li>{t.bp3}</li>
        <li>{t.bp4}</li>
        <li>{t.bp5}</li>
      </ul>

      <h2 style={{ marginTop: '2.5rem' }}>{t.faqTitle}</h2>
      {[[t.faq1q, t.faq1a],[t.faq2q, t.faq2a],[t.faq3q, t.faq3a],[t.faq4q, t.faq4a],[t.faq5q, t.faq5a]].map(([q, a], i) => (
        <div key={i} style={{ marginBottom: '1.5rem', padding: '1rem', background: '#f8f9fa', borderRadius: '8px', borderLeft: '4px solid #48bb78' }}>
          <h3 style={{ margin: '0 0 0.5rem', fontSize: '1rem' }}>{q}</h3>
          <p style={{ margin: 0, color: '#4a5568' }}>{a}</p>
        </div>
      ))}

      <div style={{ marginTop: '3rem', padding: '1.5rem', background: '#f0f4f8', borderRadius: '8px' }}>
        <h2 style={{ marginTop: 0 }}>{t.relatedTitle}</h2>
        <ul style={{ paddingLeft: '1.25rem', lineHeight: '2' }}>
          <li><a href="/en/tools/json-formatter" style={{ color: '#3182ce' }}>JSON Formatter</a></li>
          <li><a href="/en/tools/cron-parser" style={{ color: '#3182ce' }}>Cron Parser</a></li>
          <li><a href="/en/tools/uuid-generator" style={{ color: '#3182ce' }}>UUID Generator</a></li>
        </ul>
      </div>
    </article>
  );
}
