import Link from 'next/link';

const translations: Record<string, Record<string, string | string[]>> = {
  en: {
    title: 'Strong Password Generator: A Complete Guide to Secure Passwords',
    intro: 'In an era of increasing cyber threats, creating strong, unique passwords is your first line of defense. A strong password generator is an essential tool that creates cryptographically secure passwords that are nearly impossible to crack. This guide explains why you need strong passwords, how to use a password generator effectively, and best practices for managing your credentials securely.',
    h2_why: 'Why You Need a Strong Password Generator',
    whyDesc1: 'The average person has over 100 online accounts, and weak passwords are responsible for 81% of hacking-related breaches. Human-created passwords tend to follow predictable patterns — birthdays, pet names, and simple sequences like "123456" or "password" top the lists of most commonly cracked passwords.',
    whyDesc2: 'A strong password generator eliminates human predictability by creating truly random combinations of characters. These tools use cryptographically secure random number generators (CSPRNGs) to ensure each password is unique and resistant to both brute-force attacks and dictionary attacks.',
    whyStatsTitle: 'The Cost of Weak Passwords:',
    stat1: '81% of data breaches involve weak or stolen passwords',
    stat2: '23 million accounts use "123456" as their password',
    stat3: 'Average time to crack an 8-character password: less than 1 day',
    stat4: 'Average time to crack a 16-character random password: trillions of years',
    h2_characteristics: 'Characteristics of a Strong Password',
    charDesc: 'A truly strong password should have the following characteristics:',
    char1: 'Length: At least 12-16 characters (longer is better)',
    char2: 'Complexity: Mix of uppercase, lowercase, numbers, and special characters',
    char3: 'Unpredictability: No dictionary words, names, or personal information',
    char4: 'Uniqueness: Different for every account you own',
    char5: 'Randomness: Generated by a secure random process, not by a human',
    h2_howToUse: 'How to Use a Strong Password Generator',
    howDesc: 'Using a password generator is straightforward, but there are best practices to follow:',
    step1Title: 'Choose the Right Length',
    step1Desc: 'For most accounts, 16 characters provides an excellent balance of security and usability. For high-security accounts (banking, email), use 20+ characters.',
    step2Title: 'Include All Character Types',
    step2Desc: 'Enable uppercase letters, lowercase letters, numbers, and special characters. Some systems have limitations on special characters, so check the requirements first.',
    step3Title: 'Avoid Ambiguous Characters',
    step3Desc: 'Some generators offer to exclude ambiguous characters like O/0 (letter O vs zero), I/l/1 (capital i, lowercase L, one), which can be confused when typing manually.',
    step4Title: 'Copy and Save Immediately',
    step4Desc: 'Generated passwords are random and hard to memorize. Copy the password directly into a password manager rather than trying to remember it.',
    h2_bestPractices: 'Password Security Best Practices',
    bp1Title: 'Use a Password Manager',
    bp1Desc: 'Password managers like Bitwarden, 1Password, or KeePassXC can generate, store, and autofill strong passwords for all your accounts. You only need to remember one master password.',
    bp2Title: 'Enable Two-Factor Authentication (2FA)',
    bp2Desc: 'Even the strongest password can be compromised. 2FA adds an additional layer of security by requiring a second verification method.',
    bp3Title: 'Never Reuse Passwords',
    bp3Desc: 'If one service is breached and your password is leaked, attackers will try that same password on other services. Each account needs a unique password.',
    bp4Title: 'Change Passwords After a Breach',
    bp4Desc: 'Use services like Have I Been Pwned to check if your accounts have been compromised. Change passwords immediately if a breach is detected.',
    bp5Title: 'Avoid Common Patterns',
    bp5Desc: 'Even generated passwords should avoid simple patterns like "aaaa", "1234", or keyboard walks like "qwerty" or "asdfgh".',
    h2_memorable: 'Creating Memorable Yet Strong Passwords',
    memorableDesc: 'For passwords you must remember (like your password manager master password), use the passphrase method instead of random characters:',
    passphraseMethod: 'Passphrase Method:',
    pass1: 'Choose 4-6 random, unrelated words',
    pass2: 'Add numbers and special characters between words',
    pass3: 'Use word separation with spaces or symbols',
    passphraseExample: 'Example: "Correct Horse Battery Staple!47" or "Dragon7-Table-Mountain-Piano$"',
    passphraseEntropy: 'A 4-word passphrase can provide 50+ bits of entropy, making it both memorable and secure.',
    h2_faq: 'Frequently Asked Questions',
    faq1q: 'How long should a strong password be?',
    faq1a: 'For standard accounts, 12-16 characters is the minimum recommended length. For sensitive accounts like banking or primary email, use 20+ characters. Each additional character exponentially increases cracking time.',
    faq2q: 'Are password generators safe to use?',
    faq2a: 'Reputable password generators that run locally in your browser (like ours) are safe — they do not transmit data to servers. Avoid online generators that require you to submit passwords over the internet.',
    faq3q: 'Should I change my passwords regularly?',
    faq3a: 'Modern security guidance no longer recommends arbitrary password changes. Only change passwords when: there is evidence of a breach, you shared the password, or you suspect compromise.',
    faq4q: 'Can strong passwords be cracked?',
    faq4a: 'A truly random 16-character password using all character types would take trillions of years to crack with current technology. However, if a service stores passwords insecurely (e.g., plain text), any password can be compromised.',
    faq5q: 'What is the difference between a password and a passphrase?',
    faq5a: 'A password is typically a short string of random characters. A passphrase is a longer sequence of words. Passphrases can be easier to remember while providing equivalent or better security due to their length.',
    conclusion: 'A strong password generator is an essential tool in your cybersecurity arsenal. By creating long, random, unique passwords for every account and using a password manager to store them, you significantly reduce your risk of becoming a victim of credential-based attacks.',
    ctaText: 'Generate secure passwords instantly',
    ctaButton: 'Try Our Strong Password Generator →',
  },
  zh: {
    title: '强密码生成器：安全密码完全指南',
    intro: '在网络威胁日益增加的时代，创建强大且独特的密码是您的第一道防线。强密码生成器是一个必不可少的工具，它能创建几乎无法破解的加密安全密码。本指南解释为什么您需要强密码、如何有效使用密码生成器，以及安全管理凭据的最佳实践。',
    h2_why: '为什么您需要强密码生成器',
    whyDesc1: '普通人拥有超过 100 个在线账户，而弱密码导致了 81% 与黑客相关的数据泄露。人类创建的密码往往遵循可预测的模式 —— 生日、宠物名字，以及像"123456"或"password"这样的简单序列是最常被破解的密码。',
    whyDesc2: '强密码生成器通过创建真正随机的字符组合来消除人类的可预测性。这些工具使用加密安全的随机数生成器（CSPRNG）来确保每个密码都是唯一的，并且能够抵抗暴力破解攻击和字典攻击。',
    whyStatsTitle: '弱密码的代价：',
    stat1: '81% 的数据泄露涉及弱密码或被盗密码',
    stat2: '2300 万个账户使用"123456"作为密码',
    stat3: '破解8字符密码的平均时间：不到1天',
    stat4: '破解16字符随机密码的平均时间：数万亿年',
    h2_characteristics: '强密码的特征',
    charDesc: '一个真正强大的密码应该具有以下特征：',
    char1: '长度：至少12-16个字符（越长越好）',
    char2: '复杂度：混合使用大写字母、小写字母、数字和特殊字符',
    char3: '不可预测性：不包含字典单词、姓名或个人信息',
    char4: '独特性：每个账户使用不同的密码',
    char5: '随机性：由安全的随机过程生成，而非人工创建',
    h2_howToUse: '如何使用强密码生成器',
    howDesc: '使用密码生成器很简单，但有一些最佳实践需要遵循：',
    step1Title: '选择合适的长度',
    step1Desc: '对于大多数账户，16个字符在安全性和可用性之间提供了很好的平衡。对于高安全账户（银行、邮箱），使用20个以上字符。',
    step2Title: '包含所有字符类型',
    step2Desc: '启用大写字母、小写字母、数字和特殊字符。某些系统对特殊字符有限制，因此请先检查要求。',
    step3Title: '避免易混淆字符',
    step3Desc: '某些生成器提供排除易混淆字符的选项，如 O/0（字母O与数字零）、I/l/1（大写i、小写L、数字一），这些在手动输入时可能会混淆。',
    step4Title: '立即复制并保存',
    step4Desc: '生成的密码是随机的，难以记忆。直接将密码复制到密码管理器中，而不是试图记住它。',
    h2_bestPractices: '密码安全最佳实践',
    bp1Title: '使用密码管理器',
    bp1Desc: '像 Bitwarden、1Password 或 KeePassXC 这样的密码管理器可以为您的所有账户生成、存储和自动填充强密码。您只需要记住一个主密码。',
    bp2Title: '启用双因素认证（2FA）',
    bp2Desc: '即使最强的密码也可能被泄露。2FA 通过要求第二种验证方法增加了额外的安全层。',
    bp3Title: '永远不要重复使用密码',
    bp3Desc: '如果一个服务被攻破且您的密码泄露，攻击者会在其他服务上尝试相同的密码。每个账户都需要唯一的密码。',
    bp4Title: '在泄露后更改密码',
    bp4Desc: '使用 Have I Been Pwned 等服务检查您的账户是否已被泄露。如果检测到泄露，立即更改密码。',
    bp5Title: '避免常见模式',
    bp5Desc: '即使是生成的密码也应该避免简单的模式，如"aaaa"、"1234"，或键盘行走如"qwerty"或"asdfgh"。',
    h2_memorable: '创建既易记又强大的密码',
    memorableDesc: '对于您必须记住的密码（如密码管理器的主密码），使用密码短语方法而不是随机字符：',
    passphraseMethod: '密码短语方法：',
    pass1: '选择4-6个随机的、不相关的单词',
    pass2: '在单词之间添加数字和特殊字符',
    pass3: '使用空格或符号分隔单词',
    passphraseExample: '示例："Correct Horse Battery Staple!47" 或 "Dragon7-Table-Mountain-Piano$"',
    passphraseEntropy: '一个4单词的密码短语可以提供50+位的熵，使其既易记又安全。',
    h2_faq: '常见问题',
    faq1q: '强密码应该多长？',
    faq1a: '对于标准账户，建议的最小长度为12-16个字符。对于银行或主邮箱等敏感账户，使用20个以上字符。每增加一个字符都会指数级增加破解时间。',
    faq2q: '密码生成器使用起来安全吗？',
    faq2a: '在浏览器中本地运行的信誉良好的密码生成器（如我们的）是安全的 —— 它们不会将数据传输到服务器。避免需要您通过互联网提交密码的在线生成器。',
    faq3q: '我应该定期更改密码吗？',
    faq3a: '现代安全指南不再推荐任意更改密码。只在以下情况下更改密码：有泄露证据、您分享了密码，或您怀疑被泄露。',
    faq4q: '强密码可以被破解吗？',
    faq4a: '一个真正随机的16字符密码使用所有字符类型，用当前技术破解需要数万亿年。但是，如果服务不安全地存储密码（如明文），任何密码都可能被泄露。',
    faq5q: '密码和密码短语有什么区别？',
    faq5a: '密码通常是随机字符的短字符串。密码短语是较长的单词序列。由于其长度，密码短语可能更容易记忆，同时提供相当或更好的安全性。',
    conclusion: '强密码生成器是您的网络安全工具库中必不可少的工具。通过为每个账户创建长、随机、唯一的密码，并使用密码管理器存储它们，您可以显著降低成为基于凭证攻击受害者的风险。',
    ctaText: '立即生成安全密码',
    ctaButton: '立即试用我们的强密码生成器 →',
  },
};

const h2Style: React.CSSProperties = { 
  fontSize: 22, 
  fontWeight: 700, 
  marginTop: 40, 
  marginBottom: 16, 
  color: 'var(--text-primary)' 
};

const h3Style: React.CSSProperties = { 
  fontSize: 18, 
  fontWeight: 600, 
  marginTop: 24, 
  marginBottom: 12, 
  color: 'var(--text-primary)' 
};

export default function PasswordGeneratorGuide({ lang }: { lang: string }) {
  const t = translations[lang] || translations['en'];

  const faqSchema = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: [
      { '@type': 'Question', name: t.faq1q, acceptedAnswer: { '@type': 'Answer', text: t.faq1a } },
      { '@type': 'Question', name: t.faq2q, acceptedAnswer: { '@type': 'Answer', text: t.faq2a } },
      { '@type': 'Question', name: t.faq3q, acceptedAnswer: { '@type': 'Answer', text: t.faq3a } },
      { '@type': 'Question', name: t.faq4q, acceptedAnswer: { '@type': 'Answer', text: t.faq4a } },
      { '@type': 'Question', name: t.faq5q, acceptedAnswer: { '@type': 'Answer', text: t.faq5a } },
    ],
  };

  return (
    <div>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />

      <p style={{ fontSize: 16, lineHeight: 1.8, color: 'var(--text-secondary)', marginBottom: 30 }}>{t.intro}</p>

      <h2 style={h2Style}>{t.h2_why}</h2>
      <p style={{ lineHeight: 1.8, color: 'var(--text-secondary)', marginBottom: 16 }}>{t.whyDesc1}</p>
      <p style={{ lineHeight: 1.8, color: 'var(--text-secondary)', marginBottom: 16 }}>{t.whyDesc2}</p>
      
      <div style={{ padding: 16, background: 'rgba(239, 68, 68, 0.08)', borderRadius: 8, border: '1px solid rgba(239, 68, 68, 0.2)', marginBottom: 24 }}>
        <p style={{ fontWeight: 600, marginBottom: 12, color: 'var(--text-primary)' }}>{t.whyStatsTitle}</p>
        <ul style={{ lineHeight: 2, color: 'var(--text-secondary)', paddingLeft: 20, margin: 0 }}>
          <li>{t.stat1}</li>
          <li>{t.stat2}</li>
          <li>{t.stat3}</li>
          <li>{t.stat4}</li>
        </ul>
      </div>

      <h2 style={h2Style}>{t.h2_characteristics}</h2>
      <p style={{ lineHeight: 1.8, color: 'var(--text-secondary)', marginBottom: 16 }}>{t.charDesc}</p>
      <ul style={{ lineHeight: 2.2, color: 'var(--text-secondary)', paddingLeft: 20, marginBottom: 24 }}>
        <li>{t.char1}</li>
        <li>{t.char2}</li>
        <li>{t.char3}</li>
        <li>{t.char4}</li>
        <li>{t.char5}</li>
      </ul>

      <h2 style={h2Style}>{t.h2_howToUse}</h2>
      <p style={{ lineHeight: 1.8, color: 'var(--text-secondary)', marginBottom: 16 }}>{t.howDesc}</p>
      
      <div style={{ display: 'flex', flexDirection: 'column', gap: 16, marginBottom: 24 }}>
        {[
          { title: t.step1Title, desc: t.step1Desc },
          { title: t.step2Title, desc: t.step2Desc },
          { title: t.step3Title, desc: t.step3Desc },
          { title: t.step4Title, desc: t.step4Desc },
        ].map((step, i) => (
          <div key={i} style={{ padding: 16, background: 'var(--bg-input)', borderRadius: 8, border: '1px solid var(--border-color)', borderLeft: '4px solid var(--accent-blue)' }}>
            <h3 style={{ fontSize: 15, fontWeight: 700, marginBottom: 6, color: 'var(--accent-blue)' }}>{step.title}</h3>
            <p style={{ fontSize: 14, color: 'var(--text-secondary)', lineHeight: 1.6, margin: 0 }}>{step.desc}</p>
          </div>
        ))}
      </div>

      <div style={{ padding: 20, background: 'linear-gradient(135deg, rgba(59,130,246,0.1), rgba(139,92,246,0.1))', borderRadius: 12, border: '1px solid rgba(59,130,246,0.3)', textAlign: 'center', marginBottom: 30 }}>
        <p style={{ fontSize: 16, fontWeight: 600, marginBottom: 12 }}>{t.ctaText}</p>
        <Link href={`/${lang}/tools/password-generator`} style={{ color: 'var(--accent-blue)', fontWeight: 700, fontSize: 15 }}>
          {t.ctaButton}
        </Link>
      </div>

      <h2 style={h2Style}>{t.h2_bestPractices}</h2>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 16, marginBottom: 24 }}>
        {[
          { title: t.bp1Title, desc: t.bp1Desc },
          { title: t.bp2Title, desc: t.bp2Desc },
          { title: t.bp3Title, desc: t.bp3Desc },
          { title: t.bp4Title, desc: t.bp4Desc },
          { title: t.bp5Title, desc: t.bp5Desc },
        ].map((bp, i) => (
          <div key={i} style={{ padding: 16, background: 'var(--bg-input)', borderRadius: 8, border: '1px solid var(--border-color)' }}>
            <h3 style={{ fontSize: 15, fontWeight: 700, marginBottom: 6, color: 'var(--text-primary)' }}>{bp.title}</h3>
            <p style={{ fontSize: 14, color: 'var(--text-secondary)', lineHeight: 1.6, margin: 0 }}>{bp.desc}</p>
          </div>
        ))}
      </div>

      <h2 style={h2Style}>{t.h2_memorable}</h2>
      <p style={{ lineHeight: 1.8, color: 'var(--text-secondary)', marginBottom: 16 }}>{t.memorableDesc}</p>
      
      <div style={{ padding: 16, background: 'rgba(34, 197, 94, 0.08)', borderRadius: 8, border: '1px solid rgba(34, 197, 94, 0.2)', marginBottom: 16 }}>
        <p style={{ fontWeight: 600, marginBottom: 12, color: 'var(--text-primary)' }}>{t.passphraseMethod}</p>
        <ol style={{ lineHeight: 2, color: 'var(--text-secondary)', paddingLeft: 20, margin: 0 }}>
          <li>{t.pass1}</li>
          <li>{t.pass2}</li>
          <li>{t.pass3}</li>
        </ol>
      </div>
      
      <p style={{ lineHeight: 1.8, color: 'var(--text-secondary)', marginBottom: 8 }}>{t.passphraseExample}</p>
      <p style={{ lineHeight: 1.8, color: 'var(--text-secondary)', marginBottom: 24 }}>{t.passphraseEntropy}</p>

      <h2 style={h2Style}>{t.h2_faq}</h2>
      {[
        [t.faq1q, t.faq1a], [t.faq2q, t.faq2a], [t.faq3q, t.faq3a], [t.faq4q, t.faq4a], [t.faq5q, t.faq5a],
      ].map(([q, a], i) => (
        <div key={i} style={{ marginBottom: 16, padding: 16, background: 'var(--bg-input)', borderRadius: 8, border: '1px solid var(--border-color)' }}>
          <h3 style={{ fontSize: 15, fontWeight: 700, marginBottom: 8, color: 'var(--text-primary)' }}>{q}</h3>
          <p style={{ fontSize: 14, color: 'var(--text-secondary)', lineHeight: 1.7, margin: 0 }}>{a}</p>
        </div>
      ))}

      <p style={{ fontSize: 16, lineHeight: 1.8, color: 'var(--text-secondary)', marginTop: 30 }}>{t.conclusion}</p>
    </div>
  );
}
