'use client';

import React from 'react';

const translations: Record<string, Record<string, string>> = {
  en: {
    title: 'Resend vs Postmark: Transactional Email Service Comparison',
    intro: 'Resend and Postmark are both popular transactional email services, but they target different audiences. Resend is a modern, developer-focused platform with excellent React Email integration, while Postmark emphasizes reliability and deliverability with over a decade of experience. This comparison helps you choose the right email service for your application.',
    
    tldrTitle: 'TL;DR - Quick Summary',
    tldrContent: 'Choose Resend for modern developer experience, React Email integration, and competitive pricing. Choose Postmark for maximum deliverability, 15+ years of reliability, and comprehensive analytics. For startups and React developers, Resend offers the best DX. For enterprises prioritizing email delivery rates, Postmark is proven.',
    
    takeawaysTitle: 'Key Takeaways',
    takeaway1: 'Resend offers modern API with React Email native support',
    takeaway2: 'Postmark has 15+ years of deliverability expertise',
    takeaway3: 'Resend pricing is more competitive for high volumes',
    takeaway4: 'Postmark includes inbound email processing',
    takeaway5: 'Both offer excellent deliverability (99%+)',
    takeaway6: 'Resend has superior developer documentation and DX',
    
    whatIsResendTitle: 'What is Resend?',
    whatIsResendContent: 'Resend is a modern email API designed for developers, launched in 2023 by the creators of React Email. It focuses on simplicity and developer experience with a clean API, beautiful email templates using React components, and straightforward pricing. Resend integrates seamlessly with Next.js, Vercel, and modern development workflows.',
    
    whatIsPostmarkTitle: 'What is Postmark?',
    whatIsPostmarkContent: 'Postmark, founded in 2009, is a transactional email service known for exceptional deliverability and reliability. Used by companies like Basecamp and Kickstarter, Postmark processes billions of emails monthly. It offers robust analytics, inbound email parsing, and a proven track record of email delivery expertise.',
    
    pricingTitle: 'Pricing Comparison',
    pricingIntro: 'Understanding the cost structure:',
    
    featuresTitle: 'Feature Comparison',
    featuresIntro: 'Comparing core capabilities:',
    
    deliverabilityTitle: 'Deliverability & Reputation',
    deliverabilityIntro: 'Email delivery performance:',
    
    developerTitle: 'Developer Experience',
    developerIntro: 'API and integration quality:',
    
    templatesTitle: 'Email Templates',
    templatesIntro: 'Template management options:',
    
    whenToUseTitle: 'When to Use Each Service',
    resendBestFor: 'Use Resend When:',
    postmarkBestFor: 'Use Postmark When:',
    
    conclusionTitle: 'Conclusion',
    conclusionContent: 'In 2025, both Resend and Postmark are excellent choices for transactional email. Resend is ideal for modern development teams, especially those using React and Next.js, who value developer experience and clean APIs. Postmark remains the choice for businesses prioritizing proven deliverability and those needing inbound email processing. Many developers start with Resend for its DX and switch to Postmark as deliverability becomes critical at scale.',
    
    faq1q: 'Is Resend reliable for production use?',
    faq1a: 'Yes, Resend is production-ready and used by companies like Vercel, Clerk, and Raycast. While newer than Postmark, it maintains excellent uptime and deliverability through partnerships with established email providers.',
    
    faq2q: 'Does Postmark support React Email?',
    faq2a: 'Postmark supports any HTML email, including those generated by React Email. However, Resend has native React Email integration with server components support, making the DX smoother.',
    
    faq3q: 'Which has better deliverability?',
    faq3a: 'Both achieve 99%+ deliverability. Postmark has a longer track record and dedicated deliverability team. Resend achieves similar rates through its infrastructure partners. For most applications, deliverability differences are negligible.',
    
    faq4q: 'Can I use both services together?',
    faq4a: 'Yes, some companies use Resend for marketing emails and Postmark for critical transactional emails. This diversifies risk and allows using each services strengths.',
    
    faq5q: 'Does Resend support inbound email?',
    faq5a: 'Not yet. Resend focuses on outbound email only. Postmark offers inbound email parsing, which is useful for handling replies, support tickets, and automated workflows.',
    
    faq6q: 'Which has better free tier?',
    faq6a: 'Resend offers 3,000 emails/month free. Postmark offers 100 emails/month free with a $15 trial credit. For testing and small projects, Resend free tier is more generous.',
    
    faq7q: 'How is customer support?',
    faq7a: 'Postmark offers email and chat support on all plans with responsive service. Resend provides email support, with priority support on paid plans. Both have excellent documentation.',
    
    faq8q: 'Which integrates better with Next.js?',
    faq8a: 'Resend has first-class Next.js integration with server actions support, React Email components, and Vercel marketplace integration. Postmark works well but requires more setup.',
    
    tryTools: 'Try Our Related Tools',
  },
  zh: {
    title: 'Resend vs Postmark：事务性邮件服务对比',
    intro: 'Resend和Postmark都是流行的事务性邮件服务，但针对不同的受众。Resend是一个现代的、面向开发者的平台，具有出色的React Email集成，而Postmark凭借十多年的经验强调可靠性和送达率。本比较帮助你为应用选择合适的邮件服务。',
    
    tldrTitle: 'TL;DR - 快速总结',
    tldrContent: '如果你想要现代的开发者体验、React Email集成和有竞争力的定价，选择Resend。如果你优先考虑最高送达率、15年以上的可靠性和全面的分析，选择Postmark。对于初创公司和React开发者，Resend提供最佳DX。对于优先考虑邮件送达率的企业，Postmark经过验证。',
    
    takeawaysTitle: '核心要点',
    takeaway1: 'Resend提供现代API，原生支持React Email',
    takeaway2: 'Postmark拥有15年以上的送达率专业知识',
    takeaway3: 'Resend在大额交易量下定价更有竞争力',
    takeaway4: 'Postmark包含入站邮件处理',
    takeaway5: '两者都提供出色的送达率(99%+)',
    takeaway6: 'Resend拥有更优的开发者文档和DX',
    
    whatIsResendTitle: '什么是Resend？',
    whatIsResendContent: 'Resend是由React Email创建者于2023年推出的现代邮件API，专为开发者设计。它专注于简单性和开发者体验，提供干净的API、使用React组件的精美邮件模板和简单的定价。Resend与Next.js、Vercel和现代开发工作流程无缝集成。',
    
    whatIsPostmarkTitle: '什么是Postmark？',
    whatIsPostmarkContent: 'Postmark成立于2009年，是一家以卓越送达率和可靠性著称的事务性邮件服务。被Basecamp和Kickstarter等公司使用，Postmark每月处理数十亿封邮件。它提供强大的分析、入站邮件解析和经过验证的邮件送达专业知识。',
    
    pricingTitle: '定价对比',
    pricingIntro: '了解成本结构：',
    
    featuresTitle: '功能对比',
    featuresIntro: '比较核心能力：',
    
    deliverabilityTitle: '送达率与声誉',
    deliverabilityIntro: '邮件送达性能：',
    
    developerTitle: '开发者体验',
    developerIntro: 'API和集成质量：',
    
    templatesTitle: '邮件模板',
    templatesIntro: '模板管理选项：',
    
    whenToUseTitle: '何时使用每个服务',
    resendBestFor: '使用Resend的场景：',
    postmarkBestFor: '使用Postmark的场景：',
    
    conclusionTitle: '结论',
    conclusionContent: '在2025年，Resend和Postmark都是事务性邮件的优秀选择。Resend非常适合现代开发团队，特别是那些使用React和Next.js的团队，他们重视开发者体验和干净的API。Postmark仍然是优先考虑经过验证的送达率和需要入站邮件处理的企业的选择。许多开发者从Resend开始以获得其DX，随着规模扩大送达率变得关键时转向Postmark。',
    
    faq1q: 'Resend可用于生产环境吗？',
    faq1a: '可以，Resend已准备好用于生产，被Vercel、Clerk和Raycast等公司使用。虽然比Postmark新，但它通过与成熟的邮件提供商的合作关系保持了出色的正常运行时间和送达率。',
    
    faq2q: 'Postmark支持React Email吗？',
    faq2a: 'Postmark支持任何HTML邮件，包括由React Email生成的邮件。然而，Resend具有原生React Email集成和服务器组件支持，使DX更流畅。',
    
    faq3q: '哪个送达率更好？',
    faq3a: '两者都达到99%+送达率。Postmark有更长的记录和专门的送达率团队。Resend通过其基础设施合作伙伴实现类似比率。对于大多数应用，送达率差异可以忽略不计。',
    
    faq4q: '我可以同时使用两个服务吗？',
    faq4a: '可以，一些公司使用Resend发送营销邮件，Postmark发送关键事务性邮件。这分散了风险，并允许利用每个服务的优势。',
    
    faq5q: 'Resend支持入站邮件吗？',
    faq5a: '暂不支持。Resend专注于出站邮件。Postmark提供入站邮件解析，这对于处理回复、支持工单和自动化工作流程很有用。',
    
    faq6q: '哪个免费层更好？',
    faq6a: 'Resend提供每月3,000封邮件免费。Postmark提供每月100封邮件免费和15美元试用额度。对于测试和小型项目，Resend免费层更慷慨。',
    
    faq7q: '客户支持如何？',
    faq7a: 'Postmark在所有计划上提供邮件和聊天支持，响应迅速。Resend提供邮件支持，付费计划有优先支持。两者都有出色的文档。',
    
    faq8q: '哪个与Next.js集成更好？',
    faq8a: 'Resend具有一流的Next.js集成，支持服务器操作、React Email组件和Vercel市场集成。Postmark运作良好但需要更多设置。',
    
    tryTools: '试试我们的相关工具',
  },
};

export default function ResendVsPostmark({ lang }: { lang: string }) {
  const ct = translations[lang] || translations['en'];
  const isZh = lang === 'zh';

  const faqSchema = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: [
      { '@type': 'Question', name: ct.faq1q, acceptedAnswer: { '@type': 'Answer', text: ct.faq1a } },
      { '@type': 'Question', name: ct.faq2q, acceptedAnswer: { '@type': 'Answer', text: ct.faq2a } },
      { '@type': 'Question', name: ct.faq3q, acceptedAnswer: { '@type': 'Answer', text: ct.faq3a } },
      { '@type': 'Question', name: ct.faq4q, acceptedAnswer: { '@type': 'Answer', text: ct.faq4a } },
      { '@type': 'Question', name: ct.faq5q, acceptedAnswer: { '@type': 'Answer', text: ct.faq5a } },
      { '@type': 'Question', name: ct.faq6q, acceptedAnswer: { '@type': 'Answer', text: ct.faq6a } },
      { '@type': 'Question', name: ct.faq7q, acceptedAnswer: { '@type': 'Answer', text: ct.faq7a } },
      { '@type': 'Question', name: ct.faq8q, acceptedAnswer: { '@type': 'Answer', text: ct.faq8a } },
    ],
  };

  const codeStyle: React.CSSProperties = { background: 'var(--bg-input)', border: '1px solid var(--border-color)', borderRadius: 8, padding: '16px 20px', overflowX: 'auto', fontSize: 13, lineHeight: 1.8 };
  const thStyle: React.CSSProperties = { background: 'var(--bg-input)', border: '1px solid var(--border-color)', padding: '10px 14px', textAlign: 'left', fontWeight: 700 };
  const tdStyle: React.CSSProperties = { border: '1px solid var(--border-color)', padding: '10px 14px', fontSize: 13 };
  const h2Style: React.CSSProperties = { fontSize: 22, fontWeight: 700, marginTop: 40, marginBottom: 16, color: 'var(--text-primary)' };
  const h3Style: React.CSSProperties = { fontSize: 18, fontWeight: 600, marginTop: 24, marginBottom: 12, color: '#3b82f6' };
  const pStyle: React.CSSProperties = { lineHeight: 1.8, color: 'var(--text-secondary)', marginBottom: 16 };
  const boxStyle: React.CSSProperties = { padding: 20, background: 'var(--bg-input)', borderRadius: 12, border: '1px solid var(--border-color)', marginBottom: 24 };

  return (
    <div>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />

      <p style={{ fontSize: 16, lineHeight: 1.8, color: 'var(--text-secondary)', marginBottom: 30 }}>{ct.intro}</p>

      <div style={{ ...boxStyle, borderLeft: '4px solid #000', background: 'linear-gradient(135deg, rgba(0,0,0,0.1), rgba(121,189,154,0.1))' }}>
        <h3 style={{ fontSize: 18, fontWeight: 700, marginBottom: 12, color: '#000' }}>{ct.tldrTitle}</h3>
        <p style={{ lineHeight: 1.8, color: 'var(--text-secondary)', margin: 0 }}>{ct.tldrContent}</p>
      </div>

      <h2 style={h2Style}>{ct.takeawaysTitle}</h2>
      <div style={{ ...boxStyle, borderLeft: '4px solid #22c55e' }}>
        <ul style={{ lineHeight: 2, color: 'var(--text-secondary)', paddingLeft: 20, margin: 0 }}>
          <li>{ct.takeaway1}</li>
          <li>{ct.takeaway2}</li>
          <li>{ct.takeaway3}</li>
          <li>{ct.takeaway4}</li>
          <li>{ct.takeaway5}</li>
          <li>{ct.takeaway6}</li>
        </ul>
      </div>

      <h3 style={h3Style}>{ct.whatIsResendTitle}</h3>
      <p style={pStyle}>{ct.whatIsResendContent}</p>

      <h3 style={h3Style}>{ct.whatIsPostmarkTitle}</h3>
      <p style={pStyle}>{ct.whatIsPostmarkContent}</p>

      <h2 style={h2Style}>{ct.pricingTitle}</h2>
      <p style={pStyle}>{ct.pricingIntro}</p>

      <div style={{ overflowX: 'auto', marginBottom: 24 }}>
        <table style={{ width: '100%', borderCollapse: 'collapse' }}>
          <thead>
            <tr>
              <th style={thStyle}>{isZh ? '计划' : 'Plan'}</th>
              <th style={thStyle}>Resend</th>
              <th style={thStyle}>Postmark</th>
            </tr>
          </thead>
          <tbody>
            {[
              [isZh ? '免费层' : 'Free Tier', '3,000 emails/mo', '100 emails/mo + $15 trial'],
              [isZh ? '入门级' : 'Starter', '$20/mo (50K emails)', '$15/mo (15K emails)'],
              [isZh ? '专业级' : 'Pro', '$37.50/mo (100K)', '$50/mo (50K)'],
              [isZh ? '每封额外邮件' : 'Per Extra Email', '$0.80/1000', '$1.00/1000'],
              [isZh ? '包含域名' : 'Domains Included', '1', '1'],
              [isZh ? '模板数量' : 'Templates', isZh ? '无限' : 'Unlimited', isZh ? '无限' : 'Unlimited'],
              [isZh ? '附件大小' : 'Attachment Size', '40MB', '10MB'],
            ].map(([plan, resend, postmark], i) => (
              <tr key={i}>
                <td style={{ ...tdStyle, fontWeight: 600 }}>{plan}</td>
                <td style={{ ...tdStyle, color: '#000' }}>{resend}</td>
                <td style={tdStyle}>{postmark}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <h3 style={{ ...h3Style, color: '#000' }}>{isZh ? '成本示例：每月50万封邮件' : 'Cost Example: 500K Emails/Month'}</h3>
      <div style={{ overflowX: 'auto', marginBottom: 24 }}>
        <table style={{ width: '100%', borderCollapse: 'collapse' }}>
          <thead>
            <tr>
              <th style={thStyle}>{isZh ? '服务' : 'Service'}</th>
              <th style={thStyle}>{isZh ? '月成本' : 'Monthly Cost'}</th>
              <th style={thStyle}>{isZh ? '年成本' : 'Annual Cost'}</th>
            </tr>
          </thead>
          <tbody>
            {[
              ['Resend', '$370', '$4,440'],
              ['Postmark', '$515', '$6,180'],
              [isZh ? 'Resend节省' : 'Resend Savings', '$145/mo', '$1,740/yr'],
            ].map(([service, monthly, annual], i) => (
              <tr key={i}>
                <td style={{ ...tdStyle, fontWeight: 600 }}>{service}</td>
                <td style={{ ...tdStyle, color: i === 2 ? '#22c55e' : 'inherit' }}>{monthly}</td>
                <td style={{ ...tdStyle, color: i === 2 ? '#22c55e' : 'inherit' }}>{annual}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <h2 style={h2Style}>{ct.featuresTitle}</h2>
      <p style={pStyle}>{ct.featuresIntro}</p>

      <div style={{ overflowX: 'auto', marginBottom: 24 }}>
        <table style={{ width: '100%', borderCollapse: 'collapse' }}>
          <thead>
            <tr>
              <th style={thStyle}>{isZh ? '功能' : 'Feature'}</th>
              <th style={thStyle}>Resend</th>
              <th style={thStyle}>Postmark</th>
            </tr>
          </thead>
          <tbody>
            {[
              [isZh ? '入站邮件' : 'Inbound Email', isZh ? '否' : 'No', isZh ? '是' : 'Yes'],
              [isZh ? '邮件模板' : 'Email Templates', 'React Email', isZh ? 'HTML/拖放' : 'HTML/Drag-drop'],
              [isZh ? '批量发送' : 'Batch Sending', isZh ? '是' : 'Yes', isZh ? '是' : 'Yes'],
              [isZh ? '计划发送' : 'Scheduled Sending', isZh ? '是' : 'Yes', isZh ? '是' : 'Yes'],
              [isZh ? 'A/B测试' : 'A/B Testing', isZh ? '否' : 'No', isZh ? '是' : 'Yes'],
              [isZh ? '邮件分析' : 'Email Analytics', isZh ? '基本' : 'Basic', isZh ? '高级' : 'Advanced'],
              [isZh ? 'Webhook事件' : 'Webhook Events', isZh ? '是' : 'Yes', isZh ? '是' : 'Yes'],
              [isZh ? 'SMTP支持' : 'SMTP Support', isZh ? '是' : 'Yes', isZh ? '是' : 'Yes'],
              [isZh ? '团队协作' : 'Team Collaboration', isZh ? '是' : 'Yes', isZh ? '是' : 'Yes'],
              [isZh ? 'API版本' : 'API Version', 'v1 (稳定)', 'v1 (稳定)'],
            ].map(([feature, resend, postmark], i) => (
              <tr key={i}>
                <td style={{ ...tdStyle, fontWeight: 600 }}>{feature}</td>
                <td style={tdStyle}>{resend}</td>
                <td style={{ ...tdStyle, color: '#79bd9a' }}>{postmark}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <h2 style={h2Style}>{ct.deliverabilityTitle}</h2>
      <p style={pStyle}>{ct.deliverabilityIntro}</p>

      <div style={{ display: 'flex', flexDirection: 'column', gap: 12, marginBottom: 24 }}>
        <div style={{ padding: 16, background: 'var(--bg-input)', borderRadius: 8, border: '1px solid var(--border-color)', borderLeft: '4px solid #000' }}>
          <strong style={{ color: '#000' }}>Resend Deliverability</strong>
          <p style={{ margin: '6px 0 0', fontSize: 14, color: 'var(--text-secondary)', lineHeight: 1.6 }}>
            {isZh ? '通过合作伙伴基础设施实现99%+送达率。自动处理SPF、DKIM、DMARC。实时监控发件人声誉。与主要ESP保持良好关系。' : '99%+ deliverability through partner infrastructure. Automatic SPF, DKIM, DMARC handling. Real-time sender reputation monitoring. Good relationships with major ESPs.'}
          </p>
        </div>
        <div style={{ padding: 16, background: 'var(--bg-input)', borderRadius: 8, border: '1px solid var(--border-color)', borderLeft: '4px solid #79bd9a' }}>
          <strong style={{ color: '#79bd9a' }}>Postmark Deliverability</strong>
          <p style={{ margin: '6px 0 0', fontSize: 14, color: 'var(--text-secondary)', lineHeight: 1.6 }}>
            {isZh ? '15年以上送达率专业知识。专门的送达率团队。专用的发送IP选项。详细的送达率报告和建议。' : '15+ years of deliverability expertise. Dedicated deliverability team. Dedicated IP options available. Detailed deliverability reports and recommendations.'}
          </p>
        </div>
      </div>

      <h2 style={h2Style}>{ct.developerTitle}</h2>
      <p style={pStyle}>{ct.developerIntro}</p>

      <pre style={codeStyle}><code>{`// Developer Experience Comparison

// RESEND - Modern, Clean API
import Resend from "resend";

const resend = new Resend("re_xxx");

// Simple send
await resend.emails.send({
  from: "onboarding@resend.dev",
  to: "user@example.com",
  subject: "Hello World",
  html: "<strong>Welcome!</strong>"
});

// With React Email
import { WelcomeEmail } from "./emails/welcome";

await resend.emails.send({
  from: "noreply@myapp.com",
  to: "user@example.com",
  subject: "Welcome!",
  react: WelcomeEmail({ name: "John" })
});

// Next.js Server Action
"use server";
import { resend } from "@/lib/resend";

export async function sendNewsletter(formData) {
  await resend.emails.send({
    from: "newsletter@myapp.com",
    to: formData.email,
    subject: "Weekly Update",
    react: NewsletterEmail(formData)
  });
}

// POSTMARK - Traditional but Solid
const Postmark = require("postmark");

const client = new Postmark.ServerClient("xxx");

// Simple send
client.sendEmail({
  From: "noreply@myapp.com",
  To: "user@example.com",
  Subject: "Hello World",
  HtmlBody: "<strong>Welcome!</strong>",
  TextBody: "Welcome!"
});

// With template
client.sendEmailWithTemplate({
  From: "noreply@myapp.com",
  To: "user@example.com",
  TemplateAlias: "welcome",
  TemplateModel: {
    name: "John",
    action_url: "https://myapp.com/welcome"
  }
});

// Inbound email (Postmark only)
app.post("/inbound", (req, res) => {
  const { From, Subject, TextBody } = req.body;
  // Process inbound email
  res.status(200).send();
});`}</code></pre>

      <h2 style={h2Style}>{ct.templatesTitle}</h2>
      <p style={pStyle}>{ct.templatesIntro}</p>

      <pre style={codeStyle}><code>{`// Email Template Comparison

// RESEND - React Email Components
// emails/welcome.tsx
import { Html, Head, Body, Container, Heading, Text, Button } from "@react-email/components";

export function WelcomeEmail({ name }) {
  return (
    <Html>
      <Head />
      <Body style={{ backgroundColor: "#f6f9fc", fontFamily: "sans-serif" }}>
        <Container style={{ padding: "20px" }}>
          <Heading>Welcome, {name}!</Heading>
          <Text>Thanks for signing up for our service.</Text>
          <Button href="https://myapp.com/dashboard">
            Get Started
          </Button>
        </Container>
      </Body>
    </Html>
  );
}

// Benefits:
// - Full React component power
// - TypeScript support
// - Reusable components
// - Preview in browser
// - Version control

// POSTMARK - HTML Templates
// Managed in dashboard or via API

// Create template via API
await client.createTemplate({
  Name: "Welcome Email",
  Subject: "Welcome, {{name}}!",
  HtmlBody: \`
    <html>
      <body>
        <h1>Welcome, {{name}}!</h1>
        <p>Thanks for signing up.</p>
        <a href="{{action_url}}">Get Started</a>
      </body>
    </html>
  \`,
  TextBody: "Welcome, {{name}}! ..."
});

// Benefits:
// - Visual template editor
// - Template testing
// - A/B testing
// - Non-developers can edit`}</code></pre>

      <h2 style={h2Style}>{ct.whenToUseTitle}</h2>

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: 16, marginBottom: 24 }}>
        <div style={{ padding: 20, background: 'var(--bg-input)', borderRadius: 8, border: '1px solid var(--border-color)', borderTop: '4px solid #000' }}>
          <h3 style={{ fontSize: 16, fontWeight: 700, marginBottom: 12, color: '#000' }}>{ct.resendBestFor}</h3>
          <ul style={{ lineHeight: 2, color: 'var(--text-secondary)', paddingLeft: 20, margin: 0, fontSize: 14 }}>
            <li>{isZh ? 'React/Next.js项目' : 'React/Next.js projects'}</li>
            <li>{isZh ? '重视开发者体验' : 'Value developer experience'}</li>
            <li>{isZh ? '高邮件量(成本敏感)' : 'High email volume (cost-sensitive)'}</li>
            <li>{isZh ? '现代技术栈' : 'Modern tech stack'}</li>
            <li>{isZh ? '初创公司/MVP' : 'Startups/MVPs'}</li>
            <li>{isZh ? '需要代码管理模板' : 'Code-managed templates'}</li>
          </ul>
        </div>
        <div style={{ padding: 20, background: 'var(--bg-input)', borderRadius: 8, border: '1px solid var(--border-color)', borderTop: '4px solid #79bd9a' }}>
          <h3 style={{ fontSize: 16, fontWeight: 700, marginBottom: 12, color: '#79bd9a' }}>{ct.postmarkBestFor}</h3>
          <ul style={{ lineHeight: 2, color: 'var(--text-secondary)', paddingLeft: 20, margin: 0, fontSize: 14 }}>
            <li>{isZh ? '需要入站邮件处理' : 'Need inbound email'}</li>
            <li>{isZh ? '企业级应用' : 'Enterprise applications'}</li>
            <li>{isZh ? '需要A/B测试' : 'Need A/B testing'}</li>
            <li>{isZh ? '非技术团队编辑模板' : 'Non-tech template editing'}</li>
            <li>{isZh ? '需要高级分析' : 'Advanced analytics needed'}</li>
            <li>{isZh ? '送达率是关键' : 'Deliverability is critical'}</li>
          </ul>
        </div>
      </div>

      <h2 style={h2Style}>{ct.conclusionTitle}</h2>
      <p style={pStyle}>{ct.conclusionContent}</p>

      <div style={{ padding: 20, background: 'linear-gradient(135deg, rgba(0,0,0,0.1), rgba(121,189,154,0.1))', borderRadius: 12, border: '1px solid rgba(0,0,0,0.3)', textAlign: 'center', marginTop: 30, marginBottom: 30 }}>
        <p style={{ fontSize: 16, fontWeight: 600, marginBottom: 8 }}>{ct.tryTools}</p>
        <a href={'/' + lang + '/tools/json-formatter'} style={{ color: '#000', textDecoration: 'none' }}>JSON Formatter</a> • {' '}
        <a href={'/' + lang + '/tools/base64-encoder'} style={{ color: '#000', textDecoration: 'none' }}>Base64 Encoder</a> • {' '}
        <a href={'/' + lang + '/tools/hash-generator'} style={{ color: '#000', textDecoration: 'none' }}>Hash Generator</a>
      </div>

      <h2 style={h2Style}>FAQ</h2>
      {[
        [ct.faq1q, ct.faq1a],
        [ct.faq2q, ct.faq2a],
        [ct.faq3q, ct.faq3a],
        [ct.faq4q, ct.faq4a],
        [ct.faq5q, ct.faq5a],
        [ct.faq6q, ct.faq6a],
        [ct.faq7q, ct.faq7a],
        [ct.faq8q, ct.faq8a],
      ].map(([q, a], i) => (
        <div key={i} style={{ marginBottom: 16, padding: 16, background: 'var(--bg-input)', borderRadius: 8, border: '1px solid var(--border-color)' }}>
          <h3 style={{ fontSize: 15, fontWeight: 700, marginBottom: 8, color: 'var(--text-primary)' }}>{q}</h3>
          <p style={{ fontSize: 14, color: 'var(--text-secondary)', lineHeight: 1.7, margin: 0 }}>{a}</p>
        </div>
      ))}
    </div>
  );
}
