'use client';

import Link from 'next/link';
import { useLang } from '@/i18n/LangContext';
import ToolLayout from '@/components/ToolLayout';

const t: Record<string, Record<string, string>> = {
  en: {
    title: 'JSON vs XML', description: 'A detailed comparison of JSON and XML data formats.',
    intro: 'JSON and XML are the two most common data interchange formats in software development. JSON has become dominant in modern web APIs, while XML remains widely used in enterprise systems, document formats, and legacy applications.',
    tableFeature: 'Feature', tableJson: 'JSON', tableXml: 'XML',
    syntax: 'Syntax', synJson: 'Key-value pairs with {}[]', synXml: 'Tag-based markup <tag>value</tag>',
    readability: 'Readability', readJson: 'Clean and compact', readXml: 'Verbose but self-documenting',
    fileSize: 'File Size', fsJson: 'Smaller (less overhead)', fsXml: 'Larger (closing tags, attributes)',
    parsing: 'Parsing Speed', psJson: 'Fast (native in JS)', psXml: 'Slower (DOM/SAX parsers)',
    schema: 'Schema Support', scJson: 'JSON Schema (optional)', scXml: 'DTD, XSD (mature and robust)',
    comments: 'Comments', comJson: 'Not supported', comXml: 'Supported (<!-- -->)',
    namespaces: 'Namespaces', nsJson: 'Not supported', nsXml: 'Full support',
    whatIsJson: 'What is JSON?', jsonText: 'JSON (JavaScript Object Notation) is a lightweight text-based data format using key-value pairs, arrays, and nested objects. It is language-independent despite its JavaScript origins and has become the standard for REST APIs, configuration files, and NoSQL databases like MongoDB.',
    whatIsXml: 'What is XML?', xmlText: 'XML (eXtensible Markup Language) is a markup language for encoding documents in a human and machine-readable format. It supports namespaces, schemas (XSD/DTD), XSLT transformations, and XPath queries. XML is used in SOAP web services, RSS feeds, SVG graphics, office document formats (DOCX, XLSX), and enterprise integration.',
    whenJson: 'When to Use JSON', jsonUse1: 'REST API payloads', jsonUse2: 'JavaScript/Node.js applications', jsonUse3: 'NoSQL databases (MongoDB, CouchDB)', jsonUse4: 'Configuration files (package.json, tsconfig)', jsonUse5: 'Mobile app data exchange',
    whenXml: 'When to Use XML', xmlUse1: 'SOAP web services', xmlUse2: 'Enterprise application integration', xmlUse3: 'Document formats (HTML, SVG, DOCX)', xmlUse4: 'When you need XML Schema validation', xmlUse5: 'RSS/Atom feeds and sitemaps',
    verdict: 'TL;DR / Verdict', verdictText: 'Use JSON for modern web APIs, JavaScript applications, and when file size matters. Use XML for enterprise systems, document formats, and when you need schema validation, namespaces, or XSLT transformations.',
    tryTools: 'Try Our Format Tools', faqTitle: 'Frequently Asked Questions',
    faq1q: 'Is JSON better than XML?', faq1a: 'Neither is universally better. JSON is simpler, more compact, and faster to parse, making it ideal for web APIs. XML is more feature-rich with namespaces, schemas, and transformations, making it better for complex document formats and enterprise integration.',
    faq2q: 'Can XML do everything JSON can?', faq2a: 'Yes, XML can represent any data structure that JSON can, but with more verbose syntax. However, JSON cannot do everything XML can: JSON lacks namespaces, schema validation (natively), comments, and processing instructions.',
    faq3q: 'Is XML still relevant in 2025?', faq3a: 'Absolutely. XML is used in HTML5 (XHTML), SVG, office documents (DOCX, XLSX), Android layouts, SOAP services, RSS feeds, sitemaps, and many enterprise systems. While JSON dominates web APIs, XML is deeply embedded in many critical technologies.',
  },
  zh: { title: 'JSON vs XML', description: 'JSON 与 XML 数据格式的详细对比。', intro: 'JSON 和 XML 是软件开发中最常见的两种数据交换格式。', tableFeature: '特性', tableJson: 'JSON', tableXml: 'XML', syntax: '语法', synJson: '键值对 {}[]', synXml: '标签标记 <tag>value</tag>', readability: '可读性', readJson: '简洁紧凑', readXml: '冗长但自描述', fileSize: '文件大小', fsJson: '更小', fsXml: '更大（闭合标签）', parsing: '解析速度', psJson: '快（JS 原生）', psXml: '较慢（DOM/SAX）', schema: 'Schema 支持', scJson: 'JSON Schema（可选）', scXml: 'DTD, XSD（成熟）', comments: '注释', comJson: '不支持', comXml: '支持', namespaces: '命名空间', nsJson: '不支持', nsXml: '完整支持', whatIsJson: '什么是 JSON？', jsonText: 'JSON 使用键值对和数组的轻量级格式，是 REST API 和 NoSQL 数据库的标准。', whatIsXml: '什么是 XML？', xmlText: 'XML 是可扩展标记语言，支持命名空间、Schema、XSLT 转换。广泛用于 SOAP、RSS、SVG 和办公文档。', whenJson: '何时使用 JSON', jsonUse1: 'REST API', jsonUse2: 'JS/Node.js 应用', jsonUse3: 'NoSQL 数据库', jsonUse4: '配置文件', jsonUse5: '移动应用数据交换', whenXml: '何时使用 XML', xmlUse1: 'SOAP 服务', xmlUse2: '企业集成', xmlUse3: '文档格式', xmlUse4: 'Schema 验证', xmlUse5: 'RSS/站点地图', verdict: '总结', verdictText: '现代 Web API 用 JSON。企业系统和文档格式用 XML。', tryTools: '试试我们的格式化工具', faqTitle: '常见问题', faq1q: 'JSON 比 XML 更好吗？', faq1a: '各有优势。JSON 更简洁高效适合 Web API。XML 功能更丰富适合企业系统。', faq2q: 'XML 能做 JSON 能做的一切吗？', faq2a: '可以，但语法更冗长。JSON 不能做 XML 的一切（命名空间、Schema 验证等）。', faq3q: 'XML 在 2025 年还有用吗？', faq3a: '当然。XML 用于 HTML5、SVG、办公文档、Android 布局、SOAP、RSS 和许多企业系统。' },
  fr: { title: 'JSON vs XML', description: 'Comparaison de JSON et XML.', intro: 'JSON et XML sont les deux formats d\'echange les plus courants.', tableFeature: 'Caracteristique', tableJson: 'JSON', tableXml: 'XML', syntax: 'Syntaxe', synJson: 'Paires cle-valeur {}[]', synXml: 'Balises <tag>valeur</tag>', readability: 'Lisibilite', readJson: 'Compact', readXml: 'Verbeux', fileSize: 'Taille', fsJson: 'Plus petite', fsXml: 'Plus grande', parsing: 'Parsing', psJson: 'Rapide', psXml: 'Plus lent', schema: 'Schema', scJson: 'JSON Schema', scXml: 'DTD, XSD', comments: 'Commentaires', comJson: 'Non', comXml: 'Oui', namespaces: 'Namespaces', nsJson: 'Non', nsXml: 'Oui', whatIsJson: 'Qu\'est-ce que JSON ?', jsonText: 'Format leger base sur les paires cle-valeur, standard pour les APIs REST.', whatIsXml: 'Qu\'est-ce que XML ?', xmlText: 'Langage de balisage extensible avec namespaces, schemas et transformations XSLT.', whenJson: 'Quand utiliser JSON', jsonUse1: 'APIs REST', jsonUse2: 'Applications JS', jsonUse3: 'NoSQL', jsonUse4: 'Fichiers de config', jsonUse5: 'Apps mobiles', whenXml: 'Quand utiliser XML', xmlUse1: 'Services SOAP', xmlUse2: 'Integration entreprise', xmlUse3: 'Formats de documents', xmlUse4: 'Validation de schema', xmlUse5: 'RSS/Sitemaps', verdict: 'Resume', verdictText: 'JSON pour les APIs web. XML pour les systemes d\'entreprise.', tryTools: 'Essayez nos outils', faqTitle: 'Questions frequentes', faq1q: 'JSON est-il meilleur que XML ?', faq1a: 'Chacun a ses forces.', faq2q: 'XML peut-il tout faire comme JSON ?', faq2a: 'Oui mais avec une syntaxe plus verbeuse.', faq3q: 'XML est-il encore pertinent ?', faq3a: 'Absolument, dans de nombreux systemes critiques.' },
  de: { title: 'JSON vs XML', description: 'Vergleich von JSON und XML.', intro: 'JSON und XML sind die zwei gaengigsten Datenaustauschformate.', tableFeature: 'Eigenschaft', tableJson: 'JSON', tableXml: 'XML', syntax: 'Syntax', synJson: 'Key-Value-Paare {}[]', synXml: 'Tag-Markup <tag>Wert</tag>', readability: 'Lesbarkeit', readJson: 'Kompakt', readXml: 'Ausfuehrlich', fileSize: 'Dateigroesse', fsJson: 'Kleiner', fsXml: 'Groesser', parsing: 'Parsing', psJson: 'Schnell', psXml: 'Langsamer', schema: 'Schema', scJson: 'JSON Schema', scXml: 'DTD, XSD', comments: 'Kommentare', comJson: 'Nein', comXml: 'Ja', namespaces: 'Namespaces', nsJson: 'Nein', nsXml: 'Ja', whatIsJson: 'Was ist JSON?', jsonText: 'Leichtgewichtiges Format fuer REST-APIs und NoSQL-Datenbanken.', whatIsXml: 'Was ist XML?', xmlText: 'Erweiterbare Auszeichnungssprache mit Namespaces, Schemas und XSLT.', whenJson: 'Wann JSON', jsonUse1: 'REST-APIs', jsonUse2: 'JS-Anwendungen', jsonUse3: 'NoSQL', jsonUse4: 'Config-Dateien', jsonUse5: 'Mobile Apps', whenXml: 'Wann XML', xmlUse1: 'SOAP-Dienste', xmlUse2: 'Enterprise-Integration', xmlUse3: 'Dokumentformate', xmlUse4: 'Schema-Validierung', xmlUse5: 'RSS/Sitemaps', verdict: 'Fazit', verdictText: 'JSON fuer Web-APIs. XML fuer Enterprise-Systeme.', tryTools: 'Probieren Sie unsere Tools', faqTitle: 'FAQ', faq1q: 'Ist JSON besser als XML?', faq1a: 'Jedes hat Staerken.', faq2q: 'Kann XML alles was JSON kann?', faq2a: 'Ja, aber ausfuehrlicher.', faq3q: 'Ist XML noch relevant?', faq3a: 'Absolut, in vielen kritischen Systemen.' },
  es: { title: 'JSON vs XML', description: 'Comparacion de JSON y XML.', intro: 'JSON y XML son los formatos de intercambio mas comunes.', tableFeature: 'Caracteristica', tableJson: 'JSON', tableXml: 'XML', syntax: 'Sintaxis', synJson: 'Pares clave-valor {}[]', synXml: 'Etiquetas <tag>valor</tag>', readability: 'Legibilidad', readJson: 'Compacto', readXml: 'Verboso', fileSize: 'Tamano', fsJson: 'Menor', fsXml: 'Mayor', parsing: 'Parsing', psJson: 'Rapido', psXml: 'Mas lento', schema: 'Schema', scJson: 'JSON Schema', scXml: 'DTD, XSD', comments: 'Comentarios', comJson: 'No', comXml: 'Si', namespaces: 'Namespaces', nsJson: 'No', nsXml: 'Si', whatIsJson: 'Que es JSON?', jsonText: 'Formato ligero estandar para APIs REST y bases NoSQL.', whatIsXml: 'Que es XML?', xmlText: 'Lenguaje de marcado extensible con namespaces, schemas y XSLT.', whenJson: 'Cuando usar JSON', jsonUse1: 'APIs REST', jsonUse2: 'Apps JS', jsonUse3: 'NoSQL', jsonUse4: 'Archivos de config', jsonUse5: 'Apps moviles', whenXml: 'Cuando usar XML', xmlUse1: 'Servicios SOAP', xmlUse2: 'Integracion empresarial', xmlUse3: 'Formatos de documento', xmlUse4: 'Validacion de schema', xmlUse5: 'RSS/Sitemaps', verdict: 'Resumen', verdictText: 'JSON para APIs web. XML para sistemas empresariales.', tryTools: 'Prueba nuestras herramientas', faqTitle: 'FAQ', faq1q: 'Es JSON mejor que XML?', faq1a: 'Cada uno tiene fortalezas.', faq2q: 'XML puede hacer todo lo que JSON?', faq2a: 'Si, pero con sintaxis mas verbosa.', faq3q: 'XML es aun relevante?', faq3a: 'Absolutamente, en muchos sistemas criticos.' },
  ja: { title: 'JSON vs XML', description: 'JSONとXMLの詳細な比較。', intro: 'JSONとXMLはソフトウェア開発で最も一般的なデータ交換形式です。', tableFeature: '特性', tableJson: 'JSON', tableXml: 'XML', syntax: '構文', synJson: 'キー値ペア {}[]', synXml: 'タグマークアップ <tag>値</tag>', readability: '可読性', readJson: 'コンパクト', readXml: '冗長', fileSize: 'ファイルサイズ', fsJson: '小さい', fsXml: '大きい', parsing: 'パース', psJson: '速い', psXml: '遅い', schema: 'スキーマ', scJson: 'JSON Schema', scXml: 'DTD, XSD', comments: 'コメント', comJson: 'なし', comXml: 'あり', namespaces: '名前空間', nsJson: 'なし', nsXml: 'あり', whatIsJson: 'JSONとは？', jsonText: 'REST APIとNoSDBの標準的な軽量フォーマット。', whatIsXml: 'XMLとは？', xmlText: '名前空間、スキーマ、XSLTをサポートする拡張可能なマークアップ言語。', whenJson: 'JSONを使う場合', jsonUse1: 'REST API', jsonUse2: 'JSアプリ', jsonUse3: 'NoSQL', jsonUse4: '設定ファイル', jsonUse5: 'モバイルアプリ', whenXml: 'XMLを使う場合', xmlUse1: 'SOAPサービス', xmlUse2: 'エンタープライズ統合', xmlUse3: 'ドキュメント形式', xmlUse4: 'スキーマ検証', xmlUse5: 'RSS/サイトマップ', verdict: 'まとめ', verdictText: 'Web APIにはJSON。エンタープライズにはXML。', tryTools: 'ツールを試す', faqTitle: 'FAQ', faq1q: 'JSONはXMLより良いですか？', faq1a: 'それぞれ強みがあります。', faq2q: 'XMLはJSONの全てができますか？', faq2a: 'はい、ただしより冗長な構文で。', faq3q: 'XMLはまだ重要ですか？', faq3a: 'はい、多くの重要なシステムで使われています。' },
  ko: { title: 'JSON vs XML', description: 'JSON과 XML의 상세 비교.', intro: 'JSON과 XML은 소프트웨어 개발에서 가장 일반적인 데이터 교환 형식입니다.', tableFeature: '특성', tableJson: 'JSON', tableXml: 'XML', syntax: '구문', synJson: '키-값 쌍 {}[]', synXml: '태그 마크업 <tag>값</tag>', readability: '가독성', readJson: '컴팩트', readXml: '장황함', fileSize: '파일 크기', fsJson: '작음', fsXml: '큼', parsing: '파싱', psJson: '빠름', psXml: '느림', schema: '스키마', scJson: 'JSON Schema', scXml: 'DTD, XSD', comments: '주석', comJson: '없음', comXml: '있음', namespaces: '네임스페이스', nsJson: '없음', nsXml: '있음', whatIsJson: 'JSON이란?', jsonText: 'REST API와 NoSQL DB의 표준 경량 형식.', whatIsXml: 'XML이란?', xmlText: '네임스페이스, 스키마, XSLT를 지원하는 확장 가능한 마크업 언어.', whenJson: 'JSON을 사용할 때', jsonUse1: 'REST API', jsonUse2: 'JS 앱', jsonUse3: 'NoSQL', jsonUse4: '설정 파일', jsonUse5: '모바일 앱', whenXml: 'XML을 사용할 때', xmlUse1: 'SOAP 서비스', xmlUse2: '엔터프라이즈 통합', xmlUse3: '문서 형식', xmlUse4: '스키마 검증', xmlUse5: 'RSS/사이트맵', verdict: '요약', verdictText: 'Web API에는 JSON. 엔터프라이즈에는 XML.', tryTools: '도구 사용해보기', faqTitle: 'FAQ', faq1q: 'JSON이 XML보다 나은가요?', faq1a: '각각 강점이 있습니다.', faq2q: 'XML이 JSON이 할 수 있는 모든 것을 할 수 있나요?', faq2a: '네, 하지만 더 장황한 구문으로.', faq3q: 'XML은 아직 중요한가요?', faq3a: '물론입니다, 많은 중요한 시스템에서 사용됩니다.' },
};

const tableStyle={width:'100%',borderCollapse:'collapse' as const,fontSize:14};const thStyle={padding:'10px 14px',textAlign:'left' as const,borderBottom:'2px solid var(--border-color)',fontWeight:700};const tdStyle={padding:'10px 14px',borderBottom:'1px solid var(--border-color)'};const sectionStyle={marginTop:32};const h2Style={fontSize:22,fontWeight:700,marginBottom:12};const h3Style={fontSize:17,fontWeight:600,marginBottom:8};const pStyle={fontSize:14,lineHeight:1.8,color:'var(--text-secondary)',marginBottom:16};const ulStyle={fontSize:14,lineHeight:1.8,color:'var(--text-secondary)',paddingLeft:20,marginBottom:16};const cardStyle={background:'var(--bg-card)',borderRadius:12,padding:20,border:'1px solid var(--border-color)',marginBottom:16};

export default function JsonVsXml() {
  const { lang } = useLang(); const ui = t[lang] || t.en;
  const faqSchema = {'@context':'https://schema.org','@type':'FAQPage',mainEntity:[{'@type':'Question',name:ui.faq1q,acceptedAnswer:{'@type':'Answer',text:ui.faq1a}},{'@type':'Question',name:ui.faq2q,acceptedAnswer:{'@type':'Answer',text:ui.faq2a}},{'@type':'Question',name:ui.faq3q,acceptedAnswer:{'@type':'Answer',text:ui.faq3a}}]};
  return (
    <ToolLayout title={ui.title} description={ui.description} toolId="json-vs-xml">
      <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(faqSchema)}} />
      <p style={pStyle}>{ui.intro}</p>
      <div style={{overflowX:'auto',marginBottom:24}}><table style={tableStyle}><thead><tr><th style={thStyle}>{ui.tableFeature}</th><th style={thStyle}>{ui.tableJson}</th><th style={thStyle}>{ui.tableXml}</th></tr></thead><tbody>{[[ui.syntax,ui.synJson,ui.synXml],[ui.readability,ui.readJson,ui.readXml],[ui.fileSize,ui.fsJson,ui.fsXml],[ui.parsing,ui.psJson,ui.psXml],[ui.schema,ui.scJson,ui.scXml],[ui.comments,ui.comJson,ui.comXml],[ui.namespaces,ui.nsJson,ui.nsXml]].map(([f,a,b],i)=>(<tr key={i}><td style={{...tdStyle,fontWeight:600}}>{f}</td><td style={tdStyle}>{a}</td><td style={tdStyle}>{b}</td></tr>))}</tbody></table></div>
      <div style={sectionStyle}><h2 style={h2Style}>{ui.whatIsJson}</h2><p style={pStyle}>{ui.jsonText}</p></div>
      <div style={sectionStyle}><h2 style={h2Style}>{ui.whatIsXml}</h2><p style={pStyle}>{ui.xmlText}</p></div>
      <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))',gap:16,...sectionStyle}}>
        <div style={cardStyle}><h3 style={h3Style}>{ui.whenJson}</h3><ul style={ulStyle}><li>{ui.jsonUse1}</li><li>{ui.jsonUse2}</li><li>{ui.jsonUse3}</li><li>{ui.jsonUse4}</li><li>{ui.jsonUse5}</li></ul></div>
        <div style={cardStyle}><h3 style={h3Style}>{ui.whenXml}</h3><ul style={ulStyle}><li>{ui.xmlUse1}</li><li>{ui.xmlUse2}</li><li>{ui.xmlUse3}</li><li>{ui.xmlUse4}</li><li>{ui.xmlUse5}</li></ul></div>
      </div>
      <div style={{...cardStyle,background:'var(--bg-input)',...sectionStyle}}><h2 style={h2Style}>{ui.verdict}</h2><p style={{...pStyle,fontWeight:500}}>{ui.verdictText}</p></div>
      <div style={sectionStyle}><h2 style={h2Style}>{ui.tryTools}</h2><div style={{display:'flex',flexWrap:'wrap',gap:8}}>{[{href:`/${lang}/tools/json-formatter`,label:'JSON Formatter'},{href:`/${lang}/tools/xml-formatter`,label:'XML Formatter'},{href:`/${lang}/tools/xml-to-json`,label:'XML to JSON'},{href:`/${lang}/tools/csv-json`,label:'CSV ↔ JSON'}].map(link=>(<Link key={link.href} href={link.href} style={{display:'inline-block',padding:'8px 16px',borderRadius:8,border:'1px solid var(--border-color)',fontSize:13,color:'var(--accent-blue)',textDecoration:'none',background:'var(--bg-input)'}}>{link.label}</Link>))}</div></div>
      <div style={sectionStyle}><h2 style={h2Style}>{ui.faqTitle}</h2><div style={{display:'flex',flexDirection:'column',gap:8}}>{[{q:ui.faq1q,a:ui.faq1a},{q:ui.faq2q,a:ui.faq2a},{q:ui.faq3q,a:ui.faq3a}].map((faq,idx)=>(<details key={idx} style={{border:'1px solid var(--border-color)',borderRadius:8,overflow:'hidden',background:'var(--bg-input)'}}><summary style={{padding:'14px 16px',cursor:'pointer',fontSize:14,fontWeight:600}}>{faq.q}</summary><div style={{padding:'0 16px 14px',fontSize:13,lineHeight:1.7,color:'var(--text-secondary)'}}>{faq.a}</div></details>))}</div></div>
    </ToolLayout>
  );
}
