'use client';

import Link from 'next/link';
import { useLang } from '@/i18n/LangContext';
import ToolLayout from '@/components/ToolLayout';

const t: Record<string, Record<string, string>> = {
  en: {
    title: 'MySQL vs PostgreSQL', description: 'A detailed comparison of MySQL and PostgreSQL databases.',
    intro: 'MySQL and PostgreSQL are the two most popular open-source relational databases. MySQL is known for its speed and simplicity, while PostgreSQL is valued for its standards compliance and advanced features. Here is how they compare.',
    tableFeature: 'Feature', tableA: 'MySQL', tableB: 'PostgreSQL',
    license: 'License', licA: 'GPL (Oracle-owned)', licB: 'PostgreSQL License (truly open)',
    jsonSupport: 'JSON Support', jsonA: 'JSON type (basic)', jsonB: 'JSONB (binary, indexed, powerful)',
    performance: 'Read Performance', perfA: 'Faster for simple reads', perfB: 'Better for complex queries',
    replication: 'Replication', repA: 'Built-in master-slave', repB: 'Streaming + logical replication',
    fullText: 'Full-Text Search', ftA: 'Built-in (basic)', ftB: 'Advanced with ts_vector',
    extensions: 'Extensions', extA: 'Limited', extB: 'Rich ecosystem (PostGIS, pg_trgm, etc.)',
    mvcc: 'MVCC', mvccA: 'InnoDB MVCC', mvccB: 'True MVCC (no read locks)',
    whatIsA: 'What is MySQL?', aText: 'MySQL is the most popular open-source relational database, now owned by Oracle. It powers many of the world\'s largest websites including Facebook, Twitter, and YouTube. MySQL is known for its ease of use, reliable performance on read-heavy workloads, and wide hosting support. It uses InnoDB as its default storage engine with ACID compliance.',
    whatIsB: 'What is PostgreSQL?', bText: 'PostgreSQL is an advanced open-source object-relational database with over 35 years of development. It is known for data integrity, standards compliance, and extensibility. PostgreSQL supports advanced data types (JSONB, arrays, ranges), full-text search, GIS (PostGIS), and powerful query optimization. Major users include Apple, Instagram, Spotify, and Reddit.',
    whenA: 'When to Use MySQL', aUse1: 'Read-heavy web applications', aUse2: 'Simple CRUD applications', aUse3: 'WordPress and CMS platforms', aUse4: 'Shared hosting environments', aUse5: 'When simplicity and speed are priorities',
    whenB: 'When to Use PostgreSQL', bUse1: 'Complex queries and analytics', bUse2: 'GIS/geospatial applications (PostGIS)', bUse3: 'Applications needing JSONB support', bUse4: 'Data warehousing and reporting', bUse5: 'When standards compliance matters',
    verdict: 'TL;DR / Verdict', verdictText: 'Use MySQL for simple, read-heavy web applications where ease of setup and hosting support matter. Use PostgreSQL for complex applications needing advanced features, JSONB, GIS support, or strict standards compliance. PostgreSQL is increasingly the default choice for new projects.',
    tryTools: 'Try Our SQL Tools', faqTitle: 'Frequently Asked Questions',
    faq1q: 'Which is faster: MySQL or PostgreSQL?', faq1a: 'MySQL is generally faster for simple read operations and high-concurrency read workloads. PostgreSQL performs better for complex queries with joins, subqueries, and CTEs. For write-heavy workloads, PostgreSQL\'s MVCC implementation is often more efficient. The actual performance depends heavily on your specific workload.',
    faq2q: 'Can I migrate from MySQL to PostgreSQL?', faq2a: 'Yes, migration is possible using tools like pgLoader, AWS DMS, or manual export/import. Key differences to watch for include: AUTO_INCREMENT vs SERIAL, backtick vs double-quote quoting, ENUM handling, and stored procedure syntax. Plan for thorough testing after migration.',
    faq3q: 'Which is better for JSON data?', faq3a: 'PostgreSQL is significantly better for JSON data. Its JSONB type stores JSON in a binary format that supports indexing (GIN indexes), efficient queries, and in-place updates. MySQL\'s JSON type is more basic with limited indexing capabilities.',
  },
  zh: { title: 'MySQL vs PostgreSQL', description: 'MySQL 与 PostgreSQL 数据库的详细对比。', intro: 'MySQL 和 PostgreSQL 是最流行的两种开源关系数据库。', tableFeature: '特性', tableA: 'MySQL', tableB: 'PostgreSQL', license: '许可证', licA: 'GPL（Oracle 所有）', licB: 'PostgreSQL 许可证（真正开源）', jsonSupport: 'JSON 支持', jsonA: 'JSON 类型（基础）', jsonB: 'JSONB（二进制、可索引、强大）', performance: '读取性能', perfA: '简单读取更快', perfB: '复杂查询更好', replication: '复制', repA: '内置主从', repB: '流式+逻辑复制', fullText: '全文搜索', ftA: '内置（基础）', ftB: '高级 ts_vector', extensions: '扩展', extA: '有限', extB: '丰富生态（PostGIS 等）', mvcc: 'MVCC', mvccA: 'InnoDB MVCC', mvccB: '真正 MVCC（无读锁）', whatIsA: '什么是 MySQL？', aText: 'MySQL 是最流行的开源关系数据库，简单高效，适合读密集型工作负载。', whatIsB: '什么是 PostgreSQL？', bText: 'PostgreSQL 是高级的对象关系数据库，支持 JSONB、全文搜索、GIS 和强大的查询优化。', whenA: '何时使用 MySQL', aUse1: '读密集型 Web 应用', aUse2: '简单 CRUD', aUse3: 'WordPress/CMS', aUse4: '共享主机', aUse5: '简单快速优先', whenB: '何时使用 PostgreSQL', bUse1: '复杂查询和分析', bUse2: 'GIS/地理空间应用', bUse3: '需要 JSONB', bUse4: '数据仓库', bUse5: '标准合规性', verdict: '总结', verdictText: '简单读密集型用 MySQL。复杂应用和高级功能用 PostgreSQL。', tryTools: '试试我们的 SQL 工具', faqTitle: '常见问题', faq1q: 'MySQL 和 PostgreSQL 哪个更快？', faq1a: 'MySQL 简单读取更快，PostgreSQL 复杂查询更优。取决于具体工作负载。', faq2q: '可以从 MySQL 迁移到 PostgreSQL 吗？', faq2a: '可以，使用 pgLoader 或 AWS DMS 等工具。注意语法差异。', faq3q: '哪个更适合 JSON 数据？', faq3a: 'PostgreSQL 的 JSONB 类型远优于 MySQL 的 JSON 类型。' },
  fr: { title: 'MySQL vs PostgreSQL', description: 'Comparaison de MySQL et PostgreSQL.', intro: 'MySQL et PostgreSQL sont les deux bases de donnees open-source les plus populaires.', tableFeature: 'Caracteristique', tableA: 'MySQL', tableB: 'PostgreSQL', license: 'Licence', licA: 'GPL (Oracle)', licB: 'Licence PostgreSQL', jsonSupport: 'Support JSON', jsonA: 'Basique', jsonB: 'JSONB (avance)', performance: 'Performance lecture', perfA: 'Plus rapide lectures simples', perfB: 'Meilleur requetes complexes', replication: 'Replication', repA: 'Maitre-esclave', repB: 'Streaming + logique', fullText: 'Recherche plein texte', ftA: 'Basique', ftB: 'Avancee', extensions: 'Extensions', extA: 'Limitees', extB: 'Riche ecosysteme', mvcc: 'MVCC', mvccA: 'InnoDB', mvccB: 'Vrai MVCC', whatIsA: 'Qu\'est-ce que MySQL ?', aText: 'Base de donnees populaire, simple et performante pour les lectures.', whatIsB: 'Qu\'est-ce que PostgreSQL ?', bText: 'Base avancee avec JSONB, recherche plein texte, GIS et optimisation de requetes.', whenA: 'Quand MySQL', aUse1: 'Apps web lectures intensives', aUse2: 'CRUD simple', aUse3: 'WordPress/CMS', aUse4: 'Hebergement partage', aUse5: 'Simplicite prioritaire', whenB: 'Quand PostgreSQL', bUse1: 'Requetes complexes', bUse2: 'Applications GIS', bUse3: 'Besoin JSONB', bUse4: 'Data warehouse', bUse5: 'Conformite standards', verdict: 'Resume', verdictText: 'MySQL pour les apps simples. PostgreSQL pour les besoins avances.', tryTools: 'Essayez nos outils SQL', faqTitle: 'Questions frequentes', faq1q: 'Lequel est plus rapide ?', faq1a: 'Depend du type de requetes.', faq2q: 'Migration MySQL vers PostgreSQL ?', faq2a: 'Possible avec pgLoader ou AWS DMS.', faq3q: 'Lequel pour le JSON ?', faq3a: 'PostgreSQL avec JSONB est bien superieur.' },
  de: { title: 'MySQL vs PostgreSQL', description: 'Vergleich von MySQL und PostgreSQL.', intro: 'MySQL und PostgreSQL sind die zwei populaersten Open-Source-Datenbanken.', tableFeature: 'Eigenschaft', tableA: 'MySQL', tableB: 'PostgreSQL', license: 'Lizenz', licA: 'GPL (Oracle)', licB: 'PostgreSQL-Lizenz', jsonSupport: 'JSON', jsonA: 'Basisch', jsonB: 'JSONB (erweitert)', performance: 'Leseleistung', perfA: 'Schneller bei einfachen Reads', perfB: 'Besser bei komplexen Queries', replication: 'Replikation', repA: 'Master-Slave', repB: 'Streaming + logisch', fullText: 'Volltextsuche', ftA: 'Basisch', ftB: 'Erweitert', extensions: 'Erweiterungen', extA: 'Begrenzt', extB: 'Reiches Oekosystem', mvcc: 'MVCC', mvccA: 'InnoDB', mvccB: 'Echtes MVCC', whatIsA: 'Was ist MySQL?', aText: 'Populaere DB, einfach und schnell fuer Lese-Workloads.', whatIsB: 'Was ist PostgreSQL?', bText: 'Erweiterte DB mit JSONB, Volltextsuche, GIS und Query-Optimierung.', whenA: 'Wann MySQL', aUse1: 'Lese-intensive Web-Apps', aUse2: 'Einfaches CRUD', aUse3: 'WordPress/CMS', aUse4: 'Shared Hosting', aUse5: 'Einfachheit priorisiert', whenB: 'Wann PostgreSQL', bUse1: 'Komplexe Queries', bUse2: 'GIS-Anwendungen', bUse3: 'JSONB benoetigt', bUse4: 'Data Warehouse', bUse5: 'Standards-Konformitaet', verdict: 'Fazit', verdictText: 'MySQL fuer einfache Apps. PostgreSQL fuer erweiterte Anforderungen.', tryTools: 'Probieren Sie unsere SQL-Tools', faqTitle: 'FAQ', faq1q: 'Welche ist schneller?', faq1a: 'Abhaengig vom Query-Typ.', faq2q: 'Migration moeglich?', faq2a: 'Ja, mit pgLoader oder AWS DMS.', faq3q: 'Welche fuer JSON?', faq3a: 'PostgreSQL JSONB ist deutlich ueberlegen.' },
  es: { title: 'MySQL vs PostgreSQL', description: 'Comparacion de MySQL y PostgreSQL.', intro: 'MySQL y PostgreSQL son las dos bases de datos open-source mas populares.', tableFeature: 'Caracteristica', tableA: 'MySQL', tableB: 'PostgreSQL', license: 'Licencia', licA: 'GPL (Oracle)', licB: 'Licencia PostgreSQL', jsonSupport: 'JSON', jsonA: 'Basico', jsonB: 'JSONB (avanzado)', performance: 'Rendimiento lectura', perfA: 'Mas rapido lecturas simples', perfB: 'Mejor queries complejas', replication: 'Replicacion', repA: 'Master-slave', repB: 'Streaming + logica', fullText: 'Busqueda texto completo', ftA: 'Basica', ftB: 'Avanzada', extensions: 'Extensiones', extA: 'Limitadas', extB: 'Rico ecosistema', mvcc: 'MVCC', mvccA: 'InnoDB', mvccB: 'Verdadero MVCC', whatIsA: 'Que es MySQL?', aText: 'Base de datos popular, simple y rapida para lecturas.', whatIsB: 'Que es PostgreSQL?', bText: 'Base avanzada con JSONB, busqueda de texto, GIS y optimizacion de queries.', whenA: 'Cuando MySQL', aUse1: 'Apps web lecturas intensivas', aUse2: 'CRUD simple', aUse3: 'WordPress/CMS', aUse4: 'Hosting compartido', aUse5: 'Simplicidad prioridad', whenB: 'Cuando PostgreSQL', bUse1: 'Queries complejas', bUse2: 'Apps GIS', bUse3: 'Necesidad JSONB', bUse4: 'Data warehouse', bUse5: 'Cumplimiento estandares', verdict: 'Resumen', verdictText: 'MySQL para apps simples. PostgreSQL para necesidades avanzadas.', tryTools: 'Prueba nuestras herramientas SQL', faqTitle: 'FAQ', faq1q: 'Cual es mas rapida?', faq1a: 'Depende del tipo de queries.', faq2q: 'Se puede migrar?', faq2a: 'Si, con pgLoader o AWS DMS.', faq3q: 'Cual para JSON?', faq3a: 'PostgreSQL JSONB es muy superior.' },
  ja: { title: 'MySQL vs PostgreSQL', description: 'MySQLとPostgreSQLの詳細な比較。', intro: 'MySQLとPostgreSQLは最も人気のあるオープンソースRDBです。', tableFeature: '特性', tableA: 'MySQL', tableB: 'PostgreSQL', license: 'ライセンス', licA: 'GPL (Oracle)', licB: 'PostgreSQLライセンス', jsonSupport: 'JSON', jsonA: '基本的', jsonB: 'JSONB（高度）', performance: '読取性能', perfA: '単純な読取が速い', perfB: '複雑なクエリが得意', replication: 'レプリケーション', repA: 'マスタースレーブ', repB: 'ストリーミング+論理', fullText: '全文検索', ftA: '基本的', ftB: '高度', extensions: '拡張', extA: '限定的', extB: '豊富', mvcc: 'MVCC', mvccA: 'InnoDB', mvccB: '真のMVCC', whatIsA: 'MySQLとは？', aText: '人気の高いDB、読取ワークロードにシンプルで高速。', whatIsB: 'PostgreSQLとは？', bText: 'JSONB、全文検索、GIS、クエリ最適化を備えた高度なDB。', whenA: 'MySQL使用時', aUse1: '読取集中Webアプリ', aUse2: 'シンプルCRUD', aUse3: 'WordPress/CMS', aUse4: '共有ホスティング', aUse5: 'シンプルさ優先', whenB: 'PostgreSQL使用時', bUse1: '複雑なクエリ', bUse2: 'GISアプリ', bUse3: 'JSONB必要', bUse4: 'DWH', bUse5: '標準準拠', verdict: 'まとめ', verdictText: 'シンプルなアプリにはMySQL。高度な要件にはPostgreSQL。', tryTools: 'SQLツールを試す', faqTitle: 'FAQ', faq1q: 'どちらが速い？', faq1a: 'クエリタイプによります。', faq2q: '移行は可能？', faq2a: 'はい、pgLoaderやAWS DMSで。', faq3q: 'JSONにはどちら？', faq3a: 'PostgreSQLのJSONBが遥かに優れています。' },
  ko: { title: 'MySQL vs PostgreSQL', description: 'MySQL과 PostgreSQL의 상세 비교.', intro: 'MySQL과 PostgreSQL은 가장 인기 있는 오픈소스 관계형 데이터베이스입니다.', tableFeature: '특성', tableA: 'MySQL', tableB: 'PostgreSQL', license: '라이선스', licA: 'GPL (Oracle)', licB: 'PostgreSQL 라이선스', jsonSupport: 'JSON', jsonA: '기본', jsonB: 'JSONB (고급)', performance: '읽기 성능', perfA: '단순 읽기가 빠름', perfB: '복잡 쿼리가 뛰어남', replication: '복제', repA: '마스터-슬레이브', repB: '스트리밍+논리적', fullText: '전체 텍스트 검색', ftA: '기본', ftB: '고급', extensions: '확장', extA: '제한적', extB: '풍부한 생태계', mvcc: 'MVCC', mvccA: 'InnoDB', mvccB: '진정한 MVCC', whatIsA: 'MySQL이란?', aText: '인기 있는 DB, 읽기 워크로드에 심플하고 빠름.', whatIsB: 'PostgreSQL이란?', bText: 'JSONB, 전문 검색, GIS, 쿼리 최적화를 갖춘 고급 DB.', whenA: 'MySQL 사용 시', aUse1: '읽기 집중 웹 앱', aUse2: '간단한 CRUD', aUse3: 'WordPress/CMS', aUse4: '공유 호스팅', aUse5: '단순함 우선', whenB: 'PostgreSQL 사용 시', bUse1: '복잡한 쿼리', bUse2: 'GIS 앱', bUse3: 'JSONB 필요', bUse4: '데이터 웨어하우스', bUse5: '표준 준수', verdict: '요약', verdictText: '간단한 앱에는 MySQL. 고급 요구사항에는 PostgreSQL.', tryTools: 'SQL 도구 사용해보기', faqTitle: 'FAQ', faq1q: '어떤 것이 더 빠른가요?', faq1a: '쿼리 유형에 따라 다릅니다.', faq2q: '마이그레이션이 가능한가요?', faq2a: '네, pgLoader나 AWS DMS로 가능합니다.', faq3q: 'JSON에는 어떤 것이 좋은가요?', faq3a: 'PostgreSQL의 JSONB가 훨씬 우수합니다.' },
};

const tableStyle={width:'100%',borderCollapse:'collapse' as const,fontSize:14};const thStyle={padding:'10px 14px',textAlign:'left' as const,borderBottom:'2px solid var(--border-color)',fontWeight:700};const tdStyle={padding:'10px 14px',borderBottom:'1px solid var(--border-color)'};const sectionStyle={marginTop:32};const h2Style={fontSize:22,fontWeight:700,marginBottom:12};const h3Style={fontSize:17,fontWeight:600,marginBottom:8};const pStyle={fontSize:14,lineHeight:1.8,color:'var(--text-secondary)',marginBottom:16};const ulStyle={fontSize:14,lineHeight:1.8,color:'var(--text-secondary)',paddingLeft:20,marginBottom:16};const cardStyle={background:'var(--bg-card)',borderRadius:12,padding:20,border:'1px solid var(--border-color)',marginBottom:16};

export default function MysqlVsPostgresql() {
  const { lang } = useLang(); const ui = t[lang] || t.en;
  const faqSchema = {'@context':'https://schema.org','@type':'FAQPage',mainEntity:[{'@type':'Question',name:ui.faq1q,acceptedAnswer:{'@type':'Answer',text:ui.faq1a}},{'@type':'Question',name:ui.faq2q,acceptedAnswer:{'@type':'Answer',text:ui.faq2a}},{'@type':'Question',name:ui.faq3q,acceptedAnswer:{'@type':'Answer',text:ui.faq3a}}]};
  return (
    <ToolLayout title={ui.title} description={ui.description} toolId="mysql-vs-postgresql">
      <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(faqSchema)}} />
      <p style={pStyle}>{ui.intro}</p>
      <div style={{overflowX:'auto',marginBottom:24}}><table style={tableStyle}><thead><tr><th style={thStyle}>{ui.tableFeature}</th><th style={thStyle}>{ui.tableA}</th><th style={thStyle}>{ui.tableB}</th></tr></thead><tbody>{[[ui.license,ui.licA,ui.licB],[ui.jsonSupport,ui.jsonA,ui.jsonB],[ui.performance,ui.perfA,ui.perfB],[ui.replication,ui.repA,ui.repB],[ui.fullText,ui.ftA,ui.ftB],[ui.extensions,ui.extA,ui.extB],[ui.mvcc,ui.mvccA,ui.mvccB]].map(([f,a,b],i)=>(<tr key={i}><td style={{...tdStyle,fontWeight:600}}>{f}</td><td style={tdStyle}>{a}</td><td style={tdStyle}>{b}</td></tr>))}</tbody></table></div>
      <div style={sectionStyle}><h2 style={h2Style}>{ui.whatIsA}</h2><p style={pStyle}>{ui.aText}</p></div>
      <div style={sectionStyle}><h2 style={h2Style}>{ui.whatIsB}</h2><p style={pStyle}>{ui.bText}</p></div>
      <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))',gap:16,...sectionStyle}}>
        <div style={cardStyle}><h3 style={h3Style}>{ui.whenA}</h3><ul style={ulStyle}><li>{ui.aUse1}</li><li>{ui.aUse2}</li><li>{ui.aUse3}</li><li>{ui.aUse4}</li><li>{ui.aUse5}</li></ul></div>
        <div style={cardStyle}><h3 style={h3Style}>{ui.whenB}</h3><ul style={ulStyle}><li>{ui.bUse1}</li><li>{ui.bUse2}</li><li>{ui.bUse3}</li><li>{ui.bUse4}</li><li>{ui.bUse5}</li></ul></div>
      </div>
      <div style={{...cardStyle,background:'var(--bg-input)',...sectionStyle}}><h2 style={h2Style}>{ui.verdict}</h2><p style={{...pStyle,fontWeight:500}}>{ui.verdictText}</p></div>
      <div style={sectionStyle}><h2 style={h2Style}>{ui.tryTools}</h2><div style={{display:'flex',flexWrap:'wrap',gap:8}}>{[{href:`/${lang}/tools/sql-formatter`,label:'SQL Formatter'},{href:`/${lang}/tools/sql-to-prisma`,label:'SQL to Prisma'},{href:`/${lang}/tools/json-formatter`,label:'JSON Formatter'},{href:`/${lang}/tools/docker-compose-generator`,label:'Docker Compose Generator'}].map(link=>(<Link key={link.href} href={link.href} style={{display:'inline-block',padding:'8px 16px',borderRadius:8,border:'1px solid var(--border-color)',fontSize:13,color:'var(--accent-blue)',textDecoration:'none',background:'var(--bg-input)'}}>{link.label}</Link>))}</div></div>
      <div style={sectionStyle}><h2 style={h2Style}>{ui.faqTitle}</h2><div style={{display:'flex',flexDirection:'column',gap:8}}>{[{q:ui.faq1q,a:ui.faq1a},{q:ui.faq2q,a:ui.faq2a},{q:ui.faq3q,a:ui.faq3a}].map((faq,idx)=>(<details key={idx} style={{border:'1px solid var(--border-color)',borderRadius:8,overflow:'hidden',background:'var(--bg-input)'}}><summary style={{padding:'14px 16px',cursor:'pointer',fontSize:14,fontWeight:600}}>{faq.q}</summary><div style={{padding:'0 16px 14px',fontSize:13,lineHeight:1.7,color:'var(--text-secondary)'}}>{faq.a}</div></details>))}</div></div>
    </ToolLayout>
  );
}
