'use client';

import Link from 'next/link';
import { useLang } from '@/i18n/LangContext';
import ToolLayout from '@/components/ToolLayout';

const t: Record<string, Record<string, string>> = {
  en: {
    title: 'TypeScript vs JavaScript', description: 'A detailed comparison of TypeScript and JavaScript.',
    intro: 'TypeScript is a typed superset of JavaScript that compiles to plain JavaScript. While JavaScript remains the language of the web, TypeScript has rapidly gained adoption for its type safety and developer experience. Here is how they compare.',
    tableFeature: 'Feature', tableA: 'JavaScript', tableB: 'TypeScript',
    typeSystem: 'Type System', tsA: 'Dynamic (runtime types)', tsB: 'Static (compile-time types)',
    ide: 'IDE Support', ideA: 'Good (basic IntelliSense)', ideB: 'Excellent (full IntelliSense, refactoring)',
    buildStep: 'Build Step', bsA: 'None (runs directly)', bsB: 'Required (tsc compiler)',
    learning: 'Learning Curve', lcA: 'Low', lcB: 'Moderate (type system concepts)',
    ecosystem: 'Ecosystem', ecoA: 'Universal (all browsers, Node.js)', ecoB: 'Growing (DefinitelyTyped, native types)',
    errorDetection: 'Error Detection', edA: 'Runtime only', edB: 'Compile-time + runtime',
    refactoring: 'Refactoring', rfA: 'Risky (no type guarantees)', rfB: 'Safe (compiler catches errors)',
    whatIsA: 'What is JavaScript?', aText: 'JavaScript is the programming language of the web, running in every browser and on servers via Node.js. Created in 1995 by Brendan Eich, it is a dynamic, interpreted language with prototypal inheritance. JavaScript supports functional and object-oriented programming paradigms and powers virtually every website on the internet.',
    whatIsB: 'What is TypeScript?', bText: 'TypeScript is a statically typed superset of JavaScript developed by Microsoft (first released in 2012). Any valid JavaScript is valid TypeScript, but TypeScript adds optional type annotations, interfaces, generics, enums, and advanced type features. It compiles to clean, readable JavaScript and is used by Angular, Vue 3, Svelte, Next.js, and most modern frameworks.',
    whenA: 'When to Use JavaScript', aUse1: 'Quick prototypes and scripts', aUse2: 'Small projects with 1-2 developers', aUse3: 'Browser extensions and bookmarklets', aUse4: 'When build tooling overhead is undesirable', aUse5: 'Learning web development fundamentals',
    whenB: 'When to Use TypeScript', bUse1: 'Medium to large codebases', bUse2: 'Team projects (3+ developers)', bUse3: 'Libraries and packages (better DX for consumers)', bUse4: 'Enterprise applications', bUse5: 'Projects with complex data models',
    verdict: 'TL;DR / Verdict', verdictText: 'Use TypeScript for any project that will be maintained by a team or grow beyond a prototype. The upfront cost of types pays for itself in fewer bugs, better refactoring, and improved documentation. Use plain JavaScript for quick scripts, prototypes, and learning. TypeScript is increasingly the default for professional JavaScript development.',
    tryTools: 'Try Our TypeScript Tools', faqTitle: 'Frequently Asked Questions',
    faq1q: 'Is TypeScript harder to learn than JavaScript?', faq1a: 'TypeScript has a moderate learning curve on top of JavaScript. If you know JavaScript, you can start writing TypeScript immediately since all JavaScript is valid TypeScript. Learning the type system (generics, utility types, type narrowing) takes time, but basic types (string, number, boolean) are straightforward.',
    faq2q: 'Does TypeScript make code slower?', faq2a: 'No. TypeScript compiles to plain JavaScript, so there is no runtime performance overhead. The types are erased during compilation. In some cases, TypeScript can lead to faster code because the type system helps developers write more intentional, optimized code.',
    faq3q: 'Can I use TypeScript with React?', faq3a: 'Yes, TypeScript has excellent React support. Create React App, Next.js, Vite, and most React tooling have first-class TypeScript support. React\'s component props, state, and hooks all benefit greatly from TypeScript type checking. Use .tsx files for React components with TypeScript.',
  },
  zh: { title: 'TypeScript vs JavaScript', description: 'TypeScript 与 JavaScript 的详细对比。', intro: 'TypeScript 是 JavaScript 的类型化超集，编译为纯 JavaScript。虽然 JavaScript 仍是 Web 语言，TypeScript 因类型安全和开发体验快速获得采用。', tableFeature: '特性', tableA: 'JavaScript', tableB: 'TypeScript', typeSystem: '类型系统', tsA: '动态（运行时类型）', tsB: '静态（编译时类型）', ide: 'IDE 支持', ideA: '良好', ideB: '优秀（完整 IntelliSense）', buildStep: '构建步骤', bsA: '无（直接运行）', bsB: '需要（tsc 编译器）', learning: '学习曲线', lcA: '低', lcB: '中等', ecosystem: '生态系统', ecoA: '通用', ecoB: '增长中（DefinitelyTyped）', errorDetection: '错误检测', edA: '仅运行时', edB: '编译时+运行时', refactoring: '重构', rfA: '有风险', rfB: '安全', whatIsA: '什么是 JavaScript？', aText: 'JavaScript 是 Web 编程语言，运行在所有浏览器和 Node.js 上。', whatIsB: '什么是 TypeScript？', bText: 'TypeScript 是微软开发的 JavaScript 类型化超集，添加了类型注解、接口、泛型等。', whenA: '何时使用 JavaScript', aUse1: '快速原型', aUse2: '小型项目', aUse3: '浏览器扩展', aUse4: '不想要构建工具时', aUse5: '学习 Web 开发', whenB: '何时使用 TypeScript', bUse1: '中大型代码库', bUse2: '团队项目', bUse3: '库和包', bUse4: '企业应用', bUse5: '复杂数据模型', verdict: '总结', verdictText: '团队维护或需要成长的项目用 TypeScript。快速脚本和原型用 JavaScript。TypeScript 正成为专业 JS 开发的默认选择。', tryTools: '试试我们的 TypeScript 工具', faqTitle: '常见问题', faq1q: 'TypeScript 比 JavaScript 难学吗？', faq1a: '在 JavaScript 基础上有中等学习曲线。所有 JS 都是有效的 TS，基本类型很直观。', faq2q: 'TypeScript 会让代码变慢吗？', faq2a: '不会。TypeScript 编译为纯 JavaScript，没有运行时性能开销。', faq3q: 'TypeScript 可以和 React 一起用吗？', faq3a: '可以，TypeScript 有优秀的 React 支持。使用 .tsx 文件即可。' },
  fr: { title: 'TypeScript vs JavaScript', description: 'Comparaison de TypeScript et JavaScript.', intro: 'TypeScript est un sur-ensemble type de JavaScript.', tableFeature: 'Caracteristique', tableA: 'JavaScript', tableB: 'TypeScript', typeSystem: 'Systeme de types', tsA: 'Dynamique', tsB: 'Statique', ide: 'Support IDE', ideA: 'Bon', ideB: 'Excellent', buildStep: 'Etape de build', bsA: 'Aucune', bsB: 'Requise (tsc)', learning: 'Courbe d\'apprentissage', lcA: 'Faible', lcB: 'Moderee', ecosystem: 'Ecosysteme', ecoA: 'Universel', ecoB: 'En croissance', errorDetection: 'Detection d\'erreurs', edA: 'Runtime uniquement', edB: 'Compilation + runtime', refactoring: 'Refactoring', rfA: 'Risque', rfB: 'Sur', whatIsA: 'Qu\'est-ce que JavaScript ?', aText: 'Langage de programmation du web, dans tous les navigateurs.', whatIsB: 'Qu\'est-ce que TypeScript ?', bText: 'Sur-ensemble type de JavaScript par Microsoft avec annotations de types, interfaces et generiques.', whenA: 'Quand JavaScript', aUse1: 'Prototypes rapides', aUse2: 'Petits projets', aUse3: 'Extensions navigateur', aUse4: 'Sans build tools', aUse5: 'Apprentissage', whenB: 'Quand TypeScript', bUse1: 'Grandes bases de code', bUse2: 'Projets d\'equipe', bUse3: 'Bibliotheques', bUse4: 'Applications entreprise', bUse5: 'Modeles de donnees complexes', verdict: 'Resume', verdictText: 'TypeScript pour les projets maintenus en equipe. JavaScript pour les scripts rapides.', tryTools: 'Essayez nos outils TypeScript', faqTitle: 'FAQ', faq1q: 'TypeScript est-il plus difficile ?', faq1a: 'Courbe d\'apprentissage moderee au-dessus de JavaScript.', faq2q: 'TypeScript ralentit-il le code ?', faq2a: 'Non, compile en JavaScript pur sans overhead.', faq3q: 'TypeScript avec React ?', faq3a: 'Oui, excellent support avec les fichiers .tsx.' },
  de: { title: 'TypeScript vs JavaScript', description: 'Vergleich von TypeScript und JavaScript.', intro: 'TypeScript ist eine typisierte Obermenge von JavaScript.', tableFeature: 'Eigenschaft', tableA: 'JavaScript', tableB: 'TypeScript', typeSystem: 'Typsystem', tsA: 'Dynamisch', tsB: 'Statisch', ide: 'IDE-Support', ideA: 'Gut', ideB: 'Ausgezeichnet', buildStep: 'Build-Schritt', bsA: 'Keiner', bsB: 'Erforderlich (tsc)', learning: 'Lernkurve', lcA: 'Niedrig', lcB: 'Mittel', ecosystem: 'Oekosystem', ecoA: 'Universal', ecoB: 'Wachsend', errorDetection: 'Fehlererkennung', edA: 'Nur Runtime', edB: 'Kompilierzeit + Runtime', refactoring: 'Refactoring', rfA: 'Riskant', rfB: 'Sicher', whatIsA: 'Was ist JavaScript?', aText: 'Programmiersprache des Webs, in allen Browsern.', whatIsB: 'Was ist TypeScript?', bText: 'Typisierte Obermenge von JavaScript von Microsoft mit Typennotationen, Interfaces und Generics.', whenA: 'Wann JavaScript', aUse1: 'Schnelle Prototypen', aUse2: 'Kleine Projekte', aUse3: 'Browser-Extensions', aUse4: 'Ohne Build-Tools', aUse5: 'Lernen', whenB: 'Wann TypeScript', bUse1: 'Grosse Codebasen', bUse2: 'Team-Projekte', bUse3: 'Bibliotheken', bUse4: 'Enterprise-Apps', bUse5: 'Komplexe Datenmodelle', verdict: 'Fazit', verdictText: 'TypeScript fuer Team-Projekte. JavaScript fuer schnelle Skripte.', tryTools: 'Probieren Sie unsere TypeScript-Tools', faqTitle: 'FAQ', faq1q: 'Ist TypeScript schwieriger?', faq1a: 'Mittlere Lernkurve ueber JavaScript hinaus.', faq2q: 'Macht TypeScript Code langsamer?', faq2a: 'Nein, kompiliert zu purem JavaScript ohne Overhead.', faq3q: 'TypeScript mit React?', faq3a: 'Ja, ausgezeichneter Support mit .tsx-Dateien.' },
  es: { title: 'TypeScript vs JavaScript', description: 'Comparacion de TypeScript y JavaScript.', intro: 'TypeScript es un superconjunto tipado de JavaScript.', tableFeature: 'Caracteristica', tableA: 'JavaScript', tableB: 'TypeScript', typeSystem: 'Sistema de tipos', tsA: 'Dinamico', tsB: 'Estatico', ide: 'Soporte IDE', ideA: 'Bueno', ideB: 'Excelente', buildStep: 'Paso de build', bsA: 'Ninguno', bsB: 'Requerido (tsc)', learning: 'Curva de aprendizaje', lcA: 'Baja', lcB: 'Moderada', ecosystem: 'Ecosistema', ecoA: 'Universal', ecoB: 'Creciendo', errorDetection: 'Deteccion de errores', edA: 'Solo runtime', edB: 'Compilacion + runtime', refactoring: 'Refactoring', rfA: 'Riesgoso', rfB: 'Seguro', whatIsA: 'Que es JavaScript?', aText: 'Lenguaje de programacion de la web, en todos los navegadores.', whatIsB: 'Que es TypeScript?', bText: 'Superconjunto tipado de JavaScript por Microsoft con tipos, interfaces y genericos.', whenA: 'Cuando JavaScript', aUse1: 'Prototipos rapidos', aUse2: 'Proyectos pequenos', aUse3: 'Extensiones de navegador', aUse4: 'Sin build tools', aUse5: 'Aprendizaje', whenB: 'Cuando TypeScript', bUse1: 'Grandes bases de codigo', bUse2: 'Proyectos de equipo', bUse3: 'Bibliotecas', bUse4: 'Apps empresariales', bUse5: 'Modelos de datos complejos', verdict: 'Resumen', verdictText: 'TypeScript para proyectos de equipo. JavaScript para scripts rapidos.', tryTools: 'Prueba nuestras herramientas TypeScript', faqTitle: 'FAQ', faq1q: 'TypeScript es mas dificil?', faq1a: 'Curva de aprendizaje moderada sobre JavaScript.', faq2q: 'TypeScript hace el codigo mas lento?', faq2a: 'No, compila a JavaScript puro sin overhead.', faq3q: 'TypeScript con React?', faq3a: 'Si, excelente soporte con archivos .tsx.' },
  ja: { title: 'TypeScript vs JavaScript', description: 'TypeScriptとJavaScriptの詳細な比較。', intro: 'TypeScriptはJavaScriptの型付きスーパーセットです。', tableFeature: '特性', tableA: 'JavaScript', tableB: 'TypeScript', typeSystem: '型システム', tsA: '動的', tsB: '静的', ide: 'IDEサポート', ideA: '良い', ideB: '優秀', buildStep: 'ビルドステップ', bsA: 'なし', bsB: '必要（tsc）', learning: '学習コスト', lcA: '低い', lcB: '中程度', ecosystem: 'エコシステム', ecoA: 'ユニバーサル', ecoB: '成長中', errorDetection: 'エラー検出', edA: 'ランタイムのみ', edB: 'コンパイル時+ランタイム', refactoring: 'リファクタリング', rfA: 'リスクあり', rfB: '安全', whatIsA: 'JavaScriptとは？', aText: 'Webのプログラミング言語。全ブラウザとNode.jsで動作。', whatIsB: 'TypeScriptとは？', bText: 'MicrosoftのJavaScript型付きスーパーセット。型注釈、インターフェース、ジェネリクスを追加。', whenA: 'JavaScript使用時', aUse1: '素早いプロトタイプ', aUse2: '小規模プロジェクト', aUse3: 'ブラウザ拡張', aUse4: 'ビルド不要の場合', aUse5: '学習', whenB: 'TypeScript使用時', bUse1: '中〜大規模コードベース', bUse2: 'チームプロジェクト', bUse3: 'ライブラリ', bUse4: 'エンタープライズ', bUse5: '複雑なデータモデル', verdict: 'まとめ', verdictText: 'チームプロジェクトにはTypeScript。クイックスクリプトにはJavaScript。', tryTools: 'TypeScriptツールを試す', faqTitle: 'FAQ', faq1q: 'TypeScriptは難しい？', faq1a: 'JavaScript上に中程度の学習コスト。', faq2q: 'TypeScriptはコードを遅くする？', faq2a: 'いいえ、純粋なJSにコンパイルされオーバーヘッドなし。', faq3q: 'TypeScriptでReact？', faq3a: 'はい、.tsxファイルで優れたサポート。' },
  ko: { title: 'TypeScript vs JavaScript', description: 'TypeScript와 JavaScript의 상세 비교.', intro: 'TypeScript는 JavaScript의 타입 있는 상위 집합입니다.', tableFeature: '특성', tableA: 'JavaScript', tableB: 'TypeScript', typeSystem: '타입 시스템', tsA: '동적', tsB: '정적', ide: 'IDE 지원', ideA: '양호', ideB: '우수', buildStep: '빌드 단계', bsA: '없음', bsB: '필요 (tsc)', learning: '학습 곡선', lcA: '낮음', lcB: '보통', ecosystem: '생태계', ecoA: '범용', ecoB: '성장 중', errorDetection: '오류 감지', edA: '런타임만', edB: '컴파일 시+런타임', refactoring: '리팩토링', rfA: '위험', rfB: '안전', whatIsA: 'JavaScript란?', aText: '웹 프로그래밍 언어. 모든 브라우저와 Node.js에서 실행.', whatIsB: 'TypeScript란?', bText: 'Microsoft의 JavaScript 타입 상위 집합. 타입 주석, 인터페이스, 제네릭 추가.', whenA: 'JavaScript 사용 시', aUse1: '빠른 프로토타입', aUse2: '소규모 프로젝트', aUse3: '브라우저 확장', aUse4: '빌드 도구 불필요 시', aUse5: '학습', whenB: 'TypeScript 사용 시', bUse1: '중대규모 코드베이스', bUse2: '팀 프로젝트', bUse3: '라이브러리', bUse4: '엔터프라이즈 앱', bUse5: '복잡한 데이터 모델', verdict: '요약', verdictText: '팀 프로젝트에는 TypeScript. 빠른 스크립트에는 JavaScript.', tryTools: 'TypeScript 도구 사용해보기', faqTitle: 'FAQ', faq1q: 'TypeScript가 더 어려운가요?', faq1a: 'JavaScript 위에 보통 수준의 학습 곡선.', faq2q: 'TypeScript가 코드를 느리게 하나요?', faq2a: '아닙니다, 순수 JS로 컴파일되어 오버헤드 없음.', faq3q: 'TypeScript로 React를?', faq3a: '네, .tsx 파일로 훌륭한 지원.' },
};

const tableStyle={width:'100%',borderCollapse:'collapse' as const,fontSize:14};const thStyle={padding:'10px 14px',textAlign:'left' as const,borderBottom:'2px solid var(--border-color)',fontWeight:700};const tdStyle={padding:'10px 14px',borderBottom:'1px solid var(--border-color)'};const sectionStyle={marginTop:32};const h2Style={fontSize:22,fontWeight:700,marginBottom:12};const h3Style={fontSize:17,fontWeight:600,marginBottom:8};const pStyle={fontSize:14,lineHeight:1.8,color:'var(--text-secondary)',marginBottom:16};const ulStyle={fontSize:14,lineHeight:1.8,color:'var(--text-secondary)',paddingLeft:20,marginBottom:16};const cardStyle={background:'var(--bg-card)',borderRadius:12,padding:20,border:'1px solid var(--border-color)',marginBottom:16};

export default function TypescriptVsJavascript() {
  const { lang } = useLang(); const ui = t[lang] || t.en;
  const faqSchema = {'@context':'https://schema.org','@type':'FAQPage',mainEntity:[{'@type':'Question',name:ui.faq1q,acceptedAnswer:{'@type':'Answer',text:ui.faq1a}},{'@type':'Question',name:ui.faq2q,acceptedAnswer:{'@type':'Answer',text:ui.faq2a}},{'@type':'Question',name:ui.faq3q,acceptedAnswer:{'@type':'Answer',text:ui.faq3a}}]};
  return (
    <ToolLayout title={ui.title} description={ui.description} toolId="typescript-vs-javascript">
      <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(faqSchema)}} />
      <p style={pStyle}>{ui.intro}</p>
      <div style={{overflowX:'auto',marginBottom:24}}><table style={tableStyle}><thead><tr><th style={thStyle}>{ui.tableFeature}</th><th style={thStyle}>{ui.tableA}</th><th style={thStyle}>{ui.tableB}</th></tr></thead><tbody>{[[ui.typeSystem,ui.tsA,ui.tsB],[ui.ide,ui.ideA,ui.ideB],[ui.buildStep,ui.bsA,ui.bsB],[ui.learning,ui.lcA,ui.lcB],[ui.ecosystem,ui.ecoA,ui.ecoB],[ui.errorDetection,ui.edA,ui.edB],[ui.refactoring,ui.rfA,ui.rfB]].map(([f,a,b],i)=>(<tr key={i}><td style={{...tdStyle,fontWeight:600}}>{f}</td><td style={tdStyle}>{a}</td><td style={tdStyle}>{b}</td></tr>))}</tbody></table></div>
      <div style={sectionStyle}><h2 style={h2Style}>{ui.whatIsA}</h2><p style={pStyle}>{ui.aText}</p></div>
      <div style={sectionStyle}><h2 style={h2Style}>{ui.whatIsB}</h2><p style={pStyle}>{ui.bText}</p></div>
      <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))',gap:16,...sectionStyle}}>
        <div style={cardStyle}><h3 style={h3Style}>{ui.whenA}</h3><ul style={ulStyle}><li>{ui.aUse1}</li><li>{ui.aUse2}</li><li>{ui.aUse3}</li><li>{ui.aUse4}</li><li>{ui.aUse5}</li></ul></div>
        <div style={cardStyle}><h3 style={h3Style}>{ui.whenB}</h3><ul style={ulStyle}><li>{ui.bUse1}</li><li>{ui.bUse2}</li><li>{ui.bUse3}</li><li>{ui.bUse4}</li><li>{ui.bUse5}</li></ul></div>
      </div>
      <div style={{...cardStyle,background:'var(--bg-input)',...sectionStyle}}><h2 style={h2Style}>{ui.verdict}</h2><p style={{...pStyle,fontWeight:500}}>{ui.verdictText}</p></div>
      <div style={sectionStyle}><h2 style={h2Style}>{ui.tryTools}</h2><div style={{display:'flex',flexWrap:'wrap',gap:8}}>{[{href:`/${lang}/tools/json-to-typescript`,label:'JSON to TypeScript'},{href:`/${lang}/tools/typescript-to-javascript`,label:'TypeScript to JavaScript'},{href:`/${lang}/tools/json-formatter`,label:'JSON Formatter'},{href:`/${lang}/tools/regex-tester`,label:'Regex Tester'}].map(link=>(<Link key={link.href} href={link.href} style={{display:'inline-block',padding:'8px 16px',borderRadius:8,border:'1px solid var(--border-color)',fontSize:13,color:'var(--accent-blue)',textDecoration:'none',background:'var(--bg-input)'}}>{link.label}</Link>))}</div></div>
      <div style={sectionStyle}><h2 style={h2Style}>{ui.faqTitle}</h2><div style={{display:'flex',flexDirection:'column',gap:8}}>{[{q:ui.faq1q,a:ui.faq1a},{q:ui.faq2q,a:ui.faq2a},{q:ui.faq3q,a:ui.faq3a}].map((faq,idx)=>(<details key={idx} style={{border:'1px solid var(--border-color)',borderRadius:8,overflow:'hidden',background:'var(--bg-input)'}}><summary style={{padding:'14px 16px',cursor:'pointer',fontSize:14,fontWeight:600}}>{faq.q}</summary><div style={{padding:'0 16px 14px',fontSize:13,lineHeight:1.7,color:'var(--text-secondary)'}}>{faq.a}</div></details>))}</div></div>
    </ToolLayout>
  );
}
