'use client';

import Link from 'next/link';
import { useLang } from '@/i18n/LangContext';
import ToolLayout from '@/components/ToolLayout';

const t: Record<string, Record<string, string>> = {
  en: {
    title: 'npm vs Yarn vs pnpm', description: 'A detailed comparison of npm, Yarn, and pnpm package managers.',
    intro: 'npm, Yarn, and pnpm are the three major JavaScript package managers. Each takes a different approach to dependency management, offering distinct trade-offs in speed, disk usage, and features.',
    tableFeature: 'Feature', tableA: 'npm', tableB: 'Yarn', tableC: 'pnpm',
    speed: 'Install Speed', spdA: 'Moderate', spdB: 'Fast (parallel)', spdC: 'Fastest (content-addressable)',
    disk: 'Disk Usage', dskA: 'High (duplicated)', dskB: 'High (duplicated)', dskC: 'Low (shared store)',
    lockFile: 'Lock File', lfA: 'package-lock.json', lfB: 'yarn.lock', lfC: 'pnpm-lock.yaml',
    workspaces: 'Workspaces', wsA: 'Supported (v7+)', wsB: 'Native (pioneered)', wsC: 'Native + filtering',
    pnp: 'Plug\'n\'Play', ppA: 'No', ppB: 'Yes (Yarn Berry)', ppC: 'No (strict node_modules)',
    security: 'Security', secA: 'npm audit', secB: 'yarn audit', secC: 'Strict by default',
    strictness: 'Strictness', strA: 'Hoists everything', strB: 'Hoists everything', strC: 'Strict (no phantom deps)',
    whatIsA: 'What is npm?', aText: 'npm (Node Package Manager) is the default package manager for Node.js, bundled with every Node.js installation. It manages the world\'s largest software registry with over 2 million packages. npm introduced package-lock.json for deterministic installs and has significantly improved performance since v7.',
    whatIsB: 'What is Yarn?', bText: 'Yarn was created by Facebook in 2016 to address npm\'s speed and consistency issues. Yarn Classic (v1) introduced parallel downloads, offline caching, and deterministic installs. Yarn Berry (v2+) introduced Plug\'n\'Play (PnP) which eliminates node_modules entirely, storing dependencies in .pnp.cjs for faster startup.',
    whatIsC: 'What is pnpm?', cText: 'pnpm (performant npm) uses a content-addressable store that saves one copy of each package version globally and creates hard links in projects. This dramatically reduces disk usage and installation time. pnpm also enforces strict dependency resolution, preventing phantom dependencies that plague npm and Yarn.',
    whenA: 'When to Use npm', aUse1: 'Default Node.js projects', aUse2: 'CI/CD environments (no extra install)', aUse3: 'Simple projects with few dependencies', aUse4: 'When team familiarity matters', aUse5: 'Following tutorials and documentation',
    whenB: 'When to Use Yarn', bUse1: 'Large monorepos (pioneered workspaces)', bUse2: 'When you need Plug\'n\'Play (PnP)', bUse3: 'Facebook/Meta ecosystem projects', bUse4: 'When offline caching is important', bUse5: 'Projects needing advanced workspace features',
    whenC: 'When to Use pnpm', cUse1: 'Disk space constrained environments', cUse2: 'Large monorepos (excellent workspace support)', cUse3: 'When you want strict dependency isolation', cUse4: 'CI/CD pipelines (fastest installs)', cUse5: 'Projects with many shared dependencies',
    verdict: 'TL;DR / Verdict', verdictText: 'Use npm for simplicity and compatibility. Use Yarn for monorepos and PnP. Use pnpm for the best speed, disk efficiency, and strict dependency management. pnpm is increasingly the recommended choice for new projects, while npm remains the safe default.',
    tryTools: 'Try Our Dev Tools', faqTitle: 'Frequently Asked Questions',
    faq1q: 'Can I switch between package managers?', faq1a: 'Yes, you can switch by deleting node_modules and the old lock file, then running install with the new manager. Use corepack (built into Node.js 16+) to manage package manager versions. Be aware that lock file formats differ, so the exact resolved versions may change.',
    faq2q: 'What are phantom dependencies?', faq2a: 'Phantom dependencies are packages your code imports but that are not listed in your package.json. They work with npm/Yarn because hoisting makes them accessible, but they can break when dependency versions change. pnpm prevents this by default with its strict node_modules structure.',
    faq3q: 'Which is best for monorepos?', faq3a: 'All three support workspaces, but pnpm and Yarn offer the most mature support. pnpm has excellent filtering (--filter), content-addressable storage, and strict isolation. Yarn Berry offers advanced workspace protocols and constraints. npm workspaces are simpler but less feature-rich.',
  },
  zh: { title: 'npm vs Yarn vs pnpm', description: 'npm、Yarn 和 pnpm 包管理器的详细对比。', intro: 'npm、Yarn 和 pnpm 是三大 JavaScript 包管理器，各有不同的依赖管理方式。', tableFeature: '特性', tableA: 'npm', tableB: 'Yarn', tableC: 'pnpm', speed: '安装速度', spdA: '中等', spdB: '快（并行）', spdC: '最快（内容寻址）', disk: '磁盘使用', dskA: '高（重复）', dskB: '高（重复）', dskC: '低（共享存储）', lockFile: '锁文件', lfA: 'package-lock.json', lfB: 'yarn.lock', lfC: 'pnpm-lock.yaml', workspaces: '工作区', wsA: '支持（v7+）', wsB: '原生（首创）', wsC: '原生 + 过滤', pnp: 'Plug\'n\'Play', ppA: '否', ppB: '是（Yarn Berry）', ppC: '否（严格 node_modules）', security: '安全', secA: 'npm audit', secB: 'yarn audit', secC: '默认严格', strictness: '严格性', strA: '提升所有', strB: '提升所有', strC: '严格（无幻影依赖）', whatIsA: '什么是 npm？', aText: 'npm 是 Node.js 默认包管理器，拥有超过 200 万个包。', whatIsB: '什么是 Yarn？', bText: 'Facebook 于 2016 年创建的包管理器，Yarn Berry 引入了 Plug\'n\'Play。', whatIsC: '什么是 pnpm？', cText: 'pnpm 使用内容寻址存储，大幅减少磁盘使用和安装时间，并严格隔离依赖。', whenA: '何时使用 npm', aUse1: '默认 Node.js 项目', aUse2: 'CI/CD（无需额外安装）', aUse3: '简单项目', aUse4: '团队熟悉度优先', aUse5: '跟随教程', whenB: '何时使用 Yarn', bUse1: '大型 monorepo', bUse2: '需要 PnP', bUse3: 'Meta 生态项目', bUse4: '离线缓存重要时', bUse5: '高级工作区功能', whenC: '何时使用 pnpm', cUse1: '磁盘空间受限', cUse2: '大型 monorepo', cUse3: '严格依赖隔离', cUse4: 'CI/CD 管道（最快安装）', cUse5: '大量共享依赖的项目', verdict: '总结', verdictText: 'npm 最简单兼容。Yarn 适合 monorepo 和 PnP。pnpm 速度最快、磁盘最省、依赖最严格。', tryTools: '试试我们的开发工具', faqTitle: '常见问题', faq1q: '可以切换包管理器吗？', faq1a: '可以，删除 node_modules 和旧锁文件后用新管理器安装即可。', faq2q: '什么是幻影依赖？', faq2a: '代码引用但未在 package.json 中列出的包。pnpm 默认阻止这种情况。', faq3q: '哪个最适合 monorepo？', faq3a: 'pnpm 和 Yarn 的工作区支持最成熟，各有优势。' },
  fr: { title: 'npm vs Yarn vs pnpm', description: 'Comparaison de npm, Yarn et pnpm.', intro: 'npm, Yarn et pnpm sont les trois principaux gestionnaires de paquets JavaScript.', tableFeature: 'Caracteristique', tableA: 'npm', tableB: 'Yarn', tableC: 'pnpm', speed: 'Vitesse d\'installation', spdA: 'Moderee', spdB: 'Rapide', spdC: 'La plus rapide', disk: 'Espace disque', dskA: 'Eleve', dskB: 'Eleve', dskC: 'Faible', lockFile: 'Fichier lock', lfA: 'package-lock.json', lfB: 'yarn.lock', lfC: 'pnpm-lock.yaml', workspaces: 'Workspaces', wsA: 'Supporte', wsB: 'Natif', wsC: 'Natif + filtrage', pnp: 'PnP', ppA: 'Non', ppB: 'Oui', ppC: 'Non', security: 'Securite', secA: 'npm audit', secB: 'yarn audit', secC: 'Strict par defaut', strictness: 'Stricte', strA: 'Hoist tout', strB: 'Hoist tout', strC: 'Strict', whatIsA: 'Qu\'est-ce que npm ?', aText: 'Gestionnaire par defaut de Node.js avec plus de 2 millions de paquets.', whatIsB: 'Qu\'est-ce que Yarn ?', bText: 'Cree par Facebook en 2016, avec Plug\'n\'Play dans Yarn Berry.', whatIsC: 'Qu\'est-ce que pnpm ?', cText: 'Utilise un stockage adressable par contenu pour reduire l\'utilisation disque.', whenA: 'Quand npm', aUse1: 'Projets Node.js par defaut', aUse2: 'CI/CD', aUse3: 'Projets simples', aUse4: 'Familiarite equipe', aUse5: 'Tutoriels', whenB: 'Quand Yarn', bUse1: 'Grands monorepos', bUse2: 'PnP necessaire', bUse3: 'Ecosysteme Meta', bUse4: 'Cache hors ligne', bUse5: 'Workspaces avances', whenC: 'Quand pnpm', cUse1: 'Espace disque limite', cUse2: 'Grands monorepos', cUse3: 'Isolation stricte', cUse4: 'CI/CD rapide', cUse5: 'Dependances partagees', verdict: 'Resume', verdictText: 'npm pour la simplicite. Yarn pour monorepos et PnP. pnpm pour vitesse et efficacite.', tryTools: 'Essayez nos outils', faqTitle: 'FAQ', faq1q: 'Peut-on changer de gestionnaire ?', faq1a: 'Oui, supprimez node_modules et le lock file.', faq2q: 'Dependances fantomes ?', faq2a: 'Paquets importes mais non listes dans package.json. pnpm les previent.', faq3q: 'Lequel pour monorepos ?', faq3a: 'pnpm et Yarn sont les plus matures.' },
  de: { title: 'npm vs Yarn vs pnpm', description: 'Vergleich von npm, Yarn und pnpm.', intro: 'npm, Yarn und pnpm sind die drei grossen JavaScript-Paketmanager.', tableFeature: 'Eigenschaft', tableA: 'npm', tableB: 'Yarn', tableC: 'pnpm', speed: 'Installationsgeschwindigkeit', spdA: 'Mittel', spdB: 'Schnell', spdC: 'Am schnellsten', disk: 'Speicherplatz', dskA: 'Hoch', dskB: 'Hoch', dskC: 'Niedrig', lockFile: 'Lock-Datei', lfA: 'package-lock.json', lfB: 'yarn.lock', lfC: 'pnpm-lock.yaml', workspaces: 'Workspaces', wsA: 'Unterstuetzt', wsB: 'Nativ', wsC: 'Nativ + Filterung', pnp: 'PnP', ppA: 'Nein', ppB: 'Ja', ppC: 'Nein', security: 'Sicherheit', secA: 'npm audit', secB: 'yarn audit', secC: 'Strikt', strictness: 'Striktheit', strA: 'Hoistet alles', strB: 'Hoistet alles', strC: 'Strikt', whatIsA: 'Was ist npm?', aText: 'Standard-Paketmanager fuer Node.js mit ueber 2 Millionen Paketen.', whatIsB: 'Was ist Yarn?', bText: 'Von Facebook 2016 erstellt, mit Plug\'n\'Play in Yarn Berry.', whatIsC: 'Was ist pnpm?', cText: 'Nutzt Content-Addressable-Storage fuer minimalen Speicherverbrauch.', whenA: 'Wann npm', aUse1: 'Standard-Node.js-Projekte', aUse2: 'CI/CD', aUse3: 'Einfache Projekte', aUse4: 'Team-Vertrautheit', aUse5: 'Tutorials', whenB: 'Wann Yarn', bUse1: 'Grosse Monorepos', bUse2: 'PnP benoetigt', bUse3: 'Meta-Oekosystem', bUse4: 'Offline-Cache', bUse5: 'Erweiterte Workspaces', whenC: 'Wann pnpm', cUse1: 'Speicherplatz begrenzt', cUse2: 'Grosse Monorepos', cUse3: 'Strikte Isolation', cUse4: 'Schnelle CI/CD', cUse5: 'Geteilte Abhaengigkeiten', verdict: 'Fazit', verdictText: 'npm fuer Einfachheit. Yarn fuer Monorepos und PnP. pnpm fuer Geschwindigkeit und Effizienz.', tryTools: 'Probieren Sie unsere Tools', faqTitle: 'FAQ', faq1q: 'Kann man wechseln?', faq1a: 'Ja, node_modules und Lock-Datei loeschen.', faq2q: 'Phantom-Dependencies?', faq2a: 'Importierte aber nicht gelistete Pakete. pnpm verhindert dies.', faq3q: 'Welcher fuer Monorepos?', faq3a: 'pnpm und Yarn sind am ausgereiftesten.' },
  es: { title: 'npm vs Yarn vs pnpm', description: 'Comparacion de npm, Yarn y pnpm.', intro: 'npm, Yarn y pnpm son los tres principales gestores de paquetes JavaScript.', tableFeature: 'Caracteristica', tableA: 'npm', tableB: 'Yarn', tableC: 'pnpm', speed: 'Velocidad instalacion', spdA: 'Moderada', spdB: 'Rapida', spdC: 'La mas rapida', disk: 'Uso de disco', dskA: 'Alto', dskB: 'Alto', dskC: 'Bajo', lockFile: 'Archivo lock', lfA: 'package-lock.json', lfB: 'yarn.lock', lfC: 'pnpm-lock.yaml', workspaces: 'Workspaces', wsA: 'Soportado', wsB: 'Nativo', wsC: 'Nativo + filtrado', pnp: 'PnP', ppA: 'No', ppB: 'Si', ppC: 'No', security: 'Seguridad', secA: 'npm audit', secB: 'yarn audit', secC: 'Estricto', strictness: 'Estrictez', strA: 'Eleva todo', strB: 'Eleva todo', strC: 'Estricto', whatIsA: 'Que es npm?', aText: 'Gestor por defecto de Node.js con mas de 2 millones de paquetes.', whatIsB: 'Que es Yarn?', bText: 'Creado por Facebook en 2016, con Plug\'n\'Play en Yarn Berry.', whatIsC: 'Que es pnpm?', cText: 'Usa almacenamiento direccionable por contenido para reducir uso de disco.', whenA: 'Cuando npm', aUse1: 'Proyectos Node.js por defecto', aUse2: 'CI/CD', aUse3: 'Proyectos simples', aUse4: 'Familiaridad del equipo', aUse5: 'Tutoriales', whenB: 'Cuando Yarn', bUse1: 'Grandes monorepos', bUse2: 'PnP necesario', bUse3: 'Ecosistema Meta', bUse4: 'Cache offline', bUse5: 'Workspaces avanzados', whenC: 'Cuando pnpm', cUse1: 'Espacio limitado', cUse2: 'Grandes monorepos', cUse3: 'Aislamiento estricto', cUse4: 'CI/CD rapido', cUse5: 'Dependencias compartidas', verdict: 'Resumen', verdictText: 'npm para simplicidad. Yarn para monorepos y PnP. pnpm para velocidad y eficiencia.', tryTools: 'Prueba nuestras herramientas', faqTitle: 'FAQ', faq1q: 'Se puede cambiar?', faq1a: 'Si, borrar node_modules y el lock file.', faq2q: 'Dependencias fantasma?', faq2a: 'Paquetes importados pero no listados. pnpm las previene.', faq3q: 'Cual para monorepos?', faq3a: 'pnpm y Yarn son los mas maduros.' },
  ja: { title: 'npm vs Yarn vs pnpm', description: 'npm、Yarn、pnpmの詳細な比較。', intro: 'npm、Yarn、pnpmはJavaScriptの3大パッケージマネージャーです。', tableFeature: '特性', tableA: 'npm', tableB: 'Yarn', tableC: 'pnpm', speed: 'インストール速度', spdA: '普通', spdB: '速い', spdC: '最速', disk: 'ディスク使用量', dskA: '多い', dskB: '多い', dskC: '少ない', lockFile: 'ロックファイル', lfA: 'package-lock.json', lfB: 'yarn.lock', lfC: 'pnpm-lock.yaml', workspaces: 'ワークスペース', wsA: '対応', wsB: 'ネイティブ', wsC: 'ネイティブ+フィルタ', pnp: 'PnP', ppA: 'なし', ppB: 'あり', ppC: 'なし', security: 'セキュリティ', secA: 'npm audit', secB: 'yarn audit', secC: 'デフォルトで厳格', strictness: '厳格さ', strA: '全てホイスト', strB: '全てホイスト', strC: '厳格', whatIsA: 'npmとは？', aText: 'Node.jsデフォルトのパッケージマネージャー。200万以上のパッケージ。', whatIsB: 'Yarnとは？', bText: 'Facebook が2016年に作成。Yarn BerryはPlug\'n\'Playを導入。', whatIsC: 'pnpmとは？', cText: 'コンテンツアドレス可能ストレージでディスク使用量を削減。', whenA: 'npm使用時', aUse1: 'デフォルトNode.jsプロジェクト', aUse2: 'CI/CD', aUse3: 'シンプルなプロジェクト', aUse4: 'チーム慣れ', aUse5: 'チュートリアル', whenB: 'Yarn使用時', bUse1: '大規模モノレポ', bUse2: 'PnP必要', bUse3: 'Metaエコシステム', bUse4: 'オフラインキャッシュ', bUse5: '高度なワークスペース', whenC: 'pnpm使用時', cUse1: 'ディスク制限環境', cUse2: '大規模モノレポ', cUse3: '厳格な分離', cUse4: '高速CI/CD', cUse5: '共有依存関係が多い', verdict: 'まとめ', verdictText: 'npmはシンプルさ。Yarnはモノレポ+PnP。pnpmは速度と効率。', tryTools: 'ツールを試す', faqTitle: 'FAQ', faq1q: '切り替え可能？', faq1a: 'はい、node_modulesとロックファイルを削除して再インストール。', faq2q: 'ファントム依存関係とは？', faq2a: 'package.jsonに未記載のインポート。pnpmはこれを防止。', faq3q: 'モノレポにはどれ？', faq3a: 'pnpmとYarnが最も成熟。' },
  ko: { title: 'npm vs Yarn vs pnpm', description: 'npm, Yarn, pnpm의 상세 비교.', intro: 'npm, Yarn, pnpm은 JavaScript의 3대 패키지 매니저입니다.', tableFeature: '특성', tableA: 'npm', tableB: 'Yarn', tableC: 'pnpm', speed: '설치 속도', spdA: '보통', spdB: '빠름', spdC: '가장 빠름', disk: '디스크 사용', dskA: '높음', dskB: '높음', dskC: '낮음', lockFile: '락 파일', lfA: 'package-lock.json', lfB: 'yarn.lock', lfC: 'pnpm-lock.yaml', workspaces: '워크스페이스', wsA: '지원', wsB: '네이티브', wsC: '네이티브+필터', pnp: 'PnP', ppA: '없음', ppB: '있음', ppC: '없음', security: '보안', secA: 'npm audit', secB: 'yarn audit', secC: '기본 엄격', strictness: '엄격성', strA: '모두 호이스트', strB: '모두 호이스트', strC: '엄격', whatIsA: 'npm이란?', aText: 'Node.js 기본 패키지 매니저. 200만+ 패키지.', whatIsB: 'Yarn이란?', bText: 'Facebook이 2016년 만듦. Yarn Berry는 PnP 도입.', whatIsC: 'pnpm이란?', cText: '콘텐츠 주소 지정 가능 스토어로 디스크 사용량 감소.', whenA: 'npm 사용 시', aUse1: '기본 Node.js 프로젝트', aUse2: 'CI/CD', aUse3: '간단한 프로젝트', aUse4: '팀 친숙도', aUse5: '튜토리얼', whenB: 'Yarn 사용 시', bUse1: '대규모 모노레포', bUse2: 'PnP 필요', bUse3: 'Meta 생태계', bUse4: '오프라인 캐시', bUse5: '고급 워크스페이스', whenC: 'pnpm 사용 시', cUse1: '디스크 제한 환경', cUse2: '대규모 모노레포', cUse3: '엄격한 격리', cUse4: '빠른 CI/CD', cUse5: '공유 의존성 많은 프로젝트', verdict: '요약', verdictText: 'npm은 단순함. Yarn은 모노레포+PnP. pnpm은 속도와 효율.', tryTools: '도구 사용해보기', faqTitle: 'FAQ', faq1q: '전환할 수 있나요?', faq1a: '네, node_modules와 락 파일을 삭제하고 재설치하세요.', faq2q: '팬텀 의존성이란?', faq2a: 'package.json에 없는 임포트. pnpm이 이를 방지합니다.', faq3q: '모노레포에는 어떤 것?', faq3a: 'pnpm과 Yarn이 가장 성숙합니다.' },
};

const tableStyle={width:'100%',borderCollapse:'collapse' as const,fontSize:14};const thStyle={padding:'10px 14px',textAlign:'left' as const,borderBottom:'2px solid var(--border-color)',fontWeight:700};const tdStyle={padding:'10px 14px',borderBottom:'1px solid var(--border-color)'};const sectionStyle={marginTop:32};const h2Style={fontSize:22,fontWeight:700,marginBottom:12};const h3Style={fontSize:17,fontWeight:600,marginBottom:8};const pStyle={fontSize:14,lineHeight:1.8,color:'var(--text-secondary)',marginBottom:16};const ulStyle={fontSize:14,lineHeight:1.8,color:'var(--text-secondary)',paddingLeft:20,marginBottom:16};const cardStyle={background:'var(--bg-card)',borderRadius:12,padding:20,border:'1px solid var(--border-color)',marginBottom:16};

export default function NpmVsYarnVsPnpm() {
  const { lang } = useLang(); const ui = t[lang] || t.en;
  const faqSchema = {'@context':'https://schema.org','@type':'FAQPage',mainEntity:[{'@type':'Question',name:ui.faq1q,acceptedAnswer:{'@type':'Answer',text:ui.faq1a}},{'@type':'Question',name:ui.faq2q,acceptedAnswer:{'@type':'Answer',text:ui.faq2a}},{'@type':'Question',name:ui.faq3q,acceptedAnswer:{'@type':'Answer',text:ui.faq3a}}]};
  return (
    <ToolLayout title={ui.title} description={ui.description} toolId="npm-vs-yarn-vs-pnpm">
      <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(faqSchema)}} />
      <p style={pStyle}>{ui.intro}</p>
      <div style={{overflowX:'auto',marginBottom:24}}><table style={tableStyle}><thead><tr><th style={thStyle}>{ui.tableFeature}</th><th style={thStyle}>{ui.tableA}</th><th style={thStyle}>{ui.tableB}</th><th style={thStyle}>{ui.tableC}</th></tr></thead><tbody>{[[ui.speed,ui.spdA,ui.spdB,ui.spdC],[ui.disk,ui.dskA,ui.dskB,ui.dskC],[ui.lockFile,ui.lfA,ui.lfB,ui.lfC],[ui.workspaces,ui.wsA,ui.wsB,ui.wsC],[ui.pnp,ui.ppA,ui.ppB,ui.ppC],[ui.security,ui.secA,ui.secB,ui.secC],[ui.strictness,ui.strA,ui.strB,ui.strC]].map(([f,a,b,c],i)=>(<tr key={i}><td style={{...tdStyle,fontWeight:600}}>{f}</td><td style={tdStyle}>{a}</td><td style={tdStyle}>{b}</td><td style={tdStyle}>{c}</td></tr>))}</tbody></table></div>
      <div style={sectionStyle}><h2 style={h2Style}>{ui.whatIsA}</h2><p style={pStyle}>{ui.aText}</p></div>
      <div style={sectionStyle}><h2 style={h2Style}>{ui.whatIsB}</h2><p style={pStyle}>{ui.bText}</p></div>
      <div style={sectionStyle}><h2 style={h2Style}>{ui.whatIsC}</h2><p style={pStyle}>{ui.cText}</p></div>
      <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(250px,1fr))',gap:16,...sectionStyle}}>
        <div style={cardStyle}><h3 style={h3Style}>{ui.whenA}</h3><ul style={ulStyle}><li>{ui.aUse1}</li><li>{ui.aUse2}</li><li>{ui.aUse3}</li><li>{ui.aUse4}</li><li>{ui.aUse5}</li></ul></div>
        <div style={cardStyle}><h3 style={h3Style}>{ui.whenB}</h3><ul style={ulStyle}><li>{ui.bUse1}</li><li>{ui.bUse2}</li><li>{ui.bUse3}</li><li>{ui.bUse4}</li><li>{ui.bUse5}</li></ul></div>
        <div style={cardStyle}><h3 style={h3Style}>{ui.whenC}</h3><ul style={ulStyle}><li>{ui.cUse1}</li><li>{ui.cUse2}</li><li>{ui.cUse3}</li><li>{ui.cUse4}</li><li>{ui.cUse5}</li></ul></div>
      </div>
      <div style={{...cardStyle,background:'var(--bg-input)',...sectionStyle}}><h2 style={h2Style}>{ui.verdict}</h2><p style={{...pStyle,fontWeight:500}}>{ui.verdictText}</p></div>
      <div style={sectionStyle}><h2 style={h2Style}>{ui.tryTools}</h2><div style={{display:'flex',flexWrap:'wrap',gap:8}}>{[{href:`/${lang}/tools/json-formatter`,label:'JSON Formatter'},{href:`/${lang}/tools/gitignore-generator`,label:'Gitignore Generator'},{href:`/${lang}/tools/json-validator`,label:'JSON Validator'}].map(link=>(<Link key={link.href} href={link.href} style={{display:'inline-block',padding:'8px 16px',borderRadius:8,border:'1px solid var(--border-color)',fontSize:13,color:'var(--accent-blue)',textDecoration:'none',background:'var(--bg-input)'}}>{link.label}</Link>))}</div></div>
      <div style={sectionStyle}><h2 style={h2Style}>{ui.faqTitle}</h2><div style={{display:'flex',flexDirection:'column',gap:8}}>{[{q:ui.faq1q,a:ui.faq1a},{q:ui.faq2q,a:ui.faq2a},{q:ui.faq3q,a:ui.faq3a}].map((faq,idx)=>(<details key={idx} style={{border:'1px solid var(--border-color)',borderRadius:8,overflow:'hidden',background:'var(--bg-input)'}}><summary style={{padding:'14px 16px',cursor:'pointer',fontSize:14,fontWeight:600}}>{faq.q}</summary><div style={{padding:'0 16px 14px',fontSize:13,lineHeight:1.7,color:'var(--text-secondary)'}}>{faq.a}</div></details>))}</div></div>
    </ToolLayout>
  );
}
