'use client';

import { useState, useCallback } from 'react';
import ToolLayout from '@/components/ToolLayout';
import CopyButton from '@/components/CopyButton';
import Link from 'next/link';
import { useLang } from '@/i18n/LangContext';

const ui: Record<string, Record<string, string>> = {
  en: { title: 'Base64 Decode Online', description: 'Decode Base64 encoded strings to plain text or encode text to Base64 instantly in your browser. Free, private, no server required.', inputLabel: 'Input', outputLabel: 'Output', placeholder: 'Paste Base64 string or plain text here...', decode: 'Decode', encode: 'Encode', clear: 'Clear', copyLabel: 'Copy', introTitle: 'Free Online Base64 Decoder & Encoder', introText: 'Paste your Base64 encoded string and click Decode to get the original text, or enter plain text and click Encode to convert to Base64. Everything runs in your browser with no data sent to any server.', howTitle: 'How to Decode Base64', step1: 'Paste your Base64 encoded string in the input area', step2: 'Click the Decode button to convert to plain text', step3: 'Or enter plain text and click Encode for Base64 output', step4: 'Click Copy to use the result', featuresTitle: 'Features', feature1: 'Decode Base64 to UTF-8 text with full Unicode support', feature2: 'Encode any text to Base64 format', feature3: 'Handles multi-byte characters (emoji, CJK, etc.) correctly', feature4: 'URL-safe Base64 variant detection and handling', feature5: 'All processing happens locally in your browser', faqTitle: 'Frequently Asked Questions', faq1q: 'What is Base64 encoding?', faq1a: 'Base64 is a binary-to-text encoding scheme that represents binary data using 64 ASCII characters (A-Z, a-z, 0-9, +, /). It is commonly used for embedding data in URLs, emails, HTML, and API tokens like JWTs.', faq2q: 'How does Base64 decoding work?', faq2a: 'Base64 decoding reverses the encoding process: each group of 4 Base64 characters is converted back to 3 bytes of binary data, which is then interpreted as text using the specified character encoding (typically UTF-8).', faq3q: 'Can Base64 decode binary files?', faq3a: 'This tool focuses on decoding Base64 to text. For binary files (images, PDFs), you would need a tool that can save the decoded bytes directly to a file. Our Base64 tool handles text decoding with full Unicode support.', faq4q: 'Is my data sent to a server?', faq4a: 'No. All encoding and decoding happens entirely in your browser using the built-in btoa() and atob() functions. Your data never leaves your device.', faq5q: 'What is URL-safe Base64?', faq5a: 'URL-safe Base64 replaces + with - and / with _ to avoid issues in URLs. This tool automatically detects URL-safe Base64 and converts it before decoding.', relatedTitle: 'Related Tools', errorEmpty: 'Please enter content to decode or encode.', errorDecode: 'Invalid Base64 string' },
  zh: { title: 'Base64 在线解码', description: '在浏览器中即时解码 Base64 字符串或将文本编码为 Base64。免费、私密、无需服务器。', inputLabel: '输入', outputLabel: '输出', placeholder: '在此粘贴 Base64 字符串或纯文本...', decode: '解码', encode: '编码', clear: '清除', copyLabel: '复制', introTitle: '免费在线 Base64 解码器和编码器', introText: '粘贴 Base64 字符串并点击解码获取原始文本，或输入文本点击编码转换为 Base64。所有操作在浏览器中完成。', howTitle: '如何解码 Base64', step1: '在输入区域粘贴 Base64 字符串', step2: '点击解码按钮转换为纯文本', step3: '或输入文本点击编码获取 Base64', step4: '点击复制使用结果', featuresTitle: '功能', feature1: '将 Base64 解码为 UTF-8 文本，完整 Unicode 支持', feature2: '将任何文本编码为 Base64 格式', feature3: '正确处理多字节字符（表情、中日韩等）', feature4: 'URL 安全 Base64 变体检测和处理', feature5: '所有处理在浏览器中本地进行', faqTitle: '常见问题', faq1q: '什么是 Base64 编码？', faq1a: 'Base64 是一种将二进制数据用 64 个 ASCII 字符表示的编码方案，常用于 URL、邮件、HTML 和 JWT 等。', faq2q: 'Base64 解码如何工作？', faq2a: '每 4 个 Base64 字符转换回 3 字节二进制数据，然后解释为 UTF-8 文本。', faq3q: 'Base64 能解码二进制文件吗？', faq3a: '本工具专注于文本解码。对于图片等二进制文件需要专门工具。', faq4q: '数据会发送到服务器吗？', faq4a: '不会。使用浏览器内置 btoa() 和 atob() 函数处理。', faq5q: '什么是 URL 安全 Base64？', faq5a: 'URL 安全 Base64 用 - 替换 +，用 _ 替换 /，本工具自动检测并处理。', relatedTitle: '相关工具', errorEmpty: '请输入要解码或编码的内容。', errorDecode: 'Base64 字符串无效' },
  ja: { title: 'Base64 オンラインデコード', description: 'ブラウザでBase64文字列を即座にデコード/エンコード。無料・プライベート。', inputLabel: '入力', outputLabel: '出力', placeholder: 'Base64文字列またはテキストを貼り付け...', decode: 'デコード', encode: 'エンコード', clear: 'クリア', copyLabel: 'コピー', introTitle: '無料 Base64 デコーダー＆エンコーダー', introText: 'Base64文字列を貼り付けてデコード、またはテキストを入力してBase64にエンコード。', howTitle: 'Base64をデコードする方法', step1: 'Base64文字列を入力エリアに貼り付け', step2: 'デコードボタンをクリック', step3: 'またはテキストを入力してエンコード', step4: 'コピーで結果を使用', featuresTitle: '機能', feature1: 'Base64をUTF-8テキストにデコード', feature2: 'テキストをBase64にエンコード', feature3: 'マルチバイト文字を正しく処理', feature4: 'URLセーフBase64を自動検出', feature5: 'ブラウザ内で処理', faqTitle: 'よくある質問', faq1q: 'Base64エンコーディングとは？', faq1a: '64のASCII文字でバイナリデータを表現する方式です。', faq2q: 'デコードの仕組みは？', faq2a: '4文字のBase64を3バイトに戻し、UTF-8テキストとして解釈します。', faq3q: 'バイナリファイルをデコードできますか？', faq3a: 'このツールはテキストデコードに特化しています。', faq4q: 'データはサーバーに送信されますか？', faq4a: 'いいえ。ブラウザ内で処理されます。', faq5q: 'URLセーフBase64とは？', faq5a: '+を-に、/を_に置換したBase64変種です。', relatedTitle: '関連ツール', errorEmpty: 'コンテンツを入力してください。', errorDecode: '無効なBase64文字列' },
  ko: { title: 'Base64 온라인 디코드', description: '브라우저에서 Base64 문자열을 즉시 디코드/인코드. 무료, 개인 정보 보호.', inputLabel: '입력', outputLabel: '출력', placeholder: 'Base64 문자열 또는 텍스트를 붙여넣기...', decode: '디코드', encode: '인코드', clear: '지우기', copyLabel: '복사', introTitle: '무료 Base64 디코더 & 인코더', introText: 'Base64 문자열을 붙여넣고 디코드하거나 텍스트를 입력하여 Base64로 인코드하세요.', howTitle: 'Base64 디코드 방법', step1: 'Base64 문자열을 입력 영역에 붙여넣기', step2: '디코드 버튼 클릭', step3: '또는 텍스트 입력 후 인코드', step4: '복사로 결과 사용', featuresTitle: '기능', feature1: 'Base64를 UTF-8 텍스트로 디코드', feature2: '텍스트를 Base64로 인코드', feature3: '멀티바이트 문자 올바르게 처리', feature4: 'URL 안전 Base64 자동 감지', feature5: '브라우저 내 처리', faqTitle: 'FAQ', faq1q: 'Base64 인코딩이란?', faq1a: '64개의 ASCII 문자로 바이너리 데이터를 표현하는 방식입니다.', faq2q: '디코딩은 어떻게 작동하나요?', faq2a: '4개의 Base64 문자를 3바이트로 변환하여 UTF-8로 해석합니다.', faq3q: '바이너리 파일을 디코드할 수 있나요?', faq3a: '이 도구는 텍스트 디코딩에 특화되어 있습니다.', faq4q: '데이터가 서버로 전송되나요?', faq4a: '아니요. 브라우저 내에서 처리됩니다.', faq5q: 'URL 안전 Base64란?', faq5a: '+를 -로, /를 _로 대체한 Base64 변형입니다.', relatedTitle: '관련 도구', errorEmpty: '콘텐츠를 입력해 주세요.', errorDecode: '유효하지 않은 Base64 문자열' },
  fr: { title: 'Decodeur Base64 en Ligne', description: 'Decodez des chaines Base64 en texte. Gratuit, prive, sans serveur.', inputLabel: 'Entree', outputLabel: 'Sortie', placeholder: 'Collez une chaine Base64 ou du texte...', decode: 'Decoder', encode: 'Encoder', clear: 'Effacer', copyLabel: 'Copier', introTitle: 'Decodeur et Encodeur Base64 Gratuit', introText: 'Collez votre chaine Base64 et cliquez Decoder pour obtenir le texte original.', howTitle: 'Comment decoder Base64', step1: 'Collez la chaine Base64', step2: 'Cliquez Decoder', step3: 'Ou entrez du texte et cliquez Encoder', step4: 'Cliquez Copier', featuresTitle: 'Fonctionnalites', feature1: 'Decodage Base64 vers UTF-8', feature2: 'Encodage texte vers Base64', feature3: 'Support multi-octets complet', feature4: 'Detection Base64 URL-safe', feature5: 'Traitement local dans le navigateur', faqTitle: 'FAQ', faq1q: "Qu'est-ce que le Base64 ?", faq1a: 'Un schema representant des donnees binaires en 64 caracteres ASCII.', faq2q: 'Comment fonctionne le decodage ?', faq2a: '4 caracteres Base64 sont convertis en 3 octets.', faq3q: 'Peut-on decoder des fichiers binaires ?', faq3a: 'Cet outil est specialise pour le texte.', faq4q: 'Les donnees sont-elles envoyees ?', faq4a: 'Non, tout dans le navigateur.', faq5q: "Qu'est-ce que le Base64 URL-safe ?", faq5a: 'Une variante remplacant + par - et / par _.', relatedTitle: 'Outils connexes', errorEmpty: 'Veuillez entrer du contenu.', errorDecode: 'Chaine Base64 invalide' },
  de: { title: 'Base64 Decoder Online', description: 'Base64-Strings dekodieren im Browser. Kostenlos, privat, kein Server.', inputLabel: 'Eingabe', outputLabel: 'Ausgabe', placeholder: 'Base64-String oder Text einfuegen...', decode: 'Dekodieren', encode: 'Kodieren', clear: 'Leeren', copyLabel: 'Kopieren', introTitle: 'Kostenloser Base64 Decoder & Encoder', introText: 'Base64-String einfuegen und Dekodieren klicken oder Text eingeben und Kodieren.', howTitle: 'So dekodieren Sie Base64', step1: 'Base64-String einfuegen', step2: 'Dekodieren klicken', step3: 'Oder Text eingeben und Kodieren', step4: 'Kopieren klicken', featuresTitle: 'Funktionen', feature1: 'Base64 zu UTF-8 dekodieren', feature2: 'Text zu Base64 kodieren', feature3: 'Multi-Byte-Zeichen korrekt', feature4: 'URL-sicheres Base64 erkennen', feature5: 'Alles im Browser', faqTitle: 'FAQ', faq1q: 'Was ist Base64?', faq1a: 'Ein Kodierungsschema mit 64 ASCII-Zeichen.', faq2q: 'Wie funktioniert Dekodierung?', faq2a: '4 Base64-Zeichen werden in 3 Bytes umgewandelt.', faq3q: 'Kann man Binaerdateien dekodieren?', faq3a: 'Dieses Tool ist auf Text spezialisiert.', faq4q: 'Werden Daten gesendet?', faq4a: 'Nein, alles im Browser.', faq5q: 'Was ist URL-sicheres Base64?', faq5a: 'Eine Variante mit - statt + und _ statt /.', relatedTitle: 'Verwandte Tools', errorEmpty: 'Bitte Inhalt eingeben.', errorDecode: 'Ungueltiger Base64-String' },
  es: { title: 'Decodificador Base64 en Linea', description: 'Decodifica cadenas Base64 a texto. Gratis, privado, sin servidor.', inputLabel: 'Entrada', outputLabel: 'Salida', placeholder: 'Pega cadena Base64 o texto...', decode: 'Decodificar', encode: 'Codificar', clear: 'Limpiar', copyLabel: 'Copiar', introTitle: 'Decodificador y Codificador Base64 Gratis', introText: 'Pega tu cadena Base64 y haz clic en Decodificar para obtener el texto original.', howTitle: 'Como decodificar Base64', step1: 'Pega la cadena Base64', step2: 'Clic en Decodificar', step3: 'O ingresa texto y clic en Codificar', step4: 'Clic en Copiar', featuresTitle: 'Caracteristicas', feature1: 'Decodificacion Base64 a UTF-8', feature2: 'Codificacion de texto a Base64', feature3: 'Soporte multi-byte completo', feature4: 'Deteccion Base64 URL-safe', feature5: 'Procesamiento local', faqTitle: 'FAQ', faq1q: 'Que es Base64?', faq1a: 'Un esquema que representa datos binarios con 64 caracteres ASCII.', faq2q: 'Como funciona la decodificacion?', faq2a: '4 caracteres Base64 se convierten en 3 bytes.', faq3q: 'Se pueden decodificar archivos binarios?', faq3a: 'Esta herramienta es para texto.', faq4q: 'Se envian los datos?', faq4a: 'No, todo en el navegador.', faq5q: 'Que es Base64 URL-safe?', faq5a: 'Una variante que reemplaza + por - y / por _.', relatedTitle: 'Herramientas relacionadas', errorEmpty: 'Ingresa contenido.', errorDecode: 'Cadena Base64 invalida' },
  pt: { title: 'Decodificador Base64 Online', description: 'Decodifique strings Base64 para texto. Gratis, privado, sem servidor.', inputLabel: 'Entrada', outputLabel: 'Saida', placeholder: 'Cole string Base64 ou texto...', decode: 'Decodificar', encode: 'Codificar', clear: 'Limpar', copyLabel: 'Copiar', introTitle: 'Decodificador e Codificador Base64 Gratis', introText: 'Cole sua string Base64 e clique em Decodificar para obter o texto original.', howTitle: 'Como decodificar Base64', step1: 'Cole a string Base64', step2: 'Clique em Decodificar', step3: 'Ou insira texto e clique em Codificar', step4: 'Clique em Copiar', featuresTitle: 'Recursos', feature1: 'Decodificacao Base64 para UTF-8', feature2: 'Codificacao de texto para Base64', feature3: 'Suporte multi-byte completo', feature4: 'Deteccao Base64 URL-safe', feature5: 'Processamento local', faqTitle: 'FAQ', faq1q: 'O que e Base64?', faq1a: 'Um esquema que representa dados binarios com 64 caracteres ASCII.', faq2q: 'Como funciona a decodificacao?', faq2a: '4 caracteres Base64 sao convertidos em 3 bytes.', faq3q: 'Pode decodificar arquivos binarios?', faq3a: 'Esta ferramenta e para texto.', faq4q: 'Os dados sao enviados?', faq4a: 'Nao, tudo no navegador.', faq5q: 'O que e Base64 URL-safe?', faq5a: 'Uma variante que substitui + por - e / por _.', relatedTitle: 'Ferramentas relacionadas', errorEmpty: 'Insira conteudo.', errorDecode: 'String Base64 invalida' },
  it: { title: 'Decodificatore Base64 Online', description: 'Decodifica stringhe Base64 in testo. Gratuito, privato, senza server.', inputLabel: 'Input', outputLabel: 'Output', placeholder: 'Incolla stringa Base64 o testo...', decode: 'Decodifica', encode: 'Codifica', clear: 'Cancella', copyLabel: 'Copia', introTitle: 'Decodificatore e Codificatore Base64 Gratuito', introText: 'Incolla la stringa Base64 e clicca Decodifica per ottenere il testo originale.', howTitle: 'Come decodificare Base64', step1: 'Incolla la stringa Base64', step2: 'Clicca Decodifica', step3: 'O inserisci testo e clicca Codifica', step4: 'Clicca Copia', featuresTitle: 'Funzionalita', feature1: 'Decodifica Base64 in UTF-8', feature2: 'Codifica testo in Base64', feature3: 'Supporto multi-byte completo', feature4: 'Rilevamento Base64 URL-safe', feature5: 'Elaborazione locale', faqTitle: 'FAQ', faq1q: 'Cosa e Base64?', faq1a: 'Uno schema che rappresenta dati binari con 64 caratteri ASCII.', faq2q: 'Come funziona la decodifica?', faq2a: '4 caratteri Base64 vengono convertiti in 3 byte.', faq3q: 'Si possono decodificare file binari?', faq3a: 'Questo strumento e per il testo.', faq4q: 'I dati vengono inviati?', faq4a: 'No, tutto nel browser.', faq5q: 'Cosa e Base64 URL-safe?', faq5a: 'Una variante che sostituisce + con - e / con _.', relatedTitle: 'Strumenti correlati', errorEmpty: 'Inserisci contenuto.', errorDecode: 'Stringa Base64 non valida' },
  nl: { title: 'Base64 Decoder Online', description: 'Decodeer Base64-strings naar tekst. Gratis, privaat, geen server.', inputLabel: 'Invoer', outputLabel: 'Uitvoer', placeholder: 'Plak Base64 of tekst...', decode: 'Decoderen', encode: 'Coderen', clear: 'Wissen', copyLabel: 'Kopieren', introTitle: 'Gratis Base64 Decoder & Encoder', introText: 'Plak uw Base64-string en klik Decoderen voor de originele tekst.', howTitle: 'Hoe Base64 decoderen', step1: 'Plak de Base64-string', step2: 'Klik Decoderen', step3: 'Of voer tekst in en klik Coderen', step4: 'Klik Kopieren', featuresTitle: 'Functies', feature1: 'Base64 naar UTF-8 decoderen', feature2: 'Tekst naar Base64 coderen', feature3: 'Multi-byte ondersteuning', feature4: 'URL-safe Base64 detectie', feature5: 'Lokale verwerking', faqTitle: 'FAQ', faq1q: 'Wat is Base64?', faq1a: 'Een schema dat binaire data met 64 ASCII-tekens weergeeft.', faq2q: 'Hoe werkt decodering?', faq2a: '4 Base64-tekens worden omgezet naar 3 bytes.', faq3q: 'Kan men binaire bestanden decoderen?', faq3a: 'Deze tool is voor tekst.', faq4q: 'Worden gegevens verstuurd?', faq4a: 'Nee, alles in de browser.', faq5q: 'Wat is URL-safe Base64?', faq5a: 'Een variant met - in plaats van + en _ in plaats van /.', relatedTitle: 'Gerelateerde tools', errorEmpty: 'Voer inhoud in.', errorDecode: 'Ongeldige Base64-string' },
  pl: { title: 'Dekoder Base64 Online', description: 'Dekoduj ciagi Base64 na tekst. Darmowy, prywatny, bez serwera.', inputLabel: 'Wejscie', outputLabel: 'Wyjscie', placeholder: 'Wklej ciag Base64 lub tekst...', decode: 'Dekoduj', encode: 'Koduj', clear: 'Wyczysc', copyLabel: 'Kopiuj', introTitle: 'Darmowy Dekoder i Koder Base64', introText: 'Wklej ciag Base64 i kliknij Dekoduj, aby uzyskac oryginalny tekst.', howTitle: 'Jak dekodowac Base64', step1: 'Wklej ciag Base64', step2: 'Kliknij Dekoduj', step3: 'Lub wpisz tekst i kliknij Koduj', step4: 'Kliknij Kopiuj', featuresTitle: 'Funkcje', feature1: 'Dekodowanie Base64 do UTF-8', feature2: 'Kodowanie tekstu do Base64', feature3: 'Pelna obsluga wielobajtowa', feature4: 'Wykrywanie URL-safe Base64', feature5: 'Przetwarzanie lokalne', faqTitle: 'FAQ', faq1q: 'Co to jest Base64?', faq1a: 'Schemat kodowania danych binarnych za pomoca 64 znakow ASCII.', faq2q: 'Jak dziala dekodowanie?', faq2a: '4 znaki Base64 sa konwertowane na 3 bajty.', faq3q: 'Czy mozna dekodowac pliki binarne?', faq3a: 'To narzedzie jest do tekstu.', faq4q: 'Czy dane sa wysylane?', faq4a: 'Nie, wszystko w przegladarce.', faq5q: 'Co to jest URL-safe Base64?', faq5a: 'Wariant z - zamiast + i _ zamiast /.', relatedTitle: 'Powiazane narzedzia', errorEmpty: 'Wprowadz zawartosc.', errorDecode: 'Nieprawidlowy ciag Base64' },
  sv: { title: 'Base64 Avkodare Online', description: 'Avkoda Base64-straengar till text. Gratis, privat, ingen server.', inputLabel: 'Indata', outputLabel: 'Utdata', placeholder: 'Klistra in Base64 eller text...', decode: 'Avkoda', encode: 'Koda', clear: 'Rensa', copyLabel: 'Kopiera', introTitle: 'Gratis Base64 Avkodare & Kodare', introText: 'Klistra in din Base64-straeng och klicka Avkoda foer originaltexten.', howTitle: 'Hur man avkodar Base64', step1: 'Klistra in Base64-straengen', step2: 'Klicka Avkoda', step3: 'Eller skriv text och klicka Koda', step4: 'Klicka Kopiera', featuresTitle: 'Funktioner', feature1: 'Base64 till UTF-8 avkodning', feature2: 'Text till Base64 kodning', feature3: 'Full multi-byte-support', feature4: 'URL-saker Base64-detektering', feature5: 'Lokal behandling', faqTitle: 'FAQ', faq1q: 'Vad aer Base64?', faq1a: 'Ett kodningsschema med 64 ASCII-tecken.', faq2q: 'Hur fungerar avkodning?', faq2a: '4 Base64-tecken konverteras till 3 byte.', faq3q: 'Kan man avkoda binaerfiler?', faq3a: 'Detta verktyg aer foer text.', faq4q: 'Skickas data?', faq4a: 'Nej, allt i webblaasaren.', faq5q: 'Vad aer URL-saeker Base64?', faq5a: 'En variant med - istaellet foer + och _ istaellet foer /.', relatedTitle: 'Relaterade verktyg', errorEmpty: 'Ange innehall.', errorDecode: 'Ogiltig Base64-straeng' },
  no: { title: 'Base64 Dekoder Online', description: 'Dekod Base64-strenger til tekst. Gratis, privat, ingen server.', inputLabel: 'Inndata', outputLabel: 'Utdata', placeholder: 'Lim inn Base64 eller tekst...', decode: 'Dekod', encode: 'Kod', clear: 'Toom', copyLabel: 'Kopier', introTitle: 'Gratis Base64 Dekoder & Koder', introText: 'Lim inn din Base64-streng og klikk Dekod for originalteksten.', howTitle: 'Slik dekoder du Base64', step1: 'Lim inn Base64-strengen', step2: 'Klikk Dekod', step3: 'Eller skriv tekst og klikk Kod', step4: 'Klikk Kopier', featuresTitle: 'Funksjoner', feature1: 'Base64 til UTF-8 dekoding', feature2: 'Tekst til Base64 koding', feature3: 'Full multi-byte-stotte', feature4: 'URL-sikker Base64-deteksjon', feature5: 'Lokal behandling', faqTitle: 'FAQ', faq1q: 'Hva er Base64?', faq1a: 'Et kodingsskjema med 64 ASCII-tegn.', faq2q: 'Hvordan fungerer dekoding?', faq2a: '4 Base64-tegn konverteres til 3 byte.', faq3q: 'Kan man dekode binarfiler?', faq3a: 'Dette verktoeyet er for tekst.', faq4q: 'Sendes data?', faq4a: 'Nei, alt i nettleseren.', faq5q: 'Hva er URL-sikker Base64?', faq5a: 'En variant med - i stedet for + og _ i stedet for /.', relatedTitle: 'Relaterte verktoy', errorEmpty: 'Skriv inn innhold.', errorDecode: 'Ugyldig Base64-streng' },
  id: { title: 'Dekoder Base64 Online', description: 'Dekode string Base64 ke teks. Gratis, privat, tanpa server.', inputLabel: 'Input', outputLabel: 'Output', placeholder: 'Tempel string Base64 atau teks...', decode: 'Dekode', encode: 'Enkode', clear: 'Hapus', copyLabel: 'Salin', introTitle: 'Dekoder & Enkoder Base64 Gratis', introText: 'Tempel string Base64 dan klik Dekode untuk mendapatkan teks asli.', howTitle: 'Cara mendekode Base64', step1: 'Tempel string Base64', step2: 'Klik Dekode', step3: 'Atau masukkan teks dan klik Enkode', step4: 'Klik Salin', featuresTitle: 'Fitur', feature1: 'Dekode Base64 ke UTF-8', feature2: 'Enkode teks ke Base64', feature3: 'Dukungan multi-byte penuh', feature4: 'Deteksi Base64 URL-safe', feature5: 'Pemrosesan lokal', faqTitle: 'FAQ', faq1q: 'Apa itu Base64?', faq1a: 'Skema pengkodean data biner dengan 64 karakter ASCII.', faq2q: 'Bagaimana dekoding bekerja?', faq2a: '4 karakter Base64 dikonversi menjadi 3 byte.', faq3q: 'Bisa mendekode file biner?', faq3a: 'Alat ini untuk teks.', faq4q: 'Apakah data dikirim?', faq4a: 'Tidak, semua di browser.', faq5q: 'Apa itu URL-safe Base64?', faq5a: 'Varian dengan - menggantikan + dan _ menggantikan /.', relatedTitle: 'Alat terkait', errorEmpty: 'Masukkan konten.', errorDecode: 'String Base64 tidak valid' },
  th: { title: 'ตัวถอดรหัส Base64 ออนไลน์', description: 'ถอดรหัสสตริง Base64 เป็นข้อความ ฟรี เป็นส่วนตัว ไม่ต้องใช้เซิร์ฟเวอร์', inputLabel: 'อินพุต', outputLabel: 'เอาต์พุต', placeholder: 'วางสตริง Base64 หรือข้อความ...', decode: 'ถอดรหัส', encode: 'เข้ารหัส', clear: 'ล้าง', copyLabel: 'คัดลอก', introTitle: 'ตัวถอดรหัสและเข้ารหัส Base64 ฟรี', introText: 'วางสตริง Base64 และคลิกถอดรหัสเพื่อรับข้อความต้นฉบับ', howTitle: 'วิธีถอดรหัส Base64', step1: 'วางสตริง Base64', step2: 'คลิกถอดรหัส', step3: 'หรือป้อนข้อความและคลิกเข้ารหัส', step4: 'คลิกคัดลอก', featuresTitle: 'คุณสมบัติ', feature1: 'ถอดรหัส Base64 เป็น UTF-8', feature2: 'เข้ารหัสข้อความเป็น Base64', feature3: 'รองรับอักขระหลายไบต์', feature4: 'ตรวจจับ Base64 แบบ URL-safe', feature5: 'ประมวลผลในเครื่อง', faqTitle: 'คำถามที่พบบ่อย', faq1q: 'Base64 คืออะไร?', faq1a: 'รูปแบบการเข้ารหัสข้อมูลไบนารีด้วยอักขระ ASCII 64 ตัว', faq2q: 'การถอดรหัสทำงานอย่างไร?', faq2a: 'อักขระ Base64 4 ตัวแปลงเป็น 3 ไบต์', faq3q: 'ถอดรหัสไฟล์ไบนารีได้ไหม?', faq3a: 'เครื่องมือนี้สำหรับข้อความ', faq4q: 'ข้อมูลถูกส่งไปหรือไม่?', faq4a: 'ไม่ ทุกอย่างในเบราว์เซอร์', faq5q: 'URL-safe Base64 คืออะไร?', faq5a: 'รูปแบบที่ใช้ - แทน + และ _ แทน /', relatedTitle: 'เครื่องมือที่เกี่ยวข้อง', errorEmpty: 'กรุณาป้อนเนื้อหา', errorDecode: 'สตริง Base64 ไม่ถูกต้อง' },
};

function base64Decode(input: string): string {
  let cleaned = input.trim().replace(/-/g, '+').replace(/_/g, '/');
  while (cleaned.length % 4 !== 0) cleaned += '=';
  const binary = atob(cleaned);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
  return new TextDecoder('utf-8').decode(bytes);
}

function base64Encode(input: string): string {
  const bytes = new TextEncoder().encode(input);
  let binary = '';
  for (let i = 0; i < bytes.length; i++) binary += String.fromCharCode(bytes[i]);
  return btoa(binary);
}

export default function Base64DecodePage() {
  const { lang } = useLang();
  const t = ui[lang] || ui.en;
  const [input, setInput] = useState('');
  const [output, setOutput] = useState('');
  const [error, setError] = useState('');

  const handleDecode = useCallback(() => {
    setError('');
    if (!input.trim()) { setError(t.errorEmpty); setOutput(''); return; }
    try { setOutput(base64Decode(input)); } catch { setError(t.errorDecode); setOutput(''); }
  }, [input, t]);

  const handleEncode = useCallback(() => {
    setError('');
    if (!input.trim()) { setError(t.errorEmpty); setOutput(''); return; }
    try { setOutput(base64Encode(input)); } catch (e) { setError(String(e)); setOutput(''); }
  }, [input, t]);

  const handleClear = useCallback(() => { setInput(''); setOutput(''); setError(''); }, []);

  const faqSchema = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: [
    { '@type': 'Question', name: t.faq1q, acceptedAnswer: { '@type': 'Answer', text: t.faq1a } },
    { '@type': 'Question', name: t.faq2q, acceptedAnswer: { '@type': 'Answer', text: t.faq2a } },
    { '@type': 'Question', name: t.faq3q, acceptedAnswer: { '@type': 'Answer', text: t.faq3a } },
    { '@type': 'Question', name: t.faq4q, acceptedAnswer: { '@type': 'Answer', text: t.faq4a } },
    { '@type': 'Question', name: t.faq5q, acceptedAnswer: { '@type': 'Answer', text: t.faq5a } },
  ]};

  return (
    <ToolLayout title={t.title} description={t.description} toolId="base64-decode">
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />
      <div style={{ display: 'flex', gap: 8, marginBottom: 16, flexWrap: 'wrap' }}>
        <button onClick={handleDecode} className="btn btn-primary" style={{ fontSize: 13 }}>{t.decode}</button>
        <button onClick={handleEncode} className="btn btn-secondary" style={{ fontSize: 13 }}>{t.encode}</button>
        <button onClick={handleClear} className="btn btn-secondary" style={{ fontSize: 13 }}>{t.clear}</button>
      </div>
      {error && <div style={{ background: 'rgba(244,63,94,0.1)', border: '1px solid rgba(244,63,94,0.3)', borderRadius: 8, padding: '10px 14px', marginBottom: 16, fontSize: 13, color: 'var(--accent-rose,#f43f5e)' }}>{'\u2715'} {error}</div>}
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 }}>
        <div style={{ display: 'flex', flexDirection: 'column' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 }}><label style={{ fontSize: 13, fontWeight: 600 }}>{t.inputLabel}</label></div>
          <textarea value={input} onChange={(e) => setInput(e.target.value)} placeholder={t.placeholder} spellCheck={false} style={{ flex: 1, minHeight: 300, fontFamily: 'JetBrains Mono, Fira Code, monospace', fontSize: 12, lineHeight: 1.6, resize: 'vertical' }} />
        </div>
        <div style={{ display: 'flex', flexDirection: 'column' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 }}><label style={{ fontSize: 13, fontWeight: 600 }}>{t.outputLabel}</label><CopyButton text={output} label={t.copyLabel} /></div>
          <textarea value={output} readOnly spellCheck={false} style={{ flex: 1, minHeight: 300, fontFamily: 'JetBrains Mono, Fira Code, monospace', fontSize: 12, lineHeight: 1.6, background: 'var(--bg-card)', opacity: output ? 1 : 0.5, resize: 'vertical' }} />
        </div>
      </div>
      <div style={{ marginTop: 32, paddingTop: 24, borderTop: '1px solid var(--border-color)' }}>
        <h2 style={{ fontSize: 20, fontWeight: 700, marginBottom: 10 }}>{t.introTitle}</h2>
        <p style={{ fontSize: 14, color: 'var(--text-secondary)', lineHeight: 1.75, marginBottom: 24 }}>{t.introText}</p>
        <h3 style={{ fontSize: 16, fontWeight: 600, marginBottom: 8 }}>{t.howTitle}</h3>
        <ol style={{ fontSize: 14, color: 'var(--text-secondary)', lineHeight: 1.9, paddingLeft: 20, marginBottom: 24 }}><li>{t.step1}</li><li>{t.step2}</li><li>{t.step3}</li><li>{t.step4}</li></ol>
        <h3 style={{ fontSize: 16, fontWeight: 600, marginBottom: 10 }}>{t.featuresTitle}</h3>
        <ul style={{ fontSize: 14, color: 'var(--text-secondary)', lineHeight: 1.9, paddingLeft: 20, marginBottom: 24 }}><li>{t.feature1}</li><li>{t.feature2}</li><li>{t.feature3}</li><li>{t.feature4}</li><li>{t.feature5}</li></ul>
        <h3 style={{ fontSize: 16, fontWeight: 600, marginBottom: 10 }}>{t.faqTitle}</h3>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 8, marginBottom: 28 }}>
          {[{ q: t.faq1q, a: t.faq1a },{ q: t.faq2q, a: t.faq2a },{ q: t.faq3q, a: t.faq3a },{ q: t.faq4q, a: t.faq4a },{ q: t.faq5q, a: t.faq5a }].map((faq, idx) => (
            <details key={idx} style={{ border: '1px solid var(--border-color)', borderRadius: 8, overflow: 'hidden', background: 'var(--bg-input)' }}>
              <summary style={{ padding: '14px 16px', cursor: 'pointer', fontSize: 14, fontWeight: 600, color: 'var(--text-primary)', userSelect: 'none' }}>{faq.q}</summary>
              <div style={{ padding: '0 16px 14px', fontSize: 13, lineHeight: 1.7, color: 'var(--text-secondary)' }}>{faq.a}</div>
            </details>
          ))}
        </div>
        <h3 style={{ fontSize: 16, fontWeight: 600, marginBottom: 10 }}>{t.relatedTitle}</h3>
        <div style={{ display: 'flex', flexWrap: 'wrap', gap: 8 }}>
          {[{ href: `/${lang}/tools/base64`, label: 'Base64 Encoder' },{ href: `/${lang}/tools/url-encoder-decoder`, label: 'URL Encoder/Decoder' },{ href: `/${lang}/tools/hash-generator`, label: 'Hash Generator' },{ href: `/${lang}/tools/jwt-decoder`, label: 'JWT Decoder' }].map((link) => (
            <Link key={link.href} href={link.href} style={{ display: 'inline-block', padding: '8px 16px', borderRadius: 8, border: '1px solid var(--border-color)', fontSize: 13, color: 'var(--accent-blue)', textDecoration: 'none', background: 'var(--bg-input)' }}>{link.label}</Link>
          ))}
        </div>
      </div>
    </ToolLayout>
  );
}
