'use client';

import Link from 'next/link';
import { useLang } from '@/i18n/LangContext';
import ToolLayout from '@/components/ToolLayout';

const t: Record<string, Record<string, string>> = {
  en: {
    title: 'REST vs GraphQL',
    description: 'A detailed comparison of REST APIs and GraphQL to help you choose the right API architecture.',
    intro: 'REST and GraphQL are two dominant approaches to building APIs. REST has been the standard for over a decade, while GraphQL (created by Facebook in 2015) offers a more flexible query language for your data. Here is how they compare.',
    tableFeature: 'Feature', tableRest: 'REST', tableGql: 'GraphQL',
    architecture: 'Architecture', arcRest: 'Resource-based endpoints', arcGql: 'Single endpoint with queries',
    dataFetching: 'Data Fetching', dfRest: 'Fixed data per endpoint', dfGql: 'Client specifies exact data needed',
    overFetching: 'Over-fetching', ofRest: 'Common (returns full resource)', ofGql: 'Eliminated (request only needed fields)',
    underFetching: 'Under-fetching', ufRest: 'Common (multiple round trips)', ufGql: 'Eliminated (nested queries)',
    caching: 'Caching', caRest: 'Built-in HTTP caching', caGql: 'Complex (needs custom solutions)',
    learning: 'Learning Curve', leRest: 'Low', leGql: 'Moderate to High',
    versioning: 'Versioning', veRest: 'URL-based (v1/v2)', veGql: 'No versioning needed (schema evolution)',
    whatIsRest: 'What is REST?',
    restText: 'REST (Representational State Transfer) is an architectural style that uses standard HTTP methods (GET, POST, PUT, DELETE) on resource-based URLs. Each endpoint returns a fixed data structure. REST APIs are stateless, cacheable, and follow a uniform interface. They have been the dominant API style since the mid-2000s.',
    whatIsGql: 'What is GraphQL?',
    gqlText: 'GraphQL is a query language and runtime for APIs developed by Facebook. Instead of multiple endpoints, it exposes a single endpoint where clients send queries describing exactly what data they need. The server returns precisely that data. GraphQL uses a strongly-typed schema to define the API surface.',
    whenRest: 'When to Use REST',
    restUse1: 'Simple CRUD applications',
    restUse2: 'Public APIs with diverse clients',
    restUse3: 'Microservices with simple data needs',
    restUse4: 'When HTTP caching is critical',
    restUse5: 'File upload/download heavy applications',
    whenGql: 'When to Use GraphQL',
    gqlUse1: 'Complex UIs with many data relationships',
    gqlUse2: 'Mobile apps (minimize data transfer)',
    gqlUse3: 'Aggregating data from multiple sources',
    gqlUse4: 'Rapid frontend iteration',
    gqlUse5: 'Real-time features with subscriptions',
    verdict: 'TL;DR / Verdict',
    verdictText: 'Use REST for simple, resource-based APIs where caching and simplicity matter. Use GraphQL for complex data requirements, mobile apps, and when frontend teams need flexibility. Many companies use both: REST for simple services and GraphQL as a gateway layer.',
    tryTools: 'Try Our API Tools',
    faqTitle: 'Frequently Asked Questions',
    faq1q: 'Is GraphQL faster than REST?',
    faq1a: 'Not inherently. GraphQL can be faster for clients because it eliminates over-fetching and under-fetching, reducing the number of requests and data transferred. However, REST benefits from built-in HTTP caching. The actual performance depends on your data patterns and implementation.',
    faq2q: 'Can I use REST and GraphQL together?',
    faq2a: 'Yes, many companies use GraphQL as a gateway layer that aggregates data from multiple REST microservices. This gives frontend teams the flexibility of GraphQL while keeping backend services simple with REST.',
    faq3q: 'Is GraphQL replacing REST?',
    faq3a: 'No, GraphQL is not replacing REST. They serve different use cases. REST remains dominant for simple APIs, microservices, and public APIs. GraphQL excels for complex data needs and mobile applications. The industry trend is toward using both where appropriate.',
  },
  zh: {
    title: 'REST vs GraphQL', description: 'REST API 与 GraphQL 的详细对比。',
    intro: 'REST 和 GraphQL 是构建 API 的两种主流方式。REST 已是标准超过十年，GraphQL 提供更灵活的查询语言。',
    tableFeature: '特性', tableRest: 'REST', tableGql: 'GraphQL',
    architecture: '架构', arcRest: '基于资源的端点', arcGql: '单一端点 + 查询', dataFetching: '数据获取', dfRest: '每个端点固定数据', dfGql: '客户端指定需要的数据', overFetching: '过度获取', ofRest: '常见（返回完整资源）', ofGql: '消除（仅请求需要的字段）', underFetching: '不足获取', ufRest: '常见（多次请求）', ufGql: '消除（嵌套查询）', caching: '缓存', caRest: '内置 HTTP 缓存', caGql: '复杂（需自定义方案）', learning: '学习曲线', leRest: '低', leGql: '中到高', versioning: '版本管理', veRest: 'URL 版本号', veGql: '无需版本（Schema 演进）',
    whatIsRest: '什么是 REST？', restText: 'REST 使用标准 HTTP 方法操作资源 URL。无状态、可缓存、统一接口。',
    whatIsGql: '什么是 GraphQL？', gqlText: 'GraphQL 是 Facebook 开发的 API 查询语言，使用单一端点和强类型 Schema。',
    whenRest: '何时使用 REST', restUse1: '简单 CRUD 应用', restUse2: '面向多种客户端的公共 API', restUse3: '数据简单的微服务', restUse4: 'HTTP 缓存重要时', restUse5: '文件上传/下载为主的应用',
    whenGql: '何时使用 GraphQL', gqlUse1: '复杂 UI 多数据关联', gqlUse2: '移动应用（减少数据传输）', gqlUse3: '聚合多数据源', gqlUse4: '前端快速迭代', gqlUse5: '实时功能（订阅）',
    verdict: '总结', verdictText: '简单资源型 API 用 REST。复杂数据需求和移动应用用 GraphQL。很多公司两者都用。',
    tryTools: '试试我们的 API 工具', faqTitle: '常见问题',
    faq1q: 'GraphQL 比 REST 快吗？', faq1a: '不一定。GraphQL 减少了过度获取，但 REST 有内置 HTTP 缓存。实际性能取决于数据模式。',
    faq2q: 'REST 和 GraphQL 可以一起用吗？', faq2a: '可以。很多公司用 GraphQL 作为网关层聚合多个 REST 微服务。',
    faq3q: 'GraphQL 会取代 REST 吗？', faq3a: '不会。两者适用不同场景，行业趋势是按需使用。',
  },
  fr: { title: 'REST vs GraphQL', description: 'Comparaison de REST et GraphQL.', intro: 'REST et GraphQL sont deux approches dominantes pour construire des APIs.', tableFeature: 'Caracteristique', tableRest: 'REST', tableGql: 'GraphQL', architecture: 'Architecture', arcRest: 'Endpoints par ressource', arcGql: 'Endpoint unique avec requetes', dataFetching: 'Recuperation', dfRest: 'Donnees fixes par endpoint', dfGql: 'Client specifie les donnees', overFetching: 'Sur-recuperation', ofRest: 'Courante', ofGql: 'Eliminee', underFetching: 'Sous-recuperation', ufRest: 'Courante', ufGql: 'Eliminee', caching: 'Cache', caRest: 'HTTP natif', caGql: 'Complexe', learning: 'Courbe d\'apprentissage', leRest: 'Faible', leGql: 'Moyenne a elevee', versioning: 'Versionnage', veRest: 'URL (v1/v2)', veGql: 'Non necessaire', whatIsRest: 'Qu\'est-ce que REST ?', restText: 'REST utilise les methodes HTTP standard sur des URLs de ressources.', whatIsGql: 'Qu\'est-ce que GraphQL ?', gqlText: 'GraphQL est un langage de requete pour APIs avec un endpoint unique et un schema type.', whenRest: 'Quand utiliser REST', restUse1: 'Applications CRUD simples', restUse2: 'APIs publiques', restUse3: 'Microservices simples', restUse4: 'Cache HTTP critique', restUse5: 'Upload/download fichiers', whenGql: 'Quand utiliser GraphQL', gqlUse1: 'UIs complexes', gqlUse2: 'Apps mobiles', gqlUse3: 'Agregation multi-sources', gqlUse4: 'Iteration frontend rapide', gqlUse5: 'Temps reel (subscriptions)', verdict: 'Resume', verdictText: 'REST pour les APIs simples. GraphQL pour les besoins complexes.', tryTools: 'Essayez nos outils API', faqTitle: 'Questions frequentes', faq1q: 'GraphQL est-il plus rapide que REST ?', faq1a: 'Pas inheremment. Depend des patterns de donnees.', faq2q: 'Peut-on utiliser REST et GraphQL ensemble ?', faq2a: 'Oui, GraphQL peut servir de couche gateway pour des microservices REST.', faq3q: 'GraphQL remplace-t-il REST ?', faq3a: 'Non, ils servent des cas differents.' },
  de: { title: 'REST vs GraphQL', description: 'Vergleich von REST und GraphQL.', intro: 'REST und GraphQL sind zwei dominante Ansaetze fuer API-Entwicklung.', tableFeature: 'Eigenschaft', tableRest: 'REST', tableGql: 'GraphQL', architecture: 'Architektur', arcRest: 'Ressourcenbasierte Endpoints', arcGql: 'Einzelner Endpoint mit Queries', dataFetching: 'Datenabruf', dfRest: 'Feste Daten pro Endpoint', dfGql: 'Client spezifiziert Daten', overFetching: 'Over-fetching', ofRest: 'Haeufig', ofGql: 'Eliminiert', underFetching: 'Under-fetching', ufRest: 'Haeufig', ufGql: 'Eliminiert', caching: 'Caching', caRest: 'Natives HTTP-Caching', caGql: 'Komplex', learning: 'Lernkurve', leRest: 'Niedrig', leGql: 'Mittel bis hoch', versioning: 'Versionierung', veRest: 'URL-basiert', veGql: 'Nicht noetig', whatIsRest: 'Was ist REST?', restText: 'REST verwendet Standard-HTTP-Methoden auf Ressourcen-URLs.', whatIsGql: 'Was ist GraphQL?', gqlText: 'GraphQL ist eine Abfragesprache fuer APIs mit einem einzelnen Endpoint und typisiertem Schema.', whenRest: 'Wann REST verwenden', restUse1: 'Einfache CRUD-Apps', restUse2: 'Oeffentliche APIs', restUse3: 'Einfache Microservices', restUse4: 'HTTP-Caching wichtig', restUse5: 'Datei-Upload/Download', whenGql: 'Wann GraphQL verwenden', gqlUse1: 'Komplexe UIs', gqlUse2: 'Mobile Apps', gqlUse3: 'Multi-Source-Aggregation', gqlUse4: 'Schnelle Frontend-Iteration', gqlUse5: 'Echtzeit-Features', verdict: 'Fazit', verdictText: 'REST fuer einfache APIs. GraphQL fuer komplexe Datenanforderungen.', tryTools: 'Probieren Sie unsere API-Tools', faqTitle: 'Haeufig gestellte Fragen', faq1q: 'Ist GraphQL schneller als REST?', faq1a: 'Nicht inherent. Abhaengig von Datenmustern.', faq2q: 'Kann man REST und GraphQL zusammen nutzen?', faq2a: 'Ja, GraphQL als Gateway fuer REST-Microservices.', faq3q: 'Ersetzt GraphQL REST?', faq3a: 'Nein, sie dienen verschiedenen Anwendungsfaellen.' },
  es: { title: 'REST vs GraphQL', description: 'Comparacion de REST y GraphQL.', intro: 'REST y GraphQL son dos enfoques dominantes para construir APIs.', tableFeature: 'Caracteristica', tableRest: 'REST', tableGql: 'GraphQL', architecture: 'Arquitectura', arcRest: 'Endpoints por recurso', arcGql: 'Endpoint unico con queries', dataFetching: 'Obtencion de datos', dfRest: 'Datos fijos por endpoint', dfGql: 'Cliente especifica datos', overFetching: 'Sobre-obtencion', ofRest: 'Comun', ofGql: 'Eliminada', underFetching: 'Sub-obtencion', ufRest: 'Comun', ufGql: 'Eliminada', caching: 'Cache', caRest: 'HTTP nativo', caGql: 'Complejo', learning: 'Curva de aprendizaje', leRest: 'Baja', leGql: 'Media a alta', versioning: 'Versionado', veRest: 'URL (v1/v2)', veGql: 'No necesario', whatIsRest: 'Que es REST?', restText: 'REST usa metodos HTTP estandar sobre URLs de recursos.', whatIsGql: 'Que es GraphQL?', gqlText: 'GraphQL es un lenguaje de consulta para APIs con un endpoint unico y schema tipado.', whenRest: 'Cuando usar REST', restUse1: 'Apps CRUD simples', restUse2: 'APIs publicas', restUse3: 'Microservicios simples', restUse4: 'Cache HTTP critico', restUse5: 'Upload/download archivos', whenGql: 'Cuando usar GraphQL', gqlUse1: 'UIs complejas', gqlUse2: 'Apps moviles', gqlUse3: 'Agregacion multi-fuente', gqlUse4: 'Iteracion frontend rapida', gqlUse5: 'Tiempo real (subscriptions)', verdict: 'Resumen', verdictText: 'REST para APIs simples. GraphQL para necesidades complejas.', tryTools: 'Prueba nuestras herramientas API', faqTitle: 'Preguntas frecuentes', faq1q: 'Es GraphQL mas rapido que REST?', faq1a: 'No inherentemente. Depende de los patrones de datos.', faq2q: 'Se pueden usar REST y GraphQL juntos?', faq2a: 'Si, GraphQL como capa gateway para microservicios REST.', faq3q: 'GraphQL reemplaza a REST?', faq3a: 'No, sirven casos diferentes.' },
  ja: { title: 'REST vs GraphQL', description: 'RESTとGraphQLの詳細な比較。', intro: 'RESTとGraphQLはAPI構築の2つの主要なアプローチです。', tableFeature: '特性', tableRest: 'REST', tableGql: 'GraphQL', architecture: 'アーキテクチャ', arcRest: 'リソースベースのエンドポイント', arcGql: '単一エンドポイント+クエリ', dataFetching: 'データ取得', dfRest: 'エンドポイント毎に固定データ', dfGql: 'クライアントが必要なデータを指定', overFetching: 'オーバーフェッチ', ofRest: '頻繁', ofGql: '解消', underFetching: 'アンダーフェッチ', ufRest: '頻繁', ufGql: '解消', caching: 'キャッシング', caRest: 'HTTP標準キャッシュ', caGql: '複雑', learning: '学習コスト', leRest: '低い', leGql: '中〜高', versioning: 'バージョニング', veRest: 'URLベース', veGql: '不要', whatIsRest: 'RESTとは？', restText: 'RESTは標準HTTPメソッドでリソースURLを操作するアーキテクチャスタイルです。', whatIsGql: 'GraphQLとは？', gqlText: 'GraphQLはFacebookが開発したAPI用クエリ言語で、単一エンドポイントと型付きスキーマを使います。', whenRest: 'RESTを使う場合', restUse1: 'シンプルなCRUDアプリ', restUse2: '公開API', restUse3: 'シンプルなマイクロサービス', restUse4: 'HTTPキャッシュが重要', restUse5: 'ファイルアップロード/ダウンロード', whenGql: 'GraphQLを使う場合', gqlUse1: '複雑なUI', gqlUse2: 'モバイルアプリ', gqlUse3: 'マルチソース集約', gqlUse4: '高速フロントエンド反復', gqlUse5: 'リアルタイム機能', verdict: 'まとめ', verdictText: 'シンプルなAPIにはREST。複雑なデータ要件にはGraphQL。', tryTools: 'APIツールを試す', faqTitle: 'よくある質問', faq1q: 'GraphQLはRESTより速いですか？', faq1a: '本質的にそうではありません。データパターンによります。', faq2q: 'RESTとGraphQLを一緒に使えますか？', faq2a: 'はい、GraphQLをRESTマイクロサービスのゲートウェイとして使えます。', faq3q: 'GraphQLはRESTを置き換えますか？', faq3a: 'いいえ、異なるユースケースに対応します。' },
  ko: { title: 'REST vs GraphQL', description: 'REST와 GraphQL의 상세 비교.', intro: 'REST와 GraphQL은 API 구축의 두 가지 주요 접근 방식입니다.', tableFeature: '특성', tableRest: 'REST', tableGql: 'GraphQL', architecture: '아키텍처', arcRest: '리소스 기반 엔드포인트', arcGql: '단일 엔드포인트 + 쿼리', dataFetching: '데이터 가져오기', dfRest: '엔드포인트별 고정 데이터', dfGql: '클라이언트가 필요한 데이터 지정', overFetching: '오버페칭', ofRest: '빈번', ofGql: '제거', underFetching: '언더페칭', ufRest: '빈번', ufGql: '제거', caching: '캐싱', caRest: 'HTTP 기본 캐싱', caGql: '복잡', learning: '학습 곡선', leRest: '낮음', leGql: '중간~높음', versioning: '버전 관리', veRest: 'URL 기반', veGql: '불필요', whatIsRest: 'REST란?', restText: 'REST는 표준 HTTP 메서드로 리소스 URL을 조작하는 아키텍처 스타일입니다.', whatIsGql: 'GraphQL이란?', gqlText: 'GraphQL은 Facebook이 개발한 API 쿼리 언어로, 단일 엔드포인트와 타입 스키마를 사용합니다.', whenRest: 'REST를 사용할 때', restUse1: '간단한 CRUD 앱', restUse2: '공개 API', restUse3: '간단한 마이크로서비스', restUse4: 'HTTP 캐싱이 중요할 때', restUse5: '파일 업로드/다운로드', whenGql: 'GraphQL을 사용할 때', gqlUse1: '복잡한 UI', gqlUse2: '모바일 앱', gqlUse3: '멀티소스 집계', gqlUse4: '빠른 프론트엔드 반복', gqlUse5: '실시간 기능', verdict: '요약', verdictText: '간단한 API에는 REST. 복잡한 데이터 요구사항에는 GraphQL.', tryTools: 'API 도구 사용해보기', faqTitle: '자주 묻는 질문', faq1q: 'GraphQL이 REST보다 빠른가요?', faq1a: '본질적으로 그렇지 않습니다. 데이터 패턴에 따라 다릅니다.', faq2q: 'REST와 GraphQL을 함께 사용할 수 있나요?', faq2a: '네, GraphQL을 REST 마이크로서비스의 게이트웨이로 사용할 수 있습니다.', faq3q: 'GraphQL이 REST를 대체하나요?', faq3a: '아닙니다, 서로 다른 사용 사례에 적합합니다.' },
};

const tableStyle={width:'100%',borderCollapse:'collapse' as const,fontSize:14};const thStyle={padding:'10px 14px',textAlign:'left' as const,borderBottom:'2px solid var(--border-color)',fontWeight:700};const tdStyle={padding:'10px 14px',borderBottom:'1px solid var(--border-color)'};const sectionStyle={marginTop:32};const h2Style={fontSize:22,fontWeight:700,marginBottom:12};const h3Style={fontSize:17,fontWeight:600,marginBottom:8};const pStyle={fontSize:14,lineHeight:1.8,color:'var(--text-secondary)',marginBottom:16};const ulStyle={fontSize:14,lineHeight:1.8,color:'var(--text-secondary)',paddingLeft:20,marginBottom:16};const cardStyle={background:'var(--bg-card)',borderRadius:12,padding:20,border:'1px solid var(--border-color)',marginBottom:16};

export default function RestVsGraphql() {
  const { lang } = useLang(); const ui = t[lang] || t.en;
  const faqSchema = { '@context':'https://schema.org','@type':'FAQPage',mainEntity:[{'@type':'Question',name:ui.faq1q,acceptedAnswer:{'@type':'Answer',text:ui.faq1a}},{'@type':'Question',name:ui.faq2q,acceptedAnswer:{'@type':'Answer',text:ui.faq2a}},{'@type':'Question',name:ui.faq3q,acceptedAnswer:{'@type':'Answer',text:ui.faq3a}}]};
  return (
    <ToolLayout title={ui.title} description={ui.description} toolId="rest-vs-graphql">
      <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(faqSchema)}} />
      <p style={pStyle}>{ui.intro}</p>
      <div style={{overflowX:'auto',marginBottom:24}}><table style={tableStyle}><thead><tr><th style={thStyle}>{ui.tableFeature}</th><th style={thStyle}>{ui.tableRest}</th><th style={thStyle}>{ui.tableGql}</th></tr></thead><tbody>{[[ui.architecture,ui.arcRest,ui.arcGql],[ui.dataFetching,ui.dfRest,ui.dfGql],[ui.overFetching,ui.ofRest,ui.ofGql],[ui.underFetching,ui.ufRest,ui.ufGql],[ui.caching,ui.caRest,ui.caGql],[ui.learning,ui.leRest,ui.leGql],[ui.versioning,ui.veRest,ui.veGql]].map(([f,a,b],i)=>(<tr key={i}><td style={{...tdStyle,fontWeight:600}}>{f}</td><td style={tdStyle}>{a}</td><td style={tdStyle}>{b}</td></tr>))}</tbody></table></div>
      <div style={sectionStyle}><h2 style={h2Style}>{ui.whatIsRest}</h2><p style={pStyle}>{ui.restText}</p></div>
      <div style={sectionStyle}><h2 style={h2Style}>{ui.whatIsGql}</h2><p style={pStyle}>{ui.gqlText}</p></div>
      <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))',gap:16,...sectionStyle}}>
        <div style={cardStyle}><h3 style={h3Style}>{ui.whenRest}</h3><ul style={ulStyle}><li>{ui.restUse1}</li><li>{ui.restUse2}</li><li>{ui.restUse3}</li><li>{ui.restUse4}</li><li>{ui.restUse5}</li></ul></div>
        <div style={cardStyle}><h3 style={h3Style}>{ui.whenGql}</h3><ul style={ulStyle}><li>{ui.gqlUse1}</li><li>{ui.gqlUse2}</li><li>{ui.gqlUse3}</li><li>{ui.gqlUse4}</li><li>{ui.gqlUse5}</li></ul></div>
      </div>
      <div style={{...cardStyle,background:'var(--bg-input)',...sectionStyle}}><h2 style={h2Style}>{ui.verdict}</h2><p style={{...pStyle,fontWeight:500}}>{ui.verdictText}</p></div>
      <div style={sectionStyle}><h2 style={h2Style}>{ui.tryTools}</h2><div style={{display:'flex',flexWrap:'wrap',gap:8}}>{[{href:`/${lang}/tools/json-formatter`,label:'JSON Formatter'},{href:`/${lang}/tools/json-to-typescript`,label:'JSON to TypeScript'},{href:`/${lang}/tools/json-to-graphql`,label:'JSON to GraphQL'},{href:`/${lang}/tools/curl-to-code`,label:'cURL to Code'}].map(link=>(<Link key={link.href} href={link.href} style={{display:'inline-block',padding:'8px 16px',borderRadius:8,border:'1px solid var(--border-color)',fontSize:13,color:'var(--accent-blue)',textDecoration:'none',background:'var(--bg-input)'}}>{link.label}</Link>))}</div></div>
      <div style={sectionStyle}><h2 style={h2Style}>{ui.faqTitle}</h2><div style={{display:'flex',flexDirection:'column',gap:8}}>{[{q:ui.faq1q,a:ui.faq1a},{q:ui.faq2q,a:ui.faq2a},{q:ui.faq3q,a:ui.faq3a}].map((faq,idx)=>(<details key={idx} style={{border:'1px solid var(--border-color)',borderRadius:8,overflow:'hidden',background:'var(--bg-input)'}}><summary style={{padding:'14px 16px',cursor:'pointer',fontSize:14,fontWeight:600}}>{faq.q}</summary><div style={{padding:'0 16px 14px',fontSize:13,lineHeight:1.7,color:'var(--text-secondary)'}}>{faq.a}</div></details>))}</div></div>
    </ToolLayout>
  );
}
