const fs = require('fs');
const path = require('path');
const dictDir = path.join(__dirname, '..', 'src', 'i18n', 'dictionaries');
const locales = ['en','fr','de','it','es','pt','nl','pl','sv','no','zh','ja','ko','id','th'];

const toolEntries = {
  en: {
    'curl-to-code': { name: 'cURL to Code Converter', description: 'Convert cURL commands to Python, JavaScript, Go, PHP, and more', pageTitle: 'cURL to Code Converter — Python, JavaScript, Go, PHP', pageDescription: 'Convert cURL commands to Python requests, JavaScript fetch, Go, PHP, Ruby, Java, and C#. Paste any cURL command and get clean code instantly.', seoTitle: 'What is a cURL to Code Converter?', seoContent: 'A cURL to code converter translates cURL commands from API documentation or browser DevTools into equivalent code in your preferred programming language.', howToUseTitle: 'How to Use', howToUseSteps: ['Paste a cURL command', 'Select target language', 'View generated code', 'Copy the code'], useCasesTitle: 'Use Cases', useCases: ['Converting API docs to code', 'Translating browser network requests', 'Quick API prototyping', 'Learning HTTP request syntax'], faqTitle: 'FAQ', faqs: [{ q: 'What languages are supported?', a: 'Python, JavaScript (fetch/axios), Go, PHP, Ruby, Java, C#, and more.' }, { q: 'Can I paste cURL from Chrome DevTools?', a: 'Yes, copy as cURL from Chrome Network tab and paste directly.' }] },
    'yaml-validator': { name: 'YAML Validator & Formatter', description: 'Validate and format YAML with error highlighting', pageTitle: 'YAML Validator & Formatter — Lint and Beautify YAML', pageDescription: 'Validate YAML syntax, highlight errors with line numbers, and auto-format for readability. Supports Kubernetes, Docker Compose, and GitHub Actions.', seoTitle: 'What is a YAML Validator?', seoContent: 'A YAML validator checks your YAML files for syntax errors, indentation issues, and formatting problems. Essential for DevOps and configuration management.', howToUseTitle: 'How to Use', howToUseSteps: ['Paste YAML content', 'View validation results', 'Fix highlighted errors', 'Copy formatted YAML'], useCasesTitle: 'Use Cases', useCases: ['Validating Kubernetes manifests', 'Checking Docker Compose files', 'Debugging CI/CD configs', 'Formatting YAML for readability'], faqTitle: 'FAQ', faqs: [{ q: 'Does it support multi-document YAML?', a: 'Yes, documents separated by --- are validated independently.' }, { q: 'Can it detect indentation errors?', a: 'Yes, indentation issues are highlighted with specific line numbers.' }] },
    'gitignore-generator': { name: '.gitignore Generator', description: 'Generate .gitignore files for any language, framework, or IDE', pageTitle: '.gitignore Generator — Templates for Every Stack', pageDescription: 'Generate .gitignore files for Node.js, Python, Java, Go, React, Vue, VS Code, IntelliJ, macOS, and 100+ more templates.', seoTitle: 'What is a .gitignore Generator?', seoContent: 'A .gitignore generator creates customized .gitignore files by combining templates for your programming language, framework, IDE, and operating system.', howToUseTitle: 'How to Use', howToUseSteps: ['Search for your language or framework', 'Select multiple templates', 'Preview the combined .gitignore', 'Copy or download the file'], useCasesTitle: 'Use Cases', useCases: ['Setting up new projects', 'Adding framework-specific ignores', 'Preventing accidental commits', 'Standardizing team .gitignore'], faqTitle: 'FAQ', faqs: [{ q: 'Can I combine multiple templates?', a: 'Yes, select multiple languages, frameworks, and IDEs to combine them.' }, { q: 'Are the templates up to date?', a: 'Templates follow GitHub\'s official gitignore repository patterns.' }] },
    'json-to-dart': { name: 'JSON to Dart', description: 'Convert JSON to Dart classes with fromJson/toJson for Flutter', pageTitle: 'JSON to Dart Converter — Flutter Class Generator', pageDescription: 'Convert JSON data to null-safe Dart classes with fromJson() and toJson() methods. Perfect for Flutter app development.', seoTitle: 'What is JSON to Dart?', seoContent: 'JSON to Dart converts JSON API responses into Dart model classes with serialization methods, making Flutter development faster and type-safe.', howToUseTitle: 'How to Use', howToUseSteps: ['Paste JSON data', 'Set root class name', 'Choose options (null safety, etc.)', 'Copy generated Dart code'], useCasesTitle: 'Use Cases', useCases: ['Flutter API integration', 'Creating model classes', 'Type-safe JSON parsing', 'Rapid prototyping'], faqTitle: 'FAQ', faqs: [{ q: 'Does it support null safety?', a: 'Yes, generated classes use Dart null safety with nullable types where appropriate.' }, { q: 'Can it handle nested JSON?', a: 'Yes, nested objects generate separate classes with proper references.' }] },
    'nginx-config': { name: 'Nginx Config Generator', description: 'Generate Nginx configuration for reverse proxy, SSL, and more', pageTitle: 'Nginx Config Generator — Reverse Proxy, SSL, Static Sites', pageDescription: 'Generate production-ready Nginx configuration for reverse proxy, SSL/HTTPS, static sites, PHP-FPM, Node.js, and load balancing.', seoTitle: 'What is an Nginx Config Generator?', seoContent: 'An Nginx config generator creates production-ready server configuration files with proper security headers, SSL, and reverse proxy settings.', howToUseTitle: 'How to Use', howToUseSteps: ['Select server type (reverse proxy, static, etc.)', 'Configure domain and ports', 'Enable SSL and security options', 'Copy the generated config'], useCasesTitle: 'Use Cases', useCases: ['Setting up reverse proxy', 'Configuring SSL/HTTPS', 'Serving static websites', 'Load balancing setup'], faqTitle: 'FAQ', faqs: [{ q: 'Does it include SSL configuration?', a: 'Yes, with Let\'s Encrypt compatible settings, HSTS, and modern cipher suites.' }, { q: 'Can I configure multiple server blocks?', a: 'The generator creates a single server block. Add multiple blocks manually.' }] },
    'htaccess-generator': { name: '.htaccess Generator', description: 'Generate .htaccess files for redirects, security, and caching', pageTitle: '.htaccess Generator — Redirects, Security Headers, Caching', pageDescription: 'Generate Apache .htaccess files for 301 redirects, HTTPS enforcement, security headers, browser caching, gzip compression, and URL rewriting.', seoTitle: 'What is an .htaccess Generator?', seoContent: 'An .htaccess generator creates Apache configuration files for URL redirects, security headers, caching rules, and access control without editing the main server config.', howToUseTitle: 'How to Use', howToUseSteps: ['Select features to enable', 'Configure redirects and rules', 'Preview the .htaccess code', 'Copy and upload to your server'], useCasesTitle: 'Use Cases', useCases: ['Setting up 301 redirects', 'Enforcing HTTPS', 'Adding security headers', 'Enabling browser caching'], faqTitle: 'FAQ', faqs: [{ q: 'Does it work with all Apache servers?', a: 'Yes, if mod_rewrite is enabled (standard on most hosts).' }, { q: 'Can I use this for WordPress?', a: 'Yes, the generated rules work alongside WordPress .htaccess rules.' }] },
    'docker-compose-generator': { name: 'Docker Compose Generator', description: 'Build docker-compose.yml visually with service presets', pageTitle: 'Docker Compose Generator — Visual YAML Builder', pageDescription: 'Build docker-compose.yml files visually. Add services from presets (PostgreSQL, Redis, MongoDB, Nginx, Node.js) with volumes, networks, and environment variables.', seoTitle: 'What is a Docker Compose Generator?', seoContent: 'A Docker Compose generator helps you build docker-compose.yml files visually by selecting pre-configured service templates and customizing settings.', howToUseTitle: 'How to Use', howToUseSteps: ['Add services from presets', 'Configure ports and volumes', 'Set environment variables', 'Copy the docker-compose.yml'], useCasesTitle: 'Use Cases', useCases: ['Setting up development environments', 'Creating multi-container apps', 'Learning Docker Compose', 'Quick stack prototyping'], faqTitle: 'FAQ', faqs: [{ q: 'What service presets are available?', a: 'PostgreSQL, MySQL, MongoDB, Redis, Nginx, Node.js, Python, and more.' }, { q: 'Does it generate valid YAML?', a: 'Yes, the output is valid docker-compose.yml that can be used directly.' }] },
    'json-to-protobuf': { name: 'JSON to Protobuf', description: 'Convert JSON to Protocol Buffers .proto schema definitions', pageTitle: 'JSON to Protobuf Converter — Generate .proto Files', pageDescription: 'Convert JSON data to Protocol Buffers (.proto) schema definitions with proper type inference, nested messages, and enum detection for gRPC.', seoTitle: 'What is JSON to Protobuf?', seoContent: 'JSON to Protobuf converts JSON sample data into Protocol Buffer schema definitions (.proto files) used in gRPC microservices and high-performance APIs.', howToUseTitle: 'How to Use', howToUseSteps: ['Paste JSON data', 'Set package and message name', 'Review generated .proto schema', 'Copy the schema'], useCasesTitle: 'Use Cases', useCases: ['gRPC service development', 'API schema design', 'Migrating REST to gRPC', 'Protobuf learning'], faqTitle: 'FAQ', faqs: [{ q: 'What protobuf syntax version is used?', a: 'Proto3 syntax is generated by default.' }, { q: 'Does it detect repeated fields?', a: 'Yes, JSON arrays are converted to repeated fields automatically.' }] },
    'csp-generator': { name: 'CSP Header Generator', description: 'Build Content-Security-Policy headers interactively', pageTitle: 'CSP Header Generator — Content Security Policy Builder', pageDescription: 'Build Content-Security-Policy headers with an interactive directive editor. Presets for strict, moderate, and permissive policies.', seoTitle: 'What is a CSP Generator?', seoContent: 'A Content-Security-Policy generator helps you build CSP headers that protect your website from XSS, data injection, and other code injection attacks.', howToUseTitle: 'How to Use', howToUseSteps: ['Select a preset or start from scratch', 'Configure each directive', 'Add trusted sources', 'Copy the CSP header'], useCasesTitle: 'Use Cases', useCases: ['Preventing XSS attacks', 'Meeting security compliance', 'Configuring Content-Security-Policy', 'Testing CSP rules'], faqTitle: 'FAQ', faqs: [{ q: 'What directives are supported?', a: 'All standard CSP directives including default-src, script-src, style-src, img-src, and more.' }, { q: 'Can I test my CSP?', a: 'Use report-uri directive for monitoring. This tool generates the header you need.' }] },
    'sql-to-prisma': { name: 'SQL to Prisma Schema', description: 'Convert SQL CREATE TABLE to Prisma schema models', pageTitle: 'SQL to Prisma Schema Converter — Generate Prisma Models', pageDescription: 'Convert SQL CREATE TABLE statements to Prisma schema models with proper types, relations, indexes, and default values. Supports MySQL and PostgreSQL.', seoTitle: 'What is SQL to Prisma?', seoContent: 'SQL to Prisma converts existing SQL database schemas into Prisma schema format, making it easy to adopt Prisma ORM in TypeScript/Node.js projects.', howToUseTitle: 'How to Use', howToUseSteps: ['Paste SQL CREATE TABLE statements', 'Select SQL dialect (MySQL/PostgreSQL)', 'Review generated Prisma schema', 'Copy the schema'], useCasesTitle: 'Use Cases', useCases: ['Migrating to Prisma ORM', 'Reverse-engineering databases', 'Learning Prisma schema syntax', 'Database documentation'], faqTitle: 'FAQ', faqs: [{ q: 'What SQL dialects are supported?', a: 'MySQL and PostgreSQL CREATE TABLE syntax.' }, { q: 'Does it handle foreign keys?', a: 'Yes, foreign key constraints are converted to Prisma @relation directives.' }] },
  },
  zh: {
    'curl-to-code': { name: 'cURL 转代码', description: '将 cURL 命令转换为 Python、JavaScript、Go 等代码', pageTitle: 'cURL 转代码 — Python、JavaScript、Go、PHP', pageDescription: '将 cURL 命令转换为 Python requests、JavaScript fetch、Go、PHP 等代码。' },
    'yaml-validator': { name: 'YAML 验证器', description: '验证和格式化 YAML，高亮显示错误', pageTitle: 'YAML 验证器 — 语法检查和格式化', pageDescription: '验证 YAML 语法、高亮错误并自动格式化。支持 Kubernetes、Docker Compose 配置。' },
    'gitignore-generator': { name: '.gitignore 生成器', description: '为任何语言和框架生成 .gitignore 文件', pageTitle: '.gitignore 生成器 — 支持所有技术栈', pageDescription: '为 Node.js、Python、Java、Go、React 等生成 .gitignore 文件，支持 100+ 模板。' },
    'json-to-dart': { name: 'JSON 转 Dart', description: '将 JSON 转换为 Flutter 用的 Dart 类', pageTitle: 'JSON 转 Dart — Flutter 类生成器', pageDescription: '将 JSON 数据转换为空安全的 Dart 类，自动生成 fromJson/toJson 方法。' },
    'nginx-config': { name: 'Nginx 配置生成器', description: '生成反向代理、SSL 等 Nginx 配置', pageTitle: 'Nginx 配置生成器 — 反向代理、SSL、静态站点', pageDescription: '生成生产级 Nginx 配置：反向代理、SSL/HTTPS、静态站点、负载均衡。' },
    'htaccess-generator': { name: '.htaccess 生成器', description: '生成重定向、安全头和缓存的 .htaccess', pageTitle: '.htaccess 生成器 — 重定向、安全、缓存', pageDescription: '生成 Apache .htaccess 文件：301 重定向、HTTPS 强制、安全头、浏览器缓存。' },
    'docker-compose-generator': { name: 'Docker Compose 生成器', description: '可视化构建 docker-compose.yml', pageTitle: 'Docker Compose 生成器 — 可视化 YAML 构建', pageDescription: '可视化构建 docker-compose.yml，包含 PostgreSQL、Redis、MongoDB 等预设服务。' },
    'json-to-protobuf': { name: 'JSON 转 Protobuf', description: '将 JSON 转换为 Protocol Buffers 定义', pageTitle: 'JSON 转 Protobuf — 生成 .proto 文件', pageDescription: '将 JSON 数据转换为 Protocol Buffers (.proto) 模式定义，用于 gRPC 开发。' },
    'csp-generator': { name: 'CSP 头生成器', description: '交互式构建内容安全策略头', pageTitle: 'CSP 头生成器 — 内容安全策略构建器', pageDescription: '使用交互式编辑器构建 Content-Security-Policy 头，防御 XSS 攻击。' },
    'sql-to-prisma': { name: 'SQL 转 Prisma', description: '将 SQL 建表语句转换为 Prisma 模型', pageTitle: 'SQL 转 Prisma — 生成 Prisma 模型', pageDescription: '将 SQL CREATE TABLE 语句转换为 Prisma 模式模型，支持 MySQL 和 PostgreSQL。' },
  },
  ja: {
    'curl-to-code': { name: 'cURL コード変換', description: 'cURLコマンドをPython、JavaScript等に変換', pageTitle: 'cURL コード変換ツール', pageDescription: 'cURLコマンドをPython、JavaScript、Go、PHPなどのコードに変換。' },
    'yaml-validator': { name: 'YAMLバリデーター', description: 'YAML構文を検証しフォーマット', pageTitle: 'YAMLバリデーター＆フォーマッター', pageDescription: 'YAML構文チェック、エラー表示、自動フォーマット。' },
    'gitignore-generator': { name: '.gitignoreジェネレーター', description: 'あらゆる言語用の.gitignoreを生成', pageTitle: '.gitignoreジェネレーター', pageDescription: 'Node.js、Python、Java等の.gitignoreファイルを生成。' },
    'json-to-dart': { name: 'JSON→Dart変換', description: 'JSONをFlutter用Dartクラスに変換', pageTitle: 'JSON→Dart変換ツール', pageDescription: 'JSONデータをnull安全なDartクラスに変換。' },
    'nginx-config': { name: 'Nginx設定ジェネレーター', description: 'Nginx設定ファイルを生成', pageTitle: 'Nginx設定ジェネレーター', pageDescription: 'リバースプロキシ、SSL、静的サイト用のNginx設定を生成。' },
    'htaccess-generator': { name: '.htaccessジェネレーター', description: 'リダイレクトやセキュリティの.htaccessを生成', pageTitle: '.htaccessジェネレーター', pageDescription: '301リダイレクト、HTTPS強制、セキュリティヘッダー用の.htaccessを生成。' },
    'docker-compose-generator': { name: 'Docker Composeジェネレーター', description: 'docker-compose.ymlを視覚的に構築', pageTitle: 'Docker Composeジェネレーター', pageDescription: 'PostgreSQL、Redis、MongoDB等のプリセットでdocker-compose.ymlを構築。' },
    'json-to-protobuf': { name: 'JSON→Protobuf変換', description: 'JSONをProtocol Buffers定義に変換', pageTitle: 'JSON→Protobuf変換ツール', pageDescription: 'JSONデータをProtocol Buffers (.proto) スキーマに変換。' },
    'csp-generator': { name: 'CSPヘッダー生成', description: 'コンテンツセキュリティポリシーを構築', pageTitle: 'CSPヘッダージェネレーター', pageDescription: 'Content-Security-Policyヘッダーをインタラクティブに構築。' },
    'sql-to-prisma': { name: 'SQL→Prisma変換', description: 'SQLをPrismaスキーマに変換', pageTitle: 'SQL→Prisma変換ツール', pageDescription: 'SQL CREATE TABLE文をPrismaスキーマモデルに変換。' },
  },
  ko: {
    'curl-to-code': { name: 'cURL 코드 변환기', description: 'cURL 명령을 Python, JavaScript 등으로 변환', pageTitle: 'cURL 코드 변환기', pageDescription: 'cURL 명령을 Python, JavaScript, Go, PHP 코드로 변환합니다.' },
    'yaml-validator': { name: 'YAML 검증기', description: 'YAML 구문 검증 및 포맷', pageTitle: 'YAML 검증기 & 포맷터', pageDescription: 'YAML 구문 검사, 오류 표시, 자동 포맷을 지원합니다.' },
    'gitignore-generator': { name: '.gitignore 생성기', description: '모든 언어용 .gitignore 생성', pageTitle: '.gitignore 생성기', pageDescription: 'Node.js, Python, Java 등의 .gitignore 파일을 생성합니다.' },
    'json-to-dart': { name: 'JSON to Dart', description: 'JSON을 Flutter용 Dart 클래스로 변환', pageTitle: 'JSON to Dart 변환기', pageDescription: 'JSON 데이터를 null-safe Dart 클래스로 변환합니다.' },
    'nginx-config': { name: 'Nginx 설정 생성기', description: 'Nginx 설정 파일 생성', pageTitle: 'Nginx 설정 생성기', pageDescription: '리버스 프록시, SSL, 정적 사이트용 Nginx 설정을 생성합니다.' },
    'htaccess-generator': { name: '.htaccess 생성기', description: '리다이렉트, 보안 헤더용 .htaccess 생성', pageTitle: '.htaccess 생성기', pageDescription: '301 리다이렉트, HTTPS 강제, 보안 헤더용 .htaccess를 생성합니다.' },
    'docker-compose-generator': { name: 'Docker Compose 생성기', description: 'docker-compose.yml 시각적 빌더', pageTitle: 'Docker Compose 생성기', pageDescription: 'PostgreSQL, Redis, MongoDB 프리셋으로 docker-compose.yml을 구축합니다.' },
    'json-to-protobuf': { name: 'JSON to Protobuf', description: 'JSON을 Protocol Buffers 정의로 변환', pageTitle: 'JSON to Protobuf 변환기', pageDescription: 'JSON 데이터를 Protocol Buffers (.proto) 스키마로 변환합니다.' },
    'csp-generator': { name: 'CSP 헤더 생성기', description: '콘텐츠 보안 정책 헤더 구축', pageTitle: 'CSP 헤더 생성기', pageDescription: 'Content-Security-Policy 헤더를 인터랙티브하게 구축합니다.' },
    'sql-to-prisma': { name: 'SQL to Prisma', description: 'SQL을 Prisma 스키마로 변환', pageTitle: 'SQL to Prisma 변환기', pageDescription: 'SQL CREATE TABLE 문을 Prisma 스키마 모델로 변환합니다.' },
  },
};

for (const locale of locales) {
  const filePath = path.join(dictDir, `${locale}.json`);
  const dict = JSON.parse(fs.readFileSync(filePath, 'utf8'));
  const toolData = toolEntries[locale] || toolEntries.en;
  for (const [toolId, entry] of Object.entries(toolData)) {
    if (!dict.tools[toolId]) {
      if (locale !== 'en' && !entry.seoTitle) {
        dict.tools[toolId] = { ...toolEntries.en[toolId], ...entry };
      } else {
        dict.tools[toolId] = entry;
      }
    }
  }
  fs.writeFileSync(filePath, JSON.stringify(dict, null, 2) + '\n', 'utf8');
  console.log(`Updated: ${locale}.json`);
}
console.log('Done!');
