#!/usr/bin/env node
/**
 * Generate ja.json and ko.json from en.json with Japanese and Korean translations.
 * Run: node scripts/generate-ja-ko.js
 */
const fs = require('fs');
const path = require('path');

const enPath = path.join(__dirname, '../src/i18n/dictionaries/en.json');
const jaPath = path.join(__dirname, '../src/i18n/dictionaries/ja.json');
const koPath = path.join(__dirname, '../src/i18n/dictionaries/ko.json');

const en = JSON.parse(fs.readFileSync(enPath, 'utf8'));

const jaMap = {
  "Search tools... (e.g. json, base64, uuid)": "ツールを検索...（例：json、base64、uuid）",
  "All Tools": "すべてのツール",
  "FREE": "無料",
  "Home": "ホーム",
  "More Tools": "その他のツール",
  "Copy": "コピー",
  "Copied!": "コピーしました！",
  "Clear": "クリア",
  "Clear All": "すべてクリア",
  "Privacy Policy": "プライバシーポリシー",
  "About": "について",
  "Error": "エラー",
  "No tools found for": "関連するツールが見つかりません：",
  "Try a different search term": "別の検索語を試してください",
  "Input": "入力",
  "Output": "出力",
  "Encode": "エンコード",
  "Decode": "デコード",
  "Generate": "生成",
  "Convert": "変換",
  "Swap": "入れ替え",
  "Download": "ダウンロード",
  "Load Sample": "サンプルを読み込む",
  "Format": "フォーマット",
  "Minify": "圧縮",
  "Beautify": "整形",
  "Validate": "検証",
  "Parse": "解析",
  "Compare": "比較",
  "Copy All": "すべてコピー",
  "Result will appear here...": "結果がここに表示されます...",
  "characters": "文字",
  "saved": "保存済み",
  "words": "単語",
  "added": "追加",
  "removed": "削除",
  "unchanged": "変更なし",
  "Free Online": "無料オンライン",
  "Developer Tools": "開発者ツール",
  "40+ essential tools for developers. No signup, no limits. All processing happens right in your browser — your data never leaves your device.": "40以上の開発者向けツール。登録不要、制限なし。すべてブラウザ内で処理 — データはデバイスから送信されません。",
  "Search tools... (json, base64, uuid, hash...)": "ツールを検索...（json、base64、uuid、hash...）",
  "Why": "なぜ",
  "Privacy First": "プライバシー優先",
  "All data is processed locally in your browser. Nothing is sent to any server.": "すべてのデータはブラウザ内で処理され、サーバーに送信されません。",
  "Instant & Fast": "即座＆高速",
  "No loading, no waiting. Tools work instantly with zero latency.": "読み込み不要、待機なし。ツールは即座に動作します。",
  "100% Free": "100%無料",
  "No signup, no limits, no hidden fees. Free forever.": "登録不要、制限なし、隠れた費用なし。永久無料。",
  "Works Everywhere": "どこでも使用可能",
  "Fully responsive. Use on desktop, tablet, or mobile.": "完全レスポンシブ。デスクトップ、タブレット、モバイルで使用可能。",
  "Encoder / Decoder": "エンコーダー / デコーダー",
  "Formatter / Beautifier": "フォーマッター / ビューティファイアー",
  "Generator": "ジェネレーター",
  "Converter": "コンバーター",
  "Text Tools": "テキストツール",
  "Web Tools": "Webツール",
  "Free online developer tools. No signup required. All processing happens in your browser — your data never leaves your device.": "無料のオンライン開発者ツール。登録不要。すべてブラウザ内で処理 — データはデバイスから送信されません。",
  "DevToolBox. All tools are free and open-source.": "DevToolBox。すべてのツールは無料かつオープンソースです。",
  "About DevToolBox": "DevToolBoxについて",
  "DevToolBox is a collection of free, online developer tools built for programmers, designers, and everyone who works with data.": "DevToolBoxは、プログラマー、デザイナー、データを扱うすべての人のための無料オンライン開発者ツール集です。",
  "Our Mission": "私たちの使命",
  "We believe developer tools should be free, fast, and private. Every tool on DevToolBox processes data entirely in your browser — nothing is ever sent to a server.": "開発者ツールは無料で、高速で、プライベートであるべきだと考えています。DevToolBoxのすべてのツールはブラウザ内でデータを処理し、サーバーに送信することはありません。",
  "Features": "機能",
  "40+ essential developer tools": "40以上の開発者向けツール",
  "100% client-side processing — your data never leaves your browser": "100%クライアント側処理 — データはブラウザから送信されません",
  "No signup, no accounts, no tracking": "登録不要、アカウント不要、トラッキングなし",
  "Works on desktop, tablet, and mobile": "デスクトップ、タブレット、モバイルで動作",
  "Fast and lightweight": "高速で軽量",
  "Contact": "お問い合わせ",
  "Have feedback or suggestions? Open an issue on our": "フィードバックや提案がありますか？当社の",
  "DevToolBox - Free Online Developer Tools": "DevToolBox - 無料オンライン開発者ツール",
  "Free online developer tools: JSON formatter, Base64 encoder, UUID generator, regex tester, hash generator, and 40+ more. No signup required. All processing in your browser.": "無料オンライン開発者ツール：JSONフォーマッター、Base64エンコーダー、UUIDジェネレーター、正規表現テスター、ハッシュジェネレーターなど40以上。登録不要。すべてブラウザ内で処理。",
  "Blog": "ブログ",
  "DevToolBox Blog": "DevToolBoxブログ",
  "Developer guides, tutorials, and best practices for working with online tools": "オンラインツールの開発者ガイド、チュートリアル、ベストプラクティス",
  "Read More": "続きを読む",
  "At DevToolBox, your privacy is our top priority.": "DevToolBoxでは、お客様のプライバシーを最優先に考えています。",
  "Data Processing": "データ処理",
  "All tools on DevToolBox process data entirely in your browser. We never send your data to any server. Your input never leaves your device.": "DevToolBoxのすべてのツールはブラウザ内でデータを処理します。データをサーバーに送信することはありません。入力はデバイスから送信されません。",
  "Cookies": "Cookie",
  "We may use cookies for analytics purposes (e.g. Google Analytics) and advertising (e.g. Google AdSense) to understand how visitors use our site and to display relevant ads. These third-party services may collect anonymous usage data.": "分析（Google Analyticsなど）や広告（Google AdSenseなど）のためにCookieを使用し、訪問者が当サイトをどのように使用しているかを理解し、関連する広告を表示する場合があります。",
  "Advertising": "広告",
  "We display advertisements through Google AdSense to support the free operation of this website. AdSense may use cookies and web beacons to serve ads based on your prior visits.": "当サイトの無料運営を支援するため、Google AdSenseで広告を表示しています。AdSenseはCookieとウェブビーコンを使用して、過去の訪問に基づいて広告を配信する場合があります。",
  "Third-Party Services": "第三者サービス",
  "We use the following third-party services:": "以下の第三者サービスを使用しています：",
  "Google Analytics — for anonymous usage statistics": "Google Analytics — 匿名使用統計",
  "Google AdSense — for displaying advertisements": "Google AdSense — 広告表示",
  "Changes": "変更",
  "We may update this privacy policy from time to time. Check back periodically for updates.": "このプライバシーポリシーは随時更新される場合があります。定期的に確認してください。",
  "Questions about this policy? Open an issue on our GitHub repository.": "このポリシーについての質問は、GitHubリポジトリでIssueを作成してください。",
};

const koMap = {
  "Search tools... (e.g. json, base64, uuid)": "도구 검색... (예: json, base64, uuid)",
  "All Tools": "전체 도구",
  "FREE": "무료",
  "Home": "홈",
  "More Tools": "더 많은 도구",
  "Copy": "복사",
  "Copied!": "복사됨!",
  "Clear": "지우기",
  "Clear All": "전체 지우기",
  "Privacy Policy": "개인정보처리방침",
  "About": "소개",
  "Error": "오류",
  "No tools found for": "관련 도구를 찾을 수 없습니다:",
  "Try a different search term": "다른 검색어를 시도해 보세요",
  "Input": "입력",
  "Output": "출력",
  "Encode": "인코딩",
  "Decode": "디코딩",
  "Generate": "생성",
  "Convert": "변환",
  "Swap": "교환",
  "Download": "다운로드",
  "Load Sample": "샘플 로드",
  "Format": "포맷",
  "Minify": "압축",
  "Beautify": "정렬",
  "Validate": "검증",
  "Parse": "파싱",
  "Compare": "비교",
  "Copy All": "전체 복사",
  "Result will appear here...": "결과가 여기에 표시됩니다...",
  "characters": "문자",
  "saved": "저장됨",
  "words": "단어",
  "added": "추가",
  "removed": "제거",
  "unchanged": "변경 없음",
  "Free Online": "무료 온라인",
  "Developer Tools": "개발자 도구",
  "40+ essential tools for developers. No signup, no limits. All processing happens right in your browser — your data never leaves your device.": "40개 이상의 필수 개발자 도구. 가입 불필요, 제한 없음. 모든 처리는 브라우저에서 이루어집니다 — 데이터가 기기를 벗어나지 않습니다.",
  "Search tools... (json, base64, uuid, hash...)": "도구 검색... (json, base64, uuid, hash...)",
  "Why": "왜",
  "Privacy First": "개인정보 우선",
  "All data is processed locally in your browser. Nothing is sent to any server.": "모든 데이터는 브라우저에서 로컬로 처리됩니다. 서버로 전송되지 않습니다.",
  "Instant & Fast": "즉시 & 빠름",
  "No loading, no waiting. Tools work instantly with zero latency.": "로딩 없음, 대기 없음. 도구가 즉시 작동합니다.",
  "100% Free": "100% 무료",
  "No signup, no limits, no hidden fees. Free forever.": "가입 불필요, 제한 없음, 숨겨진 요금 없음. 영구 무료.",
  "Works Everywhere": "어디서나 사용 가능",
  "Fully responsive. Use on desktop, tablet, or mobile.": "완전 반응형. 데스크톱, 태블릿, 모바일에서 사용 가능.",
  "Encoder / Decoder": "인코더 / 디코더",
  "Formatter / Beautifier": "포맷터 / 뷰티파이어",
  "Generator": "생성기",
  "Converter": "변환기",
  "Text Tools": "텍스트 도구",
  "Web Tools": "웹 도구",
  "Free online developer tools. No signup required. All processing happens in your browser — your data never leaves your device.": "무료 온라인 개발자 도구. 가입 불필요. 모든 처리는 브라우저에서 이루어집니다 — 데이터가 기기를 벗어나지 않습니다.",
  "DevToolBox. All tools are free and open-source.": "DevToolBox. 모든 도구는 무료이며 오픈소스입니다.",
  "About DevToolBox": "DevToolBox 소개",
  "DevToolBox is a collection of free, online developer tools built for programmers, designers, and everyone who works with data.": "DevToolBox는 프로그래머, 디자이너, 데이터를 다루는 모든 사람을 위한 무료 온라인 개발자 도구 모음입니다.",
  "Our Mission": "우리의 미션",
  "We believe developer tools should be free, fast, and private. Every tool on DevToolBox processes data entirely in your browser — nothing is ever sent to a server.": "개발자 도구는 무료하고, 빠르고, 사적으로 유지되어야 한다고 믿습니다. DevToolBox의 모든 도구는 브라우저에서 데이터를 완전히 처리하며 서버로 전송되지 않습니다.",
  "Features": "기능",
  "40+ essential developer tools": "40개 이상의 필수 개발자 도구",
  "100% client-side processing — your data never leaves your browser": "100% 클라이언트 측 처리 — 데이터가 브라우저를 벗어나지 않습니다",
  "No signup, no accounts, no tracking": "가입 불필요, 계정 불필요, 추적 없음",
  "Works on desktop, tablet, and mobile": "데스크톱, 태블릿, 모바일에서 작동",
  "Fast and lightweight": "빠르고 가벼움",
  "Contact": "연락처",
  "Have feedback or suggestions? Open an issue on our": "피드백이나 제안이 있으시면 당사",
  "DevToolBox - Free Online Developer Tools": "DevToolBox - 무료 온라인 개발자 도구",
  "Free online developer tools: JSON formatter, Base64 encoder, UUID generator, regex tester, hash generator, and 40+ more. No signup required. All processing in your browser.": "무료 온라인 개발자 도구: JSON 포맷터, Base64 인코더, UUID 생성기, 정규식 테스터, 해시 생성기 등 40개 이상. 가입 불필요. 모든 처리는 브라우저에서.",
  "Blog": "블로그",
  "DevToolBox Blog": "DevToolBox 블로그",
  "Developer guides, tutorials, and best practices for working with online tools": "온라인 도구 개발자 가이드, 튜토리얼 및 모범 사례",
  "Read More": "더 읽기",
  "At DevToolBox, your privacy is our top priority.": "DevToolBox에서는 귀하의 개인정보를 최우선으로 합니다.",
  "Data Processing": "데이터 처리",
  "All tools on DevToolBox process data entirely in your browser. We never send your data to any server. Your input never leaves your device.": "DevToolBox의 모든 도구는 브라우저에서 데이터를 완전히 처리합니다. 데이터를 서버로 전송하지 않습니다. 입력은 기기를 벗어나지 않습니다.",
  "Cookies": "쿠키",
  "We may use cookies for analytics purposes (e.g. Google Analytics) and advertising (e.g. Google AdSense) to understand how visitors use our site and to display relevant ads. These third-party services may collect anonymous usage data.": "분석(Google Analytics 등) 및 광고(Google AdSense 등) 목적으로 쿠키를 사용하여 방문자가 사이트를 어떻게 사용하는지 이해하고 관련 광고를 표시할 수 있습니다.",
  "Advertising": "광고",
  "We display advertisements through Google AdSense to support the free operation of this website. AdSense may use cookies and web beacons to serve ads based on your prior visits.": "이 웹사이트의 무료 운영을 지원하기 위해 Google AdSense로 광고를 표시합니다. AdSense는 쿠키와 웹 비콘을 사용하여 이전 방문에 기반한 광고를 제공할 수 있습니다.",
  "Third-Party Services": "제3자 서비스",
  "We use the following third-party services:": "다음 제3자 서비스를 사용합니다:",
  "Google Analytics — for anonymous usage statistics": "Google Analytics — 익명 사용 통계",
  "Google AdSense — for displaying advertisements": "Google AdSense — 광고 표시",
  "Changes": "변경",
  "We may update this privacy policy from time to time. Check back periodically for updates.": "이 개인정보처리방침은 수시로 업데이트될 수 있습니다. 정기적으로 확인하세요.",
  "Questions about this policy? Open an issue on our GitHub repository.": "이 정책에 대한 질문이 있으시면 GitHub 저장소에 이슈를 등록해 주세요.",
};

const toolJaMap = {
  "json-formatter": { name: "JSONフォーマッター", description: "JSONをフォーマット、検証、整形。構文ハイライト対応", pageTitle: "JSONフォーマッター＆検証", pageDescription: "JSONをオンラインでフォーマット、整形、圧縮、検証。" },
  "base64": { name: "Base64エンコーダー/デコーダー", description: "テキストをBase64にエンコード、Base64をデコード", pageTitle: "Base64エンコーダー / デコーダー", pageDescription: "テキストをBase64にエンコード、Base64をデコード。UTF-8対応。" },
  "url-encoder": { name: "URLエンコーダー/デコーダー", description: "URLコンポーネントとクエリパラメータのエンコード/デコード", pageTitle: "URLエンコーダー / デコーダー", pageDescription: "URLとURIコンポーネントのエンコード/デコード。" },
  "hash-generator": { name: "ハッシュジェネレーター", description: "テキストからMD5、SHA-1、SHA-256、SHA-512ハッシュを生成", pageTitle: "ハッシュジェネレーター", pageDescription: "任意のテキストからSHA-1、SHA-256、SHA-384、SHA-512ハッシュを生成。" },
  "uuid-generator": { name: "UUIDジェネレーター", description: "ランダムUUID (v4) を一括生成", pageTitle: "UUIDジェネレーター", pageDescription: "ランダムUUID (v4) を一括生成。大文字、ハイフンなし対応。" },
  "timestamp-converter": { name: "Unixタイムスタンプ変換", description: "Unixタイムスタンプと日付を相互変換", pageTitle: "Unixタイムスタンプ変換", pageDescription: "Unixタイムスタンプを日付に、日付をタイムスタンプに変換。" },
  "color-converter": { name: "色変換", description: "HEX、RGB、HSL形式間で色を変換、プレビュー付き", pageTitle: "色変換", pageDescription: "HEX、RGB、HSL形式間で色を変換。リアルタイムプレビュー。" },
  "regex-tester": { name: "正規表現テスター", description: "正規表現をリアルタイムでマッチ＆ハイライト", pageTitle: "正規表現テスター", pageDescription: "正規表現をリアルタイムでテスト。マッチ、ハイライト、キャプチャグループ対応。" },
  "markdown-preview": { name: "Markdownプレビュー", description: "Markdownを記述してレンダリングプレビューを表示", pageTitle: "Markdownプレビュー", pageDescription: "Markdownを記述してレンダリングされたHTMLをリアルタイムでプレビュー。" },
  "jwt-decoder": { name: "JWTデコーダー", description: "JSON Web Tokenをデコードしてヘッダー、ペイロード、署名を確認", pageTitle: "JWTデコーダー", pageDescription: "JSON Web Tokenをデコード。ヘッダー、ペイロード、署名を表示。" },
  "qrcode-generator": { name: "QRコード生成", description: "テキスト、URL、任意のデータからQRコードを生成", pageTitle: "QRコード生成", pageDescription: "テキスト、URL、任意のデータからQRコードを生成。PNGでダウンロード可能。" },
  "lorem-ipsum": { name: "Lorem Ipsum生成", description: "段落、文、単語のプレースホルダーテキストを生成", pageTitle: "Lorem Ipsum生成", pageDescription: "デザイン・開発用のプレースホルダーテキストを生成。" },
  "html-entity": { name: "HTMLエンティティエンコーダー", description: "HTMLエンティティと特殊文字のエンコード/デコード", pageTitle: "HTMLエンティティエンコーダー / デコーダー", pageDescription: "特殊文字をHTMLエンティティにエンコード、またはデコード。" },
  "css-minifier": { name: "CSS圧縮 / 整形", description: "CSSを圧縮または整形", pageTitle: "CSS圧縮器 / 整形器", pageDescription: "本番用にCSSを圧縮、または可読性のために整形。" },
  "number-base": { name: "進数変換", description: "2進、8進、10進、16進数を相互変換", pageTitle: "進数変換", pageDescription: "10進、2進、8進、16進数を即座に変換。" },
  "text-diff": { name: "テキスト差分", description: "2つのテキストを比較して差分をハイライト", pageTitle: "テキスト差分チェッカー", pageDescription: "2つのテキストを比較して差分をハイライト。" },
  "word-counter": { name: "文字カウンター", description: "単語、文字、文、段落をカウント", pageTitle: "文字カウンター", pageDescription: "単語、文字、文、段落をカウント。推定読了時間付き。" },
  "password-generator": { name: "パスワード生成", description: "カスタマイズ可能な安全なランダムパスワードを生成", pageTitle: "パスワード生成", pageDescription: "長さや文字種をカスタマイズ可能な強力なパスワードを生成。" },
  "sql-formatter": { name: "SQLフォーマッター", description: "SQLクエリをフォーマットして可読性を向上", pageTitle: "SQLフォーマッター", pageDescription: "SQLクエリをフォーマットして可読性を向上。" },
  "cron-parser": { name: "Cron式パーサー", description: "Cron式を解析し次回実行時刻を表示", pageTitle: "Cron式パーサー", pageDescription: "Cron式を人間が読める形式に解析。次回実行時刻を表示。" },
  "json-yaml": { name: "JSON ↔ YAML変換", description: "JSONとYAML形式を即座に変換", pageTitle: "JSON to YAML変換", pageDescription: "JSONをYAMLに、YAMLをJSONにオンライン変換。" },
  "string-case": { name: "命名形式変換", description: "camelCase、snake_case、kebab-case等で変換", pageTitle: "命名形式変換", pageDescription: "camelCase、PascalCase、snake_case等の命名規則間で変換。" },
  "slug-generator": { name: "URLスラッグ生成", description: "テキストをSEOフレンドリーなURLスラッグに変換", pageTitle: "URLスラッグ生成", pageDescription: "任意のテキストをクリーンなSEOフレンドリーなURLスラッグに変換。" },
  "chmod-calculator": { name: "Chmod計算", description: "チェックボックスでLinuxファイル権限を計算", pageTitle: "Linux Chmod計算", pageDescription: "chmod権限の計算。数値(755)と記号(rwxr-xr-x)を相互変換。" },
  "line-sorter": { name: "行ソート＆重複削除", description: "行をソート、重複削除、反転、シャッフル等", pageTitle: "行ソート＆重複削除", pageDescription: "行をアルファベット順、数値順でソート、重複削除等。" },
  "js-html-formatter": { name: "JS/HTMLフォーマッター", description: "JavaScriptとHTMLを圧縮または整形", pageTitle: "JavaScript & HTML圧縮器 / 整形器", pageDescription: "JavaScriptとHTMLをオンラインで圧縮または整形。" },
  "image-base64": { name: "画像Base64変換", description: "画像をBase64文字列とdata URIに変換。ドラッグ＆ドロップ対応", pageTitle: "画像Base64変換", pageDescription: "画像をBase64文字列とdata URIに変換。PNG、JPG、GIF、SVG、WebP対応。" },
  "git-command-generator": { name: "Gitコマンド生成", description: "ビジュアルGitコマンドビルダー", pageTitle: "Gitコマンド生成", pageDescription: "操作を選択し、パラメータを入力してコマンドをコピー。" },
  "xml-formatter": { name: "XMLフォーマッター", description: "XMLをフォーマット、圧縮、検証", pageTitle: "XMLフォーマッター＆検証", pageDescription: "XMLをオンラインでフォーマット、圧縮、検証。" },
  "csv-json": { name: "CSV ↔ JSON変換", description: "CSVとJSON形式を即座に変換", pageTitle: "CSV to JSON変換", pageDescription: "CSVをJSONに、JSONをCSVにオンライン変換。" },
  "http-status": { name: "HTTPステータスコード参照", description: "HTTPステータスコードの意味を検索", pageTitle: "HTTPステータスコード参照", pageDescription: "1xx、2xx、3xx、4xx、5xxのHTTPステータスコードを検索。" },
  "mime-types": { name: "MIMEタイプ検索", description: "ファイル拡張子でMIMEタイプを検索", pageTitle: "MIMEタイプ検索", pageDescription: "ファイル拡張子でMIMEタイプを検索。" },
  "escape-unescape": { name: "Escape / Unescape", description: "HTML、JavaScript、JSONのエスケープ/アンエスケープ", pageTitle: "Escape Unescapeツール", pageDescription: "HTML、JavaScript、JSON用の特殊文字をエスケープ。" },
  "ip-calculator": { name: "IPサブネット計算", description: "サブネットマスク、ネットワーク、ブロードキャストを計算", pageTitle: "IPサブネット計算", pageDescription: "サブネットマスク、ネットワークアドレス、ブロードキャストを計算。" },
  "fake-data": { name: "ダミーデータ生成", description: "テスト用のダミー名、メール、住所を生成", pageTitle: "ダミーデータ生成", pageDescription: "テスト用のダミー名、メール、電話番号、住所を生成。" },
  "hmac-generator": { name: "HMACジェネレーター", description: "メッセージとシークレットからHMAC-SHA256、HMAC-SHA1を生成", pageTitle: "HMACジェネレーター", pageDescription: "SHA-256またはSHA-1でHMAC署名を生成。" },
  "url-parser": { name: "URLパーサー", description: "URLをコンポーネントに解析", pageTitle: "URLパーサー", pageDescription: "URLをプロトコル、ホスト、パス、クエリに解析。" },
  "binary-text": { name: "テキスト ↔ バイナリ変換", description: "テキストをバイナリに、バイナリをテキストに変換", pageTitle: "テキスト to バイナリ変換", pageDescription: "テキストをバイナリ(0と1)に、バイナリをテキストに変換。UTF-8対応。" },
  "pem-decoder": { name: "PEM / 証明書デコーダー", description: "PEM証明書をデコード", pageTitle: "PEM証明書デコーダー", pageDescription: "PEM形式の証明書をデコード。" },
  "html-table": { name: "HTMLテーブル生成", description: "CSVまたはJSONをHTMLテーブルに変換", pageTitle: "HTMLテーブル生成", pageDescription: "CSVまたはJSONをHTMLテーブルマークアップに変換。" },
  "bcrypt-generator": { name: "Bcrypt Hash生成", description: "コスト可変のbcryptハッシュを生成", pageTitle: "Bcrypt Hash生成", pageDescription: "コスト係数可変のbcryptパスワードハッシュを生成。" },
};

const toolKoMap = {
  "json-formatter": { name: "JSON 포맷터", description: "JSON 포맷, 검증, 정렬. 구문 강조 지원", pageTitle: "JSON 포맷터 및 검증", pageDescription: "JSON을 온라인으로 포맷, 정렬, 압축, 검증." },
  "base64": { name: "Base64 인코더/디코더", description: "텍스트를 Base64로 인코딩, Base64 디코딩", pageTitle: "Base64 인코더 / 디코더", pageDescription: "텍스트를 Base64로 인코딩, Base64를 디코딩. UTF-8 지원." },
  "url-encoder": { name: "URL 인코더/디코더", description: "URL 구성요소와 쿼리 매개변수 인코딩/디코딩", pageTitle: "URL 인코더 / 디코더", pageDescription: "URL과 URI 구성요소 인코딩/디코딩." },
  "hash-generator": { name: "해시 생성기", description: "텍스트에서 MD5, SHA-1, SHA-256, SHA-512 해시 생성", pageTitle: "해시 생성기", pageDescription: "임의의 텍스트에서 SHA-1, SHA-256, SHA-384, SHA-512 해시 생성." },
  "uuid-generator": { name: "UUID 생성기", description: "랜덤 UUID (v4) 일괄 생성", pageTitle: "UUID 생성기", pageDescription: "랜덤 UUID (v4) 일괄 생성. 대문자, 대시 없음 지원." },
  "timestamp-converter": { name: "Unix 타임스탬프 변환", description: "Unix 타임스탬프와 날짜 상호 변환", pageTitle: "Unix 타임스탬프 변환", pageDescription: "Unix 타임스탬프를 날짜로, 날짜를 타임스탬프로 변환." },
  "color-converter": { name: "색상 변환", description: "HEX, RGB, HSL 형식 간 색상 변환 및 미리보기", pageTitle: "색상 변환", pageDescription: "HEX, RGB, HSL 형식 간 색상 변환. 실시간 미리보기." },
  "regex-tester": { name: "정규식 테스터", description: "정규식을 실시간으로 매치 및 강조", pageTitle: "정규식 테스터", pageDescription: "정규식을 실시간으로 테스트. 매치, 강조, 캡처 그룹 지원." },
  "markdown-preview": { name: "Markdown 미리보기", description: "Markdown 작성 및 렌더링 미리보기", pageTitle: "Markdown 미리보기", pageDescription: "Markdown 작성 및 렌더링된 HTML 실시간 미리보기." },
  "jwt-decoder": { name: "JWT 디코더", description: "JSON Web Token 디코딩 및 헤더, 페이로드, 서명 확인", pageTitle: "JWT 디코더", pageDescription: "JSON Web Token 디코딩. 헤더, 페이로드, 서명 표시." },
  "qrcode-generator": { name: "QR 코드 생성", description: "텍스트, URL, 데이터에서 QR 코드 생성", pageTitle: "QR 코드 생성", pageDescription: "텍스트, URL, 데이터에서 QR 코드 생성. PNG 다운로드." },
  "lorem-ipsum": { name: "Lorem Ipsum 생성", description: "段落, 문장, 단어 플레이스홀더 텍스트 생성", pageTitle: "Lorem Ipsum 생성", pageDescription: "디자인·개발용 플레이스홀더 텍스트 생성." },
  "html-entity": { name: "HTML 엔티티 인코더", description: "HTML 엔티티 및 특수 문자 인코딩/디코딩", pageTitle: "HTML 엔티티 인코더 / 디코더", pageDescription: "특수 문자를 HTML 엔티티로 인코딩 또는 디코딩." },
  "css-minifier": { name: "CSS 압축 / 정렬", description: "CSS 압축 또는 정렬", pageTitle: "CSS 압축기 / 정렬기", pageDescription: "프로덕션용 CSS 압축 또는 가독성용 정렬." },
  "number-base": { name: "진수 변환", description: "2진, 8진, 10진, 16진 상호 변환", pageTitle: "진수 변환", pageDescription: "10진, 2진, 8진, 16진 즉시 변환." },
  "text-diff": { name: "텍스트 차이", description: "두 텍스트 비교 및 차이 강조", pageTitle: "텍스트 차이 검사", pageDescription: "두 텍스트 비교 및 차이 강조." },
  "word-counter": { name: "글자 수 세기", description: "단어, 문자, 문장, 단락 카운트", pageTitle: "글자 수 세기", pageDescription: "단어, 문자, 문장, 단락 카운트. 예상 읽기 시간." },
  "password-generator": { name: "비밀번호 생성", description: "커스터마이즈 가능한 안전한 랜덤 비밀번호 생성", pageTitle: "비밀번호 생성", pageDescription: "길이와 문자 유형 커스터마이즈 가능한 강력한 비밀번호 생성." },
  "sql-formatter": { name: "SQL 포맷터", description: "SQL 쿼리 포맷 및 가독성 향상", pageTitle: "SQL 포맷터", pageDescription: "SQL 쿼리 포맷 및 가독성 향상." },
  "cron-parser": { name: "Cron 식 파서", description: "Cron 식 파싱 및 다음 실행 시각 표시", pageTitle: "Cron 식 파서", pageDescription: "Cron 식을 사람이 읽을 수 있는 형식으로 파싱. 다음 실행 시각 표시." },
  "json-yaml": { name: "JSON ↔ YAML 변환", description: "JSON과 YAML 형식 즉시 변환", pageTitle: "JSON to YAML 변환", pageDescription: "JSON을 YAML로, YAML을 JSON으로 온라인 변환." },
  "string-case": { name: "네이밍 형식 변환", description: "camelCase, snake_case, kebab-case 등 변환", pageTitle: "네이밍 형식 변환", pageDescription: "camelCase, PascalCase, snake_case 등 네이밍 규칙 간 변환." },
  "slug-generator": { name: "URL 슬러그 생성", description: "텍스트를 SEO 친화적 URL 슬러그로 변환", pageTitle: "URL 슬러그 생성", pageDescription: "임의의 텍스트를 깔끔한 SEO 친화적 URL 슬러그로 변환." },
  "chmod-calculator": { name: "Chmod 계산", description: "체크박스로 Linux 파일 권한 계산", pageTitle: "Linux Chmod 계산", pageDescription: "chmod 권한 계산. 숫자(755)와 기호(rwxr-xr-x) 상호 변환." },
  "line-sorter": { name: "행 정렬 및 중복 제거", description: "행 정렬, 중복 제거, 역순, 셔플 등", pageTitle: "행 정렬 및 중복 제거", pageDescription: "행을 알파벳순, 숫자순 정렬, 중복 제거 등." },
  "js-html-formatter": { name: "JS/HTML 포맷터", description: "JavaScript와 HTML 압축 또는 정렬", pageTitle: "JavaScript & HTML 압축기 / 정렬기", pageDescription: "JavaScript와 HTML 온라인 압축 또는 정렬." },
  "image-base64": { name: "이미지 Base64 변환", description: "이미지를 Base64 문자열과 data URI로 변환. 드래그 앤 드롭", pageTitle: "이미지 Base64 변환", pageDescription: "이미지를 Base64 문자열과 data URI로 변환. PNG, JPG, GIF, SVG, WebP 지원." },
  "git-command-generator": { name: "Git 명령어 생성", description: "비주얼 Git 명령어 빌더", pageTitle: "Git 명령어 생성", pageDescription: "작업 선택, 매개변수 입력, 명령어 복사." },
  "xml-formatter": { name: "XML 포맷터", description: "XML 포맷, 압축, 검증", pageTitle: "XML 포맷터 및 검증", pageDescription: "XML 온라인 포맷, 압축, 검증." },
  "csv-json": { name: "CSV ↔ JSON 변환", description: "CSV와 JSON 형식 즉시 변환", pageTitle: "CSV to JSON 변환", pageDescription: "CSV를 JSON으로, JSON을 CSV로 온라인 변환." },
  "http-status": { name: "HTTP 상태 코드 참조", description: "HTTP 상태 코드 의미 검색", pageTitle: "HTTP 상태 코드 참조", pageDescription: "1xx, 2xx, 3xx, 4xx, 5xx HTTP 상태 코드 검색." },
  "mime-types": { name: "MIME 타입 검색", description: "파일 확장자로 MIME 타입 검색", pageTitle: "MIME 타입 검색", pageDescription: "파일 확장자로 MIME 타입 검색." },
  "escape-unescape": { name: "Escape / Unescape", description: "HTML, JavaScript, JSON 이스케이프/언이스케이프", pageTitle: "Escape Unescape 도구", pageDescription: "HTML, JavaScript, JSON용 특수 문자 이스케이프." },
  "ip-calculator": { name: "IP 서브넷 계산", description: "서브넷 마스크, 네트워크, 브로드캐스트 계산", pageTitle: "IP 서브넷 계산", pageDescription: "서브넷 마스크, 네트워크 주소, 브로드캐스트 계산." },
  "fake-data": { name: "가짜 데이터 생성", description: "테스트용 가짜 이름, 이메일, 주소 생성", pageTitle: "가짜 데이터 생성", pageDescription: "테스트용 가짜 이름, 이메일, 전화번호, 주소 생성." },
  "hmac-generator": { name: "HMAC 생성기", description: "메시지와 시크릿으로 HMAC-SHA256, HMAC-SHA1 생성", pageTitle: "HMAC 생성기", pageDescription: "SHA-256 또는 SHA-1로 HMAC 서명 생성." },
  "url-parser": { name: "URL 파서", description: "URL을 구성요소로 파싱", pageTitle: "URL 파서", pageDescription: "URL을 프로토콜, 호스트, 경로, 쿼리로 파싱." },
  "binary-text": { name: "텍스트 ↔ 이진 변환", description: "텍스트를 이진으로, 이진을 텍스트로 변환", pageTitle: "텍스트 to 이진 변환", pageDescription: "텍스트를 이진(0과 1)으로, 이진을 텍스트로 변환. UTF-8 지원." },
  "pem-decoder": { name: "PEM / 인증서 디코더", description: "PEM 인증서 디코딩", pageTitle: "PEM 인증서 디코더", pageDescription: "PEM 형식 인증서 디코딩." },
  "html-table": { name: "HTML 테이블 생성", description: "CSV 또는 JSON을 HTML 테이블로 변환", pageTitle: "HTML 테이블 생성", pageDescription: "CSV 또는 JSON을 HTML 테이블 마크업으로 변환." },
  "bcrypt-generator": { name: "Bcrypt Hash 생성", description: "비용 조절 가능한 bcrypt 해시 생성", pageTitle: "Bcrypt Hash 생성", pageDescription: "비용 계수 조절 가능한 bcrypt 비밀번호 해시 생성." },
};

function translateObj(obj, path, map, toolMap) {
  if (typeof obj === 'string') {
    const toolId = path.match(/tools\.([^.]+)/)?.[1];
    if (toolId && toolMap[toolId]) {
      const key = path.split('.').pop();
      if (toolMap[toolId][key]) return toolMap[toolId][key];
    }
    return map[obj] ?? obj;
  }
  if (Array.isArray(obj)) {
    return obj.map((item, i) => translateObj(item, `${path}[${i}]`, map, toolMap));
  }
  if (obj && typeof obj === 'object') {
    const out = {};
    for (const k of Object.keys(obj)) {
      out[k] = translateObj(obj[k], path ? `${path}.${k}` : k, map, toolMap);
    }
    return out;
  }
  return obj;
}

const ja = translateObj(en, '', jaMap, toolJaMap);
const ko = translateObj(en, '', koMap, toolKoMap);

fs.writeFileSync(jaPath, JSON.stringify(ja, null, 2), { encoding: 'utf8' });
fs.writeFileSync(koPath, JSON.stringify(ko, null, 2), { encoding: 'utf8' });

console.log('ja.json and ko.json generated successfully with UTF-8 encoding.');
