'use client';

import { useState } from 'react';
import ToolLayout from '@/components/ToolLayout';
import CopyButton from '@/components/CopyButton';
import { useLang } from '@/i18n/LangContext';
import styles from './page.module.css';

interface ConversionOptions {
  structName: string;
  useOmitempty: boolean;
  addJsonTags: boolean;
  inlineStructs: boolean;
}

function jsonToGoStruct(json: string, options: ConversionOptions): string {
  try {
    const parsed = JSON.parse(json);
    const structs: Map<string, string> = new Map();
    const processedTypes = new Set<string>();

    function toPascalCase(str: string): string {
      return str
        .replace(/([_-])([a-z])/g, (_, __, c) => c.toUpperCase())
        .replace(/^([a-z])/, (c) => c.toUpperCase())
        .split(/[_-]/)
        .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
        .join('');
    }

    function normalizeFieldName(key: string): string {
      const pascalCase = toPascalCase(key);
      // Handle common Go naming conventions
      return pascalCase
        .replace(/^Url(?=[A-Z]|$)/g, 'URL')
        .replace(/^Id(?=[A-Z]|$)/g, 'ID')
        .replace(/^Http(?=[A-Z]|$)/g, 'HTTP')
        .replace(/^Json(?=[A-Z]|$)/g, 'JSON')
        .replace(/^Xml(?=[A-Z]|$)/g, 'XML')
        .replace(/^Api(?=[A-Z]|$)/g, 'API')
        .replace(/^Sql(?=[A-Z]|$)/g, 'SQL')
        .replace(/^Uuid(?=[A-Z]|$)/g, 'UUID');
    }

    function detectType(value: unknown, fieldName: string): string {
      if (value === null || value === undefined) {
        return 'interface{}';
      }

      if (Array.isArray(value)) {
        if (value.length === 0) {
          return '[]interface{}';
        }

        const elementType = detectType(value[0], fieldName);
        return `[]${elementType}`;
      }

      if (typeof value === 'object') {
        const structName = toPascalCase(fieldName);
        if (!processedTypes.has(structName)) {
          generateStruct(value as Record<string, unknown>, structName);
        }
        return structName;
      }

      switch (typeof value) {
        case 'string':
          return 'string';
        case 'number': {
          const num = value as number;
          if (Number.isInteger(num)) {
            return num >= -2147483648 && num <= 2147483647 ? 'int32' : 'int64';
          }
          return 'float64';
        }
        case 'boolean':
          return 'bool';
        default:
          return 'interface{}';
      }
    }

    function generateStruct(obj: Record<string, unknown>, structName: string): void {
      if (processedTypes.has(structName)) return;
      processedTypes.add(structName);

      const fields = Object.entries(obj)
        .filter(([, value]) => value !== undefined)
        .map(([key, value]) => {
          const fieldName = normalizeFieldName(key);
          const fieldType = detectType(value, key);
          let line = `\t${fieldName} ${fieldType}`;

          if (options.addJsonTags) {
            const tag = options.useOmitempty
              ? ` \`json:"${key},omitempty"\``
              : ` \`json:"${key}"\``;
            line += tag;
          }

          return line;
        });

      const structDef =
        fields.length > 0
          ? `type ${structName} struct {\n${fields.join('\n')}\n}`
          : `type ${structName} struct {}`;

      structs.set(structName, structDef);
    }

    // Generate root struct
    if (Array.isArray(parsed)) {
      if (parsed.length > 0 && typeof parsed[0] === 'object' && parsed[0] !== null) {
        generateStruct(parsed[0] as Record<string, unknown>, options.structName);
      }
    } else if (typeof parsed === 'object' && parsed !== null) {
      generateStruct(parsed as Record<string, unknown>, options.structName);
    }

    // Build output
    if (options.inlineStructs) {
      return Array.from(structs.values()).reverse().join('\n\n');
    } else {
      // Return all structs separated by newlines
      return Array.from(structs.entries())
        .reverse()
        .map(([, def]) => def)
        .join('\n\n');
    }
  } catch (error) {
    throw new Error(`Invalid JSON: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
}

export default function JsonToGoStruct() {
  const { dict } = useLang();
  const t = dict.tools['json-to-go-struct'];
  const [jsonInput, setJsonInput] = useState(
    `{
  "id": 123,
  "name": "John Doe",
  "email": "john@example.com",
  "active": true,
  "balance": 45.67,
  "tags": ["developer", "golang"],
  "profile": {
    "age": 30,
    "country": "USA"
  }
}`
  );
  const [goOutput, setGoOutput] = useState('');
  const [error, setError] = useState('');
  const [options, setOptions] = useState<ConversionOptions>({
    structName: 'AutoGenerated',
    useOmitempty: true,
    addJsonTags: true,
    inlineStructs: true,
  });

  const handleConvert = () => {
    try {
      setError('');
      const result = jsonToGoStruct(jsonInput, options);
      setGoOutput(result);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'An error occurred');
      setGoOutput('');
    }
  };

  const handleLoadSample = () => {
    const sample = `{
  "user_id": 42,
  "user_name": "Alice Johnson",
  "email_address": "alice@example.com",
  "is_verified": true,
  "account_balance": 1234.56,
  "created_at": "2024-01-15T10:30:00Z",
  "preferences": {
    "theme": "dark",
    "notifications_enabled": true,
    "language": "en"
  },
  "roles": ["admin", "editor"],
  "metadata": {
    "last_login": "2024-03-14",
    "login_count": 42
  }
}`;
    setJsonInput(sample);
    setGoOutput('');
    setError('');
  };

  const handleClearAll = () => {
    setJsonInput('');
    setGoOutput('');
    setError('');
  };

  return (
    <ToolLayout
      toolId="json-to-go-struct"
      pageTitle={t.pageTitle}
      pageDescription={t.pageDescription}
    >
      <div className={styles.container}>
        <div className={styles.controls}>
          <div className={styles.controlGroup}>
            <label htmlFor="structName">{t.structNameLabel}</label>
            <input
              id="structName"
              type="text"
              value={options.structName}
              onChange={(e) =>
                setOptions({ ...options, structName: e.target.value || 'AutoGenerated' })
              }
              placeholder="AutoGenerated"
              className={styles.input}
            />
          </div>

          <div className={styles.checkboxGroup}>
            <label>
              <input
                type="checkbox"
                checked={options.addJsonTags}
                onChange={(e) =>
                  setOptions({ ...options, addJsonTags: e.target.checked })
                }
              />
              {t.addJsonTagsLabel}
            </label>
            <label>
              <input
                type="checkbox"
                checked={options.useOmitempty}
                onChange={(e) =>
                  setOptions({ ...options, useOmitempty: e.target.checked })
                }
                disabled={!options.addJsonTags}
              />
              {t.addOmitemptyLabel}
            </label>
            <label>
              <input
                type="checkbox"
                checked={options.inlineStructs}
                onChange={(e) =>
                  setOptions({ ...options, inlineStructs: e.target.checked })
                }
              />
              {t.inlineStructsLabel}
            </label>
          </div>

          <div className={styles.buttonGroup}>
            <button onClick={handleConvert} className="btn btn-primary">
              {t.convertBtn}
            </button>
            <button onClick={handleLoadSample} className="btn btn-secondary">
              {t.loadSampleBtn}
            </button>
            <button onClick={handleClearAll} className="btn btn-secondary">
              {t.clearAllBtn}
            </button>
          </div>
        </div>

        <div className={styles.editorArea}>
          <div className={styles.column}>
            <div className={styles.header}>
              <h3>{t.jsonInputLabel}</h3>
            </div>
            <textarea
              value={jsonInput}
              onChange={(e) => setJsonInput(e.target.value)}
              placeholder={t.jsonInputPlaceholder}
              className={styles.textarea}
            />
          </div>

          <div className={styles.column}>
            <div className={styles.header}>
              <h3>{t.goStructOutputLabel}</h3>
              {goOutput && <CopyButton text={goOutput} />}
            </div>
            {error ? (
              <div className={styles.error}>{error}</div>
            ) : (
              <pre className={styles.output}>{goOutput || t.outputPlaceholder}</pre>
            )}
          </div>
        </div>

        {/* SEO Content Section */}
        <div className={styles.seoContent}>
          <h2>{t.seoTitle}</h2>
          <p>{t.seoContent}</p>

          <h3>{t.seoFeaturesTitle}</h3>
          <ul>
            <li>{t.seoFeature1}</li>
            <li>{t.seoFeature2}</li>
            <li>{t.seoFeature3}</li>
            <li>{t.seoFeature4}</li>
          </ul>

          <h3>{t.howToUseTitle}</h3>
          <ol>
            {t.howToUseSteps.map((step: string, idx: number) => (
              <li key={idx}>{step}</li>
            ))}
          </ol>

          <h3>{t.useCasesTitle}</h3>
          <ul>
            {t.useCases.map((useCase: string, idx: number) => (
              <li key={idx}>{useCase}</li>
            ))}
          </ul>

          <h3>{t.faqTitle}</h3>
          <div className={styles.faqSection}>
            {t.faqs.map((faq: { q: string; a: string }, idx: number) => (
              <details key={idx} className={styles.faqItem}>
                <summary>{faq.q}</summary>
                <p>{faq.a}</p>
              </details>
            ))}
          </div>
        </div>
      </div>
    </ToolLayout>
  );
}
