'use client';

import Link from 'next/link';
import { useLang } from '@/i18n/LangContext';
import ToolLayout from '@/components/ToolLayout';

const t: Record<string, Record<string, string>> = {
  en: {
    title: 'Docker vs Kubernetes', description: 'A detailed comparison of Docker and Kubernetes.',
    intro: 'Docker and Kubernetes are often mentioned together but serve different purposes. Docker is a containerization platform for building and running containers, while Kubernetes is an orchestration system for managing containers at scale. Understanding their relationship is key to modern DevOps.',
    tableFeature: 'Feature', tableA: 'Docker', tableB: 'Kubernetes',
    purpose: 'Purpose', purA: 'Build and run containers', purB: 'Orchestrate containers at scale',
    scope: 'Scope', scpA: 'Single host', scpB: 'Multi-host cluster',
    complexity: 'Complexity', cmpA: 'Low (simple CLI)', cmpB: 'High (steep learning curve)',
    scaling: 'Scaling', sclA: 'Manual (docker-compose scale)', sclB: 'Automatic (HPA, VPA)',
    networking: 'Networking', netA: 'Bridge, host, overlay', netB: 'Service mesh, Ingress, CNI plugins',
    selfHealing: 'Self-Healing', shA: 'Restart policies only', shB: 'Full (restarts, reschedules, replaces)',
    storage: 'Storage', stoA: 'Volumes, bind mounts', stoB: 'PersistentVolumes, StorageClasses',
    whatIsA: 'What is Docker?', aText: 'Docker is a platform for building, sharing, and running containerized applications. It packages an application and its dependencies into a container image that runs consistently across environments. Docker uses a Dockerfile to define images and docker-compose.yml for multi-container applications. It is the most popular containerization tool.',
    whatIsB: 'What is Kubernetes?', bText: 'Kubernetes (K8s) is an open-source container orchestration platform originally developed by Google. It automates deployment, scaling, and management of containerized applications across clusters of machines. Kubernetes provides service discovery, load balancing, storage orchestration, automated rollouts/rollbacks, and self-healing capabilities.',
    whenA: 'When to Use Docker (without K8s)', aUse1: 'Local development environments', aUse2: 'Small applications (1-5 containers)', aUse3: 'CI/CD build pipelines', aUse4: 'Single-server deployments', aUse5: 'Learning containerization basics',
    whenB: 'When to Use Kubernetes', bUse1: 'Production microservices at scale', bUse2: 'Multi-node cluster deployments', bUse3: 'Applications needing auto-scaling', bUse4: 'Zero-downtime rolling updates', bUse5: 'Multi-cloud or hybrid deployments',
    verdict: 'TL;DR / Verdict', verdictText: 'Docker and Kubernetes are complementary, not competing. Use Docker to containerize your applications. Use Kubernetes when you need to orchestrate many containers across multiple machines. For small projects, Docker Compose is sufficient. For production microservices at scale, Kubernetes is the industry standard.',
    tryTools: 'Try Our DevOps Tools', faqTitle: 'Frequently Asked Questions',
    faq1q: 'Do I need Kubernetes to use Docker?', faq1a: 'No. Docker works perfectly on its own for building and running containers. Docker Compose handles multi-container applications on a single host. Kubernetes is only needed when you need orchestration across multiple machines with features like auto-scaling, self-healing, and rolling updates.',
    faq2q: 'Can Kubernetes run without Docker?', faq2a: 'Yes. Kubernetes deprecated Docker as a runtime in v1.24 in favor of containerd and CRI-O, which implement the Container Runtime Interface (CRI) directly. You still build images with Docker, but Kubernetes can run them with any CRI-compatible runtime.',
    faq3q: 'What about Docker Swarm?', faq3a: 'Docker Swarm is Docker\'s built-in orchestration tool, simpler than Kubernetes but with fewer features. While Swarm is easier to set up, Kubernetes has become the industry standard for container orchestration. Most cloud providers offer managed Kubernetes (EKS, GKE, AKS) but not managed Swarm.',
  },
  zh: { title: 'Docker vs Kubernetes', description: 'Docker 与 Kubernetes 的详细对比。', intro: 'Docker 和 Kubernetes 常被一起提及但用途不同。Docker 是容器化平台，Kubernetes 是容器编排系统。', tableFeature: '特性', tableA: 'Docker', tableB: 'Kubernetes', purpose: '用途', purA: '构建和运行容器', purB: '大规模编排容器', scope: '范围', scpA: '单主机', scpB: '多主机集群', complexity: '复杂度', cmpA: '低', cmpB: '高', scaling: '扩展', sclA: '手动', sclB: '自动（HPA、VPA）', networking: '网络', netA: 'Bridge、Host、Overlay', netB: 'Service Mesh、Ingress', selfHealing: '自愈', shA: '仅重启策略', shB: '完整自愈', storage: '存储', stoA: 'Volumes', stoB: 'PV、StorageClass', whatIsA: '什么是 Docker？', aText: 'Docker 将应用及其依赖打包为容器镜像，在不同环境中一致运行。', whatIsB: '什么是 Kubernetes？', bText: 'Kubernetes 自动化跨集群的容器应用部署、扩展和管理。', whenA: '何时只用 Docker', aUse1: '本地开发', aUse2: '小型应用', aUse3: 'CI/CD 构建', aUse4: '单服务器部署', aUse5: '学习容器化', whenB: '何时使用 Kubernetes', bUse1: '生产环境微服务', bUse2: '多节点集群', bUse3: '需要自动扩展', bUse4: '零停机更新', bUse5: '多云/混合部署', verdict: '总结', verdictText: 'Docker 和 Kubernetes 互补而非竞争。用 Docker 容器化应用，用 Kubernetes 大规模编排。小项目 Docker Compose 足够。', tryTools: '试试我们的 DevOps 工具', faqTitle: '常见问题', faq1q: '使用 Docker 需要 Kubernetes 吗？', faq1a: '不需要。Docker 单独使用就很好。只在需要多机编排时才需要 Kubernetes。', faq2q: 'Kubernetes 可以不用 Docker 吗？', faq2a: '可以。K8s v1.24 起弃用 Docker 运行时，改用 containerd 和 CRI-O。', faq3q: 'Docker Swarm 呢？', faq3a: 'Docker Swarm 比 Kubernetes 简单但功能少。Kubernetes 已成为行业标准。' },
  fr: { title: 'Docker vs Kubernetes', description: 'Comparaison de Docker et Kubernetes.', intro: 'Docker et Kubernetes servent des objectifs differents mais complementaires.', tableFeature: 'Caracteristique', tableA: 'Docker', tableB: 'Kubernetes', purpose: 'Objectif', purA: 'Construire et executer des conteneurs', purB: 'Orchestrer des conteneurs a grande echelle', scope: 'Portee', scpA: 'Un seul hote', scpB: 'Cluster multi-hotes', complexity: 'Complexite', cmpA: 'Faible', cmpB: 'Elevee', scaling: 'Mise a l\'echelle', sclA: 'Manuelle', sclB: 'Automatique', networking: 'Reseau', netA: 'Bridge, Host, Overlay', netB: 'Service Mesh, Ingress', selfHealing: 'Auto-reparation', shA: 'Politiques de redemarrage', shB: 'Complete', storage: 'Stockage', stoA: 'Volumes', stoB: 'PV, StorageClasses', whatIsA: 'Qu\'est-ce que Docker ?', aText: 'Plateforme de conteneurisation pour construire et executer des applications.', whatIsB: 'Qu\'est-ce que Kubernetes ?', bText: 'Plateforme d\'orchestration pour gerer des conteneurs a grande echelle.', whenA: 'Quand Docker seul', aUse1: 'Developpement local', aUse2: 'Petites apps', aUse3: 'CI/CD', aUse4: 'Deploiement serveur unique', aUse5: 'Apprentissage', whenB: 'Quand Kubernetes', bUse1: 'Microservices en production', bUse2: 'Clusters multi-noeuds', bUse3: 'Auto-scaling', bUse4: 'Mises a jour sans interruption', bUse5: 'Multi-cloud', verdict: 'Resume', verdictText: 'Docker pour conteneuriser. Kubernetes pour orchestrer a grande echelle.', tryTools: 'Essayez nos outils DevOps', faqTitle: 'FAQ', faq1q: 'Kubernetes est-il necessaire pour Docker ?', faq1a: 'Non, Docker fonctionne parfaitement seul.', faq2q: 'Kubernetes fonctionne-t-il sans Docker ?', faq2a: 'Oui, avec containerd ou CRI-O.', faq3q: 'Et Docker Swarm ?', faq3a: 'Plus simple mais moins de fonctionnalites que Kubernetes.' },
  de: { title: 'Docker vs Kubernetes', description: 'Vergleich von Docker und Kubernetes.', intro: 'Docker und Kubernetes dienen unterschiedlichen aber komplementaeren Zwecken.', tableFeature: 'Eigenschaft', tableA: 'Docker', tableB: 'Kubernetes', purpose: 'Zweck', purA: 'Container erstellen und ausfuehren', purB: 'Container orchestrieren', scope: 'Umfang', scpA: 'Einzelner Host', scpB: 'Multi-Host-Cluster', complexity: 'Komplexitaet', cmpA: 'Niedrig', cmpB: 'Hoch', scaling: 'Skalierung', sclA: 'Manuell', sclB: 'Automatisch', networking: 'Netzwerk', netA: 'Bridge, Host, Overlay', netB: 'Service Mesh, Ingress', selfHealing: 'Selbstheilung', shA: 'Neustart-Policies', shB: 'Vollstaendig', storage: 'Speicher', stoA: 'Volumes', stoB: 'PV, StorageClasses', whatIsA: 'Was ist Docker?', aText: 'Containerisierungsplattform zum Erstellen und Ausfuehren von Anwendungen.', whatIsB: 'Was ist Kubernetes?', bText: 'Orchestrierungsplattform zur Verwaltung von Containern im grossen Massstab.', whenA: 'Wann nur Docker', aUse1: 'Lokale Entwicklung', aUse2: 'Kleine Apps', aUse3: 'CI/CD', aUse4: 'Einzelserver', aUse5: 'Lernen', whenB: 'Wann Kubernetes', bUse1: 'Produktions-Microservices', bUse2: 'Multi-Node-Cluster', bUse3: 'Auto-Scaling', bUse4: 'Zero-Downtime-Updates', bUse5: 'Multi-Cloud', verdict: 'Fazit', verdictText: 'Docker zum Containerisieren. Kubernetes zum Orchestrieren.', tryTools: 'Probieren Sie unsere DevOps-Tools', faqTitle: 'FAQ', faq1q: 'Braucht man Kubernetes fuer Docker?', faq1a: 'Nein, Docker funktioniert allein.', faq2q: 'Kubernetes ohne Docker?', faq2a: 'Ja, mit containerd oder CRI-O.', faq3q: 'Docker Swarm?', faq3a: 'Einfacher aber weniger Features als Kubernetes.' },
  es: { title: 'Docker vs Kubernetes', description: 'Comparacion de Docker y Kubernetes.', intro: 'Docker y Kubernetes sirven propositos diferentes pero complementarios.', tableFeature: 'Caracteristica', tableA: 'Docker', tableB: 'Kubernetes', purpose: 'Proposito', purA: 'Construir y ejecutar contenedores', purB: 'Orquestar contenedores a escala', scope: 'Alcance', scpA: 'Un solo host', scpB: 'Cluster multi-host', complexity: 'Complejidad', cmpA: 'Baja', cmpB: 'Alta', scaling: 'Escalado', sclA: 'Manual', sclB: 'Automatico', networking: 'Red', netA: 'Bridge, Host, Overlay', netB: 'Service Mesh, Ingress', selfHealing: 'Auto-reparacion', shA: 'Politicas de reinicio', shB: 'Completa', storage: 'Almacenamiento', stoA: 'Volumes', stoB: 'PV, StorageClasses', whatIsA: 'Que es Docker?', aText: 'Plataforma de contenedorizacion para construir y ejecutar aplicaciones.', whatIsB: 'Que es Kubernetes?', bText: 'Plataforma de orquestacion para gestionar contenedores a escala.', whenA: 'Cuando solo Docker', aUse1: 'Desarrollo local', aUse2: 'Apps pequenas', aUse3: 'CI/CD', aUse4: 'Servidor unico', aUse5: 'Aprendizaje', whenB: 'Cuando Kubernetes', bUse1: 'Microservicios en produccion', bUse2: 'Clusters multi-nodo', bUse3: 'Auto-escalado', bUse4: 'Actualizaciones sin downtime', bUse5: 'Multi-cloud', verdict: 'Resumen', verdictText: 'Docker para contenedorizar. Kubernetes para orquestar a escala.', tryTools: 'Prueba nuestras herramientas DevOps', faqTitle: 'FAQ', faq1q: 'Se necesita Kubernetes para Docker?', faq1a: 'No, Docker funciona solo.', faq2q: 'Kubernetes sin Docker?', faq2a: 'Si, con containerd o CRI-O.', faq3q: 'Docker Swarm?', faq3a: 'Mas simple pero menos funciones que Kubernetes.' },
  ja: { title: 'Docker vs Kubernetes', description: 'DockerとKubernetesの詳細な比較。', intro: 'DockerとKubernetesは異なるが補完的な目的を持ちます。', tableFeature: '特性', tableA: 'Docker', tableB: 'Kubernetes', purpose: '目的', purA: 'コンテナの構築と実行', purB: 'コンテナの大規模オーケストレーション', scope: '範囲', scpA: '単一ホスト', scpB: 'マルチホストクラスタ', complexity: '複雑さ', cmpA: '低い', cmpB: '高い', scaling: 'スケーリング', sclA: '手動', sclB: '自動', networking: 'ネットワーク', netA: 'Bridge, Host, Overlay', netB: 'Service Mesh, Ingress', selfHealing: '自己修復', shA: '再起動ポリシーのみ', shB: '完全', storage: 'ストレージ', stoA: 'Volumes', stoB: 'PV, StorageClasses', whatIsA: 'Dockerとは？', aText: 'アプリケーションをコンテナイメージにパッケージ化するプラットフォーム。', whatIsB: 'Kubernetesとは？', bText: 'コンテナの大規模なデプロイ、スケーリング、管理を自動化するプラットフォーム。', whenA: 'Dockerのみ使用時', aUse1: 'ローカル開発', aUse2: '小規模アプリ', aUse3: 'CI/CD', aUse4: '単一サーバー', aUse5: '学習', whenB: 'Kubernetes使用時', bUse1: '本番マイクロサービス', bUse2: 'マルチノードクラスタ', bUse3: 'オートスケーリング', bUse4: 'ゼロダウンタイム更新', bUse5: 'マルチクラウド', verdict: 'まとめ', verdictText: 'Dockerでコンテナ化。Kubernetesで大規模オーケストレーション。', tryTools: 'DevOpsツールを試す', faqTitle: 'FAQ', faq1q: 'DockerにKubernetesは必要？', faq1a: 'いいえ、Dockerは単独で動作します。', faq2q: 'KubernetesはDocker無しで？', faq2a: 'はい、containerdやCRI-Oで動作します。', faq3q: 'Docker Swarmは？', faq3a: 'よりシンプルですがKubernetesより機能が少ないです。' },
  ko: { title: 'Docker vs Kubernetes', description: 'Docker와 Kubernetes의 상세 비교.', intro: 'Docker와 Kubernetes는 서로 다르지만 보완적인 목적을 가집니다.', tableFeature: '특성', tableA: 'Docker', tableB: 'Kubernetes', purpose: '목적', purA: '컨테이너 빌드 및 실행', purB: '대규모 컨테이너 오케스트레이션', scope: '범위', scpA: '단일 호스트', scpB: '멀티 호스트 클러스터', complexity: '복잡성', cmpA: '낮음', cmpB: '높음', scaling: '스케일링', sclA: '수동', sclB: '자동', networking: '네트워킹', netA: 'Bridge, Host, Overlay', netB: 'Service Mesh, Ingress', selfHealing: '자가 치유', shA: '재시작 정책만', shB: '완전', storage: '스토리지', stoA: 'Volumes', stoB: 'PV, StorageClasses', whatIsA: 'Docker란?', aText: '애플리케이션을 컨테이너 이미지로 패키징하는 플랫폼.', whatIsB: 'Kubernetes란?', bText: '대규모 컨테이너 배포, 스케일링, 관리를 자동화하는 플랫폼.', whenA: 'Docker만 사용 시', aUse1: '로컬 개발', aUse2: '소규모 앱', aUse3: 'CI/CD', aUse4: '단일 서버', aUse5: '학습', whenB: 'Kubernetes 사용 시', bUse1: '프로덕션 마이크로서비스', bUse2: '멀티 노드 클러스터', bUse3: '오토 스케일링', bUse4: '무중단 업데이트', bUse5: '멀티 클라우드', verdict: '요약', verdictText: 'Docker로 컨테이너화. Kubernetes로 대규모 오케스트레이션.', tryTools: 'DevOps 도구 사용해보기', faqTitle: 'FAQ', faq1q: 'Docker에 Kubernetes가 필요한가요?', faq1a: '아닙니다, Docker는 단독으로 작동합니다.', faq2q: 'Kubernetes는 Docker 없이 가능한가요?', faq2a: '네, containerd나 CRI-O로 가능합니다.', faq3q: 'Docker Swarm은?', faq3a: '더 간단하지만 Kubernetes보다 기능이 적습니다.' },
};

const tableStyle={width:'100%',borderCollapse:'collapse' as const,fontSize:14};const thStyle={padding:'10px 14px',textAlign:'left' as const,borderBottom:'2px solid var(--border-color)',fontWeight:700};const tdStyle={padding:'10px 14px',borderBottom:'1px solid var(--border-color)'};const sectionStyle={marginTop:32};const h2Style={fontSize:22,fontWeight:700,marginBottom:12};const h3Style={fontSize:17,fontWeight:600,marginBottom:8};const pStyle={fontSize:14,lineHeight:1.8,color:'var(--text-secondary)',marginBottom:16};const ulStyle={fontSize:14,lineHeight:1.8,color:'var(--text-secondary)',paddingLeft:20,marginBottom:16};const cardStyle={background:'var(--bg-card)',borderRadius:12,padding:20,border:'1px solid var(--border-color)',marginBottom:16};

export default function DockerVsKubernetes() {
  const { lang } = useLang(); const ui = t[lang] || t.en;
  const faqSchema = {'@context':'https://schema.org','@type':'FAQPage',mainEntity:[{'@type':'Question',name:ui.faq1q,acceptedAnswer:{'@type':'Answer',text:ui.faq1a}},{'@type':'Question',name:ui.faq2q,acceptedAnswer:{'@type':'Answer',text:ui.faq2a}},{'@type':'Question',name:ui.faq3q,acceptedAnswer:{'@type':'Answer',text:ui.faq3a}}]};
  return (
    <ToolLayout title={ui.title} description={ui.description} toolId="docker-vs-kubernetes">
      <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(faqSchema)}} />
      <p style={pStyle}>{ui.intro}</p>
      <div style={{overflowX:'auto',marginBottom:24}}><table style={tableStyle}><thead><tr><th style={thStyle}>{ui.tableFeature}</th><th style={thStyle}>{ui.tableA}</th><th style={thStyle}>{ui.tableB}</th></tr></thead><tbody>{[[ui.purpose,ui.purA,ui.purB],[ui.scope,ui.scpA,ui.scpB],[ui.complexity,ui.cmpA,ui.cmpB],[ui.scaling,ui.sclA,ui.sclB],[ui.networking,ui.netA,ui.netB],[ui.selfHealing,ui.shA,ui.shB],[ui.storage,ui.stoA,ui.stoB]].map(([f,a,b],i)=>(<tr key={i}><td style={{...tdStyle,fontWeight:600}}>{f}</td><td style={tdStyle}>{a}</td><td style={tdStyle}>{b}</td></tr>))}</tbody></table></div>
      <div style={sectionStyle}><h2 style={h2Style}>{ui.whatIsA}</h2><p style={pStyle}>{ui.aText}</p></div>
      <div style={sectionStyle}><h2 style={h2Style}>{ui.whatIsB}</h2><p style={pStyle}>{ui.bText}</p></div>
      <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))',gap:16,...sectionStyle}}>
        <div style={cardStyle}><h3 style={h3Style}>{ui.whenA}</h3><ul style={ulStyle}><li>{ui.aUse1}</li><li>{ui.aUse2}</li><li>{ui.aUse3}</li><li>{ui.aUse4}</li><li>{ui.aUse5}</li></ul></div>
        <div style={cardStyle}><h3 style={h3Style}>{ui.whenB}</h3><ul style={ulStyle}><li>{ui.bUse1}</li><li>{ui.bUse2}</li><li>{ui.bUse3}</li><li>{ui.bUse4}</li><li>{ui.bUse5}</li></ul></div>
      </div>
      <div style={{...cardStyle,background:'var(--bg-input)',...sectionStyle}}><h2 style={h2Style}>{ui.verdict}</h2><p style={{...pStyle,fontWeight:500}}>{ui.verdictText}</p></div>
      <div style={sectionStyle}><h2 style={h2Style}>{ui.tryTools}</h2><div style={{display:'flex',flexWrap:'wrap',gap:8}}>{[{href:`/${lang}/tools/docker-compose-generator`,label:'Docker Compose Generator'},{href:`/${lang}/tools/yaml-validator`,label:'YAML Validator'},{href:`/${lang}/tools/json-yaml`,label:'JSON ↔ YAML'},{href:`/${lang}/tools/nginx-config`,label:'Nginx Config Generator'}].map(link=>(<Link key={link.href} href={link.href} style={{display:'inline-block',padding:'8px 16px',borderRadius:8,border:'1px solid var(--border-color)',fontSize:13,color:'var(--accent-blue)',textDecoration:'none',background:'var(--bg-input)'}}>{link.label}</Link>))}</div></div>
      <div style={sectionStyle}><h2 style={h2Style}>{ui.faqTitle}</h2><div style={{display:'flex',flexDirection:'column',gap:8}}>{[{q:ui.faq1q,a:ui.faq1a},{q:ui.faq2q,a:ui.faq2a},{q:ui.faq3q,a:ui.faq3a}].map((faq,idx)=>(<details key={idx} style={{border:'1px solid var(--border-color)',borderRadius:8,overflow:'hidden',background:'var(--bg-input)'}}><summary style={{padding:'14px 16px',cursor:'pointer',fontSize:14,fontWeight:600}}>{faq.q}</summary><div style={{padding:'0 16px 14px',fontSize:13,lineHeight:1.7,color:'var(--text-secondary)'}}>{faq.a}</div></details>))}</div></div>
    </ToolLayout>
  );
}
